### ISSUE TITLE
好像mysql有密码就无法跑动啊？

### ISSUE THREAD

**Issue by fengbaozhiling** [thx/rap2-delos#1]
在什么地方设置密码呢

**Comment by Bosn** [comment]
搜下mysql或者root

**Comment by xwillsu** [comment]
rap2-delos/config下会有不同env的设置

**Comment by Bosn** [comment]
是的，所以npm run dev，走的是development模式，对应配置是config.dev.js
npm run start 走的是生产production模式，对应配置是config.prod.js

详细的脚本配置在package.json中。
