### ISSUE TITLE
仓库的创建都是私有的吧，能创建公开仓库吗，或者加上这个选项？

### ISSUE THREAD

**Issue by fengbaozhiling** [thx/rap2-delos#10]
建议新增创建公开仓库，有些仓库应该需要开放给所有人查看
新增屏蔽仓库，开发者只需要看到自己需要的仓库就好
建议开发“加入团队”的功能，让管理者审核通过就能查看到项目的接口；

现在团队几百人，要加人减人都很麻烦，需要管理者一个个加

**Comment by Bosn** [comment]
已增加仓库权限社会，详见commit

仓库新增权限设置，选择私有时，对应的仓库列表及仓库详情除团队成员外用户无法访问。mock数据因涉及登陆状态，并未有限制。
