### ISSUE TITLE
有接口出现错误

### ISSUE THREAD

**Issue by milobluebell** [thx/rap2-delos#101]
麻烦请看一下这个提在rap1的issue：[https://github.com/thx/RAP/issues/1165](url)

**Comment by Bosn** [comment]
rap1已停止维护，请不要把rap1的issue发到rap2区域哦。

**Comment by milobluebell** [comment]
是rap2的bug，我只是一开始点了rap1的github链接而已。 此外，再增加一个新的相同BUG，接口：http://rap2api.taobao.org/app/mock/6799/GET/hotsearch

**Comment by milobluebell** [comment]
朋友，你重新打开一下吧。  具体操作方法是，导入了一个相对比较负责的json格式的响应内容，然后点击保存，就爆炸了，再也无法输出我想要的东西了，只是给我{}。非常像服务器宕机那样。。
