### ISSUE TITLE
关于退出的功能bug

### ISSUE THREAD

**Issue by BQSQ** [thx/rap2-delos#102]
使用账号登陆后http://rap2.taobao.org/ ，点击退出跳转到 http://rap2.taobao.org/account/login，这个时候直接访问 http://rap2.taobao.org 地址，还是登陆状态，F12看到退出是一个 /account/login 的跳转，猜测这一切都是前端干的，没有后台数据业务处理。

**Comment by Bosn** [comment]
问题已复现，会尽快解决修复。

**Comment by Bosn** [comment]
测试了下目前最新版没有这个问题，后续发布到rap.taobao.org请关注。
