### ISSUE TITLE
导入的 Array 内容均为 Primitive 时，Array 内部内容将会被忽略

### ISSUE THREAD

**Issue by alvarto** [thx/rap2-delos#106]
示例输入：

```
{
  "arr": [1,2,3,4]
}
```

期待输出

```
{
  "arr": [1,2,3,4]
}
```

实际输出

```
{}
```

**Comment by alvarto** [comment]
相关bug：https://github.com/thx/rap2-dolores/issues/12

**Comment by alvarto** [comment]
相关bug: https://github.com/thx/rap2-delos/issues/56

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-dolores/commit/c9c131819a2b3ea45ddccf9d686be15be250782d
