### ISSUE TITLE
前/后端视图区分

### ISSUE THREAD

**Issue by alvarto** [thx/rap2-delos#108]
前端视图展现Mock，后端视图展现数据类型。

比如`Array` | `+1` | `[1,2,3,4]`，实际上是 1、2、3、4 的轮换，而他的类型被显示为Array，其实对于后端来说会比较混淆。

又比如`Function`| | `() => Math.random()`，实际是Number的返回值。

需要定义的事情是，对于已经定义好了前端的mock内容，后端视图里导入了json，出现了conflict，应当如何处理？
（可以去掉后端视图的角度，只能由mock导入定义，但这样会导致适用需求面的减少。）

**Comment by alvarto** [comment]
Ref: #37

**Comment by Bosn** [comment]
这个其实就是为什么我RAP1搞了个Mock数据显示、隐藏按钮。但其实后端也需要关注下Mock数据的逻辑。来理解接口值的选取范围。这块儿，我比较纠结。有利有弊。
