### ISSUE TITLE
数据库出错问题

### ISSUE THREAD

**Issue by luckyjiet** [thx/rap2-delos#11]
1、user表运行初始化数据后缺少empId字段
2、route/analytics.js，中由于1的问题，有个select user.empId报错，同时这个文件里，updatedAt，请统一下，强迫症患者，不要select中 前面At，后面at，数据库的字段时updatedAt

**Comment by Bosn** [comment]
empId为我们内部部署的系统使用的字段，对外已经去掉了。应该是没去干净，我再检查一下。

**Comment by jasonx4131** [comment]
@luckyjiet @Bosn 
能否回答一下我的 #16 
#17 这两个问题，谢谢

**Comment by John-Base** [comment]
Unknown column 'module.priority' in 'field list  
数据库脚本是不是和代码不匹配，这个排序字段没有啊
