### ISSUE TITLE
Where is rap2 documents

### ISSUE THREAD

**Issue by cocobiz** [thx/rap2-delos#111]
没有使用过rap1, 第一次用rap2, 有没有rap2的文档, 
我看rap1的文档前端引入插件的script是这样的:
<script type="text/javascript" src="http://{{domainName}}/rap.plugin.js?projectId={{projectId}}&mode={{mode}}"></script>

q1: domianName是http://127.0.0.1:3000 还是http://127.0.0.1:8080?
q2: 我分别试了上面的两个URL, 并没有一个有效的返回.

**Comment by Bosn** [comment]
亲，RAP1和RAP2是两个不同的系统，RAP2的使用方法，请参考http://rap2.taobao.org/api

**Comment by Bosn** [comment]
如仍有问题，欢迎随时reopen带上具体的问题哦
