### ISSUE TITLE
代码中的数据表名与数据库中的表名不匹配导致查询失败

### ISSUE THREAD

**Issue by 1993Plus** [thx/rap2-delos#112]
![7](https://user-images.githubusercontent.com/5886066/37707549-759820f4-2d3e-11e8-8c5c-b0951e808df8.png)
![8](https://user-images.githubusercontent.com/5886066/37707550-75ef60da-2d3e-11e8-8ac8-4b129cfc2af2.png)

实际名称
![9](https://user-images.githubusercontent.com/5886066/37707551-764f93ce-2d3e-11e8-8988-7be5e2369586.png)

**Comment by Bosn** [comment]
请更新到最新版本哈，刚刚TS化的那个不稳定版本确实有很多问题，最新的经过测试都是可用的哦。
