### ISSUE TITLE
在RAP2如何导出表格呢？

### ISSUE THREAD

**Issue by p-bigsmart** [thx/rap2-delos#113]
公司准备用RAP做数据分离，让我研究下RAP。
看到官网说建议用RAP2，但是RAP2好像没有导出表格这一个方法吗？

**Comment by Bosn** [comment]
暂时没有该功能的规划，可以通过API自行做插件研发。

RAP的核心，是将文档放在线上，保证实时同步，导出文档副本，违背了这个初衷。所以官方暂时不会考虑实现这个需求哦。但是API是提供了整个文档数据的获取接口的。
