### ISSUE TITLE
npm run build 出错

### ISSUE THREAD

**Issue by Gamehu** [thx/rap2-delos#114]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rap2-delos@1.0.0~prebuild: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~build: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~build: PATH: C:\Users\gameh\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\webstorm_project\mockServer\rap2-delos\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\apache-maven-3.5.0;D:\Program Files\apache-maven-3.5.0\bin;D:\Program Files\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;D:\Program Files\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Go\bin;D:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;"C:\Program Files (x86)\Java\jdk1.8.0_144\bin;C:\Program Files (x86)\Java\jdk1.8.0_144\jre\bin;";D:\Program Files\nodejs\;D:\Program Files (x86)\Yarn\bin\;D:\Program Files\Python\Python36\Scripts\;D:\Program Files\Python\Python36\;C:\Users\gameh\AppData\Local\Microsoft\WindowsApps;D:\Users\gameh\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;;D:\Program Files\Microsoft VS Code\bin;C:\Users\gameh\AppData\Roaming\npm;C:\Users\gameh\AppData\Local\Yarn\bin
9 verbose lifecycle rap2-delos@1.0.0~build: CWD: D:\webstorm_project\mockServer\rap2-delos
10 silly lifecycle rap2-delos@1.0.0~build: Args: [ '/d /s /c', 'rm -rf dist/ && tsc' ]
11 silly lifecycle rap2-delos@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle rap2-delos@1.0.0~build: Failed to exec build script
13 verbose stack Error: rap2-delos@1.0.0 build: `rm -rf dist/ && tsc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\gameh\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\gameh\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd D:\webstorm_project\mockServer\rap2-delos
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gameh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-delos@1.0.0 build: `rm -rf dist/ && tsc`
22 error Exit status 1
23 error Failed at the rap2-delos@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Bosn** [comment]
按照README上面的步骤做，确保node版本符合README上的要求。

tsc命令（npm install -g typescript）被正确安装

其它的。。。你的问题可以再仔细一点，一个字没有就一个错误日志想要怎样。。。。

**Comment by yanglijin0911** [comment]
这个问题解决了吗,我也是同样的问题,能否告知下解决的方法?
