### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by vlean** [thx/rap2-delos#116]
rap1里的有些功能挺好用，建议rap2里也做下支持吧。

1. 接口的粘贴复制。现在只能单个的编辑，很不方便。
2.文档导出，导入。最好能支持Swagger的格式导入导出。另外建议可以导出成网页的。
3.数据类型丰富一下。或者支持自定义标识。  例如Array。有Array<string>、Array<number>等。

**Comment by Bosn** [comment]
1. ISSUES区提过了
2. 文档导入导出暂时不支持，未来也不打算支持，有JSON API，自己做一个转换很容易。Swagger导出正在开发。
3. 有Array、Array等？
