### ISSUE TITLE
install 遇到错误

### ISSUE THREAD

**Issue by printfcoder** [thx/rap2-delos#12]
1. install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@7.9.0 (node-v51 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/shuxian/Projects/git/git-tools/alibaba-rap/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> pre-commit@1.2.2 install /Users/shuxian/Projects/git/git-tools/alibaba-rap/node_modules/pre-commit
> node install.js

pre-commit:
pre-commit: Detected an existing git pre-commit hook
pre-commit: Old pre-commit hook backuped to pre-commit.old
pre-commit:

2. run check

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-delos@1.0.0 check: `npm run linter && test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

3. 错误日志
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'check' ]
2 info using npm@5.5.1
3 info using node@v7.9.0
4 verbose run-script [ 'precheck', 'check', 'postcheck' ]
5 info lifecycle rap2-delos@1.0.0~precheck: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~check: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~check: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~check: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users//Projects/git/git-tools/alibaba-rap/node_modules/.bin:/Users//opt/apache-maven/3.5.0/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Library/gradle/gradle-3.5/bin:/Users//workspace/go/bin:/Users//Library/Android/sdk/tools:/Users//Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle rap2-delos@1.0.0~check: CWD: /Users/Projects/git/git-tools/alibaba-rap
10 silly lifecycle rap2-delos@1.0.0~check: Args: [ '-c', 'npm run linter && test' ]
11 silly lifecycle rap2-delos@1.0.0~check: Returned: code: 1  signal: null
12 info lifecycle rap2-delos@1.0.0~check: Failed to exec check script
13 verbose stack Error: rap2-delos@1.0.0 check: `npm run linter && test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd /Users/Projects/git/git-tools/alibaba-rap
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "check"
18 verbose node v7.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-delos@1.0.0 check: `npm run linter && test`
22 error Exit status 1
23 error Failed at the rap2-delos@1.0.0 check script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

4. 运行后打开8080
![image](https://user-images.githubusercontent.com/20906540/33354321-3fb50de8-d4ed-11e7-9497-b9cc9e05a131.png)

**Comment by printfcoder** [comment]
搞错了，不过建议把rap2-dolores和delos合并一下。

**Comment by Bosn** [comment]
@printfcoder 一个是前端，一个是后端。之所以拆开，就是为了让逻辑更清晰，后续人越来越多维护起来也方便一些。

多包管理可以自己调研下[lerna](https://github.com/lerna/lerna)

**Comment by printfcoder** [comment]
你是对的，但是二者离开了谁都玩不起来，wiki上应该注明一下二者要联合跑起来才是最终的rap。我一进来
rap2-delos项目就以为是全部
于是 git pull, npm install,npm run 就跑了，发现不对，再倒回去看，分析了一下，还需要跑dolores。

**Comment by Bosn** [comment]
README第一句话就是RAP包含两个组件，delos和dolores。

Bosn

On 29 Nov 2017, at 11:56, Shu xian <notifications@github.com<mailto:notifications@github.com>> wrote:


你是对的，但是二者离开了谁都玩不起来，wiki上应该注明一下二者要联合跑起来才是最终的rap。我一进来
rap2-delos项目就以为是全部
于是 git pull, npm install,npm run 就跑了，发现不对，再倒回去看，分析了一下，还需要跑dolores。

**Comment by printfcoder** [comment]
作为作者，你当然是知道两个组件是不是在一个大组件里的，可是对于使用者，第一眼看上去就以为最外层就是一个rap大组件，它有两个小组件：delos和dolores，运行这个大组件就行了。

第一句话只说明是前端或后台组件，并没有说两个是不同的项目，两者互相支持，仅依靠一个link不显眼，没有显式说明两个不在一个项目里。新人进入入项目github首页并不知道delos和dolores是什么，它们是不是在当前github项目里，还是分开的，都不知道，即使有github首页的标题而又并不是rap。

我只是觉得文档开头应该更详细些。让人感觉有些粗糙。
