### ISSUE TITLE
未匹配到任何接口

### ISSUE THREAD

**Issue by ruoxiaojie** [thx/rap2-delos#121]
http://192.168.1.247:8002/app/mock/28/GET/q
{"isOk":false,"errMsg":"未匹配到任何接口 No matched interface"}

http://192.168.1.247:8002/app/mock/28/q
{
  "ww": "w"
}
这个怎么解决   测试也不能正常使用

**Comment by ruoxiaojie** [comment]
今天刚拉的代码   求帮助

**Comment by ruoxiaojie** [comment]
这个问题已经解决了，

#############################
但是点击测试还是 未匹配到任何接口

**Comment by Bosn** [comment]
前端的URL填错了，把GET拿掉就好了。

**Comment by Houngtze** [comment]
use the postman or other tools to request the api，dont click the link
