### ISSUE TITLE
get post可以不在域名上体现么？或者有什么解决方案

### ISSUE THREAD

**Issue by VVZ1991** [thx/rap2-delos#122]
http://rap2api.taobao.org/app/mock/9303/POST/goodsSite/appDiyFont/getDiyFont
![wechatimg133](https://user-images.githubusercontent.com/8370996/38242158-acb5bf06-3766-11e8-80db-1eb3699eaeb9.jpeg)
为啥url上为什么要体现POST和GET “goodsSite/appDiyFont/getDiyFont”本来我们app端 后半段写死，前半段用于mock和正式接口的切换。 中间加了POST和GET 这让我们的切换。感觉很不方便。 有什么解决方案么

**Comment by ruoxiaojie** [comment]
哥们  我这 url有  post  get   就是匹配不到接口   手动删掉就能查   你知道什么原因吗

**Comment by Bosn** [comment]
该BUG已经修复了哈，请查看最近的提交记录。rapapi.taobao.org系统还没更新。
代码库已经更新了，待版本稳定会更新到线上哦
