### ISSUE TITLE
修改密码

### ISSUE THREAD

**Issue by liguohao96** [thx/rap2-delos#124]
1.能否采用https进行数据传输
2.能否加入修改密码的功能

**Comment by walkersing** [comment]
自己写吧

**Comment by Bosn** [comment]
1. 官网是DEMO站点，服务器不提供HTTPS支持。请自行部署HTTPS协议下的服务器。
2. 可以的。

**Comment by Bosn** [comment]
已增加密码修改功能哦，请更新rap2-delos和rap2-dolores两个包哦

**Comment by coalchan** [comment]
噢，good，终于开始更新代码了哈

**Comment by Bosn** [comment]
@coalchan 是啊，年前年后的一堆项目刚结束，现在有时间了。
