### ISSUE TITLE
你们官网挂了

### ISSUE THREAD

**Issue by YangGoldDragon** [thx/rap2-delos#126]
如题，赶快叫你们运维去看一下吧。

**Comment by Bosn** [comment]
刚刚试了没问题啊，你说的是rap1吗

**Comment by YangGoldDragon** [comment]
http://rapapi.org/
这个网站

**Comment by Bosn** [comment]
已重启，但是RAP1服务器已经撑不住日益增长的流量了内存老是爆满，建议自己部署，或使用RAP2。

服务器方面我再和PE磨一磨看看能不能拿到新机器。
