### ISSUE TITLE
https协议测试功能不能访问

### ISSUE THREAD

**Issue by lijiangwei** [thx/rap2-delos#129]
https协议部署的工程，打开打开测试页面test/test.plugin.jquery.html?id=16页面报错
`let redirect = `${RAP.protocol}://${RAP.host}/app/mock/${match.repositoryId}/${match.method}/${match.url}``

这里取到的protocol是http，浏览器会限制访问
`Mixed Content: The page at 'https://api.lovemm.xin/test/test.plugin.jquery.html?id=16' was loaded over HTTPS, but requested an insecure script 'http://api.lovemm.xin/app/mock/16/GET//example/1523790069379?callback=jQuery1124020887178371521609_1523806571231&_=1523806571232'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Bosn** [comment]
在插件前自行设置呀，在全局RAP对象初始化后，增加

```javascript
window.RAP.protocal = 'https';
```
