### ISSUE TITLE
现在的版本路径不能有?参数吗?

### ISSUE THREAD

**Issue by 195440** [thx/rap2-delos#13]
![554b6d141565e8dc0e543f4d2438ac6](https://user-images.githubusercontent.com/18521081/33408634-7acdcfa8-d5b2-11e7-962a-6998a090b31b.png)
![c0756888b5978bfc539eb98d4576d67](https://user-images.githubusercontent.com/18521081/33408635-7bd278f4-d5b2-11e7-9cdf-342a8d992b74.png)
路径带参数返回空白!!!

**Comment by Bosn** [comment]
最新版本试了问题没有复现，rap2.taobao.org上面的版本比较老我更新完近期补丁后会更新线上系统。
