### ISSUE TITLE
建议取消链接里的POST和GET前缀。

### ISSUE THREAD

**Issue by njleonzhang** [thx/rap2-delos#131]
mock链接里，现在时有POST和GET前缀的。

```
http://rap2api.taobao.org/app/mock/10570/POST/zyuser/login/
http://rap2api.taobao.org/app/mock/10570/GET/zyuser/logout/
```

那么开发的时候我的链接里就需要有`POST`和`GET`, 替换真是服务器的时候，我需要去一处处删除，很麻烦，请考虑从url里删除。当然我网络库里特殊处理这一块也行，单这个设计是否合理呢，还是说这是阿里内部的规范 😂

**Comment by Bosn** [comment]
已经去掉了去掉了，最新代码去掉了哦，官网系统还没更新。

**Comment by njleonzhang** [comment]
@Bosn 期待更新
