### ISSUE TITLE
 期望返回的response不只有200，而是可以选择401，404，500

### ISSUE THREAD

**Issue by tedtse** [thx/rap2-delos#132]
如题，期望返回的Mock请求可以设置状态码，200，401，500等，这样前端就可以更加方便地完成各种交互编码

**Comment by Bosn** [comment]
很好的需求，测试了一下可以实现，会在后续版本中增加哈。

**Comment by hqwlkj** [comment]
这个 功能什么时候可以 添加？近期有计划吗？ @Bosn

**Comment by Bosn** [comment]
已添加

**Comment by hqwlkj** [comment]
@Bosn    在 http://rap2.taobao.org/ 中没有看见，是不是还没有发布呢？

**Comment by Bosn** [comment]
有啊，在接口编辑中，有个状态码可以选择。
