### ISSUE TITLE
官方网站无法访问了

### ISSUE THREAD

**Issue by jackgreentemp** [thx/rap2-delos#134]
您好：
http://rap2.taobao.org/无法访问
访问以前的api，http://rap2api.taobao.org/app/mock/9138/POST/GETORGTREE，结果是“Internal Server Error”

**Comment by cdpsai** [comment]
下班了，明天上班估计就恢复了，许愿。

**Comment by Bosn** [comment]
正在更新哈，服务器升级中~~~~

**Comment by Bosn** [comment]
升级完成了哦
