### ISSUE TITLE
rap2.taobao.org速度太慢，我想将仓库导出，有这个功能吗？

### ISSUE THREAD

**Issue by cdpsai** [thx/rap2-delos#136]
还是用私服算了，慢的同事都发火了。

**Comment by Bosn** [comment]
看了下，数据库 CPU很高，我会把数据库迁移到云上。减缓前端压力。

仓库导出的话在弄，https://github.com/thx/rap2-delos/issues/31  在这里。
官网原计划只是做DEMO站点，但是现在用的人真的是比预想的多.... 我会申请资源加入人力维护。。。。

**Comment by wangwen1220** [comment]
可以参照 RAP1=>RAP2 迁移工具自己开发一套 RAP2=>RAP2 迁移工具
![image](https://user-images.githubusercontent.com/1627874/52845948-54fdcd80-3143-11e9-9ab0-98b017234b9f.png)
