### ISSUE TITLE
最近的rap2好不稳定

### ISSUE THREAD

**Issue by KevinZyz** [thx/rap2-delos#137]
最近在使用rap2接口的时候，要么就一直加载，要么就直接返回个Internal Server Error, 访问个首页都会卡死， 请问会改善吗

**Comment by Bosn** [comment]
正在申请资源，但是rap2官网是DEMO站点，不是sass... 未来也不会收费。

建议正式使用自行部署。官方的运维我们会努力，但是无法保证。也不会收取任何费用。

**Comment by Bosn** [comment]
近期速度慢是自建数据库性能不够用了。已经申请了云服务器，预计今天到货做迁移，短期内稳定性会得到改善。

**Comment by KevinZyz** [comment]
好的，非常感谢你的回答
