### ISSUE TITLE
rap2最近特别慢，是为啥

### ISSUE THREAD

**Issue by LeoDemon** [thx/rap2-delos#138]

**Comment by milobluebell** [comment]
+1  就此时此刻，已经无法访问了.....蛋疼，而且好像接口地址也换了POST/GET等方法在URL中去掉了。

**Comment by xyb110112** [comment]
rap服务挂了？赶紧抢救·一下啊·。

**Comment by Bosn** [comment]
已经做了缓存 + 数据库上云，如果还有特别慢的现象，请贴个链接我来针对性查一下哦亲~~~
