### ISSUE TITLE
[建议 ] 希望能提供 docker 版本的 release

### ISSUE THREAD

**Issue by WallenHan** [thx/rap2-delos#14]
**希望能提供dock版本release**
既然 issue 中有那么多安装出问题的，不如一劳永逸 学习 swagger， 提供 docker 版本。

**Comment by Bosn** [comment]
在路上

**Comment by piaohailin** [comment]
是啊，救救node小白吧。。。搭个环境要几天，没法用了。

**Comment by blackdog1987** [comment]
我自己传了一个delos的镜像上去
delos需要依赖mysql和redis。mysql和redis可以配置为自己的，也可以用docker运行

https://github.com/blackdog1987/rap2-delos/blob/master/docker-compose.yml

如果是已经有mysql和redis的童鞋，需要注释掉已经有的service，配置上相应的mysql和redis配置，yaml文件中暴露的是38080端口，可以修改为自己想暴露的接口，相应的，dolores项目中需要修改访问的接口地址和端口。
另，如果是第一次运行，docker-compose命令会报错，可以忽略掉，保持delos运行，然后登录到rap2-delos中执行node scripts/init 命令初始化数据库，然后重启docker-compose。

目前我们公司的rap2的环境我已经改为了docker部署了，暂时运行良好。
