### ISSUE TITLE
注册后的账号无法再次登录

### ISSUE THREAD

**Issue by iwin4aids** [thx/rap2-delos#140]
1、注册登录的问题
目前官网rap注册登录也有点问题，而我自己部署的rap2更是一直存在这个问题，注册后的账号退出再登录居然提示密码错误，mysql user表里面的密码字段看起来是MD5的32位 尝试修改了下也不对，这个问题我觉得对这种成熟产品的第二版不应该有的.
2、我是使用nginx部署前端dolores build产物，但是页面操作时没什么问题，如果随便按一下刷新的话就变成404了，这个问题不知道是不是我nginx配置的问题，希望官方给一个比较详细的部署文档。

**Comment by Bosn** [comment]
更新到最新代码了吗

**Comment by Bosn** [comment]
最新代码在服务启动时会对已有数据进行一遍加密

**Comment by Bosn** [comment]
更新后需要重新编译和重启哦

**Comment by wonderffee** [comment]
请问lz的404问题解决了吗？
我用的 https://github.com/sayhub-project/rap2-easy-end 部署的，里面也是用的nginx，页面操作没有什么问题，但是刷新的话也会变成404，经测试只要把http://127.0.0.1/repository/这种二级网址直接在浏览器中粘贴地址访问就会出现404，怀疑是nginx的配置问题

**Comment by Bosn** [comment]
@wonderffee

**Comment by Bosn** [comment]
@wonderffee 是的，因为你有二级路径的时候，路径没有匹配到正确的位置。给你我的有关配置做参考，自己也可以搜索下React的Nginx配置。

```
  server {
    listen 80;
    server_name rap2.taobao.org;
    root /root/server/rap2-dolores;
    try_files $uri /index.html;
  }
```

**Comment by wonderffee** [comment]
感谢，我在在 location / { 里面加上一行：
try_files $uri /index.html;
再重启docker就解决了

**Comment by iwin4aids** [comment]
感谢，已解决，nginx配置问题
