### ISSUE TITLE
mock接口问题

### ISSUE THREAD

**Issue by MR820** [thx/rap2-delos#145]
api提供的接口：http://server.api.castim.cn/app/mock/5//example/123456
前端拦截发出的请求：http://server.api.castim.cn/app/mock/5/GET//example/123456
ajax代码如下：
$.ajax({
    url : '/example/123456', // 自动拦截
    method : 'GET',
    dataType : 'JSON',
    success : function(data) {
      // 返回根据RAP文档及规则生成的mock数据
      $('#result').html(JSON.stringify(data))
    }
})

**Comment by EnglishZhuoji** [comment]
遇到类似的问题，发出的请求为： http://192.168.0.251:8080/app/mock/20/GET/example/123
![image](https://user-images.githubusercontent.com/13271456/39228265-cf4dee5a-488f-11e8-9c1d-43f5eb0f509a.png)
![image](https://user-images.githubusercontent.com/13271456/39228275-dd30aaf8-488f-11e8-9649-5e29fff763f3.png)

**Comment by alvarto** [comment]
rel: https://github.com/thx/rap2-delos/issues/65

**Comment by Bosn** [comment]
该问题 @alvarto 已修复，请参考上面的 commit 3746970
