### ISSUE TITLE
查询所有仓库的时候有BUG

### ISSUE THREAD

**Issue by hqwlkj** [thx/rap2-delos#148]
正式环境访问 所有仓库 服务器响应超时 ：http://rap2api.taobao.org/repository/list?user=&organization=&name=&cursor=1&limit=100

clone  的代码 运行报错了：
![image](https://user-images.githubusercontent.com/12181423/39235076-84c16a70-48a7-11e8-9de6-33f5b62a48ec.png)

**Comment by hqwlkj** [comment]
#143

**Comment by Bosn** [comment]
最新的版本已经修复了，麻烦再试一下。

**Comment by hqwlkj** [comment]
已更新，问题已修复，但是钉钉能不能 同意一下申请呢？ @Bosn
