### ISSUE TITLE
添加API 参数，返回数据报500

### ISSUE THREAD

**Issue by zdsec999** [thx/rap2-delos#149]
数据库表Properties中的字段 priority， 其属性为int(11)

但传入的数据为：1524666729233   (这个值像是时间戳)

INSERT INTO `Properties` (`id`,`scope`,`type`,`name`,`value`,`description`,`parentId`,`priority`,`interfaceId`,`creatorId`,`moduleId`,`repositoryId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'request','String','test','test','',-1,**1524666729233**,153,100000048,52,21,'2018-04-25 14:32:09','2018-04-25 14:32:09')

不知道是我们系统环境问题，还是其它原因，写入数据库时的priority 值，貌似写的是时间戳，导致写失败。
git log:  43fd092dfdef54308c7eb75056366f994f695e13

麻烦确认一下！

thanks!

**Comment by billjs** [comment]
我也报一样的错误，这bug也太多了吧。

**Comment by zdsec999** [comment]
你把那个字段的属性 改为 bigin(50)

就可以写入数据了

**Comment by Bosn** [comment]
最新版本已修复，请执行文件 src/database/v2018_5_15_change.sql 更新数据库表即可。
