### ISSUE TITLE
接口编辑保存保存

### ISSUE THREAD

**Issue by willmynew** [thx/rap2-delos#155]
使用最新的代码，在接口保存是出现错误：
SequelizeDatabaseError: Out of range value for column 'priority' at row 1

我将 src/routes/repository.ts 的723行的Date.now() 修改为上一版本问题就没有了。

请问这个地方的Date.now()的作用是什么？

**Comment by Bosn** [comment]
优先级，用于保持实体的顺序的。

老一版本priority值是动态count(*) 整个Property表，目前线上rap2官网刚放上几个月property已经有百万级条目了，所以出现严重性能问题。

所以改成了Date.now()，Out of range的问题还在查，可能会用更简化计数器的方法来优化。

**Comment by zdsec999** [comment]
@Bosn  

数据库定义字段与写入的数据不匹配，导致那个报错， 

数据库表Properties中的字段 priority， 其属性为int(11)

但传入的数据为：1524666729233 ，超出int(11)

调整那个字段的属性就可以了！

**Comment by HassanChiang** [comment]
![image](https://user-images.githubusercontent.com/5477025/39702352-1964c42c-5237-11e8-8818-c19bd0082138.png)
接口和模块表的 priority  我改成 bigint 解决了。

**Comment by lanmingle** [comment]
@HassanChiang 给这个属性坑得跑步起来,我还以为我搭建有什么问题呢.

**Comment by Bosn** [comment]
嗯，该问题已修复。请执行脚本
`src/database/v2018_5_15_change.sql`
来更新数据库哦
