### ISSUE TITLE
npm run check时报错，请指教，谢谢

### ISSUE THREAD

**Issue by jasonx4131** [thx/rap2-delos#16]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-delos@1.0.0 check: `npm run linter && test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-30T12_01_13_291Z-debug.log

以下是/root/.npm/_logs/2017-11-30T12_01_13_291Z-debug.log日志文件记录

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nodejs9/bin/node',
1 verbose cli   '/usr/local/nodejs9/bin/npm',
1 verbose cli   'run',
1 verbose cli   'check' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose run-script [ 'precheck', 'check', 'postcheck' ]
5 info lifecycle rap2-delos@1.0.0~precheck: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~check: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~check: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~check: PATH: /usr/local/nodejs9/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/rap2/node_modules/.bin:/usr/local/nodejs9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle rap2-delos@1.0.0~check: CWD: /usr/local/rap2
10 silly lifecycle rap2-delos@1.0.0~check: Args: [ '-c', 'npm run linter && test' ]
11 silly lifecycle rap2-delos@1.0.0~check: Returned: code: 1  signal: null
12 info lifecycle rap2-delos@1.0.0~check: Failed to exec check script
13 verbose stack Error: rap2-delos@1.0.0 check: `npm run linter && test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs9/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs9/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd /usr/local/rap2
16 verbose Linux 3.10.0-693.5.2.el7.x86_64
17 verbose argv "/usr/local/nodejs9/bin/node" "/usr/local/nodejs9/bin/npm" "run" "check"
18 verbose node v9.2.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-delos@1.0.0 check: `npm run linter && test`
22 error Exit status 1
23 error Failed at the rap2-delos@1.0.0 check script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by luckyjiet** [comment]
你试下node 8.9的版本，之前我用最新版，好像有包不适用

**Comment by jasonx4131** [comment]
@luckyjiet 我在另外的电脑上跑起来了。如下图
![kcr2iqh61l r_y8qibht q9](https://user-images.githubusercontent.com/11881255/33466305-f61f1ca4-d687-11e7-9722-1f0a446ad5ec.png)
![s0 45s3ql i s7 k6 01](https://user-images.githubusercontent.com/11881255/33466309-f9b593a2-d687-11e7-9901-77c385dc2b2e.png)
现在这个状态对吗？如何使用？

**Comment by sea13502** [comment]
同run check 报错，windows下跑步起来？？哪里的问题？？

**Comment by Bosn** [comment]
@sea13502 windows。。。。我有空搞搞。但是node系的东西个人建议还是部署Linux，你可以用Docker + VMWare虚拟下，很简单的

**Comment by sea13502** [comment]
好的，谢谢

**Comment by luckyjiet** [comment]
@jasonx4131 你发的这个是服务端，express写的，文档里不是还有个前端项目么，react的，把服务端起了，然后前端build一下，nginx配一下静态页面就好了，怎么方便怎么来
