### ISSUE TITLE
redis 怎么配置（非本地）

### ISSUE THREAD

**Issue by zhouruizhong** [thx/rap2-delos#166]

**Comment by xiaoxing598** [comment]
修改配置文件中的redis连接信息即可

vim src/config/config.dev.ts
```
redis: {
    host: '192.168.1.xxx'
  }
```

**Comment by zhouruizhong** [comment]
redis: {
    host: '192.168.1.88',
    port: 6579
  }
修改后还是提示
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by xiaoxing598** [comment]
把所有环境的配置都改了，我上面只列了一个文件，你要学会举一反三啊

**Comment by Bosn** [comment]
@xiaoxing598 @zhouruizhong 
天啊，不要全改。

npm run dev => 开发模式，会使用config.dev.ts
npm start => 生产模式，会使用config.prod.ts

另外tsc是需要编译的，没生效可能是你没有执行
npm run build

**Comment by zhouruizhong** [comment]
非常感谢，可以了，执行npm run build 就可以了
