### ISSUE TITLE
rap1不再用了吗？

### ISSUE THREAD

**Issue by aqingyan** [thx/rap2-delos#171]
rap不再用了吗？这两天访问总是提示：【网址为 http://rapapi.org/platform/home.do 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONNECTION_ABORTED】之前的数据咋办吖?

**Comment by Bosn** [comment]
RAP1内存老是溢出，用的人太多了，而且公司现在资源都给RAP2了，没资源给RAP1.

想继续使用RAP1的，请自行部署自己的服务器。
不想自己部署的，请尽快使用迁移工具迁移到RAP2.

**Comment by aqingyan** [comment]
emmm，迁移工具报500错误。。。
在2018年5月15日 10:27，Bosn<notifications@github.com> 写道：

RAP1内存老是溢出，用的人太多了，而且公司现在资源都给RAP2了，没资源给RAP1.

想继续使用RAP1的，请自行部署自己的服务器。
不想自己部署的，请尽快使用迁移工具迁移到RAP2.

**Comment by aqingyan** [comment]
http://rapapi.org/workspace/myWorkspace.do?projectId=34180#348853

**Comment by Bosn** [comment]
问题已修复，可以了。
