### ISSUE TITLE
导入json报错

### ISSUE THREAD

**Issue by HassanChiang** [thx/rap2-delos#173]
Uncaught TypeError: Cannot read property 'gitlab.alibaba-inc.com:thx' of undefined

![image](https://user-images.githubusercontent.com/5477025/40035722-b1fcb236-5835-11e8-85a9-895f276338f0.png)

**Comment by Bosn** [comment]
已修复
https://github.com/thx/rap2-delos/commit/2cc3e9010211948c3bb64d3bab513ac3a8aa11c3
