### ISSUE TITLE
给团队添加团员时不能通过邮箱添加，重名的又一大堆！

### ISSUE THREAD

**Issue by Michael-Ge** [thx/rap2-delos#178]
给团队添加团员时不能通过邮箱添加，重名的又一大堆！这个要马上改啊，几十个人叫一个名字，这怎么找啊。

**Comment by Bosn** [comment]
嗯，是个BUG，会加入到修复计划中。rap2官网的。。。用户有点多。

**Comment by Bosn** [comment]
fixed, will be pushed today later.

**Comment by JasmineChoi** [comment]
这个问题非常严重。一个团员名字起了个 |  。搜不到。又不能搜邮箱。修改资料又无法修改。又没有让他自己申请加入团队的功能
