### ISSUE TITLE
Docker-compose deploy problem

### ISSUE THREAD

**Issue by cesar-blog** [thx/rap2-delos#179]
I deploy  the rap2-delos with Docker.
Everything is good and local docker images repository generate 3 new images.
Then i run 'docker-compose up' directive  in the project root path which exposes 38080 port.

type localhost:38080 in Google browser.
It shows "Hello RAP!" ??? Does it mean service startup failure？

**Comment by blackdog1987** [comment]
No. This images just include the backend of rap2. you need deploy the frontend and config the url correctly.

the frontend:  https://github.com/thx/rap2-dolores

**Comment by blackdog1987** [comment]
Btw, you can see the service `delos` in `docker-compose.yml`. you can weather build form the source code by enabling  `build .` or build from the image I uploaded by enabling `image: blackdog1987/rap2-delos:1.1.0`

**Comment by cesar-blog** [comment]
Thanks! @blackdog1987 
I know what u say.
I aslo deploy the frontend successfully. But i don't know what to type  in "config.prod.js"  "serve" env var in the frontend project.
Btw, backend project expose port is 38080.

**Comment by blackdog1987** [comment]
just set the serve to the backend url.

`serve: 'http://10.10.10.10:38080'`. set the ip(10.10.10.10) to your own

**Comment by Bosn** [comment]
感谢blackdog1987的耐心回答。
两位中文大神的英文对话惊呆了小弟我。
