### ISSUE TITLE
布署好了，如何使用？

### ISSUE THREAD

**Issue by jasonx4131** [thx/rap2-delos#18]
rap2-dolores is running as http://localhost:8097
----------------------------------------
DATABASE √
    HOST     localhost
    PORT     3306
    DATABASE RAP2_DELOS_APP
----------------------------------------

访问网址，只提示有  https://rap2.alibaba-inc.com
怎么操作?能否给些指点

**Comment by Bosn** [comment]
rap2-delos是后端API包，还有个前端的，看下README哈，包含两个仓库。

rap2-dolores是前端仓库的。两个都运行才可以。

**Comment by jasonx4131** [comment]
弄前端时，提示 Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime

**Comment by Bosn** [comment]
按照文字提示，应该是某个程序不支持你所在的环境。请检查下node/npm等版本是否正确。

**Comment by hqwlkj** [comment]
操作到这一步之后，怎么通过IP或者域名访问呢？
![image](https://user-images.githubusercontent.com/12181423/39064440-1caa6e0e-4501-11e8-82c6-011a48bb71dc.png)

我的 config.prod.ts 中的 port 已经修改为：8081了。
