### ISSUE TITLE
怎么把数据库里的数据清空?

### ISSUE THREAD

**Issue by ZYmooon** [thx/rap2-delos#180]
后端数据台混乱了,每次新建一个仓库,里面的参数乱七八糟,不知道是谁改的?
还有,本地搭建的环境会不会影响线上的mock数据?

**Comment by Bosn** [comment]
开发模式会自动mock数据，用npm start启动生产模式是不会有mock数据的。

**Comment by Bosn** [comment]
开发模式下的mock数据是为了方便测试。会自动填充一些随机的数据。

**Comment by ZYmooon** [comment]
这样啊,之前不知道,谢谢啦
