### ISSUE TITLE
建议rap2支持多级栏目导航

### ISSUE THREAD

**Issue by zhouyuanliang** [thx/rap2-delos#184]
目前rap2只支持一级栏目，然后下面就是直接建接口了，项目稍微大一些的话，完全不够用，不方便接口归类整理，希望改进

**Comment by Bosn** [comment]
暂时不考虑哦，如果亲需要更多的层级，可以考虑项目拆分。通过协作仓库来连在一起。

单仓库层级如果需要很多，只能自己开发了哦。
