### ISSUE TITLE
多人维护同一个接口时，未保存接口长期无法编辑！

### ISSUE THREAD

**Issue by zhouyuanliang** [thx/rap2-delos#185]
场景：
A编辑接口时，未点保存就退出了。
之后其它人再进入查看此接口，则一直提示：“当前接口已经被 XXX 锁定！”，但此时A其实已经N多天都没有登录过此项目了。。。。。

建议：
用户编辑未保存的情况，在该用户下线后一段时间后进行还原操作。

**Comment by Bosn** [comment]
系统无法判断锁定的用户是否“忘记了”，强制下线，会导致文档的丢失。
团队协作上，谁锁定了，是可以看到了，去人和人沟通就好了。系统无法判断应该丢掉你的资料踢下线，所以从数据和资料安全的角度，我们选择持续锁定到锁定人释放。

当然您也可以自己开发强制踢下线的功能。
