### ISSUE TITLE
新建接口时，导入相应的json，然后点击保存报错

### ISSUE THREAD

**Issue by Duzcinfo** [thx/rap2-delos#186]
json数据：
{
  "result": {
    "user_id": "1",
    "account": "13888888888",
    "pwd": "",
    "user_head": "",
    "nickname": "",
    "total_asset": 0,
    "last_income": 0,
    "balance": 0,
    "sex": null,
    "state": 1,
    "user_type": 1,
    "user_token": "VKLJ9LZ8IFHN4UQMSBKC68XG3AL7LAGH",
    "created_at": "2018-05-21 17:45:50"
  },
  "alertMessage": "",
  "sign": "B2D533B756F71EEE6B69E4939CB5E422",
  "state": 200,
  "errMessage": "",
  "timestamp": "1526958206"
}
#########################################################################
报错信息：
![image](https://user-images.githubusercontent.com/16814728/40348019-dcb3e1c6-5dd4-11e8-9e28-f26134b0e6e0.png)
![image](https://user-images.githubusercontent.com/16814728/40348040-edbf0874-5dd4-11e8-85a0-e73e22bbfb30.png)

**Comment by Bosn** [comment]
环境配置错误，图中信息无法辨别，加钉钉群和群友们一起看看吧。
