### ISSUE TITLE
有没有将对后端接口测试的功能（类postman）集成进来的计划？

### ISSUE THREAD

**Issue by kkroy-zs** [thx/rap2-delos#188]
前后端分离后，借助rap2可以对接口做统一管理并可以直接为前端提供mock接口访问，但后端实现接口时，实现出的接口只能借助于其他工具（postman等）进行测试，因此后端实现的接口是否符合已定义好的接口定义并不能得到严格意义上的一致性保证，在开发过程中会造成一些不必要的麻烦。

**Comment by Bosn** [comment]
POSTMAN集成计划内，而且目前第一优先级在处理哦亲。

**Comment by gaochengyidlmu** [comment]
@Bosn 十分感谢，postman 数据如果能够导入，真的是美滋滋

**Comment by Bosn** [comment]
是RAP2导入到Postman哈，已经实现了。@gaochengyidlmu

**Comment by gaochengyidlmu** [comment]
好的，我先试试 @Bosn
