### ISSUE TITLE
是否支持后端接口测试？

### ISSUE THREAD

**Issue by baishengmei** [thx/rap2-delos#189]
是否可以利用rap2，根据定义好的请求接口生成请求发送到我们的后端接口进行测试？
如果可以的话，后端接口返回内容是否会与rap2中定义好的响应接口进行校验？

**Comment by Bosn** [comment]
功能开发基本都搞定了，但是还没对外开放。自动化测试ROOM平台，目前由 @alvarto 负责。

**Comment by honorew** [comment]
你好，请问现在这个功能开放了么？

**Comment by Bosn** [comment]
@honorew 和测试团队共建的，涉及内部业务较多，暂时对方未考虑开放。
