### ISSUE TITLE
能否支持map类型

### ISSUE THREAD

**Issue by Adol1111** [thx/rap2-delos#192]
目前rap只支持一些静态的key，比如"username","password"这些是已知的key
但是有些时候我们的key是一定规则的动态类型，比如日期、或者用户id等等，这种方式好像就没有办法表示了吧

```
{
    "2018-1-1":  [ .... ],
    "2018-1-2": [ .... ]
}
```
```
{
   "1": { "id": 1,"username": "aaa"},
   "2": { "id": 2,"username": "bbb" }
}
```

这些类型的数据能否有一种更好的描述方式

**Comment by Bosn** [comment]
此种情况，因为是动态的，整个map，属于一个属性。而规则的表示，可以参考Mock.js对于此种类型的支持，如果支持，按照其语法去写就好。

例如字段名：mapData, 
Mock数据： { "key1": [], "key2": []}
