### ISSUE TITLE
cannot compile by typescript, error as following...

### ISSUE THREAD

**Issue by fly2leoo** [thx/rap2-delos#195]
# ➜  node sudo cnpm install -g typescript
Password:
Downloading typescript to /usr/local/lib/node_modules/typescript_tmp
Copying /usr/local/lib/node_modules/typescript_tmp/_typescript@2.9.1@typescript to /usr/local/lib/node_modules/typescript
Installing typescript's dependencies to /usr/local/lib/node_modules/typescript/node_modules
All packages installed (used 3ms, speed 0B/s, json 0(0B), tarball 0B)
[typescript@2.9.1] link /usr/local/bin/tsc@ -> /usr/local/lib/node_modules/typescript/bin/tsc
[typescript@2.9.1] link /usr/local/bin/tsserver@ -> /usr/local/lib/node_modules/typescript/bin/tsserver
# ➜  node cd rap2-delos 
# ➜  rap2-delos git:(master) ls
Dockerfile         database           package.json       src                tsconfig.json
README.md          docker-compose.yml public             test               tslint.json
# ➜  rap2-delos git:(master) cnpm install
⠋ [53/65] Installing to-regex@^3.0.1  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
⠦ [56/65] Installing vizion@^0.2[pm2@2.10.4 › gkt@https://tgz.pm2.io/gkt-1.0.0.tgz] install gkt from remote https://tgz.pm2.io/gkt-1.0.0.tgz, may be very slow, please keep patience
⠸ [58/65] Installing sprintf-js@~1.0.2  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
⠦ [59/65] Installing is-promise@^2.1.0  LIBTOOL-STATIC Release/hiredis-c.a
⠦ [59/65] Installing array-uniq@^1.0.1  CXX(target) Release/obj.target/hiredis/src/hiredis.o
⠸ [59/65] Installing array-uniq@^1.0.1  CXX(target) Release/obj.target/hiredis/src/reader.o
⠙ [59/65] Installing array-uniq@^1.0.1  SOLINK_MODULE(target) Release/hiredis.node
✔ Installed 65 packages
✔ Linked 606 latest versions
node-pre-gyp http GET https://cdn.npm.taobao.org/dist/fsevents/v1.2.4/fse-v1.2.4-node-v59-darwin-x64.tar.gz
node-pre-gyp http 200 https://cdn.npm.taobao.org/dist/fsevents/v1.2.4/fse-v1.2.4-node-v59-darwin-x64.tar.gz
[fsevents] Success: "/Users/********/checkout/node/rap2-delos/node_modules/_fsevents@1.2.4@fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
✔ Run 4 scripts
anti semver sequelize-typescript@0.6.5 › @types/sequelize@4.27.14 › @types/bluebird@* delcares @types/bluebird@*(resolved as 3.5.20) but using ancestor(sequelize-typescript)'s dependency @types/bluebird@3.5.18(resolved as 3.5.18)
deprecate urllib@2.28.1 › proxy-agent@2.3.1 › socks-proxy-agent@3.0.1 › socks@^1.1.10 If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
Recently updated (since 2018-05-26): 16 packages (detail see file /Users/********/checkout/node/rap2-delos/node_modules/.recently_updates.txt)
  Today:
    → @types/koa@^2.0.43(2.0.46) (00:29:50)
    → standard@11.0.1 › eslint@4.18.2 › js-yaml@^3.9.1(3.12.0) (06:48:26)
✔ All packages installed (737 packages installed from npm registry, 1 packages installed from remote url, used 10s, speed 565.98kB/s, json 670(5.44MB), tarball 77.41kB)
# ➜  rap2-delos git:(master) cnpm run build

> rap2-delos@1.0.0 build /Users/******/checkout/node/rap2-delos
> rimraf -rf dist/ && tsc

node_modules/_sequelize-typescript@0.6.5@sequelize-typescript/lib/utils/types.d.ts:9:16 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

9     [P in Diff<keyof T, K>]: T[P];
                 ~~~~~~~


src/routes/organization.ts:160:9 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

160     ctx.prevAssociations = await reloaded.$get('members')
            ~~~~~~~~~~~~~~~~

src/routes/organization.ts:162:9 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

162     ctx.nextAssociations = await reloaded.$get('members')
            ~~~~~~~~~~~~~~~~


src/routes/organization.ts:177:12 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

177   if (!ctx.prevAssociations || !ctx.nextAssociations) return
               ~~~~~~~~~~~~~~~~

src/routes/organization.ts:177:37 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

177   if (!ctx.prevAssociations || !ctx.nextAssociations) return
                                        ~~~~~~~~~~~~~~~~


src/routes/organization.ts:178:21 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

178   let prevIds = ctx.prevAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~

src/routes/organization.ts:179:21 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

179   let nextIds = ctx.nextAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~


src/routes/repository.ts:256:9 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

256     ctx.prevAssociations = reloaded.members
            ~~~~~~~~~~~~~~~~

src/routes/repository.ts:259:9 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

259     ctx.nextAssociations = reloaded.members
            ~~~~~~~~~~~~~~~~


src/routes/repository.ts:285:12 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

285   if (!ctx.prevAssociations || !ctx.nextAssociations) return
               ~~~~~~~~~~~~~~~~

src/routes/repository.ts:285:37 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

285   if (!ctx.prevAssociations || !ctx.nextAssociations) return
                                        ~~~~~~~~~~~~~~~~


src/routes/repository.ts:286:21 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

286   let prevIds = ctx.prevAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~

src/routes/repository.ts:287:21 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

287   let nextIds = ctx.nextAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rap2-delos@1.0.0 build: `rimraf -rf dist/ && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mingmingruyue321** [comment]
node_modules/@types/koa-router/index.ts.d
 export interface IRouterContext extends Koa.Context {
        /**
         * url params
         */
        params: any;
    }
modify
 export interface IRouterContext extends Koa.Context {
        /**
         * url params
         */
        [params: string]: any;
    }

**Comment by mingmingruyue321** [comment]
node_modules/@type/koa-router/index.ts.d
export interface IRouterContext extends Koa.Context {
/**
* url params
/
params: any;
}
modify
export interface IRouterContext extends Koa.Context {
/*
* url params
*/
[params: string]: any;
}

**Comment by mingmingruyue321** [comment]
node_modules/@type/koa-router/index.ts.d
export interface IRouterContext extends Koa.Context {
/**
* url params
/
params: any;
}
modify
export interface IRouterContext extends Koa.Context {
/*
* url params
*/
[params: string]: any;
}

**Comment by AnInputForce** [comment]
我自己动手编译，报的错一模一样
楼上大神能补充详细点儿么？

**Comment by mingmingruyue321** [comment]
1、package.json 里"@types/koa": "^2.0.43", 去掉 ^ 改为 "@types/koa": "2.0.43"
2、 npm install
就可以了

**Comment by AnInputForce** [comment]
谢谢楼上的大神！
“does not exist on type 'IRouterContext'.”已解决了；
现在只剩下这个错误了：

`node_modules/_sequelize-typescript@0.6.5@sequelize-typescript/lib/utils/types.d.ts:9:16 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
Type 'string | number | symbol' is not assignable to type 'string'.
Type 'number' is not assignable to type 'string'.

9 [P in Diff<keyof T, K>]: T[P];
~~~~~~~`

继续求助 :)

**Comment by rikugun** [comment]
@AnInputForce 
修改 tsconfig.json
增加
`   
 "skipLibCheck":true,
`
https://github.com/RobinBuschmann/sequelize-typescript/issues/379

**Comment by AnInputForce** [comment]
多谢楼上大神，已按指点搞定。

**Comment by shinygang** [comment]
@mingmingruyue321 @rikugun 大神，我这边一直还是提示这些错误，而且还有
```
src/routes/organization.ts:177:12 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

177   if (!ctx.prevAssociations || !ctx.nextAssociations) return
               ~~~~~~~~~~~~~~~~


src/routes/organization.ts:177:37 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

177   if (!ctx.prevAssociations || !ctx.nextAssociations) return
                                        ~~~~~~~~~~~~~~~~


src/routes/organization.ts:178:21 - error TS2339: Property 'prevAssociations' does not exist on type 'IRouterContext'.

178   let prevIds = ctx.prevAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~


src/routes/organization.ts:179:21 - error TS2339: Property 'nextAssociations' does not exist on type 'IRouterContext'.

179   let nextIds = ctx.nextAssociations.map((item: any) => item.id)
                        ~~~~~~~~~~~~~~~~


src/routes/organization.ts:191:37 - error TS2339: Property 'body' does not exist on type 'Request'.

191   let { id, ownerId } = ctx.request.body
                                        ~~~~


src/routes/postman.ts:8:9 - error TS2339: Property 'data' does not exist on type 'IRouterContext'.

8     ctx.data = COMMON_ERROR_RES.ERROR_PARAMS
                                               ~~~~
```
求帮忙指导下。我tsc版本是2.9.2。
