### ISSUE TITLE
新建模块时报错

### ISSUE THREAD

**Issue by kwens** [thx/rap2-delos#198]
如题所述，
查询日志，报错如下：
![tim 20180604101012](https://user-images.githubusercontent.com/16912478/40894987-8fbde4ba-67df-11e8-9c29-b4de1d566a3d.png)

**Comment by Bosn** [comment]
请确认是否为最新的rap2-delos master分支的版本。该问题是之前已经修复过的BUG。通过更新代码可以解决。
