### ISSUE TITLE
数据库相关问题：缺少字段、事务等

### ISSUE THREAD

**Issue by xwillsu** [thx/rap2-delos#2]
1. 默认情况下`npm run create-db`使用的是哪个数据库配置：dev or prod？配置好prod之后，执行无反应；
2. 此文件提供的DDL语句缺少字段：
`rap2-delos/scripts/rap2_delos.sql`
table `interfaces`、`priority`、`properties`：缺少`priority`字段
table `loggers`缺少`creatorId`字段
3. 比较严重的一个问题是，没有增加**事务控制**
请核实

**Comment by Bosn** [comment]
1. 默认走的是生产，可以看到package.json中没有加任何的NODE_ENV, 所以在/config/index.js中会路由到prod, 如果想要使用别的配置，修改package.json中，script.create-db字段，在前面增加NODE_ENV=development 可以切换成开发模式，具体参考下其它script

2. 该文件并不是用于初始化的，如何初始化还是要看我的官方README，是通过Sequelize通过O/R Mapping自动创建。

3. 我没看到该项目事务控制的必要项，也因此不足以付出性能为大家来增加事务控制。

**Comment by xwillsu** [comment]
感谢如此细致的解答。前两个明白了，我是因为create-db没有执行成功才去翻那个sql文件的。
关于第三点，我倒是觉得此项目一般会被某个部门或者项目组部署到内网，对数据进行操作产生的并发应该不会太高，保证数据的完整性优先级稍高一些。

**Comment by Bosn** [comment]
每个人使用场景不一样，对于我们内部集团使用，或者官网rap2.taobao.org都存在较高的并发，RAP1之所以弃用，也是因为核心框架性能非常差，所以重做了RAP2。如果自己公司业务需要事务处理可以自己加一下。

**Comment by xwillsu** [comment]
OK，感谢！
