### ISSUE TITLE
npm run build 无法通过找不到解决方法

### ISSUE THREAD

**Issue by xgithub** [thx/rap2-delos#203]
node_modules/_sequelize-typescript@0.6.5@sequelize-typescript/lib/utils/types.d.ts:9:16 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

9     [P in Diff<keyof T, K>]: T[P];
                 ~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rap2-delos@1.0.0 build: `rimraf -rf dist/ && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rap2-delos@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-06T04_43_32_147Z-debug.log

**Comment by xgithub** [comment]
/root/.npm/_logs/2018-06-06T04_43_32_147Z-debug.log 日志内容


0 info it worked if it ends with ok
1 verbose cli [ '/work/opt/node/bin/node',
1 verbose cli   '/work/opt/node/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rap2-delos@1.0.0~prebuild: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~build: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~build: PATH: /work/opt/node/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/work/service/rap2-delos/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.8.0_25/bin:/usr/java/jdk1.8.0_25/jre/bin:/work/opt/node/bin:/root/bin
9 verbose lifecycle rap2-delos@1.0.0~build: CWD: /work/service/rap2-delos
10 silly lifecycle rap2-delos@1.0.0~build: Args: [ '-c', 'rimraf -rf dist/ && tsc' ]
11 silly lifecycle rap2-delos@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle rap2-delos@1.0.0~build: Failed to exec build script
13 verbose stack Error: rap2-delos@1.0.0 build: `rimraf -rf dist/ && tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/work/opt/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/work/opt/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd /work/service/rap2-delos
16 verbose Linux 2.6.32-131.0.15.el6.x86_64
17 verbose argv "/work/opt/node/bin/node" "/work/opt/node/bin/npm" "run-script" "build"
18 verbose node v8.11.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error rap2-delos@1.0.0 build: `rimraf -rf dist/ && tsc`
22 error Exit status 2
23 error Failed at the rap2-delos@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by Bosn** [comment]
请参考链接：https://github.com/thx/rap2-delos/issues/195

**Comment by xgithub** [comment]
感谢！
