### ISSUE TITLE
rap2网站不知道为什么会出现账号登陆不进去的情况

### ISSUE THREAD

**Issue by guoke360** [thx/rap2-delos#204]
之前注册了账号以后再另一台主机登陆时各种登陆不上去，明显密码是正确的返回值是204但是就是登陆不进去啊，这个是什么情况啊，是服务器问题，还是我们主机的问题呢

**Comment by Bosn** [comment]
亲，您记错密码的可能性比较大哦。如果是自己部署的服务，可以通过直接修改数据库密码（两次MD5）即可。如果是线上的，可以注册个新账号，让其他人把你重新加入到项目组。
