### ISSUE TITLE
标签有问题吧

### ISSUE THREAD

**Issue by moxiaonai** [thx/rap2-delos#207]
![image](https://user-images.githubusercontent.com/13172934/41074398-924aac92-6a3a-11e8-9457-a085631eb09c.png)

**Comment by Bosn** [comment]
😂😂😂感谢反馈，已记录，会尽快修复。

**Comment by Bosn** [comment]
哈哈哈哈，特意blame了下，发现1年前就有。赶紧艾特下BUG作者，哈哈哈哈哈

@nuysoft 已经修复了，下个版本更新就好了，小问题。
