### ISSUE TITLE
数据库密码加密方式是什么？

### ISSUE THREAD

**Issue by czkJQ** [thx/rap2-delos#21]

**Comment by webkong** [comment]
并没有加密吧？ 我看数据看都是原始值

**Comment by Bosn** [comment]
RAP1是两次MD5，RAP2还没加

**Comment by Bosn** [comment]
已添加md5加密，服务启动时会自动校验，会自动对历史密码进行双md5加密，如果加密成功不会再重复加密。具体参考上面commit code
