### ISSUE TITLE
数据类型选 function，写出的 js 报错的话整个仓库无法加载

### ISSUE THREAD

**Issue by xalexec** [thx/rap2-delos#214]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/3349091/41353405-bf875b7e-6f4e-11e8-9156-9ff2e09b6a53.png">

js 报错后会导致再个仓库无法加载，只能删除仓库

**Comment by Bosn** [comment]
收到，这是个严重BUG，会高优先级处理，谢谢。

**Comment by Bosn** [comment]
亲可以提供下DEMO吗？比如你function 如何填写的，我用funxxxction(){}  ,或者function(){return 111xxx111; } 这种做测试，系统都会自动识别，转成字符串，不会影响仓库的加载啊。

**Comment by Bosn** [comment]
可能是您用的语法规则刚好绕过了我们不完善的校验逻辑。麻烦提供点详细信息便于问题排查谢谢

**Comment by xalexec** [comment]
() => Mock.Random.guid()  截图上正好有

**Comment by Bosn** [comment]
好吧，我这里图裂了没看到图。。。尴尬

**Comment by Bosn** [comment]
rap2.taobao.org已发布修复

**Comment by xalexec** [comment]
rap2.taobao.org 并没有修复
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/3349091/42545556-45a1e8ee-84eb-11e8-898f-1feac41156ae.png">

**Comment by Bosn** [comment]
项目地址提供下看看

**Comment by xalexec** [comment]
http://rap2.taobao.org/repository/editor?id=17883

**Comment by Bosn** [comment]
已发布。其实说修复的时候就已经修复了，但是rap2.taobao.org官网更新是滞后的。
