### ISSUE TITLE
可以支持路径参数吗？

### ISSUE THREAD

**Issue by jayhuanggz** [thx/rap2-delos#216]
比如
GET：　/api/products/{id}
POST: 　/api/products/{id}
等等

**Comment by Bosn** [comment]
支持的啊，试一下就知道咯~~~不过参数是标准的RESTful， 这样/:id  而不是{id}

**Comment by jayhuanggz** [comment]
前几天都在忙其他事情，　今天试了，不行，不知道是不是设置不对，　请看一下截图
![screenshot from 2018-06-28 10 01 48](https://user-images.githubusercontent.com/37493681/42008874-5542a7d8-7aba-11e8-9b08-d257a404b471.png)

然后接口 /api/admin/programs/123　返回：

![screenshot from 2018-06-28 10 03 10](https://user-images.githubusercontent.com/37493681/42008902-7b3a85b4-7aba-11e8-8476-754ffe754ca1.png)

私有部署的2.3版本

**Comment by Caeson** [comment]
@jayhuanggz 您好，请问rap2是如何支持路径参数呢？谢谢！

**Comment by CocktailZY** [comment]
> 前几天都在忙其他事情，　今天试了，不行，不知道是不是设置不对，　请看一下截图
> ![screenshot from 2018-06-28 10 01 48](https://user-images.githubusercontent.com/37493681/42008874-5542a7d8-7aba-11e8-9b08-d257a404b471.png)
> 
> 然后接口 /api/admin/programs/123　返回：
> 
> ![screenshot from 2018-06-28 10 03 10](https://user-images.githubusercontent.com/37493681/42008902-7b3a85b4-7aba-11e8-8476-754ffe754ca1.png)
> 
> 私有部署的2.3版本

同样的问题，请问解决了吗

**Comment by jayhuangessue** [comment]
没有解决，一直都不行也没人解决，　都懒得再在这里问了

**Comment by jayhuangessue** [comment]
> > 前几天都在忙其他事情，　今天试了，不行，不知道是不是设置不对，　请看一下截图
> > ![screenshot from 2018-06-28 10 01 48](https://user-images.githubusercontent.com/37493681/42008874-5542a7d8-7aba-11e8-9b08-d257a404b471.png)
> > 然后接口 /api/admin/programs/123　返回：
> > ![screenshot from 2018-06-28 10 03 10](https://user-images.githubusercontent.com/37493681/42008902-7b3a85b4-7aba-11e8-8476-754ffe754ca1.png)
> > 私有部署的2.3版本
> 
> 同样的问题，请问解决了吗

没有，　一直不行也没人解决，　都懒得再在这里问了
