### ISSUE TITLE
接口不能定义多个入参条件，有点弱鸡

### ISSUE THREAD

**Issue by latel** [thx/rap2-delos#217]
现在一个接口，分很多入参条件很正常把，现在只能一个条件定义一个接口，参数多了很麻烦，没法聚合
![image](https://user-images.githubusercontent.com/5621862/41583733-f7e2694a-73d7-11e8-805f-4bc077740516.png)

-----华丽的分割线-----

可能没说清楚，事实时很多接口都需要根据入参的不同返回不同格式的数据，现在好像没法支持。个人觉得这是一个很常见的需求。

**Comment by Bosn** [comment]
你说“根据不同呢参数返回不同的格式的数据”

RAP中的一个接口，更明确的说，就是一种格式。所以你这样写没问题，也有必要。不然你预期如何让系统去记录你所有的格式呢？（如果你不分开去给出这些不同的格式）。

**Comment by latel** [comment]
是不是可以收纳到一个接口里， 定义响应内容那一块的时候增加一个请求参数的判断，不然入参条件多了，组合起来，左侧的列表可就太多了

**Comment by xiaoxing598** [comment]
@latel 你指的是参数的位置？一个是在请求地址后面，另一个是包含在POST请求体中？

**Comment by latel** [comment]
post请求体

**Comment by Bosn** [comment]
@latel 嗯，做接口的分组管理是一个好办法，其实对于这种多种结构的接口，建议您也可以直接新建个TAB就好了，TAB也可以有分组的作用。

**Comment by forrestchang** [comment]
> @latel 嗯，做接口的分组管理是一个好办法，其实对于这种多种结构的接口，建议您也可以直接新建个TAB就好了，TAB也可以有分组的作用。

这个和接口分组没关系吧，就是同一个接口使用不同的参数，返回值应该根据传入的参数来确定。

例如：

```
GET /example?version=1 ==> {'resp': 'versio 1'}
GET /example?version=2 ==> {'resp': 'version 2'}
```
