### ISSUE TITLE
如何使用rap2进行真实接口的数据格式校验

### ISSUE THREAD

**Issue by zhangkyou** [thx/rap2-delos#218]
1.如何使用这个仓库的点“测试”生成的文件，test/test.plugin.jquery.html?id=:interfaceid
2.接口 app/mock/schema/:interfaceid?scope=request返回的数据不是标准的json-schema，如何用配置的模板数据来校验真实接口的数据格式呢？

**Comment by Bosn** [comment]
1. 主菜单点“接口“，了解一下？插件后面有个”用法“按钮
2. 强校验目前我们在内部产品ROOM中已经落地和完善，放出来的时间，可以咨询有关负责人 @alvarto

**Comment by Tomihaohao** [comment]
我也想知道 怎么进行真实接口效验？ 而且前后端分离的 很多都是SPA 应用 提供的  插件感觉没用。。

**Comment by zhangkyou** [comment]
@Bosn 为什么申请加钉钉群很久了，都没有通过。。。

**Comment by Bosn** [comment]
@zhangkyou
没收到申请，群号码“RAP West World”群的钉钉群号： 11789704
再试试？

**Comment by zhangkyou** [comment]
@Bosn 申请了好多回了，不知道为什么你们收不到

**Comment by Bosn** [comment]
不了解，群里加了300人，为什么就您一直无法添加。是否号码被禁了？也可以钉钉单独加我试试。我的钉钉是18611877328
