### ISSUE TITLE
请问在rap上怎样使用mock的path数据模版

### ISSUE THREAD

**Issue by willmynew** [thx/rap2-delos#220]
<img width="1206" alt="wechatworkscreenshot_306afd48-6233-4957-8763-faafb1c06f78" src="https://user-images.githubusercontent.com/4137034/41772163-1ed5a200-764a-11e8-9f9f-62bcee8b30b3.png">
如图：如果数据在同级的话，我直接使用@就可以取到。

我在mock的官网 [http://mockjs.com/examples.html#Path]( http://mockjs.com/examples.html#Path) 中看到可以这样取到父级的属性值
<img width="1031" alt="wechatworkscreenshot_c410b636-e337-476f-9adf-8256c1e3a657" src="https://user-images.githubusercontent.com/4137034/41772341-cbc007da-764a-11e8-89da-bf2254055aa1.png">

我想请教的是：在rap中能使用mock的path?

**Comment by Bosn** [comment]
RAP本质上，只是生成了Mock.js模板，从`模板`到`数据`，是完全由Mock.js来决定的。

所以只要生成了模板，模板是否支持，完全取决于Mock.js。
