### ISSUE TITLE
请问有详细的从 rap1 导入数据到 rap2 教程吗？

### ISSUE THREAD

**Issue by bugyak** [thx/rap2-delos#224]
包括项目，帐号等。

**Comment by bugyak** [comment]
钉钉群申请了一直没通过了=

**Comment by blackdog1987** [comment]
rap2自带了项目的迁移方法
至于你说的账号等信息，我在钉钉群里传了一个word文档，你按照那个思路试试

**Comment by bugyak** [comment]
进不去群啊。

**Comment by Bosn** [comment]
钉钉群号码：11789704

要么您输错了号，或者用的不是钉钉。里面300多人了，您放心，号码肯定没问题的。

**Comment by bugyak** [comment]
我刚又申请了一遍……还是没通过。

**Comment by bugyak** [comment]
为什么我的申请加群还没通过……

**Comment by Bosn** [comment]
可能是没缘分

**Comment by Bosn** [comment]
![](http://chuantu.biz/t6/349/1532676737x-1566683172.png)
已经336人，就你加不进去，我也知道哟~~~~

**Comment by bugyak** [comment]
@Bosn 嗯，我是用钉钉，但是提交了加群申请一直没有被通过。

**Comment by bugyak** [comment]
![img_7444](https://user-images.githubusercontent.com/7711294/44512351-cd338b00-a6ec-11e8-8fb3-291577afdc47.jpg)
