### ISSUE TITLE
bug:导出postman后url异常

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#227]
1. 导出到postman后，请求的url丢失。（rap2中的接口写的是相对路径，/project/env/list）
2. post方式导出后，请求的参数是url的方式，后端接受参数是根据RequestBody接受的参数（postman中的传参方式应该是body。

期望结果：
![aa1](https://user-images.githubusercontent.com/2356974/42070344-72e9484a-7b88-11e8-9a06-5eb9a0c8cc76.png)

实际结果：
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2356974/42070361-851b8e92-7b88-11e8-92d8-10729d184777.png">

**Comment by zhangkyou** [comment]
我的也是这个情况，召唤大神@Bosn

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-delos/commit/443db96b62804cb53107890c41cf9c8f2d03df78

**Comment by Bosn** [comment]
问题1： fixed
问题2：RAP2确实存在缺陷，并没有区分参数是GET QUERY还是BODY FORMDATA，以及是raw / file 还是 form，所以问题2将在RAP2完善该问题的补全后解决。

**Comment by blackdog1987** [comment]
@Bosn postman url的问题依然存在

![image](https://user-images.githubusercontent.com/2356974/42155101-05833f6a-7e1a-11e8-83e1-b157db18aa0d.png)

**Comment by Bosn** [comment]
@blackdog1987 master代码仓库已经提交了，官网DEMO站点 rapapi.org 会滞后。建议您部署下本机试一试。

**Comment by heartdong** [comment]
master代码目前还是不是能解决第二个问题的，解决办法
找到src\service\postman.ts这个代码，替换下面这个方法即可解决
```
function getBody(pList: Property[]) {
  return {
    "mode": "urlencoded" as "urlencoded",
    "urlencoded": pList.filter(x => x.pos === REQUEST_PARAMS_TYPE.BODY_PARAMS)
      .map(x => ({ key: x.name, value: x.value, description: x.description, type: "text" as "text"})),
  }
}
```
