### ISSUE TITLE
导出到postman支持动态url

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#228]
导出到postman后，url为动态url，比如： {{url}}/user/add。然后添加环境变量url，值设置为mock地址，便于切换环境。postman的截图如下：

![aa1](https://user-images.githubusercontent.com/2356974/42068159-f95e26c2-7b7c-11e8-8c22-d0994b36cd7f.png)
![aa2](https://user-images.githubusercontent.com/2356974/42068163-fba48502-7b7c-11e8-8910-0408884275eb.png)
![aa3](https://user-images.githubusercontent.com/2356974/42068164-fe45e346-7b7c-11e8-91a2-84cee3b90e7a.png)

**Comment by Bosn** [comment]
Added. commits will be pushed today.
