### ISSUE TITLE
rap1导入报错

### ISSUE THREAD

**Issue by bailnl** [thx/rap2-delos#229]
应该是编解码导致了问题 
![wechatworkscreenshot_fe6d8e9d-d946-45fd-ae6e-0ba097b81e86](https://user-images.githubusercontent.com/2436993/42071440-c71c3562-7b8d-11e8-9a9d-f6b5c37b222a.png)
这样就好了
![image](https://user-images.githubusercontent.com/2436993/42071465-eba97674-7b8d-11e8-9428-25c37a166294.png)

**Comment by Bosn** [comment]
fixed
