### ISSUE TITLE
怎样在linux后台运行？

### ISSUE THREAD

**Issue by gudujian77** [thx/rap2-delos#23]
我使用nohup执行npm start，会话界面退出后，就会关闭，请问需要怎么样执行？
nohup npm start >nohup.out 2>&1 &

**Comment by SunnySunning** [comment]
同问+1

**Comment by new0211032** [comment]
我是装了个nodejs的插件：pm2

**Comment by huanglins** [comment]
pm2 怎么启动。 pm2 start 这种不行吧，没有 app.js 。

**Comment by Bosn** [comment]
### 以开发模式为例
```shell
nohup npm start &
```
这样就可以后台执行
