### ISSUE TITLE
Bug: Rap1->Rap2，仓库迁移报错

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#236]
导入以下URL报错：

http://rapapi.org/workspace/myWorkspace.do?projectId=35379#358227

<img width="937" alt="image" src="https://user-images.githubusercontent.com/2356974/42565007-dca4e0e0-8534-11e8-8396-e281ca149620.png">

**Comment by Bosn** [comment]
最新版本测试导入正常，请确认版本。另外官网rap2.taobao.org其实会比master版本会滞后一些。
