### ISSUE TITLE
接口编辑，相应内容导入json时候保存保存，但刷新的时候却看到了数据，之后数据格式不对，`data`是个列表，`sysUserId`是列表的内容却跑到了和`data`的同一级去。

### ISSUE THREAD

**Issue by SamlenTsoi** [thx/rap2-delos#244]
![image](https://user-images.githubusercontent.com/23205343/42856464-fadf96c0-8a77-11e8-9bde-e696c2d95380.png)
![image](https://user-images.githubusercontent.com/23205343/42856650-b46cf524-8a78-11e8-80a4-f816a3e92379.png)
![image](https://user-images.githubusercontent.com/23205343/42856523-2e06bda8-8a78-11e8-829a-d1e3ba065a35.png)

**Comment by Bosn** [comment]
没看懂您想表达什么....

**Comment by SamlenTsoi** [comment]
就是Json导入数据时，如果是数组的话，导入后的数据不正确。

**Comment by Bosn** [comment]
麻烦提供可复现的测试数据，按照模板重新提交下ISSUE，谢谢。
