### ISSUE TITLE
rap1的接口版本功能没有了？

### ISSUE THREAD

**Issue by JasmineChoi** [thx/rap2-delos#246]
rap2接口看不到版本控制功能。rap1原有的慢存上有创建版本的功能，rap2上没有了？

**Comment by Bosn** [comment]
RAP2是新产品，RAP1的部分功能会逐步迁移。

**Comment by Bosn** [comment]
版本管理确实暂时还没有，我们会逐步添加所有缺失的功能。

**Comment by JasmineChoi** [comment]
那要什么时候上线版本控制的功能

**Comment by Bosn** [comment]
RAP1要迁移的功能，以及我们自己计划的功能很多，单一功能我们没有排期。

**Comment by JasmineChoi** [comment]
rap2完整上线后，rap1文档可以直接转成rap2吗

**Comment by Bosn** [comment]
rap2一直都是完整上线，公司内部也在一年前就切换到RAP2了。

RAP2提供了导入仓库功能（从RAP1），具体麻烦自己研究一下。

**Comment by Bosn** [comment]
issues里搜索“导入”

**Comment by JasmineChoi** [comment]
好的，谢谢
