### ISSUE TITLE
根据resquest来生成response

### ISSUE THREAD

**Issue by njleonzhang** [thx/rap2-delos#250]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
比如，我想让后台返回一个含有20个元素的列表，我把20作为一个参数带了过去。RAP2 能读这个参数来生成结果么？

**Comment by Bosn** [comment]
RAP1是有的，RAP2还没实现。这个我们肯定会实现的。

**Comment by JesseZhao1990** [comment]
@Bosn 这个功能非常关键。我们从rap1迁移到rap2之后发现没这个功能。根本没法跑起来。又用回rap1了

**Comment by Bosn** [comment]
#### 如何引用请求参数？
在初始值中填写`$参数名$`，RAP2 Mock服务会根据实际的传参将其替换为实际传入值。例如字段`param`填写初始值`$xxx$`，当收到请求`url?xxx=123`时，实际返回值为`{ "param": "123" }`

**Comment by njleonzhang** [comment]
@Bosn 似乎并没有用啊。
