### ISSUE TITLE
新增Dashboard

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#252]
在使用的过程中，各个团队的leader（或者是rap仓库管理员）需要查看一些统计信息。具体的展现形式需要承虎大哥帮忙想想了。
现在rap2中的【状态】一栏的内容更像是一个“宣传”性质的页面，而不是对”管理“设计的。
比如，团队的leader可能需要知道，按日、周、月，新增接口的数量，修改接口的数量，接口mock的数量。每个团队成员在各个仓库中的提交次数，分别创建了多少接口，等等。
目前数据层面好像也不支持这些数据，如果支持的话，我们可以通过自己的一个dashboard里去调用一个接口爬取数据。当然我们也能自己去扫库，不过数据库是可能会改变表结构的。

**Comment by Bosn** [comment]
很抱歉，官方暂时不考虑实现该需求。
