### ISSUE TITLE
模块之间的排序拖动204

### ISSUE THREAD

**Issue by flyCatOne** [thx/rap2-delos#255]
**BUG描述**

模块之间的排序拖动没有成功。
**复现步骤**
如题

**期望结果**
排序成功

**实际结果**
排序实际未成功

**截图**

**自建服务器还是使用了rap2.taobao.org**
如果是自建服务器，提供操作系统版本

**附加信息**
Request URL: http://rap2api.taobao.org/module/sort
Request Method: OPTIONS
Status Code: 204 No Content
Remote Address: 118.190.87.105:80
Referrer Policy: no-referrer-when-downgrade

**Comment by Bosn** [comment]
fixed

**Comment by Bosn** [comment]
commit: https://github.com/thx/rap2-delos/commit/eae07f1e476da06d9c19c0ffa86fab134ad58bab
