### ISSUE TITLE
RAP1怎么升级RAP2？

### ISSUE THREAD

**Issue by jianhao84** [thx/rap2-delos#257]
RAP1怎么升级RAP2？

**Comment by Bosn** [comment]
两系统完全独立，欲升级请看README

**Comment by Bosn** [comment]
RAP2是全新架构设计的，和RAP1没什么关系。重新建立RAP2就好，但是RAP2有从RAP1仓库导入的功能。可以用来迁移数据。

**Comment by jianhao84** [comment]
Rap1上说会出迁移工具。。。如果升级不能向下兼容，那。。。。

发件人: Bosn [mailto:notifications@github.com] 
发送时间: 2018年7月23日 9:57
收件人: thx/rap2-delos <rap2-delos@noreply.github.com>
抄送: jianhao84 <287360083@qq.com>; Author <author@noreply.github.com>
主题: Re: [thx/rap2-delos] RAP1怎么升级RAP2？ (#257)

 

RAP2是全新架构设计的，和RAP1没什么关系。重新建立RAP2就好，但是RAP2有从RAP1仓库导入的功能。可以用来迁移数据。

**Comment by Bosn** [comment]
迁移工具，就是仓库迁移啊。整库的迁移，其实遍历下调个API并不是很难。

两个数据库不同账号体系，你想要什么样的迁移规则，自己决定。

**Comment by jianhao84** [comment]
Rap2的仓库导入功能在哪里？能指导下吗？是批量导入还是单个的？

 

发件人: Bosn [mailto:notifications@github.com] 
发送时间: 2018年7月23日 9:57
收件人: thx/rap2-delos <rap2-delos@noreply.github.com>
抄送: jianhao84 <287360083@qq.com>; Author <author@noreply.github.com>
主题: Re: [thx/rap2-delos] RAP1怎么升级RAP2？ (#257)

 

RAP2是全新架构设计的，和RAP1没什么关系。重新建立RAP2就好，但是RAP2有从RAP1仓库导入的功能。可以用来迁移数据。

**Comment by Bosn** [comment]
自己搜索下？

**Comment by jianhao84** [comment]
好的，3q

 

发件人: Bosn [mailto:notifications@github.com] 
发送时间: 2018年7月23日 11:14
收件人: thx/rap2-delos <rap2-delos@noreply.github.com>
抄送: jianhao84 <287360083@qq.com>; Author <author@noreply.github.com>
主题: Re: [thx/rap2-delos] RAP1怎么升级RAP2？ (#257)

 

自己搜索下？
