### ISSUE TITLE
页面立刻卡死

### ISSUE THREAD

**Issue by iYoullloveGitHub** [thx/rap2-delos#259]
**BUG描述**
新建接口, 新建 字段 pz, 将
浙@cword(ABCDEFGH)@cword(0123456789,4)   复制 到 初始值,页面立刻卡死

**复现步骤**
100%复现

**期望结果**

**实际结果**

**截图**

**自建服务器还是使用了rap2.taobao.org**
如果是自建服务器，提供操作系统版本

**附加信息**

**Comment by Bosn** [comment]
经测试，该问题为Mock.js的BUG，可通过调用Mock.mock('浙@CWord(ABCDEFGH)@CWord(0123456789,4)')复现。

请在mock.js的repo提issue
请@nuysoft 关注
