### ISSUE TITLE
首次加载需手动执行数据库init

### ISSUE THREAD

**Issue by linjinze999** [thx/rap2-delos#260]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在k8s部署时，首次部署delos需要执行数据库init，后续不需要，不符合部署原则

**您是否有建议的实现方案**
可否在init脚本中判断已经init过。每次构建都会执行Init脚本，但后续不会再去初始化数据库

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
不知道什么是k8s，init是自行控制的。跑一次就行了，为啥要多次跑init呢？

**Comment by linjinze999** [comment]
Kubernetes是当前开源使用最多的容器管理平台，类似此文中的docker-compose功能，它管理多个主机，保证应用高可用。在设计原则中，同一个应用，是不建议刚开始有一个init的yaml文件，然后删掉再创建没有Init的yaml文件的

**Comment by Bosn** [comment]
scripts里面对于init/build/dev/start都有明确的定义。自己调用哪个，调用几次，都是自己控制的。

具体使用什么工具，自己去配置。和scripts本身没有关系。
