### ISSUE TITLE
dolores

### ISSUE THREAD

**Issue by linjinze999** [thx/rap2-delos#261]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
希望dolores前端也能容器化，支持后台地址配置

**您是否有建议的实现方案**
希望dolores前端也能容器化，支持后台地址配置

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
1. 一直都支持后台地址配置，就在config.*.js
2. 纯静态的React App没有容器化的必要。想用nginx / apache / serve 自便。build完成后，不过就是一个index.html + js

**Comment by linjinze999** [comment]
1. 配置是希望容器里的配置，我们利用k8s部署，仍然需要自己手动构建一个镜像。
2. 能否为项目节点打tag，目前较难找到稳定版本的节点。同时希望前端dolores和后台delos有大致的版本对应关系，避免新前端使用旧后台版本，或者反过来。
