### ISSUE TITLE
接口修改地址和描述不能保存

### ISSUE THREAD

**Issue by moyifeng2000** [thx/rap2-delos#262]
**BUG描述**
接口修改地址和描述不能保存

**复现步骤**
新建一个接口保存.然后在点修改,修改地址和描述点保存,地址和描述恢复到之前的内容.跟踪发现post数据只有参数明细的数据,并没有传送表头的修改信息.
![default](https://user-images.githubusercontent.com/20902163/43130625-afe35f0c-8f69-11e8-801f-49d07183d03b.png)
![default](https://user-images.githubusercontent.com/20902163/43130666-bcb2441e-8f69-11e8-96eb-3da669ff3e22.png)

**期望结果**
接口修改地址和描述可以保存

**实际结果**

**截图**

自建服务器
如果是自建服务器，提供操作系统版本
centos7   rap 2.3

**附加信息**

**Comment by Bosn** [comment]
版本应该过期了，更新到最新代码就好了。

参数区上方去修改URL已经取消掉了。因为左边接口名字那里已经有小铅笔修改的位置了。

**Comment by Bosn** [comment]
可以参考下rap2.taobao.org上面的效果，现在点编辑，不会编辑接口的信息。接口信息在左侧接口名字旁小铅笔按钮单独修改。
