### ISSUE TITLE
接口的入参校验

### ISSUE THREAD

**Issue by kkroy-zs** [thx/rap2-delos#264]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
对于接口定义，目前入参只有定义，却没有校验，与rap2的接口调用时，甚至可以不输入任何参数即可得到mock数据。与后端联调时，前端由于没有设置或设置错误入参导致发生的问题很多。

**您是否有建议的实现方案**
入参的逻辑校验可以非常复杂，但并不是所有校验都需要做。
所以只做必填项及参数是否在参数列表中的校验应该就可以满足前后端联调的基本需求了。
但一旦校验出现错误，返回一个4xx的自定义状态码，并在response body中加入错误内容。

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
已添加，请关注今天稍晚时间的push
