### ISSUE TITLE
新增请求参数,然后保存,参数未保存成功,但页面未提示任何错误

### ISSUE THREAD

**Issue by zhanngle** [thx/rap2-delos#266]
**BUG描述**
我是刚刚使用docker部署了rap2,页面可以登录,可以新增团队,新增仓库,新增接口,然后为接口新增参数,再保存,参数未保存成功,但页面没有提示任何错误

**复现步骤**
打开一个接口,新增请求参数,保存

**期望结果**
新增的参数能保存成功

**实际结果**
参数未保存成功

**截图**

**自建服务器还是使用了rap2.taobao.org**
自建服务器,在centos7中,使用Docker部署

**附加信息**

**Comment by Bosn** [comment]
确认代码更新到最新版本了吗
