### ISSUE TITLE
自建服务器应该clone那个分支？

### ISSUE THREAD

**Issue by catqware** [thx/rap2-delos#267]
**BUG描述**
我clone了master的，使用docker构建，但是无法正常使用。比如刷新报错，删除模块无效，删除接口无效，新增接口无效，退出无效，查看全部仓库报错....

**复现步骤**

**期望结果**

**实际结果**

**截图**

**自建服务器还是使用了rap2.taobao.org**
如果是自建服务器，提供操作系统版本

**附加信息**

**Comment by Bosn** [comment]
master即可，报错是配置环境的问题。可以加群和网友互帮互助

**Comment by Bosn** [comment]
钉钉群号码见README
