### ISSUE TITLE
需求：增加接口（仓库）版本设计

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#269]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我们目前会同时使用多个版本的接口，老接口会逐步弃用，测试会基于其中某一个版本进行测试。目前只能通过不停的创建仓库来达到目的。

**您是否有建议的实现方案**
rap1是有仓库版本的概念的，可能是得益于原来的数据库设计中，存在一个大字段用于保存所有的仓库json格式的信息（类似nosql）。所以rap1是可以随时进行版本的切换的。建议rap2中添加版本的控制。

**其它帮助我们理解您需求的描述、截图**
<img width="810" alt="image" src="https://user-images.githubusercontent.com/2356974/43385099-7205134e-9412-11e8-8453-867543a6c61b.png">

**Comment by blackdog1987** [comment]
添加了该功能后，数据量可能会剧增。性能可能会受到影响。

**Comment by Bosn** [comment]
完整版本控制，实现起来成本较大。个人觉得可以先实现DIFF LOG，显示更新记录以及具体更新了哪些字段，如：

**Comment by Junsion** [comment]
前期DIFF LOG的形式可以满足初步需求，是否有在开发计划内？

**Comment by Bosn** [comment]
版本功能。。。暂时，还没有人力和排期。HOLD.

**Comment by asynclog** [comment]
> 版本功能。。。暂时，还没有人力和排期。HOLD.

版本管理功能, 最新有计划吗?

**Comment by weifengtang** [comment]
现在有计划排期吗

**Comment by wonderomg** [comment]
同求
