### ISSUE TITLE
编辑时需要锁定文档，锁定文档要在单个tab上，不能是项目或仓库。

### ISSUE THREAD

**Issue by airing0805** [thx/rap2-delos#27]
在0.14版本的时候，文档会提示被锁定。这个功能非常好。锁定的范围不最好能锁定到tab页的级别，不要锁定到整个项目。
多个人同时编辑接口文档时，在0.14版本的时候通过项目来切分，避免冲突，但是查看接口文档时非常不方便。如果在0.14的基础上，锁定文档能只锁定到tab，使用起来会非常方便。

**Comment by Bosn** [comment]
RAP2锁定是在接口级的，只要没有同时编辑同一个接口就不会引发冲突。这也是RAP2重构的核心目的之一。
