### ISSUE TITLE
nohup serve *** -p 3000 & 短暂运行后服务自动down

### ISSUE THREAD

**Issue by lilaizhencn** [thx/rap2-delos#271]
**BUG描述**
nohup serve *** -p 3000 & 短暂运行后服务自动down

**复现步骤**
1. nohup serve *** -p 3000 & 启动
2.打开页面 观察
3.等待10分钟左右
4.服务就自动down

**期望结果**
nohup后不要down

**实际结果**

**截图**

**自建服务器还是使用了rap2.taobao.org**
如果是自建服务器，提供操作系统版本

自建的服务器  centos 7.4
**附加信息**

**Comment by Bosn** [comment]
系统运维问题。。。pm2了解一下，另外DOWN掉要么内存，要么致命错误自己查日志。本社区不负责基础运维教学请自行查询，或加群和群友共同互帮互助。
