### ISSUE TITLE
rap2文档备份和导入

### ISSUE THREAD

**Issue by JasmineChoi** [thx/rap2-delos#273]
rap2没有文档备份和导入功能。如果不小心把某个仓库，或模块删除，那所有文档都将丢失。

![default](https://user-images.githubusercontent.com/15829284/43567876-aee2eea8-9665-11e8-8574-9b3f62448f70.png)
虽然在仓库上方可以查看并保存完整json数据，但是无法直接导入成文档

**Comment by Bosn** [comment]
该功能尚无，且暂时没有对应规划。

**Comment by keshunchen** [comment]
备份的功能希望考虑一下，尤其不是自己搭建而是直接使用RAP2.TAOBAO.ORG没备份心里不踏实

**Comment by lzqiang** [comment]
rap2 通过json导入的时候  注释字段值怎么导入
