### ISSUE TITLE
npm run create-db报错

### ISSUE THREAD

**Issue by puzhaoqi** [thx/rap2-delos#274]
**BUG描述**
安装README.md中操作，前面都是对的。npm run create-db报错
**复现步骤**

**期望结果**

**实际结果**

**截图**
<img width="467" alt="qq20180803-111314 2x" src="https://user-images.githubusercontent.com/10040900/43622348-45665830-970e-11e8-9353-ebfc340e25e6.png">
<img width="948" alt="qq20180803-111234 2x" src="https://user-images.githubusercontent.com/10040900/43622352-48a533fe-970e-11e8-9a59-78da516e4e2c.png">

**自建服务器还是使用了rap2.taobao.org**
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
node v10.8.0
MySQL 5.7.23 
redis 4.0.10
**附加信息**

**Comment by puzhaoqi** [comment]
<img width="1006" alt="qq20180803-153209 2x" src="https://user-images.githubusercontent.com/10040900/43630956-5903d6ee-9734-11e8-90c9-4e8196093c59.png">

**Comment by puzhaoqi** [comment]
<img width="1037" alt="qq20180803-170210 2x" src="https://user-images.githubusercontent.com/10040900/43634551-fd1f9538-973e-11e8-8411-60491ae539ef.png">
<img width="693" alt="qq20180803-170045 2x" src="https://user-images.githubusercontent.com/10040900/43634553-fe30c564-973e-11e8-808d-71a5aeb886cd.png">

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-delos/commit/2ae02a800fab1a8d759609b32857ac51dead9f84
