### ISSUE TITLE
导入数据保存失败

### ISSUE THREAD

**Issue by dongxicc** [thx/rap2-delos#276]
**BUG描述**
导入从postman响应数据，成功
点击保存，无响应，发现后端返回错误报错
查找原因，发现有的字段类型解析为Null，页面显示String，但保存传给后端是 null
因此在数据库 Propertites 表 type 添加枚举值 Null ， 可以提交成功 但前台页面显示Null
**复现步骤**

**期望结果**

**实际结果**

**截图**

**自建服务器还是使用了rap2.taobao.org**
如果是自建服务器，提供操作系统版本
自建服务器。。ubuntu server 1804

**附加信息**

**Comment by Bosn** [comment]
麻烦提供完整报错信息，不然无法排查
