### ISSUE TITLE
第一次使用rap2，通过pc访问，访问不了，consol提示错误

### ISSUE THREAD

**Issue by Hideer** [thx/rap2-delos#277]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

通过pc访问的时候提示这样的错误
`
Failed to load http://rap2api.taobao.org/account/info: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://rap2.taobao.org' is therefore not allowed access.
`
注：同网段下，手机能访问

**Comment by Bosn** [comment]
浏览器版本？

**Comment by Bosn** [comment]
请新开“BUG反馈帖” 按格式反馈详细信息。
