### ISSUE TITLE
『Function类型』不起作用了

### ISSUE THREAD

**Issue by fanjieqi** [thx/rap2-delos#278]
**BUG描述**
前后端都拉了最新的代码下来，原先设置为『Function类型』的示例参数，现在预览下来参数名固定为了『string』，然后模拟值变成了函数自身的文本字符串。

**复现步骤**
就是当前最新的代码。

**期望结果**
Function类型能正常工作。

**实际结果**
Function类型未能正常工作。

**截图**
![image](https://user-images.githubusercontent.com/5510776/43874371-19b63b4c-9bbe-11e8-91f3-a78eec812657.png)

**环境**
Chrome 67.0.3396.99

**附加信息**

**Comment by Bosn** [comment]
经排查 @alvarto 在Tree.js中的case 'Function' 中修改了一些代码导致该问题，修复中...

**Comment by Bosn** [comment]
fixed, 请关注近期的push。预计在今晚
