### ISSUE TITLE
rap2编辑接口 输入正则报错

### ISSUE THREAD

**Issue by JohnWang0930** [thx/rap2-delos#279]
**BUG描述**
rap2编辑接口 输入正则报错

**复现步骤**
1创建接口
2编辑接口 修改接口类型为正则
3输入 // 后在双斜杠中输入{}

**期望结果**
正常输入

**实际结果**
console报错，页面变白

**截图**
![image](https://user-images.githubusercontent.com/30688319/43874749-129f595e-9bc0-11e8-94af-871d46848a9d.png)

**环境**
* 自建服务器：系统centos
* 浏览器：chrome

**附加信息**

**Comment by Bosn** [comment]
// 被判为注释？为什么要加//

**Comment by JohnWang0930** [comment]
因为要写正则 想着写的方便点就先写了// 
然后在双斜杠里面再写相关正则

**Comment by Bosn** [comment]
最新版本已fixed
