### ISSUE TITLE
要保留0.14版本的路由功能

### ISSUE THREAD

**Issue by airing0805** [thx/rap2-delos#28]
要保留0.14版本的路由功能，看到2版本有这个功能，最好是保留下来。我们的接口通过代理配置，没有路由会增加很多的配置项，代码实现起来也不难。

**Comment by Bosn** [comment]
亲说的路由是URL匹配的一些规则对吧，这个肯定要有的，是很核心的功能。

**Comment by Bosn** [comment]
关于不同仓库共享的问题，请仔细看下创建项目时的协作库ID设置那里
