### ISSUE TITLE
注册不了账号

### ISSUE THREAD

**Issue by puzhaoqi** [thx/rap2-delos#280]
**BUG描述**
注册不了账号

**复现步骤**

**期望结果**

**实际结果**

**截图**

<img width="998" alt="qq20180810-093426 2x" src="https://user-images.githubusercontent.com/10040900/43934196-a34df468-9c80-11e8-9361-429656568a3c.png">

**环境**
redis: 4.0.9
5.7.23 MySQL
node: v10.8.0

**附加信息**

**Comment by Bosn** [comment]
数据库连接错

本REPO不负责环境安装答疑。
