### ISSUE TITLE
响应参数导入json后有问题

### ISSUE THREAD

**Issue by puzhaoqi** [thx/rap2-delos#281]
**BUG描述**
如图，venues中的对象，导入前有五个不一样的，导入后，都成了第一个

**复现步骤**

**期望结果**
导入后是不一样的对象

**实际结果**

**截图**
<img width="276" alt="wx20180810-215151 2x" src="https://user-images.githubusercontent.com/10040900/43961532-cddd2200-9ce7-11e8-9838-a23ecb3fff57.png">
<img width="299" alt="wx20180810-215216 2x" src="https://user-images.githubusercontent.com/10040900/43961542-d46b9980-9ce7-11e8-948c-d22396af3fb8.png">

**环境**
http://rap2.taobao.org/

**附加信息**

**Comment by Bosn** [comment]
目前JSON导入的是结构，数据是从结构反向生成的数据。暂时不提供数组完全对等的导入导出，请自行修改字段的Mock规则来生成随机化的数据。
