### ISSUE TITLE
rap2.taobao.org 无法新建接口

### ISSUE THREAD

**Issue by SuperMarioBean** [thx/rap2-delos#284]
**BUG描述**
使用的是 rap2.taobao.org，

**复现步骤**
点击“新建接口”按钮后，按照正常流程创建接口，点击提交后

**期望结果**
展现 loading 界面，界面展现完毕后得到新的接口项
点击新的接口项，点击编辑可以正常编辑
点击保存可以正常保存
点击取消可以正常取消编辑

**实际结果**
没有任何 loading 界面，直接就是创建接口界面消失，手动刷新页面后才会出现新的接口项
点击新的接口项，会出现“当前接口已经被 锁定！” 图1, 此后无论点击保存还是，都会报错，“发生错误：undefined”图2，另外，新建接口时，浏览器console 会报错图3

**截图**

![image](https://user-images.githubusercontent.com/3890843/44083210-ea323958-9fe5-11e8-9707-cd7f5c3a800f.png)

![image](https://user-images.githubusercontent.com/3890843/44083263-191482c6-9fe6-11e8-9963-55a6b673015a.png)

![image](https://user-images.githubusercontent.com/3890843/44083361-5a9129de-9fe6-11e8-8d94-4d3653151896.png)

![image](https://user-images.githubusercontent.com/3890843/44083378-65b7f040-9fe6-11e8-8672-1aacdd30f5c0.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
非自建服务器

* 如果是前端错误，请提供浏览器版本
![image](https://user-images.githubusercontent.com/3890843/44083400-731f32ca-9fe6-11e8-99a5-4998b14dcd88.png)
包括 chrome 也有相同问题

* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
Fixed，已修复。抱歉今天做了系统的更细，dolores和delos版本不一致。

**Comment by SuperMarioBean** [comment]
客气，感谢及时回复。
