### ISSUE TITLE
账号的密码在代码中已经使用了两次md5进行加密，但是npm run create-db仍然是明文

### ISSUE THREAD

**Issue by xieshaohu** [thx/rap2-delos#286]
**BUG描述**
账号的密码在代码中已经使用了两次md5进行加密，但是npm run create-db仍然是明文，导致按照教程初始化工程之后，登录的时候报告账号密码错误

**复现步骤**
git clone工程，按照教程npm run build, npm run create-db，npm run dev，启动前端，登录是报告账号密码错误

**期望结果**
登录成功，看到主界面

**实际结果**
登录失败，报告账号密码错误

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
CentOS 7 64bit
* 如果是前端错误，请提供浏览器版本
不是前端错误
* 其它可能帮助我们排查问题的环境信息
代码版本为提交问题时的master分支最新代码

**附加信息**

**Comment by Bosn** [comment]
create-db是测试账号，明文，意味着无法通过账号密码登陆。是计划中的行为。

不然可以用create-db测试账号登陆任何RAP系统，这不是我们想看到的。

**Comment by xieshaohu** [comment]
那应该在README中添加说明，告知小白用户怎样能够顺利登录系统。按照手册安装完成后，点击登录默认报错，一顿代码阅读才知道问题出在md5函数上。或者把admin账号的密码做成md5

**Comment by Bosn** [comment]
好的，我会完善README
不过预设测试账号不能直接登陆是常识哦，理由说过了不再重复，自己随意注册用户即可登陆。

**Comment by xieshaohu** [comment]
README中直接告诉小白用户预设账号不能登录，注册新账号即可使用也是好的。
