### ISSUE TITLE
增加记住密码功能

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#287]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
每次打开浏览器都要输入账号和密码，公司把浏览器自带的“记住密码”的功能是屏蔽掉的。很烦人

**您是否有建议的实现方案**
提供勾选项“记住密码”，用localstorage等方式做记住密码的功能。同时，该功能最好做一个密码的加密存储（用账号作为key对密码进行加密存储）。否则安全扫描到了又要挨批评了。
例如:
aes(passwd,email)

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
localStroage存密码... 然后在前端取回填充？
execuse me?

**Comment by blackdog1987** [comment]
@Bosn 那正确的姿势是怎么记住密码啊... 每次都输入账号密码很烦啊 🤷‍♂️

**Comment by Bosn** [comment]
1password了解一下。。。。
另外浏览器都有记忆功能。你场不让浏览器记住，本身就是你场的安全要求。。。😂

**Comment by Bosn** [comment]
暂时不考虑实现。
