### ISSUE TITLE
没有rap数据库

### ISSUE THREAD

**Issue by LvJianfeng** [thx/rap2-delos#288]
**BUG描述**
生产环境下：没有rap数据库。

**Comment by xieshaohu** [comment]
先自己创建数据库，npm run build 之后执行npm run create-db创建表

**Comment by LvJianfeng** [comment]
@xieshaohu 那个创建的是RAP2_DELOS_APP数据库，我现在就是手动去创建的，但是生产环境我看要求的是rap数据库，所以才问的呢

**Comment by Bosn** [comment]
名字自己随便改的，叫啥都可以，和配置文件对上就行。

**Comment by LvJianfeng** [comment]
@Bosn  嗯嗯，请教下，npm run create-db执行的时候，初始化数据打印全是乱码是为什么呀
