### ISSUE TITLE
刷新404问题

### ISSUE THREAD

**Issue by LvJianfeng** [thx/rap2-delos#289]
**BUG描述**
在已登录状态下，在根URL上刷新没有问题，但是在其他页面会出现问题。

**操作状态**
根地址120.12.11.88，正常刷新没问题
在http://120.12.11.88/*，通过页面点击触发没有问题，如果在当前URL上刷新就会导致404错误。
比如http://120.12.11.88/repository或者http://120.12.11.88/api等

**Comment by blackdog1987** [comment]
你都愿意提issue了。。。不如好好看看wiki

**Comment by LvJianfeng** [comment]
@blackdog1987 谢谢，疏忽了。

**Comment by youngjuning** [comment]
@LvJianfeng 请问怎么解决了，那个wiki说让改nginx什么意思，这个不是用的node吗？
