### ISSUE TITLE
sequelize deprecated String based ope rators are now deprecated

### ISSUE THREAD

**Issue by wyh497823256** [thx/rap2-delos#290]
**BUG描述**
sequelize deprecated String based ope
rators are now deprecated

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
是
windows server 2008 r2 enterprise
nodejs  v8.11.3
mysql 5.7

* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
C:\Users\Administrator>pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lin
es option)
C:\Users\Administrator\.pm2\pm2.log last 15 lines:
PM2        | [2018-08-16T10:35:57.467Z] PM2 log: App name:redis-server id:1 onli
ne
PM2        | [2018-08-16T10:35:57.548Z] PM2 log: App [redis-server] with id [1]
and pid [3744], exited with code [1] via signal [SIGINT]
PM2        | [2018-08-16T10:35:57.551Z] PM2 log: Starting execution sequence in
-fork mode- for app name:redis-server id:1
PM2        | [2018-08-16T10:35:57.555Z] PM2 log: App name:redis-server id:1 onli
ne
PM2        | [2018-08-16T10:35:58.100Z] PM2 log: App [redis-server] with id [1]
and pid [3464], exited with code [1] via signal [SIGINT]
PM2        | [2018-08-16T10:35:58.102Z] PM2 log: Starting execution sequence in
-fork mode- for app name:redis-server id:1
PM2        | [2018-08-16T10:35:58.106Z] PM2 log: App name:redis-server id:1 onli
ne
PM2        | [2018-08-16T10:35:58.315Z] PM2 log: App [redis-server] with id [1]
and pid [5580], exited with code [1] via signal [SIGINT]
PM2        | [2018-08-16T10:35:58.318Z] PM2 log: Starting execution sequence in
-fork mode- for app name:redis-server id:1
PM2        | [2018-08-16T10:35:58.332Z] PM2 log: App name:redis-server id:1 onli
ne
PM2        | [2018-08-16T10:35:58.482Z] PM2 log: App [redis-server] with id [1]
and pid [2568], exited with code [1] via signal [SIGINT]
PM2        | [2018-08-16T10:35:58.485Z] PM2 log: Starting execution sequence in
-fork mode- for app name:redis-server id:1
PM2        | [2018-08-16T10:35:58.489Z] PM2 log: App name:redis-server id:1 onli
ne
PM2        | [2018-08-16T10:35:58.696Z] PM2 log: App [redis-server] with id [1]
and pid [680], exited with code [1] via signal [SIGINT]
PM2        | [2018-08-16T10:35:58.697Z] PM2 log: Script D:\SERVERSOFT\REDIS\REDI
S-SERVER.EXE had too many unstable restarts (16). Stopped. "errored"

C:\Users\Administrator\.pm2\logs\redis-server-error-1.log last 15 lines:
C:\Users\Administrator\.pm2\logs\redis-server-out-1.log last 15 lines:
1|redis-se | [880] 16 Aug 10:35:57.149 # Creating Server TCP listening socket *:
6379: listen: Unknown error
1|redis-se | [3216] 16 Aug 10:35:57.227 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [3216] 16 Aug 10:35:57.233 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [2576] 16 Aug 10:35:57.439 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [2576] 16 Aug 10:35:57.445 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [3744] 16 Aug 10:35:57.510 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [3744] 16 Aug 10:35:57.516 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [3464] 16 Aug 10:35:57.786 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [3464] 16 Aug 10:35:57.792 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [5580] 16 Aug 10:35:58.218 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [5580] 16 Aug 10:35:58.223 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [2568] 16 Aug 10:35:58.469 # Warning: no config file specified, usi
ng the default config. In order to specify a config file use D:\SERVERSOFT\REDIS
\REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [2568] 16 Aug 10:35:58.473 # Creating Server TCP listening socket *
:6379: listen: Unknown error
1|redis-se | [680] 16 Aug 10:35:58.579 # Warning: no config file specified, usin
g the default config. In order to specify a config file use D:\SERVERSOFT\REDIS\
REDIS-SERVER.EXE /path/to/redis.conf
1|redis-se | [680] 16 Aug 10:35:58.585 # Creating Server TCP listening socket *:
6379: listen: Unknown error

C:\Users\Administrator\.pm2\logs\rap-server-delos-out-0.log last 15 lines:
0|rap-serv | ----------------------------------------
0|rap-serv | [2018-08-16 02:35:58.872]   worker#4552 rap2-dolores is running as
9002
0|rap-serv | ----------------------------------------
0|rap-serv | DATABASE √
0|rap-serv |     HOST     localhost
0|rap-serv |     PORT     3306
0|rap-serv |     DATABASE RAP2_DELOS_APP
0|rap-serv | ----------------------------------------
0|rap-serv | [2018-08-16 02:35:59.089]   worker#5164 rap2-dolores is running as
9002
0|rap-serv | ----------------------------------------
0|rap-serv | DATABASE √
0|rap-serv |     HOST     localhost
0|rap-serv |     PORT     3306
0|rap-serv |     DATABASE RAP2_DELOS_APP
0|rap-serv | ----------------------------------------

C:\Users\Administrator\.pm2\logs\rap-server-delos-error-0.log last 15 lines:
0|rap-serv | [2018-08-16 02:30:44.144] master#1756 worker#1180 has disconnected.

0|rap-serv | Thu, 16 Aug 2018 02:30:50 GMT sequelize deprecated String based ope
rators are now deprecated. Please use Symbol based operators for better security
, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operato
rs at node_modules\sequelize\lib\sequelize.js:242:13
0|rap-serv | Thu, 16 Aug 2018 02:30:50 GMT sequelize deprecated String based ope
rators are now deprecated. Please use Symbol based operators for better security
, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operato
rs at node_modules\sequelize\lib\sequelize.js:242:13
0|rap-serv | [2018-08-16 02:30:50.344] master#4304 worker#4560 is now connected
to null:9002.
0|rap-serv | [2018-08-16 02:30:50.472] master#4304 worker#4136 is now connected
to null:9002.
0|rap-serv | [2018-08-16 02:34:11.364] master#4304 worker#4560 has disconnected.

0|rap-serv | [2018-08-16 02:34:11.370] master#4304 worker#4560 died (3221225786)
. restarting...
0|rap-serv | Thu, 16 Aug 2018 02:34:12 GMT sequelize deprecated String based ope
rators are now deprecated. Please use Symbol based operators for better security
, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operato
rs at node_modules\sequelize\lib\sequelize.js:242:13
0|rap-serv | [2018-08-16 02:34:12.840] master#4304 worker#2632 is now connected
to null:9002.
0|rap-serv | [2018-08-16 02:35:53.922] master#4304 worker#4136 has disconnected.

0|rap-serv | [2018-08-16 02:35:53.922] master#4304 worker#2632 has disconnected.

0|rap-serv | Thu, 16 Aug 2018 02:35:58 GMT sequelize deprecated String based ope
rators are now deprecated. Please use Symbol based operators for better security
, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operato
rs at node_modules\sequelize\lib\sequelize.js:242:13
0|rap-serv | Thu, 16 Aug 2018 02:35:58 GMT sequelize deprecated String based ope
rators are now deprecated. Please use Symbol based operators for better security
, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operato
rs at node_modules\sequelize\lib\sequelize.js:242:13
0|rap-serv | [2018-08-16 02:35:58.875] master#792 worker#4552 is now connected t
o null:9002.
0|rap-serv | [2018-08-16 02:35:59.094] master#792 worker#5164 is now connected t
o null:9002.

**Comment by Bosn** [comment]
警告不影响运行不做修复
