### ISSUE TITLE
编辑接口-响应内容使用导入出现"value.indexOf is not a function"

### ISSUE THREAD

**Issue by wyh497823256** [thx/rap2-delos#291]
**BUG描述**
编辑接口，在响应内容中使用导入功能，导入以下json串 ：
```
{
  "code": 200,
  "message": "",
  "result": {}
}
```
响应模板出现提示：
`value.indexOf is not a function`
需要保存接口后，才能显示正常
**复现步骤**
1、随便一个接口
2、点击编辑接口
3、在响应内容-点击导入

**期望结果**

```
{
  "code": 200,
  "message": "",
  "result": {}
}
```
**实际结果**
`value.indexOf is not a function`

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by LvJianfeng** [comment]
@wyh497823256 我也遇到，不过保存后就好了

**Comment by huarse** [comment]
楼上 + 1，我也是一保存就好了

**Comment by blackdog1987** [comment]
确实有这个bug，导入的时候就会出现这个，我每次解决的方式是删除掉value，然后就正常了

**Comment by BruceTim** [comment]
+1,保存后重新进入就好了

**Comment by Bosn** [comment]
已经修复过了。
