### ISSUE TITLE
rap 怎么升级到rap2?

### ISSUE THREAD

**Issue by itmifen** [thx/rap2-delos#292]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
rap 能否在保留原有账户和数据的情况下，升级到rap2，rap在公司大面积使用，希望能直接升级，保留数据。

**Comment by blackdog1987** [comment]
默认情况下不提供该方法
在丁丁群里没？如果在丁丁群里的话，看看群附件里，我发过一个迁移的文档（一个word）。
可以迁移组织架构，成员

仓库信息需要你们人工迁

**Comment by Bosn** [comment]
同上

**Comment by ludingding228** [comment]
@blackdog1987 能否公开下你的迁移文档？比如放在wiki中，谢谢~

**Comment by blackdog1987** [comment]
> @blackdog1987 能否公开下你的迁移文档？比如放在wiki中，谢谢~

你在钉钉群里的话，可以从共享文件里去找找。如果没有的话我可以下下来邮件转你一份。
但是迁移脚本已经半年了，项目的ddl肯定发生了很大的改变，所以我建议你借鉴思路，不能直接用其中的脚本。记得迁移之前做好相应的备份工作，以免出现问题。

**Comment by ludingding228** [comment]
> > @blackdog1987 能否公开下你的迁移文档？比如放在wiki中，谢谢~
> 
> 你在钉钉群里的话，可以从共享文件里去找找。如果没有的话我可以下下来邮件转你一份。
> 但是迁移脚本已经半年了，项目的ddl肯定发生了很大的改变，所以我建议你借鉴思路，不能直接用其中的脚本。记得迁移之前做好相应的备份工作，以免出现问题。

那麻烦转我一份吧，谢谢！我给你mail@dongguochao.com发邮件了
