### ISSUE TITLE
接口校验阶段能否提供一个必填项？

### ISSUE THREAD

**Issue by xiashuang5112** [thx/rap2-delos#293]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在使用Rap2定义数据请求接口时，如果某个属性值为必传项，这个功能目前无法满足。

**您是否有建议的实现方案**
在接口定义类添加一列数据是否必填。

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/38963214/44324264-b6402f00-a487-11e8-9e51-94891da3a159.png)

**Comment by Bosn** [comment]
已经有了
