### ISSUE TITLE
##RAP2的授权协议疑问##

### ISSUE THREAD

**Issue by wudeyong** [thx/rap2-delos#298]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

查询到RAP的授权协议为GPL3.0，RAP2尚未标注任何授权协议

**您是否有建议的实现方案**

建议增加授权协议

**其它帮助我们理解您需求的描述、截图**

无

**Comment by Bosn** [comment]
https://github.com/thx/rap2-dolores/blob/master/LICENCE.txt
