### ISSUE TITLE
关于新建模块建议

### ISSUE THREAD

**Issue by Paleozoic** [thx/rap2-delos#3]
模块的定义，相当于是对接口的一个分组管理；那么可不可以添加一个父模块的概念，设计成无限目录分级，提供对模块本身的管理呢？
现在是：项目-模块-接口
修改后是：项目-父父模块-父模块-...-模块-接口
这样还可以避免模块过多的时候，模块标签挤到下一行？
一个项目作为一个系统，如果模块特别多，模块不分组，管理起来就比较麻烦了。

**Comment by Bosn** [comment]
项目比较大的时候，可以拆分多个子项目，通过协作仓库的方式可以实现项目间数据的共享。

之前其实就有做模块=> 页面 => 接口，但是因为过于复杂，所以直接变成模块=>接口。

**Comment by Paleozoic** [comment]
谢谢。不过拆分子项目的话，有点让项目去适应管理工具的感觉，而项目的拆分与否往往不会随便更改：）

**Comment by Bosn** [comment]
众口难调，之前层级多，大家反馈麻烦。现在做了简化又会有人觉得不够用。所以如果真的有超级复杂的项目，按模块拆分项目是合理且必须的，而不是通过无线堆叠接口到一个超级巨大的项目里，这样也不容易管理不同项目之间的版本。

你可以一期一个项目，二期一个，三期一个，采取继承的方式实现项目数据的共享。但是也让文档变得更加清晰。

**Comment by Paleozoic** [comment]
谢谢。的确众口难调，有时候也是合理的工具引导项目管理变得更合理。
既然是阿里内部普遍使用的工具，经过生产环境的检验，相信自有其合理之处。
：）我这种【喜欢建立深层文件夹对各种文件进行分类管理】的人，已经要被历史的巨轮碾压成尘了 = =|||

**Comment by fengbaozhiling** [comment]
深层次的目录很可怕，如同我司的组织架构一样，我现在没搞懂公司是什么组织架构
