### ISSUE TITLE
rap第一版能导出api文档，但是为啥rap2却不能导出文档？

### ISSUE THREAD

**Issue by superLiuJing** [thx/rap2-delos#300]
公司自己部署了一套rap 就是因为能生成api文档，现在rap2虽然能导出到postman，但是postman也只能生成json文件，不能生成带表格的api文档，请问要导出文档怎么做？自己通过json解析？？

**Comment by Bosn** [comment]
RAP1是我大学的时候做的，RAP2另外一个同学做的。

RAP的重点，是文档一致。你导出一个副本给别人，别人拿到的是一个副本无法保证最新。综合考虑，现阶段我们不考虑出文档导出功能。有需要确实可以自行解析，API提供了文档数据的输出。

**Comment by lyh348532001** [comment]
@Bosn rap1计划啥时候提供使用啊？，还有东西没有导出来！

**Comment by Bosn** [comment]
@lyh348532001 亲，现在应该可以了，建议加微信群，issues一般适合不紧急问题的。
