### ISSUE TITLE
接口路径相同，但是 method 不同会出现接口重复问题

### ISSUE THREAD

**Issue by huarse** [thx/rap2-delos#302]
**BUG描述**

有两个不同的接口，路径相同，一个是删除 item，一个是获取详情，配置接口时用的是不同的方法，但是返回报错。

**截图**

![image](https://user-images.githubusercontent.com/3724927/44456550-68682a00-a633-11e8-8c77-9546da322fa6.png)

![image](https://user-images.githubusercontent.com/3724927/44456492-466ea780-a633-11e8-8561-555cb31062a4.png)

**Comment by Bosn** [comment]
最新merged版本已修复，改了一行代码在mock.ts增加了mock参数适配。
