### ISSUE TITLE
建议增加接口分组功能

### ISSUE THREAD

**Issue by charmfocus** [thx/rap2-delos#305]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
模块下接口太多，能有对接口分组的功能最好了，方便查看

**您是否有建议的实现方案**
新增Group表，在Interface表中增加GroupId，前台界面进行修改，在模块页增加添加分组功能，在分组下再新增接口

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
暂时不考虑，之前分的层级多大家觉得麻烦，现在少了一个层级又希望添加分组。众口难调，建议项目力度小一些，通过写作仓库来串联不同项目。
