### ISSUE TITLE
容器部署，修改容器默认时区为东八区，delos打印日志时间是UTC0

### ISSUE THREAD

**Issue by ganl** [thx/rap2-delos#307]
**BUG描述**
容器部署，修改容器默认时区为东八区，delos打印日志时间是UTC0；ssh到容器里用date查看日期时间正常：
```
docker-compose exec delos sh
/app # date
Sun Aug 26 18:01:59 CST 2018
/app #
```

**复现步骤**

使用https://github.com/ganl/rap2-docker Docker部署的

```
cp env-example .env
docker-compose up -d dolores
```

查看delos日志：`docker-compose logs -f delos`

**期望结果**
日志输出时间戳为北京时间

**实际结果**

delos_1    | [2018-08-26 10:00:50.347]   worker#20 rap2-dolores is running as 80
delos_1    | [2018-08-26 10:00:50.347]   worker#26 rap2-dolores is running as 80
delos_1    | [2018-08-26 10:00:50.355]   worker#15 rap2-dolores is running as 80

**截图**
![image](https://user-images.githubusercontent.com/11937688/44627238-c01cd300-a95c-11e8-8f0d-c77b9d4d4018.png)

**环境**
* MacOS Docker 部署

**附加信息**

**Comment by Bosn** [comment]
感谢您提交Issue。Docker目前没有提供官方的部署哦亲，暂时不提供Docker配置相关的支持。请自行修复，或向Docker镜像的作者咨询。

**Comment by ganl** [comment]
本地npm run dev 看了下并不是docker部署的问题
dispatch.ts 中 now() 使用了 toISOString， 会与北京时间有8个小时的时差
![image](https://user-images.githubusercontent.com/11937688/44674357-d6f81e00-aa5f-11e8-9fdb-90e5edcf1b3e.png)

**Comment by youngjuning** [comment]
- [Docker 容器与宿主机共享时区配置](https://muguang.me/it/2658.html)
