### ISSUE TITLE
单个接口可以在任何地方做导入导出，或迁移

### ISSUE THREAD

**Issue by airing0805** [thx/rap2-delos#31]
单个接口可以在任何地方做导入导出，需求多变的时候，模快划分不是那么清晰，后期重新规划时，接口需要在项目间进行迁移。

**Comment by Bosn** [comment]
有的，目前核心重点的功能需求就是导入导出。

除了RAP JSON格式外，还会支持Postman Colleciton 和 Swagger API Spec

**Comment by HiZhaoxiaoyang** [comment]
去玩儿群二无若群翁绕弯儿群翁人情味二群

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/commit/25e5c430eb54f0b6850af54fd843d917bcf5629a
