### ISSUE TITLE
rap2-dolores安装过程提示找不到node_modules/node-sass/scripts/install.js

### ISSUE THREAD

**Issue by jianyan163qq** [thx/rap2-delos#312]
**BUG描述**
rap2-dolores安装过程提示找不到node_modules/node-sass/scripts/install.js

**复现步骤**
master分支,根目录执行npm install

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/7659148/44834230-19d61380-ac63-11e8-9755-250d04ef159a.png)

**环境**
centos6
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
**附加信息**

**Comment by Bosn** [comment]
基本软件环境安装问题请自行搜索解决吧

**Comment by tom2ling** [comment]
@jianyan163qq  兄弟不知道 你这个问题是否已经解决了?我也是同样的环境,在同样的位置报错.
