### ISSUE TITLE
请教下npm start后怎么停止服务呢？

### ISSUE THREAD

**Issue by yuxuanjava** [thx/rap2-delos#314]
用npm start启动了项目，执行npm stop报错。ps看到5个进程好像是守护的也杀不掉，应该怎么关闭呢？
![image](https://user-images.githubusercontent.com/22096805/44888927-2f504980-ad06-11e8-8cdf-dd33549b7c3f.png)

**Comment by sjby365** [comment]
pm2也要关掉，不然杀死后自动启动。

下面脚本自行更改下：

#!/bin/bash
Id=`ps -ef|grep /home/rap2-delos |grep -v grep|grep -v PPID|awk '{ print $2}'`
Id2=`ps -ef|grep /usr/local/bin/http-server |grep -v grep|grep -v PPID|awk '{ print $2}'`
Id3=`ps -ef|grep pm2 |grep -v grep|grep -v PPID|awk '{ print $2}'`
echo "Stop rap2-delos:"
kill -9 $Id $Id2 $Id3

**Comment by yuxuanjava** [comment]
好了好了、用pm2关掉了
