### ISSUE TITLE
导入json数据后浏览器卡死

### ISSUE THREAD

**Issue by HelloAndWord** [thx/rap2-delos#315]
**BUG描述**
        针对新建接口进行json数据导入，导入保存后，浏览器卡死后台服务崩溃，重启后该接口所在的团队无法进入

**复现步骤**
        暂未复现

**期望结果**
        无卡死，或卡死后如何做故障恢复，现在卡死后相当于团队中的所有接口无法再打开

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
  自建服务器，centos 5.9
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
麻烦提供下测试数据，如果数据敏感，请单独发送至我的邮箱bosn@outlook.com

**Comment by Bosn** [comment]
请提交数据后reopen
