### ISSUE TITLE
新建接口保存undefined

### ISSUE THREAD

**Issue by 18810710841** [thx/rap2-delos#316]
**BUG描述**
新建接口，在保存时报错：发生错误：undefined

**复现步骤**
新建接口-->输入参数-->保存
在保存时报错
**期望结果**
能正常保存数据

**实际结果**
不能保存

**截图**
![image](https://user-images.githubusercontent.com/22389446/45066136-7a47d380-b0ef-11e8-9b6c-33e55f79d0ae.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本 ：CentOS-7-x86_64-Minimal-1611.iso
       docker-engine-1.13.1-1.el7.centos.x86_64
* 如果是前端错误，请提供浏览器版本：Google Chrome 版本 68.0.3440.75（正式版本） （32 位）
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by BruceTim** [comment]
我也出现了,点击仓库重新进去确实保存了,也解锁了

**Comment by Sioxas** [comment]
同样出现了，点编辑按钮出现当前接口已经被 锁定！，刷新页面后点编辑报错，不能保存接口

**Comment by shibahuasheng** [comment]
同样是这个问题求解决方案

**Comment by Bosn** [comment]
麻烦提供下后端错误日志（rap2-delos）的，提供了再reopen谢谢

**Comment by BruceTim** [comment]
刷新一下治标,升级服务器接口到最新版本治本

**Comment by cjy0705** [comment]
> 刷新一下治标,升级服务器接口到最新版本治本

docker部署的

**Comment by BruceTim** [comment]
一样,拉最新代码重新编译部署

**Comment by cjy0705** [comment]
> 一样,拉最新代码重新编译部署

docker镜像没有更新，代码是最新代码
