### ISSUE TITLE
保存模块时没有同步更新到redis

### ISSUE THREAD

**Issue by xiaoxing598** [thx/rap2-delos#317]
**BUG描述**
router.post('/module/update', async (ctx, next) => {
  const { id, name, description } = ctx.request.body
  await Module.update({ name, description }, {
    where: { id }
  })
  ctx.body = {
    data: {
      name,
      description,
    },
  }
  return next()
}, async (ctx) => {
  if (ctx.body.data === 0) return
  let mod = ctx.request.body
  await Logger.create({
    userId: ctx.session.id,
    type: 'update',
    repositoryId: mod.repositoryId,
    moduleId: mod.id,
  })
})

**复现步骤**
保存或更新模块数据

**期望结果**
数据库和redis同步更新

**实际结果**
仅数据库有更新

**截图**

**环境**
* 自建服务器
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
没看懂，为什么要更新到modules?您提交的BUG产生的直接影响是什么呢？

**Comment by xiaoxing598** [comment]
因为模块自身的信息有变更，但你只是保存到数据库了，可页面上仍然是从redis中取的，所以会造成数据实际上保存了，但页面上看到的仍然是旧内容，给用户的感觉是数据变更没有成功。

我现在简单的修复了这个问题，在保存到数据库以后，再添加一步，把redis中缓存的信息删除，这样页面在缓存中加载不到，就会从数据库加载了。

**Comment by Bosn** [comment]
已修复，详见晚些时间的push
