### ISSUE TITLE
增加版本说明

### ISSUE THREAD

**Issue by Blackgan3** [thx/rap2-delos#319]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我不知道现在是什么版本的rap2,用的很懵逼

**您是否有建议的实现方案**
打tag，release版本

**其它帮助我们理解您需求的描述、截图**
没有版本号，用的很懵逼

**Comment by Bosn** [comment]
好的，这个反馈收到后续我们会考虑以正式的release发布。
