### ISSUE TITLE
增加数据库创建文件

### ISSUE THREAD

**Issue by Blackgan3** [thx/rap2-delos#320]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在本地直接运行create-db出来的数据表有时会报错，导致用的时候心惊胆跳，create-db出来的表之间的关联表的关系有时设定不正确

**您是否有建议的实现方案**
添加一个sql创建的文件，直接在mysql工具上创建表

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
报错就解决错误，sql运行未必就不报错哦。
RAP2的数据是用sequelize models自动生成出来的，根据不同操作系统，sequelize会做转化处理。
