### ISSUE TITLE
增加可以屏蔽注册配制，人员按需自己创建，类似GitLab。

### ISSUE THREAD

**Issue by zhangjiaxin281** [thx/rap2-delos#321]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by blackdog1987** [comment]
这属于你的定制需求 要你自己去实现了 做法是，屏蔽掉登录页面的注册按钮，只通过接口进行注册 官方版本肯定不会这么做的。。。
