### ISSUE TITLE
接口列表和参数分别添加滚动条

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#324]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
通常接口列表中会有几十个接口，每次浏览接口的时候切换接口的时候鼠标都需要频繁的上下滚动

**您是否有建议的实现方案**
见截图

**其它帮助我们理解您需求的描述、截图**
![aaa](https://user-images.githubusercontent.com/2356974/45281768-69da9300-b50b-11e8-9e53-4fa82f6f18df.png)

**Comment by Bosn** [comment]
added
