### ISSUE TITLE
优化：减少调用仓库的次数

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#325]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
每次切换接口的时候，都会发起请求获取所有的仓库信息（ http://rap2api.taobao.org/repository/get?id=xxx）。

- 好处： 并行开发的时候，每次都能获取到最新的内容。结合后端redis的缓存，后端执行效率高
- 坏处： 性能影响。现在我们的一个仓库，调用一次需要拉取所有的仓库内容。现在我们的每个仓库都是2m以上，很卡。

**您是否有建议的实现方案**
在仓库中，切换接口的时候，不调用后端接口，直接读取前端的数据。每次都是拉取的全量的数据，所以只需要客户端自己处理数据即可。
针对仓库多人协同编写的问题，可以通过
- 【版本检查】接口，替换掉【getRepository】接口
- 页面增加一个【刷新】

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
亲的版本应该没有更新，可以看下官网rap2.taobao.org
早在 一个月前我更新的版本已经修复了老是重复获取仓库的BUG哦
