### ISSUE TITLE
现在是否有字段之间的关联mock功能

### ISSUE THREAD

**Issue by jingyu00123** [thx/rap2-delos#326]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
比如我是响应内容中有三个字段，value、color、desc  之间是互相对应的，什么范围的值会对应什么颜色和描述

**您是否有建议的实现方案**
是否可以定义一个大的mock ，中间可以标志变量

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
暂时还不支持哦亲，这是一个不错的需求未来计划中我们会考虑，感谢亲的反馈。
