### ISSUE TITLE
admin@rap2.com初始化密码数据库中明文存储

### ISSUE THREAD

**Issue by micuncang** [thx/rap2-delos#329]
**BUG描述**
初始化数据库中默认用户密码明文存储导致登录失败

**期望结果**
密码使用加密方式存储

**Comment by micuncang** [comment]
![image](https://user-images.githubusercontent.com/3069117/45356679-869fc500-b5f6-11e8-96e4-23091accf868.png)

数据库使用npm run create-db初始化

**Comment by Bosn** [comment]
初始化仅用于测试，明文存储意味着密码无法登陆是既定的设计行为，否则所有人可以拿着初始密码登陆任何未删除初始账号的系统。
