### ISSUE TITLE
建议：重启Docker和内部容器，发现用户数据全部丢失。建议docker-compose.xml关闭init data初始化功能

### ISSUE THREAD

**Issue by WeiXiaoan** [thx/rap2-delos#331]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
问题：按照Readme教程，基于Docker部署完Rap2后，重启Docker和内部容器，发现用户数据全部丢失

**您是否有建议的实现方案**
经过排查，发现rap2的docker-compose.yml文件中，有如下几行

![image](https://user-images.githubusercontent.com/21210336/45476684-27ff5600-b772-11e8-8b51-2756e346d098.png)

默认开启的一行会初始化数据库。
需要将其注释，开启without init下的一行，才能保证数据库不会每次都init。

实际上，在ReadMe文件中关于Docker的部署环节里，是有手动init数据库的步骤的。
![image](https://user-images.githubusercontent.com/21210336/45476591-e4a4e780-b771-11e8-90f0-dbdf4b716c71.png)

我觉得开启默认初始化功能并非开发团队本意，且ReadMe中并未对此部分进行说明，这对于严格按照官网部署的开发人员不够友好，所以我建议开发团队关闭默认Docker文件中的init数据库功能。

**Comment by Bosn** [comment]
请自行学习docker，了解如何持久化数据。如何使用docker 不在本repo讨论范围。
