### ISSUE TITLE
Bug：内网基于Docker部署完前后端后，前端页面访问【仓库】标签下的【所有仓库】无响应，后端服务器产生错误日志

### ISSUE THREAD

**Issue by WeiXiaoan** [thx/rap2-delos#332]
**BUG描述**
内网基于Docker部署Rap2后，前端页面访问【仓库】标签下的【所有仓库】无响应。
Docker容器中，rap-delos的错误日志如下。
![53691a84-768c-4e87-9dbe-1b31950a3f8f](https://user-images.githubusercontent.com/21210336/45477061-3dc14b00-b773-11e8-94da-1c6171be589e.jpg)

**复现步骤**
正常登陆，点击【仓库标签】，左侧下拉选项栏中选择【所有仓库】

**期望结果**
正常显示所有仓库

**实际结果**
前端无反应，长时间后显示【没有结果】

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
内网自建centOS7服务器，基于Docker部署的前后端
* 如果是前端错误，请提供浏览器版本
Chrome浏览器最新版
* 其它可能帮助我们排查问题的环境信息

**附加信息**
WeChat：13966968799

**Comment by Bosn** [comment]
数据库报错了，已知信息下推算不出问题，安装配置问题建议加钉钉群，详见首页README.md
