### ISSUE TITLE
希望提供一个完整版编辑器

### ISSUE THREAD

**Issue by hyingreborn** [thx/rap2-delos#334]
目前仅提供了一个textarea，且编辑区域较小，建议借鉴一下easy-mock，编辑区域弄大点，如果能加个CodeMirror这样的编辑器，支持一下简单的tab缩进，自动拼写就更好了

**Comment by Bosn** [comment]
之前提过了，暂时不考虑。RAP2不是wiki，对文档格式有要求，推荐使用云雀。非常方便好用的文档整理工具。我们在非常有限的人力下，还是会集中文档结构和数据结构的管理，而不是文档格式。
