### ISSUE TITLE
导入postMan后，切换为raw模式无数据

### ISSUE THREAD

**Issue by Feadav** [thx/rap2-delos#335]
**BUG描述**
post请求，参数类型为json,导入postMan后，自动生成为form-data类型，切换为raw无数据

**复现步骤**
1.新建一个接口，输入接口名，选择post方式；
2.编辑header:Content-Type:application/json;
3.编辑body params 选择raw,点击导入，粘贴json数据，保存；
4.导入到postMan,显示为form-data格式；切换为raw无数据；

**期望结果**

可以在raw下正常显示json格式参数
**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Ricky-Hao** [comment]
+1，这个问题导致我所有的post接口导入到postman都不能直接使用，得自己编辑body才行。

**Comment by mydreaplus** [comment]
3.编辑body params 选择raw,点击导入，粘贴json数据，保存；

此时并没有正确保存为raw

**Comment by Bosn** [comment]
body模式暂时只支持form-data 形式，可以点击bulk edit转成文本进行二次编辑成其它格式。

**Comment by liuandong** [comment]
+1,axios默认都是json\application了，期待支持啊
