### ISSUE TITLE
Rap2 前端部署后无法访问后端接口

### ISSUE THREAD

**Issue by ElvisVern** [thx/rap2-delos#336]
**BUG描述**
![image](https://user-images.githubusercontent.com/13827109/45583928-53627c00-b8fd-11e8-8c40-d0891fc7fdd1.png)
38080端口提供后端服务

![image](https://user-images.githubusercontent.com/13827109/45583941-7b51df80-b8fd-11e8-9121-878a3f83c2b6.png)
config 文件 serve 配置修改

**复现步骤**

**期望结果**
可以打开前端页面

**实际结果**
出现 net::ERR_CONNECTION_REFUSED  错误

**截图**
![image](https://user-images.githubusercontent.com/13827109/45583957-b48a4f80-b8fd-11e8-933f-720e31ead4f0.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
acc_Account.js

RAP里并没有这个文件啊

**Comment by Bosn** [comment]
端口5000是不是挂载别的服务了呢？
RAP2有两个服务，一个是前端rap2-dolores，一个是后端rap2-delos
确认下rap2-dolores的启动状态？

**Comment by ElvisVern** [comment]
@Bosn  thanks  
config.prod.js  文件中  serve 配置写错了  应该写外网IP地址而不是localhost ...   
问题已解决

**Comment by kunlan** [comment]
> @Bosn thanks
> config.prod.js 文件中 serve 配置写错了 应该写外网IP地址而不是localhost ...
> 问题已解决

哈哈,感谢啊,一样的问题
