### ISSUE TITLE
config.prod.ts 如何配置redis cluster及密码

### ISSUE THREAD

**Issue by later123** [thx/rap2-delos#337]
请问生产环境部署中，config.prod.ts  能连接带密码的redis集群吗？ 如何配置呢？我的配置如下， 不知道是否正确：

    redis: {
        host: process.env.REDIS_URL || 'devops-redis1.com' || 'devops-redis2.com' || 'devops-redis3.com' || 'devops-redis4.com ' || 'devops-redis5.com' || 'devops-redis5.com',
        port: (process.env.REDIS_PORT && parseInt(process.env.REDIS_PORT)) || 6379
        password: 123456
    }

**Comment by oXnMe** [comment]
port行尾加逗号

**Comment by Bosn** [comment]
同上，参考.dev.ts就可以了。格式都是一样的。
