### ISSUE TITLE
Rap1已经停服不维护么？现在登录进去都报错

### ISSUE THREAD

**Issue by shine0565** [thx/rap2-delos#338]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
想测试下rap1导入到rap2，发现rap1已经无法登录了

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by shine0565** [comment]
我的Centos 6.5 在通过npm安装的时候，发现总是安装失败，报hiredis无法安装的错，后查看hiredis的文档发现需要将升级python到v2.7，gcc升级到v4.8.5，升级后可以成功安装、

**Comment by Bosn** [comment]
bingo, rap1 is out of service.
