### ISSUE TITLE
有计划改进UI吗？

### ISSUE THREAD

**Issue by jingsam** [thx/rap2-delos#340]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

我现在在调研API管理平台，RAP2的功能我看了下逻辑组织比较合理，就是UI有点辣眼睛，字太小，而且字体颜色偏淡，看不清楚，未来有计划改进UI设计吗？

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by wuhaih** [comment]
RAP界面确实丑了点，高大上的东西需要高颜值

**Comment by Bosn** [comment]
@wuhail 因为我没有设计师呀，哈哈哈。

**Comment by Bosn** [comment]
@jingsam 该项目我一个人还是业余时间维护哈。兴趣项目。您对ui有要求也可以尝试提提mr哈，我这边有时间了也会不停的去完善。

**Comment by xmsz** [comment]
现在有设计师了吗 这个实在太丑了 用起来太难受
