### ISSUE TITLE
是否能支持swagger文件导入？

### ISSUE THREAD

**Issue by kingfs** [thx/rap2-delos#341]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我从rap到rap2都在用，但是有一个问题比较麻烦，rap都是在界面上进行操作，api字段都是在rap上操作，rap里面支持导入json来生产api描述，但是这样不方便做版本控制，导入到svn等需求

目前swagger（openapi）编写等api描述越来越多，而且其支持等工具也越来越多，是否可以考虑支持导入swagger文档？

**您是否有建议的实现方案**
建议支持swagger api描述文件导入

**其它帮助我们理解您需求的描述、截图**
之前使用过easy-mock工具，直接导入swagger api描述文件，很方便做测试
https://github.com/easy-mock/easy-mock

**Comment by Bosn** [comment]
暂时不支持哦亲
