### ISSUE TITLE
pm2 守护rap-dolores 

### ISSUE THREAD

**Issue by zhouruizhong** [thx/rap2-delos#343]
**BUG描述**
pm2 start npm --watch --name rap2-delos -- run dev 后页面可以打开，但是页面样式乱

**复现步骤**
pm2 start npm --watch --name rap2-delos -- run dev

**期望结果**
正常

**实际结果**
首页及其他页面没有css样式，导致页面变形

**截图**

![image](https://user-images.githubusercontent.com/6695306/46061266-ac050500-c198-11e8-80cc-af7ce67a0472.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
![qq 20180926131215](https://user-images.githubusercontent.com/6695306/46061388-0e5e0580-c199-11e8-8e50-e85a7df99902.png)

**Comment by mydreaplus** [comment]
这里是后端Api服务项目啊

**Comment by Bosn** [comment]
看下README正确部署。。。。页面乱是你安装不正确。

开发模式npm run dev
生产模式npm start  然后用服务去加载静态资源文件夹。。。

**Comment by wenlisu** [comment]
遇到相同的问题，楼主解决了吗？
