### ISSUE TITLE
导入响应内容时json中value为null时提交，响应模板显示"Cannot read property '0' of null"，也不能保存

### ISSUE THREAD

**Issue by zycmws** [thx/rap2-delos#344]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
导入数据示例：
  {"test":null}

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
该问题源代码已经修复了，rap2.taobao.org还没更新。

**Comment by themismin** [comment]
/root/.pm2/logs/rap-server-delos-error-0.log last 15 lines:
0|rap-serv |   SequelizeDatabaseError: Data truncated for column 'type' at row 1
0|rap-serv |       at Query.formatError (/opt/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
0|rap-serv |       at Query.handler [as onResult] (/opt/rap2-delos/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
0|rap-serv |       at Query.Command.execute (/opt/rap2-delos/node_modules/mysql2/lib/commands/command.js:30:12)
0|rap-serv |       at Connection.handlePacket (/opt/rap2-delos/node_modules/mysql2/lib/connection.js:513:28)
0|rap-serv |       at PacketParser.onPacket (/opt/rap2-delos/node_modules/mysql2/lib/connection.js:81:16)
0|rap-serv |       at PacketParser.executeStart (/opt/rap2-delos/node_modules/mysql2/lib/packet_parser.js:76:14)
0|rap-serv |       at Socket.<anonymous> (/opt/rap2-delos/node_modules/mysql2/lib/connection.js:89:29)
0|rap-serv |       at emitOne (events.js:116:13)
0|rap-serv |       at Socket.emit (events.js:211:7)
0|rap-serv |       at addChunk (_stream_readable.js:263:12)
0|rap-serv |       at readableAddChunk (_stream_readable.js:250:11)
0|rap-serv |       at Socket.Readable.push (_stream_readable.js:208:10)
0|rap-serv |       at TCP.onread (net.js:601:20)
