### ISSUE TITLE
希望响应内容也和RAP1一样有颜色的层次感

### ISSUE THREAD

**Issue by wenzhouzhao** [thx/rap2-delos#346]
希望响应内容也和RAP1一样有颜色的层次感
![1](https://user-images.githubusercontent.com/29218038/46126366-855dd180-c25f-11e8-896a-b6161018c9ab.jpg)
![2](https://user-images.githubusercontent.com/29218038/46126369-8a228580-c25f-11e8-8c93-4fb7750186a5.jpg)

**Comment by Bosn** [comment]
已经有缩进和灰色背景配色了啊，RAP1的颜色太花哨了。所以做了灰色系的处理。
