### ISSUE TITLE
复制接口后，返回的层级关系丢失，只留下第一层的参数

### ISSUE THREAD

**Issue by hualuomoli** [thx/rap2-delos#349]
**BUG描述**

复制接口后，返回的层级关系丢失，只留下第一层的参数

**复现步骤**

创建一个超过一个层级的返回数据，点击接口后在有方选择移动，然后在弹出框选择复制。
进入复制的接口，查看返回数据，发现只留下第一层的参数

**期望结果**

可以正常完成一个复制功能

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
