### ISSUE TITLE
前端服务rap2-dolores,一直报500错误

### ISSUE THREAD

**Issue by tom2ling** [thx/rap2-delos#350]
**BUG描述**
1.搭建好服务后,点击注册,无反应,查看console,有500错误.
截图无法上传

2.使用系统内置admin用户登录.报错json出现意外令牌
打开console,报500错误
![image](https://user-images.githubusercontent.com/20769441/46255235-4df45c80-c4cd-11e8-8f3c-dc7489de6dc6.png)

3.数据库内置用户,用户名w无法显示
截图无法上传.

**环境**
你好,昨天刚刚搭建了rap2-dolores前端,打开页面检索,console中一直报500错误.我的系统是centos6.7,mysql 5.7,redis4.0.11,node8.12,后端服务,没有任务报错,只是前端服务报错.
不知道问题出在哪里?

**Comment by tom2ling** [comment]
我使用的是cnpm 进行的build操作,是否跟这个有关系.build目录下没有account 目录,这个是什么原因?需要手动创建吗

**Comment by Bosn** [comment]
从现象来看，说明您前端rap2-dolores正常，但是rap2-delos node后端服务异常。

建议看看node的报错日志，以及后端500接口的错误信息具体返回了什么。

**Comment by saheibe** [comment]
出现一样的问题 ， 服务端异常 ， 使用 run dev  没问题，  run start 出现上面状况

**Comment by namet117** [comment]
@saheibe  你可以先执行 `npm run clean` 把后端的进程先关掉。
然后在命令行里手动执行一下 `NODE_ENV=production node dist/dispatch.js`，如果报错的话就能看到错误信息了。

**Comment by afresh** [comment]
解决了吗？我也遇到了。

**Comment by EvilSoulsh** [comment]
npm run build  之后    rap2-delos/dist/config/config.prod.js    这个文件里面这三行要改    一下午才找到原因    太坑了

        username: process.env.MYSQL_USERNAME || 'root',
        password: process.env.MYSQL_PASSWD || '自己的数据库密码',
        database: process.env.MYSQL_SCHEMA || 'RAP2_DELOS_APP',
