### ISSUE TITLE
使用特殊节点“_root_”，访问mock地址，输出结果带有"_root_"。

### ISSUE THREAD

**Issue by hycdev** [thx/rap2-delos#351]
**BUG描述**
使用特殊节点“_root_”，访问mock地址，输出结果带有"_root_"。

**期望结果**
访问mock地址，输出结果不要有"_root_"，最外层应该就是数组。

**截图**
![image](https://user-images.githubusercontent.com/23395109/46255726-5780c300-c4d3-11e8-9986-289932203681.png)

**Comment by Bosn** [comment]
正确：__root__

**Comment by hycdev** [comment]
> 正确：`__root__` (两个下划线）
> 错误：`_root_`（一个下划线）
改成两个下划线后，接口返回结果没有内容。
![image](https://user-images.githubusercontent.com/23395109/46602038-ac4eba00-cb21-11e8-9c51-e47a58c637f2.png)
