### ISSUE TITLE
新注册的用户退出系统后,无法登录.

### ISSUE THREAD

**Issue by tom2ling** [thx/rap2-delos#353]
**BUG描述**
我是自建的,更改数据库密码也不行,只要刚注册的用户一旦logout,就无法登录了.这个问题让人费解

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
看一下自己的代码版本，是不是最新。另外密码是否经过了两次MD5

**Comment by wuhaih** [comment]
使用官网的RAP2，忘记密码了，结果没地方找回来，我也是醉啦

**Comment by wenslo** [comment]
> 使用官网的RAP2，忘记密码了，结果没地方找回来，我也是醉啦

很难受

**Comment by lanboys** [comment]
很尴尬。。
