### ISSUE TITLE
使用__root__，mock接口返回结果没内容

### ISSUE THREAD

**Issue by hycdev** [thx/rap2-delos#354]
> 错误：`_root_`（一个下划线）
改成两个下划线后，接口返回结果没有内容。
![image](https://user-images.githubusercontent.com/23395109/46602038-ac4eba00-cb21-11e8-9c51-e47a58c637f2.png)

_Originally posted by @hycdev in https://github.com/thx/rap2-delos/issues/351#issuecomment-427775766_

**Comment by Bosn** [comment]
文档信息截图下？是不是自己设置了初始值。另外你__mock__节点上有东西吗

**Comment by hycdev** [comment]
> 文档信息截图下？是不是自己设置了初始值。另外你__mock__节点上有东西吗
![image](https://user-images.githubusercontent.com/23395109/46658867-424c1880-cbe6-11e8-8ef2-cb276c649ff6.png)

**Comment by Bosn** [comment]
有链接么？预览数据是正确的

**Comment by hycdev** [comment]
> 有链接么？预览数据是正确的
本地起的服务，请求地址http://127.0.0.1:8080/app/mock/16/person

**Comment by hycdev** [comment]
> 有链接么？预览数据是正确的
在你们提供的公网服务上也这这种情况。
