### ISSUE TITLE
对json字符串的 内部字段描述支持或者提供您的建议方案

### ISSUE THREAD

**Issue by xilutian** [thx/rap2-delos#357]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

您好 ，
1，我们接口有一部分包括json字符串形式，比如下面这种形式

{
    "DataJson": "[{\"Id\":\"3113\",\"CodeType\":\"ChangeReason\",\"CodeTitle\":\"天气原因\",\"CodeId\":\"1\",\"ShowOrder\":\"1\",\"ParentID\":\"\",\"ROWSTAT\":\"\"},{\"Id\":\"3114\",\"CodeType\":\"ChangeReason\",\"CodeTitle\":\"交通管制\",\"CodeId\":\"2\",\"ShowOrder\":\"2\",\"ParentID\":\"\",\"ROWSTAT\":\"\"},{\"Id\":\"3115\",\"CodeType\":\"ChangeReason\",\"CodeTitle\":\"道路原因\",\"CodeId\":\"3\",\"ShowOrder\":\"3\",\"ParentID\":\"\",\"ROWSTAT\":\"\"}]",
    "RecordSize": 3,
    "Result": true,
    "ErrorMsg": null
}

这样通过 导入 json 的功能 ，导入后

![1539415048 1](https://user-images.githubusercontent.com/14370659/46902641-379dc600-cefb-11e8-963f-23601cfc1e6c.jpg)

这样对于 json串中内部字段的描述  如果仅仅放在简介里面 ，就显得不是那么清晰。想请教一下 有什么好的解决方案或者咱产品能否支持一下 （可能是个性化需求，还请见谅！）

2, 我看到您之前回复 有导入的功能 ，请问这个导入的功能怎么使用

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

我们现在是手工写word文档 解决这种json字符串 内部字段描述的问题  ，如下图
![1539415913 1](https://user-images.githubusercontent.com/14370659/46902746-26ee4f80-cefd-11e8-8285-6aa61b3afe74.jpg)

**Comment by Bosn** [comment]
您可能没太理解数据类型。您导入的字段DataJson就是字符串类型的，所以导入后是一个字符串的`值`。

**Comment by xilutian** [comment]
嗯嗯，我知道是字符串类型，就这种接口返回的参数，对应dataJSON 内部的字段，应该怎么写字段说明
