### ISSUE TITLE
建议支持 json导入及接口排序

### ISSUE THREAD

**Issue by old-bird** [thx/rap2-delos#358]
1、RAP2能支持RAP1导出的json吗？

2、RAP1里页面的概念很好啊， RAP2里能支持吗？

3、RAP2里的接口能支持排序吗？？

**Comment by Bosn** [comment]
1. JSON导入都是一样的哈，如果是RAP1迁移到RAP2，在主菜单=>团队=>仓库列表中，点右上角【导入仓库】
2. 暂时没有
3. 哪个层级的排序？参数？接口？

**Comment by ljqwstc** [comment]
接口层级的排序不支持。可以拖动，但是不支持排序。参数是支持排序的。
