### ISSUE TITLE
需求：添加导出功能

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#359]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
有的时候需要将接口开放给第三方公司访问，但是网络原因无法给他们访问我们的rap地址。所以需要导出到一个文档中，将文档提交给第三方使用。现在我们的方式是手动一个一个截图，效率及其低下，而且不易修改。

**您是否有建议的实现方案**
通过一个html模版，在一个项目中，选择相应的接口进行导出。html简单的采用原生的html代码即可。建议导出的各个关键项，都是input标签，不要使用span或者div标签，便于导出以后进一步进行修改。导出成功以后，可以打开html，通过页面打印。如果需要修改，则修改完毕后进行打印即可。

**其它帮助我们理解您需求的描述、截图**

**Comment by iyouling** [comment]
强烈支持这个需求，能导出一个仓库的接口说明文档（如word格式），特别是在做软著，产品说明书等需求时需要。

**Comment by JoyceLizhuo** [comment]
支持这个需求，希望能导出一个接口文档，word格式也好，html也好，pdf都可以

**Comment by JonSnow592622272** [comment]
期待导出功能完善，支持word文档、html或者pdf导出

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
