### ISSUE TITLE
为什么 API URL 里面都要带上 GET POST 呢？

### ISSUE THREAD

**Issue by fkpwolf** [thx/rap2-delos#36]
比如 http://rap2api.taobao.org/app/mock/ xxxx/GET/api/v1/algo/， 我理解这样是为了直接在页面上测试 GET POST 这种 URL，但是程序访问的话 URL 里面是不带这些参数的啊。

**Comment by Bosn** [comment]
这是RAP2之前作者的设计，确实这里的处理不够好。后续会完善。

**Comment by gitors** [comment]
我也对这个问题比较困扰，建议可以做两套url 标准，一套直接页面测试对，一套是程序里面配置的，这样方便与自己的 服务器接口进行切换。

**Comment by zhangdaren** [comment]
现在这样做，切换好麻烦的，要做几套地址，替换时候也要几套地址。

**Comment by Bosn** [comment]
最新的版本已经去掉了，可以了解一下。前端有一个路径链接错误的BUG，已经修复稍晚会儿提交。
