### ISSUE TITLE
基于docker部署的时差问题，有解决方案吗

### ISSUE THREAD

**Issue by jiangskui** [thx/rap2-delos#360]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by amiter** [comment]
容器内是UTC时区，可以考虑在docker run的时候，挂载主机的时间/etc/localtime 和时区/etc/timezone

**Comment by Bosn** [comment]
感谢楼上热心网友回复。时差问题不在issues讨论范围内哟亲
