### ISSUE TITLE
之前录入的数据没了

### ISSUE THREAD

**Issue by wenslo** [thx/rap2-delos#361]
**BUG描述**
与三日前（2018年10月13日）所录数据，今日，登录，无一而存

**复现步骤**
登录rap2.taobao.org

**期望结果**
三日前所录数据留存

**实际结果**
三日前所录数据无一而存

其他信息
非自建服务器，地址为rap2.taobao.org，账号为wenhlo@163.com

**Comment by Bosn** [comment]
项目名称或id提供一下谢谢

**Comment by Bosn** [comment]
2018-10-15 06:26:37 左右删除了10个接口。
麻烦您和同事确认下，如果非本人操作，请更新下密码是否密码过于简单被网络黑客破解。谢谢。

**Comment by Bosn** [comment]
重复帖，请参考https://github.com/thx/rap2-delos/issues/362

已做类似处理
