### ISSUE TITLE
接口不见了

### ISSUE THREAD

**Issue by abamyang** [thx/rap2-delos#362]
BUG描述
昨天能看到四日前的接口，今天就看不到了，记录里面能看到接口修改记录，没有删除记录

复现步骤
登录rap2.taobao.org

期望结果
三日前所录数据留存

实际结果
三日前所录数据无一而存

其他信息
非自建服务器，地址为rap2.taobao.org，账号为a@aa.com

**Comment by Bosn** [comment]
项目名称或id提供一下谢谢

**Comment by Bosn** [comment]
2018-10-15 06:26:37 左右删除了10个接口。
麻烦您和同事确认下，如果非本人操作，请更新下密码是否密码过于简单被网络黑客破解。谢谢。

**Comment by Bosn** [comment]
已删除的内容已经手动恢复

**Comment by wenslo** [comment]
> 项目名称或id提供一下谢谢

驾校服务平台；id：23292

**Comment by Bosn** [comment]
比如您密码如果是123456，非被人操作资料被删除，真的是没有办法的事情哟～～～请确认下自己密码是否够强大，谢谢。

**Comment by wenslo** [comment]
> 比如您密码如果是123456，非被人操作资料被删除，真的是没有办法的事情哟～～～请确认下自己密码是否够强大，谢谢。

嗯嗯。好的。谢谢
