### ISSUE TITLE
无法编辑接口

### ISSUE THREAD

**Issue by veryWrong** [thx/rap2-delos#365]
**BUG描述**
点击编辑接口，接口被锁定无法保存

**复现步骤**
点击编辑->保存按钮处显示‘当前接口已经被 锁定！’（只有一个账号操作该接口）

**期望结果**

**实际结果**

**截图**
![tim 20181019101137](https://user-images.githubusercontent.com/30597213/47193810-67c7e780-d387-11e8-93cd-5ae1117d2b2c.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by guowei1651** [comment]
顶起来，我用master版本也是一样的

**Comment by jeasonnow** [comment]
@Bosn 目前从服务端打印出的日志看，保存的时候，依然会报错：
`SequelizeDatabaseError: Incorrect integer value: 'memory-1' for column 'parentId' at row 1`

**Comment by Bosn** [comment]
更新到最新试试，目前rap2.taobao.org部署的也是最新master。
如果保存不行，请检查rap2-delos日志，是否在版本升级中，没有运行DATABASE文件夹中对应的数据库变更文件，导致无法正确保存。

**Comment by cjy0705** [comment]
我也遇到这个问题了，还不知道这么解决

**Comment by veryWrong** [comment]
> 我也遇到这个问题了，还不知道这么解决

我升级到最新版本后就没有出现这个问题了

**Comment by ss5wiking** [comment]
我也是，没法编辑

**Comment by AnInputForce** [comment]
我在11天回复过类似issue，希望对你有所帮助：

> 我是升级了六个月前的rap2到现在的版本。发现无法编辑。

> 仔细梳理，应该是变更完字段，没有更新redis缓存。清空缓存后，问题解决，可以编辑。验证中。
> 不知道你们是不是这种情况，仅供参考。
> 
> 查看release目录下的md：


> > V2.6 更新说明 2018-7-5
> > 数据库字段变更请执行 datbase/v2.6***
> > 因字段变更，需要清空redis缓存
> > 运行redis-cli
> > 执行 flushall 命令清空缓存
