### ISSUE TITLE
nginx配置gzip和keepalive优化访问速度

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#368]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
最近我们公司自己部署的rap很多同学反馈性能很慢。但是公网（rap2.taobao.org）速度很快，于是对请求做了一些分析，最终通过nginx优化配置解决的速度很慢的问题。

我们的部署方式是，一台nginx做动静分离和负载均衡。

**您是否有建议的实现方案**

- 通过upstream，后端做负载均衡，多开几个服务，不赘言
- nginx配置长链接keepalive。注意需要同时启用`proxy_http_version 1.1`。公网版本已经开启了该配置。
- 通过gzip压缩http请求。`gzip_types application/json` (其他类型的自己看自己需求)，最好还加上`gzip_http_version 1.1`。添加该参数后访问性能提升了一倍左右（3mb response，优化前1.5s，优化后0.4s~0.8s）

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
其实理论上静态资源都应该上CDN才对，因为量级之前一直很小所以没做到这种粒度。
建议nginx开gzip压缩+静态资源上CDN。单机可以用pm2做多core的负载均衡。多机可以参考其他node 多机部署。RAP2是支持多例的。

**Comment by blackdog1987** [comment]
> 其实理论上静态资源都应该上CDN才对，因为量级之前一直很小所以没做到这种粒度。
> 建议nginx开gzip压缩+静态资源上CDN。单机可以用pm2做多core的负载均衡。多机可以参考其他node 多机部署。RAP2是支持多例的。

目前看来静态资源不是性能瓶颈，浏览器好像自动做缓存了。前端调用后端接口（尤其是/repositories/get）的responseBody体非常大（查询的结果是一个很大的json，3兆），压缩以后只是对responsebody进行了压缩。可以减少一些流量

**Comment by AnInputForce** [comment]
请教个问题，我通过docker镜像启动的nginx，也配置了 gzip_types application/json，但是看response header，并没有Content-Encoding: gzip,请教下大神，有什么需要注意的地方么？
确实接口多了，响应非常慢：“尤其是/repositories/get的responseBody体非常大”，我这边已经达到了4.8M。启用gzip后也没看到对应的文件大小有所减少。

**Comment by AnInputForce** [comment]
继续请教一下大神，补充一下问题：

我看到前端src/config/config.pord.js需要配置
`serve: 'http://10.1.1.20:9080',`

那么如果我需要配置upstream，后端多配置几个实例，
这里会不会和 src/config/config.pord.js冲突？还是 有什么特殊写法，

可以兼顾 src/config/config.pord.js 和 upstream？

**Comment by blackdog1987** [comment]
> 请教个问题，我通过docker镜像启动的nginx，也配置了 gzip_types application/json，但是看response header，并没有Content-Encoding: gzip,请教下大神，有什么需要注意的地方么？
> 确实接口多了，响应非常慢：“尤其是/repositories/get的responseBody体非常大”，我这边已经达到了4.8M。启用gzip后也没看到对应的文件大小有所减少。

来丁丁群里找我，这里不方便协助你，我要看你的nginx完整配置

**Comment by AnInputForce** [comment]
> > 请教个问题，我通过docker镜像启动的nginx，也配置了 gzip_types application/json，但是看response header，并没有Content-Encoding: gzip,请教下大神，有什么需要注意的地方么？
> > 确实接口多了，响应非常慢：“尤其是/repositories/get的responseBody体非常大”，我这边已经达到了4.8M。启用gzip后也没看到对应的文件大小有所减少。
> 
> 来丁丁群里找我，这里不方便协助你，我要看你的nginx完整配置

钉钉群ID: 11789704 钉钉群申请数次了，管理员貌似最近很忙啊，没批准 :<

**Comment by 471679659** [comment]
访问速度是上来了， 但是保存和修改还算很慢，有办法解决吗？

**Comment by AnInputForce** [comment]
> > 继续请教一下大神，补充一下问题：
> > 我看到前端src/config/config.pord.js需要配置
> > `serve: 'http://10.1.1.20:9080',`
> > 那么如果我需要配置upstream，后端多配置几个实例，
> > 这里会不会和 src/config/config.pord.js冲突？还是 有什么特殊写法，
> > 可以兼顾 src/config/config.pord.js 和 upstream？
> 
> 这两个没啥关系
> serve: 'http://10.1.1.20:9080' 这个地址是配置的nginx的地址，访问的是nginx的端口
> 
> upstream是出口，是nginx转发出去的地址

官方钉钉群加不上。
我可能没描述清楚。
现有前端代码，需要在打包之前，在src/config/config.pord.js中配置后端rap2的服务器地址。
这样前端代码打包后，放入nginx中部署，不配置upstream，会请求对应配置地址。

如果在nginx配置了upstream的地址，那么前端发起请求时，需要走src/config/config.pord.js还是upstream中的地址。
有机会我再验证下。

谢谢大神指点。

**Comment by blackdog1987** [comment]
> 访问速度是上来了， 但是保存和修改还算很慢，有办法解决吗？

不能解决，慢是哪方面慢？ 你把network打开看看，然后看看后台，是入库慢，还是网络传输慢 如果是网络传输慢的话是没有办法解决的 最多你可以通过查看httprequest的参数，通过ng，把保存和修改的接口请求的request也压缩了

**Comment by blackdog1987** [comment]
> > > 继续请教一下大神，补充一下问题：
> > > 我看到前端src/config/config.pord.js需要配置
> > > `serve: 'http://10.1.1.20:9080',`
> > > 那么如果我需要配置upstream，后端多配置几个实例，
> > > 这里会不会和 src/config/config.pord.js冲突？还是 有什么特殊写法，
> > > 可以兼顾 src/config/config.pord.js 和 upstream？
> > 
> > 
> > 这两个没啥关系
> > serve: 'http://10.1.1.20:9080' 这个地址是配置的nginx的地址，访问的是nginx的端口
> > upstream是出口，是nginx转发出去的地址
> 
> 官方钉钉群加不上。
> 我可能没描述清楚。
> 现有前端代码，需要在打包之前，在src/config/config.pord.js中配置后端rap2的服务器地址。
> 这样前端代码打包后，放入nginx中部署，不配置upstream，会请求对应配置地址。
> 
> 如果在nginx配置了upstream的地址，那么前端发起请求时，需要走src/config/config.pord.js还是upstream中的地址。
> 有机会我再验证下。
> 
> 谢谢大神指点。

画了个部署的[逻辑图](http://blackdog.oss-cn-qingdao.aliyuncs.com/ff80458c-5519-452e-8716-7eb538cdb6f7.png??x-oss-process=s)，你看下
