### ISSUE TITLE
前端和后端都是用Master分支最新代码，可用性不强

### ISSUE THREAD

**Issue by guowei1651** [thx/rap2-delos#369]
**BUG描述**
1. 登录的默认用户名密码没有地方可以获取，我是从代码中硬找出来的。
2. 登录之后默认测试数据影响使用，需要删除。
3. 删除数据后，新建仓库，新建仓库之后没有再新建接口，发现新加接口成功，但是没有提示提交接口消息体的地方。
4. 点击编辑接口，提示接口已锁定

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
使用Docker构建最近的分支版本

**附加信息**

**Comment by Bosn** [comment]
1. 您注册新账户就可以了亲
2. 录入一些基础数据便于新搭建服务后快速上手哈，您不需要直接删除即可。
3. 右边点编辑按钮，进入编辑模式，然后就可以添加参数了哟。
4. 您是说首次进入，就发现锁定了？有显示被谁锁定了吗？会不会当时您的同事也在访问编辑同一个接口呢

**Comment by guowei1651** [comment]
嗯嗯。谢谢。
1. 在进入系统之后添加接口不能添加消息体，也不显示新加的接口。所以，我认为在点击添加接口之后会弹出框进行消息体的添加，但是没有。
2. 在刷新几遍之后，接口可以显示出来，但是没有消息体。我就点击编辑，结果立马编程接口已锁定，也没有弹出消息体编辑页面。而且一直是锁定态。
3. 接口测试，我点击接口上面的接口测试。弹出来test.jquery.html页面无法找到。不是在前端的，提示的是后端没有这个文件。

**Comment by zhiqiang0626** [comment]
前后端都是最新的代码，和楼上报一样的错误。
