### ISSUE TITLE
数据库连接池泄漏

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#370]
**BUG描述**
程序运行了几天以后，出现数据库无法访问的情况，后台日志显示查询超时。问题原因和解决方案后面补充。

**复现步骤**
超过8小时不跑任何流量

**期望结果**
mysql的连接数和连接池的连接数相同

**实际结果**
查看mysql中的连接数和程序连接池的连接数，程序的连接池连接数大于mysql的连接数（active）

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
MySQL5.7，默认配置
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

出现该问题的原因是因为连接池的配置问题。MySQL有一个配置参数：wait_timeout。该参数默认28800（8小时），含义是，连接挂起超时为8小时。数据库连接池连接数据库后，通过软件层面，维护了连接的状态。达到8小时，连接未发出任何sql后，连接会被mysql主动杀掉。此时连接池不知道连接已经死亡。所以连接池中就遗留了死连接。

解决方案：

1. 调整mysql的wait_timeout值，改为7天。但是可能造成mysql的连接泄漏的问题。
2. 连接池配置增加validate参数。

资料可以查询：
https://github.com/sequelize/sequelize/issues/7068
https://github.com/coopernurse/node-pool/blob/v2.5/lib/generic-pool.js#L90

涉及的文件可能是：

- config.prod.ts
- config.dev.ts
- config.local.ts

`db.pool.validate`

想体pr来着，但是确实不回nodejs。目前我们的解决方式是修改了数据库连接超时时间为7天。期待尽快修复。这个问题困扰我们很久了。

**Comment by Bosn** [comment]
非常感谢亲带solution的issue，已经在处理。
