### ISSUE TITLE
cnpm run dev 失败

### ISSUE THREAD

**Issue by jx10086** [thx/rap2-delos#371]
**BUG描述**
![image](https://user-images.githubusercontent.com/5323228/47553932-d209fa80-d93a-11e8-9680-a2835efc3f24.png)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
node版本太低了，不支持async func，注意下README对于环境版本的要求哦亲
