### ISSUE TITLE
接口编辑后无法保存

### ISSUE THREAD

**Issue by javajeans** [thx/rap2-delos#372]
**BUG描述**
进入接口编辑，保存和取消无法点击

**复现步骤**
1.进入实例模块
2.点击编辑
3.随意输入一组参数
4.点击保存

**期望结果**
能够点击保存

**实际结果**

**截图**
报错效果
![image](https://user-images.githubusercontent.com/5735392/47567619-9e8e9680-d961-11e8-98f8-11a5f65592da.png)

浏览器console截图
![image](https://user-images.githubusercontent.com/5735392/47567695-dbf32400-d961-11e8-8f2a-fe0896a7a215.png)

**环境**

环境是
centos7.4，服务端是docker环境
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
Docker中的镜像版本过旧，人力问题官方不维护docker镜像，配置文件仅供参考。请使用最新master分支代码构建。

**Comment by AnInputForce** [comment]
我在11天回复过类似issue，希望对你有所帮助：

> 我是升级了六个月前的rap2到现在的版本。发现无法编辑。

> 仔细梳理，应该是变更完字段，没有更新redis缓存。清空缓存后，问题解决，可以编辑。验证中。
> 不知道你们是不是这种情况，仅供参考。
> 
> 查看release目录下的md：


> > V2.6 更新说明 2018-7-5
> > 数据库字段变更请执行 datbase/v2.6***
> > 因字段变更，需要清空redis缓存
> > 运行redis-cli
> > 执行 flushall 命令清空缓存
