### ISSUE TITLE
个人新建仓库，转为团队仓库的功能新增

### ISSUE THREAD

**Issue by amiter** [thx/rap2-delos#374]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
> 在使用rap的过程中，如果有同学以个人身份创建了一个项目，在没有添加项目成员的情况下其他人无法查看，在实际内部使用中，权限按团队分配的。造成项目添加成员很繁琐，现在手动改数据库把项目改为团队项目。

**您是否有建议的实现方案**
> 在项目编辑时，可以将项目改为团队项目

**其它帮助我们理解您需求的描述、截图**

**Comment by blackdog1987** [comment]
我们也需要。。。
目前是通过改库。。。
人员离职以后，交接仓库管理员也是改库

**Comment by Bosn** [comment]
模块移动已支持，还支持JSON导出导入。
