### ISSUE TITLE
支持redis sentinel

### ISSUE THREAD

**Issue by zackzhangzz** [thx/rap2-delos#375]
能否支持redis sentinel模式？

**Comment by Bosn** [comment]
不了解哦亲，配置文件都在config.xxx.ts中，您可以自行随意修改和设置哦亲。

**Comment by zackzhangzz** [comment]
redis.ts中
 private static client: redis.RedisClient = config.redis && config.redis.isRedisCluster ? new ioredis.Cluster(config.redis.nodes, {redisOptions: config.redis.redisOptions}) : redis.createClient(config.redis)
限定死了就单机和cluster模式

**Comment by zackzhangzz** [comment]
不了解为什么要随便关闭呢

**Comment by zackzhangzz** [comment]
private static client: redis.RedisClient = new ioredis({
    sentinels: [{ host : '10.202.80.117', port: 17800 }, { host : '10.202.80.118', port: 17800 }],
    password : 'zhangzhen16@xg',
    name: 'master7800',
	connectTimeout: 5000
  })
按照思路改的代码

**Comment by Bosn** [comment]
@zackzhangzz 亲，RAP2默认给出的是常见的redis / redis cluster的配置哦，具体使用redis sentinel 技术，或其他更深入的用法，RAP2是开源的您可以自行配置和修改即可。

如何使用redis不是本issues区域讨论的问题范围。我认为回答完了，或者跑题的issue我就会关闭。您认为没有解决，也可以随时reopen呀
