### ISSUE TITLE
rap to rap2 数据库迁移脚本

### ISSUE THREAD

**Issue by wangdongxun** [thx/rap2-delos#378]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
希望能提供rap1 to rap2 数据库迁移脚本

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by gitrootid** [comment]
可以参考我写的：https://github.com/gitrootid/rootidspider/tree/master/rap1_to_rap2

**Comment by Bosn** [comment]
除了楼上写的以外，本身RAP2，在团队主页下仓库的页面，有导入功能，可以从RAP1导入到RAP2，按项目
