### ISSUE TITLE
我在官网http://rap2.taobao.org/创建了仓库，并创建了接口，但是别人打开后是空的

### ISSUE THREAD

**Issue by jimpier** [thx/rap2-delos#379]
**BUG描述**
我在官网http://rap2.taobao.org/创建了仓库，并创建了接口，但是别人（非团队人员）打开后是空的，打开浏览器开发者工具，报错了
![image](https://user-images.githubusercontent.com/23303312/48058411-50935180-e1f1-11e8-913d-3bca033035fd.png)

**Comment by Bosn** [comment]
这种情况需要您将该用户加到团队的项目成员里。
