### ISSUE TITLE
会增加对外部模拟请求吗？

### ISSUE THREAD

**Issue by monkeyming** [thx/rap2-delos#38]
**会增加对外部模拟请求吗？**
完成接口开发后，想用rap生成的请求参数，去调用实际地址！这部分功能会增加吗？

**Comment by Bosn** [comment]
有的，这个部分会通过导出Postman脚本来实现真实接口测试。

**Comment by Adol1111** [comment]
@Bosn 问一下是导出Postman脚本，然后再手动到Postman中执行，还是能直接发起请求？还有能否像postman一样，存储测试用例？

**Comment by Bosn** [comment]
该功能还在研发中
