### ISSUE TITLE
响应内容json导入出现500异常

### ISSUE THREAD

**Issue by WangJias** [thx/rap2-delos#380]
**BUG描述**
接口响应内容，使用json导入, 当json内有字段值为null时, 提交至后台的type字段为Null, 报500异常

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
chrome  70.0.3538.77

**附加信息**

**Comment by espider** [comment]
请问这个bug解决了么？我用的master版本还有这个问题

**Comment by yklove** [comment]
@espider 可以参考这个解决 https://github.com/thx/rap2-delos/pull/383

**Comment by espider** [comment]
@yklove 感谢回复，我已经自己改了下～
