### ISSUE TITLE
希望未来能够支持rpc接口管理

### ISSUE THREAD

**Issue by chinaccj** [thx/rap2-delos#382]
比如dubbo：参数里面是对象，返回值也是对象。

**Comment by chinaccj** [comment]
简介如何支持换行？

**Comment by Bosn** [comment]
暂时没有人力支持该需求哦，我们内部要优先满足我们自己的技术需求。暂时没有RPC

简介换行，问题，我们会考虑增加，谢谢。

**Comment by zhouxiaohai** [comment]
希望支持jsonrpc接口管理

**Comment by Bosn** [comment]
有特殊接口要求可以自行nginx proxy中转，或直接修改源代码进行支持。
