### ISSUE TITLE
编辑接口保存后，提示【发生错误：undefined】

### ISSUE THREAD

**Issue by oklhg** [thx/rap2-delos#384]
使用Dokcer+Nginx静态文件的方式进行部署，其他操作都正常，在编辑接口选择保存或取消的时候，会报：【发生错误：undefined】，尝试各种方式，均会出现。部署环境为Centos7

**Comment by mrlizonglin** [comment]
同问。

**Comment by Bosn** [comment]
请参考楼上相似问题的解决方案，有问题再reopen
