### ISSUE TITLE
操作日志接入MQ

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#385]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
通过MQ（kafka）投递操作日志消息，以便和其他系统集成。
比如：某系统通过kafka订阅消息，被通知某接口发生了改变（修改，删除），通过调用/repository/get接口获取接口最新的完整信息
![7cd60d1a-3855-467d-abb8-d245d02f3da0](https://user-images.githubusercontent.com/2356974/48390032-1539db00-e73b-11e8-9bab-34cc6f7583b9.png)

**您是否有建议的实现方案**
如果你们有计划我就等你们的代码了，如果没计划的话回头我调试好了提PR了

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
暂时没有这个开发计划，欢迎提PR，感恩的❤️

**Comment by blackdog1987** [comment]
> 暂时没有这个开发计划，欢迎提PR，感恩的❤️

我关啦  用canal实现了
