### ISSUE TITLE
使用特殊节点“_root_”，访问mock地址，输出结果带有"_root_"

### ISSUE THREAD

**Issue by lijiema** [thx/rap2-delos#387]
复现步骤：
1.  preview 里去掉了 __root__, 但请求页面包含
地址： 

<img width="1156" alt="screen shot 2018-11-15 at 4 16 34 pm" src="https://user-images.githubusercontent.com/42959845/48539427-09444980-e8f2-11e8-8984-ae355616db53.png">
<img width="773" alt="screen shot 2018-11-15 at 4 26 56 pm" src="https://user-images.githubusercontent.com/42959845/48539839-4fe67380-e8f3-11e8-9aec-6b26e8f6f24d.png">

**Comment by Bosn** [comment]
注意是2个下划线，不是1个。
