### ISSUE TITLE
接口body类型不管怎么选，导出的postman接口的mode都是formdata

### ISSUE THREAD

**Issue by liuandong** [thx/rap2-delos#388]
**BUG描述**
axios默认的是json/application,我们期望它可以直接导给后端的postman
但是接口body类型不管怎么选，导出的postman接口的mode都是formdata

**复现步骤**
接口body类型不管怎么选，导出的postman接口的mode都是formdata

**期望结果**
可以支持body是json/application格式的postman接口输出

**实际结果**

**截图**

**环境**
rap2api.taobao.com

**附加信息**

**Comment by saheibe** [comment]
同问  ，遇到同样的问题 ，

**Comment by mengTnT** [comment]
我也是这个问题，这样的话，导入postman这个功能似乎也没用了

**Comment by fanbo11** [comment]
是的，是的，我也遇到这个问题，还有一个问题就是参数选择为必选，也传值了，postman调用返回未填。https://github.com/thx/rap2-delos/issues/394

**Comment by JyFangYang** [comment]
![image](https://user-images.githubusercontent.com/49144942/55311313-2b032f00-5495-11e9-98e8-497d3a678129.png)    此处写死  并且数据库没有字段存储所选择body类型。

**Comment by Delena1988** [comment]
同问 ，遇到同样的问题

**Comment by shengang1978** [comment]
我还以为只有我碰到这个问题。 都半年了， 这个bug还没有修复啊。这个响应速度有点慢啊

**Comment by fanbo11** [comment]
已经放弃治疗了
 
 
------------------ Original ------------------

**Comment by xu1225** [comment]
同问 ，遇到同样的问题

**Comment by treadpit** [comment]
支持了下选择 `body params` 为 `raw` 的格式，能正常导出为 `postman` 可识别的 `json` 文件，[可使用该仓库下的 `docker-compose.yml` 文件](https://github.com/treadpit/rap2-delos)，前端仓库 `rap2-deloers` 是不是太久没更新了跑起来错误太多了...

**Comment by gggfreak** [comment]
这项目是否没人维护了。试了下用官方的平台，也有这样的问题

**Comment by androidxu** [comment]
有点担忧。

**Comment by twodogegg** [comment]
18年的问题，现在还没解决。又是一个烂尾项目么。
同问也有这个问题啊。

**Comment by Bosn** [comment]
目前接口还没有对 `content-type` 描述上的支持。

参数位置上这两天会修复

**Comment by Bosn** [comment]
导出postman我们内部用的很少，同时raw类型，其实和常规的key + value类型差异比较大，所以这个问题一直HOLD。

对于`content-type` 由于Mock服务其实不会做特殊的支持，所以完全可以在接口描述里去添加。（当然如果有合适的场景我们也可以新增这个支持）

对于Postman的raw类型、其它类型的导出，我们暂时不考虑在官方支持。
