### ISSUE TITLE
引用请求参数问题

### ISSUE THREAD

**Issue by que01** [thx/rap2-delos#390]
**BUG描述**
$参数名$仅能替换json根节点的变量 在对象内部则无法替换。
```
{
  foo       <--- 这里可以替换
  subData: {
      foo   <--- 这个位置就不会被替换
  }
}
```

**Comment by JoyceLizhuo** [comment]
我这边是只有url?xxx=ssss这种请求参数可以通过 $参数名$ 获取，当参数为url/:id或者body中的参数时候都不能获取到用 $参数名$

**Comment by Bosn** [comment]
已标记为bug，解决中

**Comment by Hack-DJ** [comment]
> 已标记为bug，解决中

除了引用参数不能在非根节点不能替换外，以后能不能再function 中执行呢？比如根据参数返回不同结果这种，现在貌似是输出的时候直接替换展示的

**Comment by baoluqi** [comment]
> 除了引用参数不能在非根节点不能替换外，以后能不能再function 中执行呢？比如根据参数返回不同结果这种，现在貌似是输出的时候直接替换展示的

遇到了相同的问题，现在又办法在function中使用参数做筛选吗？

**Comment by akkuman** [comment]
> 我这边是只有url?xxx=ssss这种请求参数可以通过 $参数名$ 获取，当参数为url/:id或者body中的参数时候都不能获取到用 $参数名$

@Bosn 相同的问题

**Comment by JserShadow** [comment]
这个bug貌似还是存在

**Comment by JserShadow** [comment]
这个问题貌似还是存在
![image](https://user-images.githubusercontent.com/30838436/80274995-11243200-8711-11ea-8bb4-48fcba2408c9.png)
入参：?keyword=aaa
![image](https://user-images.githubusercontent.com/30838436/80275031-43ce2a80-8711-11ea-9d81-7999c56073f1.png)
大概什么时候可以修复呢😢

**Comment by MaybeQHL** [comment]
目前bug还在

**Comment by showkiwi** [comment]
bug依然存在，啥时解决一下呗

**Comment by geeklyc** [comment]
$pageOffset$ 最外层能生效，里层就不行

**Comment by Bosn** [comment]
修复了修复了。。。稍后提交代码.

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/commit/872e5aae21454421591954aeeca6d31795943e17
