### ISSUE TITLE
create-db 数据错误

### ISSUE THREAD

**Issue by xywf221** [thx/rap2-delos#391]
**BUG描述**
部署rap2完全按照流程来的，但是dolores前端提示账号密码错误,进去进去看了下代码逻辑
，密码逻辑是md5(md5(password)),进入数据库查看发现密码全是明文！！
**复现步骤**
不死心删除表重来一次,还是老样子,后台数据库把admin的密码改为c3284d0f94606de1fd2af172aba15bf3 重试登录成功

**期望结果**
其实这个自己改改表数据就能用，只是过来反馈下

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
亲，这是故意的。可能默认名字换**reserve**这样更好。create-db生成一些测试数据，只是为了快速了解环境正常。但是显然，不应该让所有的部署，都可以用同样的账号密码登陆。

例如有人部署，不允许外部注册，但是通过初始化数据可以登陆，这是非常危险的。
