### ISSUE TITLE
复制接口bug

### ISSUE THREAD

**Issue by wang1784594241** [thx/rap2-delos#392]
**BUG描述**
复制接口看了一下接口数据，字段的父id居然不是新接口里字段的id，而是被复制接口里的字段id，导致只能显示父id为-1的数据

**复现步骤**
移动接口-复制

**期望结果**
复制正确

**实际结果**
复制完只能显示父id为-1的数据

**截图**

**环境**
自建服务器 但是这个问题应该是你们后台的问题 
**附加信息**
看到之前也有人提这个bug，赶紧解决吧，用的太难受了

**Comment by espider** [comment]
还没解决么？看来只能自己改了

**Comment by Ankerxiao** [comment]
@wang1784594241 @espider 请问你们是怎么解决接口复制的问题的

**Comment by espider** [comment]
> @wang1784594241 @espider 请问你们是怎么解决接口复制的问题的

把非一级节点也都复制一遍，附上正确的父ID就行
