### ISSUE TITLE
勾选必填后，即使传值也提示未传值

### ISSUE THREAD

**Issue by xalexec** [thx/rap2-delos#394]
**BUG描述**
勾选必填后，即使传值也提示未传值

**复现步骤**
新建请求参数 Body Params-raw导入
{
  "data": {
    "a": {
      "b": 1,
      "c": 1
    }
  }
}
勾选b为必选字段
新建响应内容 
{
  "meta": {
    "success": true
  }
}
postman 发送
{
  "data": {
    "a": {
      "b": 1,
      "c": 1
    }
  }
}

**期望结果**
{
  "meta": {
    "success": true
  }
}
**实际结果**
{
    "isOk": false,
    "errMsg": "必选参数b未传值。 Required parameter b has no value."
}

**截图**
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/3349091/48898566-07e1c680-ee88-11e8-9fef-427908d657ee.png">

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by fanbo11** [comment]
顶一下，我也遇到这个问题。

**Comment by fanbo11** [comment]
期待高手解答。

**Comment by Bosn** [comment]
你接口定义的是，data.b必传，还是b必传？

有一种情况就是你定义了b必传，但是你传的是data, data.b是有的。那。。。自然。。。不可以。

**Comment by fanbo11** [comment]
还有一个问题是：类型：post的接口点击地址连接报错 :{"isOk":false,"errMsg":"未匹配到任何接口 No matched interface"}

**Comment by fanbo11** [comment]
> 你接口定义的是，data.b必传，还是b必传？
> 
> 有一种情况就是你定义了b必传，但是你传的是data, data.b是有的。那。。。自然。。。不可以。



> 你接口定义的是，data.b必传，还是b必传？
> 
> 有一种情况就是你定义了b必传，但是你传的是data, data.b是有的。那。。。自然。。。不可以。

"data": {
"b": 1,
"c": 1
}
类似于上面的结构，data 和 b同时定义必传或其中一个定义必传都会报错。

**Comment by fanbo11** [comment]
https://github.com/thx/rap2-delos/issues/394#issuecomment-465393880
"data": {
"b": 1,
"c": 1
}
类似于上面的结构，data 和 b同时定义必传或其中一个定义必传都会报错。

**Comment by fanbo11** [comment]
@Bosn 
"data": {
"b": 1,
"c": 1
}
类似于上面的结构，data 和 b同时定义必传或其中一个定义必传都会报错。

**Comment by fanbo11** [comment]
**复现步骤**
新建post请求，参数 Body Params-raw导入
{
    "key1": "value1",
    "key2": "value2",
    "data": {
        "b": 1,
        "c": 1
    }
}
勾选data和b为必选字段或data和b任意一个为必选字段。
新建响应内容
{
    "meta": {
        "success": true
    }
}
postman 发送
{
    "key1": "value1",
    "key2": "value2",
    "data": {
        "b": 1,
        "c": 1
    }
}

**期望结果**
{
"meta": {
"success": true
}
}
**实际结果**
{
"isOk": false,
"errMsg": "必选参数b未传值。 Required parameter b has no value."
} 
------------------ Original ------------------

**Comment by deyi2019** [comment]
我遇到的是  head必选   postman请求后  提示未传值。。。
