### ISSUE TITLE
在我没有加入仓库（有加入团队）的时候，能看到这个仓库，但是点击进入这个仓库就出错。

### ISSUE THREAD

**Issue by yangdehong** [thx/rap2-delos#395]
**BUG描述**
在我没有加入仓库（有加入团队）的时候，能看到这个仓库，但是点击进入这个仓库就出错。

**复现步骤**
拿一个没有加入仓库而有加入团队的人，点击全部仓库，进入

**期望结果**
有进入能看但是没有修改权限

**实际结果**
报错

**截图**
![image](https://user-images.githubusercontent.com/29390137/48903626-053a9d80-ee97-11e8-9e74-d7f7335263e5.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
最新版已修复
