### ISSUE TITLE
有时候保存失败，不知道是不是参数太多的问题

### ISSUE THREAD

**Issue by yangdehong** [thx/rap2-delos#396]
**BUG描述**
有时候保存失败，不知道是不是参数太多的问题

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/29390137/48905648-14244e80-ee9d-11e8-88f7-7ad81fbcdb77.png)
![image](https://user-images.githubusercontent.com/29390137/48905676-29997880-ee9d-11e8-846b-5f6f85f59301.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by MethodAndParagon** [comment]
这个原因是字段里面不能有null，你的这个distributorPhoneNumberId 传json的时候是null，导致保存时候发生错误，无法保存。建议修改成""试试。

**Comment by yangdehong** [comment]
我的这个是Long类型的数据，不能用”“的，有没有其他问题啊

**Comment by yangdehong** [comment]
> 这个原因是字段里面不能有null，你的这个distributorPhoneNumberId 传json的时候是null，导致保存时候发生错误，无法保存。建议修改成""试试。

我的这个是Long类型的数据，不能用”“的，有没有其他问题啊

**Comment by SuperTommy007** [comment]
string类型的值不能为空

**Comment by MethodAndParagon** [comment]
> > 这个原因是字段里面不能有null，你的这个distributorPhoneNumberId 传json的时候是null，导致保存时候发生错误，无法保存。建议修改成""试试。
> 
> 我的这个是Long类型的数据，不能用”“的，有没有其他问题啊

Long用0啊，就是他这个不能用null，都要给默认值

**Comment by Bosn** [comment]
请给出可以复现的步骤，“有时候”的问题，不是很好排查呀亲
