### ISSUE TITLE
通过《导出到Postman》这个接口可以爬到所有用户的仓库

### ISSUE THREAD

**Issue by 1010543618** [thx/rap2-delos#398]
**BUG描述**
通过《导出到 Postman 》这个接口可以爬到所有用户的仓库

**复现步骤**
http://rap2api.taobao.org/postman/export?id=$1至100000$

**附加信息**
改成生成的 URL 参数为 GUID 且一定时间内可以下载怎么样？很乐意 Pull requests 。

**Comment by Bosn** [comment]
欢迎提交MR，确实本项目没做安全性校验。对于安全级别有要求，存放敏感数据的，建议内网搭建即可。

**Comment by 1010543618** [comment]
@Bosn 有时间尝试下 : )
