### ISSUE TITLE
需求：仓库页增加修改日志查看功能

### ISSUE THREAD

**Issue by blackdog1987** [thx/rap2-delos#399]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在查看某个仓库的时候，通过页面无法知道最近有没有修改，有哪些大概的修改

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
最新版已支持版本管理和查看，就等咯
