### ISSUE TITLE
run dev 时报错

### ISSUE THREAD

**Issue by dbliu** [thx/rap2-delos#4]
前面步骤正常， npm run check  也无报错

开发环境：
   系统： win7 x64;
    node:  8.9.0
    npm： 5.5.1

报错日志：

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle rap2-delos@1.0.0~predev: rap2-delos@1.0.0
6 info lifecycle rap2-delos@1.0.0~dev: rap2-delos@1.0.0
7 verbose lifecycle rap2-delos@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-delos@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\rap2\node_modules\.bin;C:\Users\53KF\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\53KF\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Users\53KF\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle rap2-delos@1.0.0~dev: CWD: C:\rap2
10 silly lifecycle rap2-delos@1.0.0~dev: Args: [ '/d /s /c',
10 silly lifecycle   'NODE_ENV=development nodemon --watch scripts --watch src scripts/dev.js' ]
11 silly lifecycle rap2-delos@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle rap2-delos@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: rap2-delos@1.0.0 dev: `NODE_ENV=development nodemon --watch scripts --watch src scripts/dev.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rap2-delos@1.0.0
15 verbose cwd C:\rap2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-delos@1.0.0 dev: `NODE_ENV=development nodemon --watch scripts --watch src scripts/dev.js`
22 error Exit status 1
23 error Failed at the rap2-delos@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Bosn** [comment]
建议使用虚拟机Linux进行操作和部署，windows系我没时间研究...

开源社区、一些环境上的支持程度，也确实很有限。
