### ISSUE TITLE
拖拽进入数据或者对象里

### ISSUE THREAD

**Issue by mynameismaosheng** [thx/rap2-delos#400]
![3e0b853254db262a235b6675233b74f](https://user-images.githubusercontent.com/19756360/49005110-decf7780-f1a0-11e8-9a29-15c7ba8a4132.png)
我记得rap1是可以实现这个, 
在rap2里, 起先创建的数据结构想的不够周全, 想拖进去.  这个拖拽只支持排序没有支持修改数据结构呀

**Comment by Bosn** [comment]
rap1还真没这个功能。。。。但是确实有字段的复制功能，这个我会考虑后续加到rap2里。
