### ISSUE TITLE
rap2-dolores在docker中如何通过环境变量来控制server连接配置

### ISSUE THREAD

**Issue by smooth00** [thx/rap2-delos#403]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
如题，rap2-dolores中的配置文件rap2-dolores/src/config/config.prod.js写死了，生成docker时如何通过环境变量来配置，没找到好的方法。

**您是否有建议的实现方案**
建议提供一下docker运行的样例说明

**其它帮助我们理解您需求的描述、截图**

**Comment by maxiloEmmmm** [comment]
download project and zip to rap2.tar.gz
`bash
#dockerfile
FROM node

RUN npm install serve -g && mkdir ~/app && cd ~/app
WORKDIR ~/app
ADD ./rap2.tar.gz .
RUN cd rap2 && npm install

EXPOSE 80
CMD cd rap2 && npm run build && serve -s ./build -p 80 `

`js
//src/config/config.prod.js
serve: process.env.REACT_APP_BACK_SERVER_ADDR
`

`bash
docker run -p 80:80 -e REACT_APP_BACK_SERVER_ADDR=url_width_protocol  -d u_build_imgage_name`

**Comment by ganl** [comment]
参考 [修改配置](https://github.com/ganl/rap2-docker#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE)


修改.env，主要的几个地方：

* 修改dolores中delos服务的serve相关值

```
# used in config.prod.js
DELOS_SERVE_PROTOCOL=http
# local's IP or Domain or hostname
DELOS_SERVE_HOST=localhost
#Generally, same with DELOS_PORT
DELOS_SERVE_PORT=8080
```

**Comment by smooth00** [comment]
> 参考 [修改配置](https://github.com/ganl/rap2-docker#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE)

非常感谢，这才是我们想要的一整套方案

**Comment by Bosn** [comment]
感谢楼上以及开源爱好者提供的补充，谢谢。
