### ISSUE TITLE
移动接口复制Array工作不正常

### ISSUE THREAD

**Issue by Bosn** [thx/rap2-delos#407]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Ankerxiao** [comment]
@blackdog1987 请问你是怎么解决复制问题的，我这边根本就复制不了，报下面这个错
![image](https://user-images.githubusercontent.com/15648589/61343667-27978600-a881-11e9-9370-c04b1bf29d3d.png)

**Comment by blackdog1987** [comment]
> @blackdog1987 请问你是怎么解决复制问题的，我这边根本就复制不了，报下面这个错
> ![image](https://user-images.githubusercontent.com/15648589/61343667-27978600-a881-11e9-9370-c04b1bf29d3d.png)

@Ankerxiao 初步看起来是字段中的字符串拿出来转JSON的是否报错了，你这个和我说的那个不一样。
Unexpected token I in JSON at position。。。。。。

**Comment by Ankerxiao** [comment]
@blackdog1987 那这个怎么解决呢，我看源码也不知道怎么弄，你能帮我看看吗
