### ISSUE TITLE
Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by 91diy** [thx/rap2-delos#409]
**BUG描述**
本地部署完成后，登录，注册皆出现 Unexpected token I in JSON at position 0，服务端500报错。
POST http://127.0.0.1:8080/account/register 500 (Internal Server Error)
loggerMiddleware.js:6 USER_ADD_FAILED
loggerMiddleware.js:7 

**复现步骤**

**期望结果**

**实际结果**

**截图**

![Uploading 1.png…](
![Uploading 2.png…]()
)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by AnInputForce** [comment]
我是升级了六个月前的rap2到现在的版本。发现无法编辑。前端报同样错误。
仔细梳理，应该是变更完字段，没有更新redis缓存。清空缓存后，问题解决，可以编辑。验证中。
不知道你们是不是这种情况，仅供参考。

查看release目录下的md：

> # V2.6 更新说明 2018-7-5

> * 数据库字段变更请执行 `datbase/v2.6***`
> * 因字段变更，需要清空redis缓存
>  1. 运行redis-cli
>   2. 执行 `flushall` 命令清空缓存

**Comment by Bosn** [comment]
谢谢亲分享解决方案。

**Comment by BurningCloud** [comment]
Unexpected token I in JSON at position 0
