### ISSUE TITLE
错误的验证码

### ISSUE THREAD

**Issue by 91diy** [thx/rap2-delos#411]
**BUG描述**

错误的验证码。

开发者模式npm run dev启动报错：错误的验证码。

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/34885851/50037891-b0331700-0051-11e9-850d-51b9b43c5615.png)

**附加信息**

**Comment by Bosn** [comment]
点验证码，换一个试试呢

**Comment by yangxylab** [comment]
换了100次都换不对啊……

**Comment by yangxylab** [comment]
楼主怎么解决的呢

**Comment by yangxylab** [comment]
我解决了，我是直接用的生产模式，在配置里面把数据库名称改了，session key改了，就OK了。官方连个完整的文档都没有，真是累死人

**Comment by Bosn** [comment]
非常抱歉哦
