### ISSUE TITLE
如何配置静态文件打包路径

### ISSUE THREAD

**Issue by vacants** [thx/rap2-delos#412]
因为域名限制，rap2-dolores 生成的文件不能放在域名根目录下，比如我需要使用 http://abc.domian.com/rap 这个路径访问首页，这时候会提示 No match for /rap/，而且点击"首页"的时候会跳回 http://abc.domian.com

有没有什么方法可以配置使用子路径进行访问呢？

![2018-12-21_185755](https://user-images.githubusercontent.com/16208824/50339420-83e83080-0552-11e9-94c6-7730abd4dd89.png)

**Comment by Bosn** [comment]
修改下首页链接就好了呀
