### ISSUE TITLE
页面展示"I"和“l”问题

### ISSUE THREAD

**Issue by Mr147** [thx/rap2-delos#413]
![qq 20181229170540](https://user-images.githubusercontent.com/29937292/50536121-05137900-0b8c-11e9-8eba-7259c39cca47.png)
图中的第一个参数mobile的倒数第二个字符是小写l；第三个参数sprdId的倒数第二个字符是大写I；展示的一模一样，请优化

**Comment by Bosn** [comment]
臣妾做不到啊
