### ISSUE TITLE
接口地址能否支持通配符？

### ISSUE THREAD

**Issue by leafOfTree** [thx/rap2-delos#414]
有些接口地址包含了变化的参数，如 id，后端会写成 `/example/{id}`。

请问在定义接口地址时能否支持通配符，例如 `/example/*`，能匹配 `/example/1`, `/example/2` 等？

**Comment by ganl** [comment]
支持的
例如：user/:id([0-9]+)

**Comment by leafOfTree** [comment]
谢谢
