### ISSUE TITLE
请求参数

### ISSUE THREAD

**Issue by webzlj** [thx/rap2-delos#415]
**BUG描述**
rap2：请求参数foo为必选参数，然后前端传过来的foo值为空--http://rap2api.taobao.org/app/mock/122706/dash?foo    这样也可以有响应，请问是接口设置如何设置验证呢，还是没有这个功能。请问有学习文档吗，都搜索不到

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
目前判断上，只要有参数（不是undefined）就算传了，如果判断参数是否传，要考虑到空字符串，0这种情况，目前还不支持，可以自行修改源代码进行逻辑上的补充。后续这块儿0值如何处理，我也会规划一下如何优化，谢谢。
