### ISSUE TITLE
前端服务(rap2-dolores)访问显示空白页面

### ISSUE THREAD

**Issue by deif2005** [thx/rap2-delos#416]
**BUG描述**
后端服务启动正常，但是前端访问显示页面空白，页面title显示正常。

**复现步骤**

**期望结果**

**实际结果**

**截图**
![q1](https://user-images.githubusercontent.com/11917091/50688275-af454200-105f-11e9-84d9-e3ff85c49793.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
要看F12面板，控制台错误消息
