### ISSUE TITLE
restful 接口参数类型支持

### ISSUE THREAD

**Issue by dongm2ez** [thx/rap2-delos#42]
现在不能区别资源传值的不同

比如 PUT {{host}}:{{port}}/post/:org_id/info/:increment_id?order_type=all

环境变量、url参数、问号传参以及body传值都无法区分，希望未来能够加入这些区分功能

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/issues/9

该功能已实现，代码参考上面的issue哈，具体源码如下。rap2.taobao.org更细预计在月底前。

https://github.com/thx/rap2-delos/commit/7f9442cd0acd757880b92a8dcf2f562e4e73f96e
