### ISSUE TITLE
docker部署异常

### ISSUE THREAD

**Issue by showdown-zhou** [thx/rap2-delos#424]
自己基于docker部署的后台服务，点击编辑的时候总是提示“接口被锁定”，点击保存都是未知错误
![image](https://user-images.githubusercontent.com/39110520/51177077-9bb89780-18f9-11e9-8d9b-3ce60f46904f.png)

**Comment by ofloxacin** [comment]
同样的问题

**Comment by hustar0102** [comment]
是因为使用

> 自己基于docker部署的后台服务，点击编辑的时候总是提示“接口被锁定”，点击保存都是未知错误
> ![image](https://user-images.githubusercontent.com/39110520/51177077-9bb89780-18f9-11e9-8d9b-3ce60f46904f.png)

是因为使用的docker-compose里的delos的版本太低
![image](https://user-images.githubusercontent.com/24261648/51373096-28519880-1b3a-11e9-928e-6e7f4f407153.png)
还是1.0.0，去docker hub中搜索blackdog1987/rap2-delos，换成最新版本，就能解决

**Comment by showdown-zhou** [comment]
> 是因为使用
> 
> > 自己基于docker部署的后台服务，点击编辑的时候总是提示“接口被锁定”，点击保存都是未知错误
> > ![image](https://user-images.githubusercontent.com/39110520/51177077-9bb89780-18f9-11e9-8d9b-3ce60f46904f.png)
> 
> 是因为使用的docker-compose里的delos的版本太低
> ![image](https://user-images.githubusercontent.com/24261648/51373096-28519880-1b3a-11e9-928e-6e7f4f407153.png)
> 还是1.0.0，去docker hub中搜索blackdog1987/rap2-delos，换成最新版本，就能解决

嗯已经解决了，我不通过镜像编译，通过最新的代码编译镜像就好了，谢谢

**Comment by liaozhide** [comment]
为什么我切换了rap2的tag版本   然后重新安装   还是不行？
