### ISSUE TITLE
建议：文档比较多的时候，修改查看都会变慢

### ISSUE THREAD

**Issue by MethodAndParagon** [thx/rap2-delos#425]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
文档比较多的时候（我这里大概有400个接口），修改查看都很慢。用redis monitor看的时候发现，存的缓存key， repository_id这个value是把整个需要都放了进去，导致这个value有好几MB，查看修改不很方便。

**您是否有建议的实现方案**
谈不上啥好建议，是否可以记录当前页，进去的时候，只显示当前页的东西，获取存储等也只是当前页，来降低value的大小提升速度。

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
嗯，确实是一个优化上的问题，已记录，感谢您的反馈。

**Comment by jiangyunhai** [comment]
我这边也是，看了下内存占用，已经2个多G了，非常慢，这目前只是一个项目库在用
请团队成员尽快优化吧，个人觉得这是个比较大的问题，虽然不属于BUG，但是团队用起来的确很头疼

**Comment by piaofudeyu** [comment]
rap1的时候就出现过类似问题，数据一下子都加载到内存中，导致巨卡巨慢。以为升级到2会好一些，开发人员会注意一些。没想到啊~ “阿里不过如此” 虽然不负责任，但是有一定的意思在里面
