### ISSUE TITLE
希望支持Swagger导入/导出，这样会让人非常陶醉的~ 3Q~

### ISSUE THREAD

**Issue by l308718280** [thx/rap2-delos#428]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
没人力鸭，因为我们自己不用Swagger😂😂😂
开源工具，有需要自行开发，感恩的❤️
另外本身API支持JSON格式数据的导入导出，其实做一个转换的adapor就好啦
