### ISSUE TITLE
官网注册不了，登录接口报错500 rap2.taobao.org

### ISSUE THREAD

**Issue by karosLi** [thx/rap2-delos#429]
1. DingDing Group ID 订订群: 11789704, 钉钉群怎么进入？
2.官网注册不了，登录接口报错500 rap2.taobao.org

**Comment by jeffwcx** [comment]
没人处理吗？完全登不上去！好坑啊，周末还得做东西。

**Comment by vikeham** [comment]
还没解决，项目解散了吗，好歹把数据还给我们啊！！！

**Comment by Bosn** [comment]
登陆没问题的啊，您可以看看，如果还是不行，可以把能有的信息（账号、密码）单独发到我的邮箱：
