### ISSUE TITLE
仓库权限疑问

### ISSUE THREAD

**Issue by wangyumin184** [thx/rap2-delos#43]
最近为公司部署了一套,试用了几天，有几个小问题
1. 仓库没有找到public 权限，必须为每个人分配一次权限，比较麻烦。希望增加权限选择。
2. 团队所属仓库，添加成员后，成员无法在 仓库 菜单直接看到该仓库，需进入团队菜单，然后从团队菜单才能发现该仓库。 （不知道是bug还是需求）
3. 项目中跳转页面全部使用的是  <Link to=’‘></Link> 进行路由跳转，请问如何为所有的路由统一添加一个跟路径 比如：  127.0.0.1:8080/repository   替换为   127.0.0.1:8080/xx/repository

**Comment by dongm2ez** [comment]
恩，同样有一个不方便的就是，团队成员在仓库内权限，现在只有所有者和成员，成员都可以编辑，希望能有开发者和只能看的而不能编辑的区分

**Comment by Bosn** [comment]
@dongm2ez 加入了团队，但没加入仓库成员的，就是只能看不能改。

目前我正在增加两种新的权限机制：

团队权限设置：公开（全员可见，改还是只有仓库成员可以改）， 私有（仅成员可见）

仓库权限设置：公开（所有团队成员可见，改还是只有仓库成员可以改），私有（团队成员也不可见，只有仓库成员可见）


对于楼主
@wangyumin184 所说的，没任何权限谁都能改的，出于安全考虑结合总体用户需求，不考虑实现。亲有这方面的需求可以自己在源代码上做修改。

**Comment by dongm2ez** [comment]
个人项目如何移交给团队

**Comment by Bosn** [comment]
仓库owner选别人就转移给别人了。

团队不能持有项目owner权限，只有用户才能持有owner权限。

**Comment by dongm2ez** [comment]
那如何将之前建立的个人项目转换成团队项目

**Comment by JasmineChoi** [comment]
同样遇到这个问题。有些成员没注意把项目建成自己的仓库了。如果转换成团队的仓库

**Comment by dongm2ez** [comment]
@JasmineChoi 我是通过修改数据库数据解决的，程序上没有相关功能

**Comment by JasmineChoi** [comment]
@dongm2ez 那就只能用自己部署的环境了。我们现在还用着阿里的环境
