### ISSUE TITLE
rap2 不同服务器之间的项目导入

### ISSUE THREAD

**Issue by fabianGitApp** [thx/rap2-delos#431]
之前我们添加了一个项目到淘宝服务器上（rap2），但是有些卡。
目前部署了一套到我们自己的服务器上（rap2），请问如何将之前的项目导过来

**Comment by Bosn** [comment]
很抱歉目前数据迁移上我们只提供了RAP1到RAP2，不同服务器之间的数据导入导出没有。
但是您可以参考API页面上提供的接口，可以获取整个RAP2的数据JSON，然后自行开发进行导入。
