### ISSUE TITLE
dock部署rap2后端，本地部署rap2前端，部署完成，在创建接口后进行编辑却 提示当前接口已经被 锁定！

### ISSUE THREAD

**Issue by liaozhide** [thx/rap2-delos#432]
**BUG描述**
dock部署rap2后端，本地部署rap2前端，部署完成，在创建接口后进行编辑却 提示当前接口已经被 锁定！  点击保存后  提示错误：undefined

**复现步骤**

**期望结果**

**实际结果**

**截图**
![rap2](https://user-images.githubusercontent.com/30857179/51827514-8d6c7180-2324-11e9-9668-157de4c5abe5.png)
![rap2](https://user-images.githubusercontent.com/30857179/51827520-90676200-2324-11e9-8794-f1b3bd86a140.png)

**环境**
环境为centos7

**附加信息**

**Comment by liaozhide** [comment]
求解决

**Comment by liaozhide** [comment]
目前确认是rap2的前端有问题，我切换rap2前端的dev代码，可以编辑保存，但是会出现访问空白的问题。切换master的话就会出现当前接口已经被 锁定的问题。求修复

**Comment by 1991wangliang** [comment]
我是今天刚用的最新的master代码docker方式部署的然后用 https://github.com/thx/rap2-dolores 编译的。但是发现编辑的时候提示锁定，然后刷新以后可以编辑。但是编辑完了以后就无法保存。
![qq 20190131170233](https://user-images.githubusercontent.com/5245347/52043303-5099b800-257a-11e9-8fd3-b8e324840d4b.png)

**Comment by ClausClaus** [comment]
查看https://hub.docker.com/r/blackdog1987/rap2-delos/tags的tag，切换到最新的2.6xx还是不行。。要哭了

**Comment by liaozhide** [comment]
不要用docker方式安装，docker安装有问题。本地安装可以

**Comment by liaozhide** [comment]
> 查看https://hub.docker.com/r/blackdog1987/rap2-delos/tags的标签，切换到最新的2.6xx还是不行..要哭了

不要用docker方式安装，docker安装有问题。本地安装可以

**Comment by Bosn** [comment]
非官方的docker的BUG，用官方的试试吧。其它途径的改版，只能找他们的作者去问问啥情况。
