### ISSUE TITLE
测试功能不可用

### ISSUE THREAD

**Issue by hustar0102** [thx/rap2-delos#433]
**BUG描述**
测试功能不可用

**复现步骤**
docker部署，在点击测试按钮时，显示not found

**期望结果**
显示接口的返回值

**实际结果**
显示not found

**截图**
![image](https://user-images.githubusercontent.com/24261648/51882394-b4c14e00-23b9-11e9-867d-596a1e7194b9.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
docker部署非官方提供的，请在对应的渠道的git上寻求帮助，谢谢。
