### ISSUE TITLE
无法新建仓库

### ISSUE THREAD

**Issue by ghost** [thx/rap2-delos#435]
**BUG描述**
淘宝提供的公网仓库无法新建仓库(http://rap2.taobao.com)

**复现步骤**

**期望结果**

**实际结果**

**截图**
POST http://rap2api.taobao.org/repository/create 500 (Internal Server Error)
repository.js:30 Unexpected token I in JSON at position 0

上面内容是chrome console展示打印的日志信息

**环境**
使用的是 http://rap2.taobao.org 提供的服务

**附加信息**

**Comment by Bosn** [comment]
经测试功能完好，请再试一次，如果扔有问题，请反馈您的账号到我的邮箱bosn@outlook.com  谢谢。
