### ISSUE TITLE
这个rap2和rap根本不是一个东西。。什么垃圾东西，官网都做不好，注册报错，还把那么多用户的信息直接显示出来，疯了吗

### ISSUE THREAD

**Issue by kdyzm** [thx/rap2-delos#436]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
您何必关注一个垃圾东西呢，人生苦短，活的开心。祝您心情愉快，慢走。
