### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by yanglijin0911** [thx/rap2-delos#439]
**BUG描述**
一直报如下错,急需解决

**复现步骤**
1.配置文件config.dev.ts
2.执行命令如下,执行到npm run build时报错如下:
npm install
npm install -g typescript
npm run build

**期望结果**

**实际结果**

**截图**
src/routes/router.ts:18:31 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

18 router.get('/status.taobao', (ctx) => {
                                 ~~~


src/routes/router.ts:21:34 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

21 router.get('/test/test.status', (ctx) => {
                                    ~~~

src/routes/router.ts:26:28 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

26 router.get('/proxy', async(ctx) => {
                              ~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rap2-delos@1.0.0 build: `rimraf -rf dist/ && tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rap2-delos@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-31T13_52_17_806Z-debug.log
[root@lab-sv-rap rap2-delos]# cat /root/.npm/_logs/20

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
阿里服务器,centos 7
**附加信息**

**Comment by Bosn** [comment]
TypeScript版本的问题，楼上给了反馈意见，您可以尝试一下。另外看起来像是没有找到ctx的TypeScript声明文件导致的。

**Comment by maxianwei** [comment]
3 verbose stack Error: rap2-delos@2.9.0 build: `rimraf -rf dist/ && tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid rap2-delos@2.9.0
15 verbose cwd /data/.jenkins/workspace/sls-developer-platform-service-test
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/root/.nvm/v10.16.0/bin/node" "/root/.nvm/v10.16.0/bin/npm" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error rap2-delos@2.9.0 build: `rimraf -rf dist/ && tsc`
22 error Exit status 2
23 error Failed at the rap2-delos@2.9.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

我跟楼主的报错看起来一样，我的tsconfig.json中的值就是false，可是还是报错，有谁可以解答一下吗
[root@test-jenkins service-test]# grep   noImplicitAny  tsconfig.json 
    "noImplicitAny": false,
