### ISSUE TITLE
不能注册，也不能登录，导致仓库数据不能拿到！！！如果可以，请开放一个仓库到处接口，或者将仓库数据发送给仓库所有者的邮箱

### ISSUE THREAD

**Issue by ArtIsLong** [thx/rap2-delos#440]
**BUG描述**
http://rap2.taobao.org/repository， 不能登录，也不能注册

**复现步骤**

**期望结果**
能够正常使用

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
非常抱歉，过年期间服务器爆仓了。我们没有专人维护线上站点，如果正式使用请自行部署。

http://rap2.taobao.org/api

对于仓库数据，其实一直有提供API来提供JSON形式的项目数据，您可以参考下。
