### ISSUE TITLE
注册和登录都会在请求里面显示用户的密码

### ISSUE THREAD

**Issue by pangkailang** [thx/rap2-delos#441]
**BUG描述**
登录时，或者注册时发现在请求里面能够看到密码明文

**复现步骤**
f12打开浏览器调试窗口---选择network--发送登录请求---看请求参数

**期望结果**
不会保留密码，post请求不该展现任何东西吧

**实际结果**

**截图**

![image](https://user-images.githubusercontent.com/31604104/52202053-4e03cf00-28a8-11e9-8b27-09c838db02bf.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
在线版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
不然呢。。。。😂😂😂
