### ISSUE TITLE
官网登陆报错

### ISSUE THREAD

**Issue by Weblcq** [thx/rap2-delos#442]
**BUG描述**
http://rap2api.taobao.org/account/login 500 (Internal Server Error)

AccountRelative.js:101 Unexpected token I in JSON at position 0
**复现步骤**
官网输入信息后点登陆

**期望结果**

登陆成功

**实际结果**
Unexpected token I in JSON at position 0

**截图**
 
![_20190211103052](https://user-images.githubusercontent.com/22806459/52543890-31a3ed00-2de8-11e9-8446-1ce146f1b450.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

http://rap2.taobao.org/  官网
**附加信息**

**Comment by wzlsz** [comment]
同上

**Comment by julysohu** [comment]
官方可以回复一下么。。api文档都在里边。。

**Comment by dunkboy** [comment]
天啊 太可怕了 这么多天都没人回复一句吗？

**Comment by Bosn** [comment]
服务器挂了，已恢复。在想办法升级配置。不过。。。我们这个就是同学们有空的时候自己在维护的项目，永远也不会收费，拿出来就是share一下。业务忙的时候，就没时间管了。所以建议您正式使用自行部署。

**Comment by pawoma** [comment]
写了两天的api文档，现在官网登录不了，一直提示密码错误，但我确定密码肯定正确， 密码找回也是收不到邮件，文档要发给产品看了，非常着急 ，能麻烦看下吗，或者帮忙把文档导出也行
