### ISSUE TITLE
该项目是否还在维护

### ISSUE THREAD

**Issue by guojilong** [thx/rap2-delos#443]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by 18688960184** [comment]
啥时候好啊，这个是常态吗？突然发现不能用了，着急啊

**Comment by xujj277** [comment]
官网最近一直挂

**Comment by zhongwuhunter** [comment]
官网太慢了，基本都打不开，用不了

**Comment by SuperTommy007** [comment]
自己部署的，用着挺好的啊

**Comment by Bosn** [comment]
官网主要用于demo，永不收费的。。。。也并没有专人维护。建议正式使用自己搭建。

该项目的源代码肯定会一直维护的，不过我们一般都是业务项目不忙的时候，才会搞一搞，并没有专人专职在维护。
