### ISSUE TITLE
TypeError: Cannot create property 'headers' on boolean 'false' ！

### ISSUE THREAD

**Issue by danxiao5201** [thx/rap2-delos#444]
TypeError: Cannot create property 'headers' on boolean 'false'
      at next.catch.err (/home/rap2/rap2-delos-master/node_modules/kcors/index.js:91:21)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by danxiao5201** [comment]
Has anybody met?

**Comment by danxiao5201** [comment]
RAP2

Click in after creating the warehouse. The page does not move. It is loaded all the time.

**Comment by Bosn** [comment]
How to reproduce this bug? Can u say it clear?

**Comment by waltkong** [comment]
How did you solve this ? I met this now ,got no idea. After creating a repository, enter into this repository and blocked here,continuing loading. The js error report is `
Access to fetch at 'http://127.0.0.1:8080/repository/get?id=16' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.  `

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
