### ISSUE TITLE
开发环境能通过web访问 生产模式就访问不了了

### ISSUE THREAD

**Issue by mogudada** [thx/rap2-delos#446]
**BUG描述**
开发环境能通过web访问 生产模式就访问不了了

**复现步骤**

**期望结果**
生产模式是不是不能web 访问

**实际结果**

**截图**
pm2访问不了
![image](https://user-images.githubusercontent.com/34201576/52851972-5aaedf80-3152-11e9-96c8-2e96ab9767d3.png)
开发者模式能访问
![image](https://user-images.githubusercontent.com/34201576/52852106-aeb9c400-3152-11e9-9847-85ba60f16f7b.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
是 centos7.5 
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by mogudada** [comment]
已经解决了 config里面的prod也要配置 一开始只配置了 dev

**Comment by javacodecreeks** [comment]
> **BUG描述**
> 开发环境能通过web访问 生产模式就访问不了了
> 
> **复现步骤**
> 
> 
> **期望结果**
> 生产模式是不是不能web 访问
> 
> **实际结果**
> 
> 
> **截图**
> pm2访问不了
> ![image](https://user-images.githubusercontent.com/34201576/52851972-5aaedf80-3152-11e9-96c8-2e96ab9767d3.png)
> 开发者模式能访问
> ![image](https://user-images.githubusercontent.com/34201576/52852106-aeb9c400-3152-11e9-9847-85ba60f16f7b.png)
> 
> 
> **环境**
> * 是否是自建服务器？如果为自建，请提供操作系统版本
> 是 centos7.5 
> * 如果是前端错误，请提供浏览器版本
> * 其它可能帮助我们排查问题的环境信息
> 
> **附加信息**
>
