### ISSUE TITLE
官网瘫痪中。。

### ISSUE THREAD

**Issue by julysohu** [thx/rap2-delos#447]
**BUG描述**
官网瘫痪中，无法使用，项目api文档都在里边。。如果不再提供服务能否把离线文档发给我们？

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by dunkboy** [comment]
对呀 官网好卡哦 根本没法用 如果要关闭 是不是应该提前告知一下呀 不然坑惨了

**Comment by SummerWindL** [comment]
建议自己搭建一个服务

**Comment by lanxiuying** [comment]
已经自行搭好了,但是没有转移的脚本，要自己写

**Comment by Bosn** [comment]
fixed，爆仓了，在和PE协调升级配置。生产使用建议自搭。
