### ISSUE TITLE
参数使用@dataimage标签无返回

### ISSUE THREAD

**Issue by yangxylab** [thx/rap2-delos#448]
**BUG描述**
如题，验证码api
响应参数名称img，类型string，初始值@dataImage('5x2')，前端测试无返回(返回{})
如果img初始值改为data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAG0lEQVQYV2P8fvnyf2Y+fgbGb+fP/2cWFGQAAFEWB3eGR+A+AAAAAElFTkSuQmCC
则没问题。
可是问题是他俩是一样的啊，只是一个是mock随机生成的，一个是手动固定的……
**复现步骤**

随意重复
**期望结果**
返回正常base64编码后的img

**实际结果**
{}

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
centos7.6 updated
* 如果是前端错误，请提供浏览器版本

* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by yangxylab** [comment]
补充一下，预览正常，就是访问接口不行……
![image](https://user-images.githubusercontent.com/35053204/52898561-67970600-321a-11e9-9ed9-27ae6097fa66.png)
![image](https://user-images.githubusercontent.com/35053204/52898572-7978a900-321a-11e9-97bb-5565c2da67cc.png)

**Comment by yangxylab** [comment]
继续补充图片
然后我把img改成base64的内容就好了，就是上面图中生成的那串base64图片内容
![image](https://user-images.githubusercontent.com/35053204/52898610-bf357180-321a-11e9-99fd-e469d638c5fd.png)
响应正常了
![image](https://user-images.githubusercontent.com/35053204/52898618-cfe5e780-321a-11e9-8e39-4b4ccbf74003.png)

**Comment by yangxylab** [comment]
还可以回复么

**Comment by Bosn** [comment]
@yangxylab 不好意思，我看你上面帖子说xxxx就好了，我以为您已经解决了😂😂😂

RAP2本身带的mockjs版本，可能和最新的mockjs版本不一致，也会导致功能支持上，不一定能对等。
我查一下。

**Comment by yangxylab** [comment]
> @yangxylab 不好意思，我看你上面帖子说xxxx就好了，我以为您已经解决了😂😂😂
> 
> RAP2本身带的mockjs版本，可能和最新的mockjs版本不一致，也会导致功能支持上，不一定能对等。
> 我查一下。

😂
辛苦辛苦！

**Comment by housuchuan** [comment]
请问这个问题解决了么 @Bosn

**Comment by 51037405** [comment]
mock.js 中调用了
`var Canvas = module.require('canvas')`
nodejs不支持canvas渲染，所以无法实现dataImage方法。
`TypeError: module.require is not a function`

**Comment by Bosn** [comment]
mockjs版本问题，我们已经在开发mockjs2来解决
