### ISSUE TITLE
postman导入时，如果在rap2里面使用了mock标签，则导入后参数值也是mock标签

### ISSUE THREAD

**Issue by yangxylab** [thx/rap2-delos#450]
**BUG描述**
如题，导入后参数为mock标签，而不是mock随机生成的数据，不知算不算bug……
因为我觉得postman导入的数据，应该就像rap2中预览数据一样的才对

**复现步骤**

**期望结果**

**实际结果**

**截图**

![image](https://user-images.githubusercontent.com/35053204/53062755-d4e9b600-34fc-11e9-8ff8-4ec5576701e4.png)

![image](https://user-images.githubusercontent.com/35053204/53062536-188ff000-34fc-11e9-8ea2-113001568c5b.png)

**环境**
Cent0S7 1801
postman6.4.4 macos10.14

**附加信息**

**Comment by Bosn** [comment]
是这样的，这个是MockJS工具的用法，需要在值上做处理来标记Mock规则，如果不满足需求，可以自行清空。

目前还没有想好代替逻辑，（比如把所有Mock标签去掉？）

你有什么好的提议嘛
