### ISSUE TITLE
yarn run build出错 TS2339

### ISSUE THREAD

**Issue by findman** [thx/rap2-delos#451]
**BUG描述**
Build时TS2339错误

**复现步骤**

yarn run build

**期望结果**

**实际结果**
`$ yarn run build
yarn run v1.12.3
$ rimraf -rf dist/ && tsc
src/routes/account.ts:71:50 - error TS2339: Property 'body' does not exist on type 'Reque
st'.

71   let { email, password, captcha } = ctx.request.body
                                                    ~~~~


src/routes/account.ts:113:51 - error TS2339: Property 'body' does not exist on type 'Requ
est'.

113   let { fullname, email, password } = ctx.request.body
                                                      ~~~~

src/routes/account.ts:148:36 - error TS2339: Property 'body' does not exist on type 'Requ
est'.

148   const { password } = ctx.request.body
                                       ~~~~


src/routes/account.ts:297:29 - error TS2339: Property 'body' does not exist on type 'Requ
est'.

297   const email = ctx.request.body.email
                                ~~~~

src/routes/account.ts:298:32 - error TS2339: Property 'body' does not exist on type 'Requ
est'.

298   const password = ctx.request.body.password
                                   ~~~~


src/routes/mock.ts:207:69 - error TS2339: Property 'body' does not exist on type 'Request
'.

207     let params = method === 'GET' ? ctx.request.query : ctx.request.body
                                                                        ~~~~

src/routes/organization.ts:137:44 - error TS2339: Property 'body' does not exist on type
'Request'.

137   let body = Object.assign({}, ctx.request.body, { creatorId, ownerId: creatorId })
                                               ~~~~


src/routes/organization.ts:152:44 - error TS2339: Property 'body' does not exist on type
'Request'.

152   let body = Object.assign({}, ctx.request.body)
                                               ~~~~

src/routes/organization.ts:169:28 - error TS2339: Property 'body' does not exist on type
'Request'.

169   let { id } = ctx.request.body
                               ~~~~


src/routes/organization.ts:191:37 - error TS2339: Property 'body' does not exist on type
'Request'.

191   let { id, ownerId } = ctx.request.body
                                        ~~~~

src/routes/repository.ts:217:44 - error TS2339: Property 'body' does not exist on type 'R
equest'.

217   let body = Object.assign({}, ctx.request.body, { creatorId, ownerId: creatorId })
                                               ~~~~


src/routes/repository.ts:251:44 - error TS2339: Property 'body' does not exist on type 'R
equest'.

251   let body = Object.assign({}, ctx.request.body)
                                               ~~~~

src/routes/repository.ts:293:28 - error TS2339: Property 'body' does not exist on type 'R
equest'.

293   let { id } = ctx.request.body
                               ~~~~


src/routes/repository.ts:314:53 - error TS2339: Property 'body' does not exist on type 'R
equest'.

314   let { id, ownerId, organizationId } = ctx.request.body
                                                        ~~~~

src/routes/repository.ts:353:28 - error TS2339: Property 'body' does not exist on type 'R
equest'.

353   let { id } = ctx.request.body
                               ~~~~


src/routes/repository.ts:364:28 - error TS2339: Property 'body' does not exist on type 'R
equest'.

364   let { id } = ctx.request.body
                               ~~~~

src/routes/repository.ts:399:40 - error TS2339: Property 'body' does not exist on type 'R
equest'.

399   let body = Object.assign(ctx.request.body, { creatorId })
                                           ~~~~


src/routes/repository.ts:417:49 - error TS2339: Property 'body' does not exist on type 'R
equest'.

417   const { id, name, description } = ctx.request.body
                                                    ~~~~

src/routes/repository.ts:430:25 - error TS2339: Property 'body' does not exist on type 'R
equest'.

430   let mod = ctx.request.body
                            ~~~~


src/routes/repository.ts:459:29 - error TS2339: Property 'body' does not exist on type 'R
equest'.

459   let { ids } = ctx.request.body
                                ~~~~

src/routes/repository.ts:534:40 - error TS2339: Property 'body' does not exist on type 'R
equest'.

534   let body = Object.assign(ctx.request.body, { creatorId })
                                           ~~~~


src/routes/repository.ts:556:26 - error TS2339: Property 'body' does not exist on type 'R
equest'.

556   let body = ctx.request.body
                             ~~~~

src/routes/repository.ts:568:25 - error TS2339: Property 'body' does not exist on type 'R
equest'.

568   let itf = ctx.request.body
                            ~~~~


src/routes/repository.ts:581:44 - error TS2339: Property 'body' does not exist on type 'R
equest'.

581   const { modId, itfId, op } = ctx.request.body
                                               ~~~~

src/routes/repository.ts:658:28 - error TS2339: Property 'body' does not exist on type 'R
equest'.

658   let { id } = ctx.request.body
                               ~~~~


src/routes/repository.ts:691:28 - error TS2339: Property 'body' does not exist on type 'R
equest'.

691   let { id } = ctx.request.body
                               ~~~~

src/routes/repository.ts:715:29 - error TS2339: Property 'body' does not exist on type 'R
equest'.

715   let { ids } = ctx.request.body
                                ~~~~


src/routes/repository.ts:756:40 - error TS2339: Property 'body' does not exist on type 'R
equest'.

756   let body = Object.assign(ctx.request.body, { creatorId })
                                           ~~~~

src/routes/repository.ts:766:32 - error TS2339: Property 'body' does not exist on type 'R
equest'.

766   let properties = ctx.request.body // JSON.parse(ctx.request.body)
                                   ~~~~


src/routes/repository.ts:783:45 - error TS2339: Property 'body' does not exist on type 'R
equest'.

783   let { properties, summary } = ctx.request.body // JSON.parse(ctx.request.body)
                                                ~~~~

src/routes/repository.ts:892:41 - error TS2339: Property 'body' does not exist on type 'R
equest'.

892   const { docUrl, orgId } = ctx.request.body
`

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

typescript Version 3.3.3333

node v10.15.0

**附加信息**
typescript Version 2.9.1
下删除node_modules重新获取未能解决报错

**Comment by Bosn** [comment]
请使用npm install
yarn的话，需要自行解决依赖错误。

**Comment by wxungang** [comment]
https://github.com/thx/rap2-delos/issues/439
