### ISSUE TITLE
在某个仓库创建模块后，不能进去了

### ISSUE THREAD

**Issue by xiaochonghao** [thx/rap2-delos#452]
**BUG描述**
仓库的成员（非创建者）在仓库中创建一个模块后，就不能再次进入该仓库中了。

**复现步骤**

**期望结果**
非创建者如果不能创建模块，那么久应该有类似“权限不足”的警告提示；如果能创建，就应该能进去啊

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/18009560/53216310-1ca04700-368f-11e9-9a7c-2bce9f934dde.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by xiaochonghao** [comment]
![image](https://user-images.githubusercontent.com/18009560/53216233-ecf13f00-368e-11e9-90da-db26a492d41c.png)

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
