### ISSUE TITLE
响应格式导入[{},{} ]类型 线上bug

### ISSUE THREAD

**Issue by inwikipedia** [thx/rap2-delos#453]
**BUG描述**
响应格式导入[{},{} ]类型  线上默认一个下划线 _root_  应该内置修改成2个下划线

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by crystalztl** [comment]
建议移除"_root_"

**Comment by Bosn** [comment]
fixed
