### ISSUE TITLE
在弹窗输入的时候，中文输入法按esc取消打字的时候窗口会直接关掉

### ISSUE THREAD

**Issue by maybeTomorrow** [thx/rap2-delos#456]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在弹窗输入的时候，中文输入法按esc取消打字的时候窗口会直接关掉

**您是否有建议的实现方案**
建议取消esc关闭弹窗，或者增加这个设置

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/3241680/53719707-d4a4cf80-3e99-11e9-86b4-ef667578600b.png)

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
