### ISSUE TITLE
http://rap2.taobao.org官网已挂

### ISSUE THREAD

**Issue by okool** [thx/rap2-delos#459]
**BUG描述**
官网JS错误,无法访问.
官网经常抽疯,文档建议用gitpages.

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
fixed
