### ISSUE TITLE
Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by afresh** [thx/rap2-delos#460]
**BUG描述**
登陆注册都会出现该错误“Unexpected token I in JSON at position 0”

**复现步骤**
登陆注册都会出现该错误“Unexpected token I in JSON at position 0”

**期望结果**
登陆注册成功通过

**实际结果**
报错500，Unexpected token I in JSON at position 0

**截图**
![TIM截图20190311104118](https://user-images.githubusercontent.com/5461256/54097294-65276680-43ea-11e9-98b3-3d5e83b56a8f.png)

**环境**
* 自建服务器，Windows Server 2008 R2 Standard 64bit。
* 浏览器版本 Chrome 43.0.2357.81
* 前台是IIS搭载的web服务
* PM2

**附加信息**
根据https://github.com/thx/rap2-delos/issues/409 更新了数据库字段无效。

**Comment by afresh** [comment]
这个问题dev版本是不存在的，所以我暂时用dev来部署项目了。但终究这还是bug，希望官方能够重视并尽早解决，看了很多issues都提到这个问题！

**Comment by ohmygd** [comment]
这个问题我刚解决， 我这边一开始装的时候是好的， 然后之前测试机断电了， 然后再把服务打开的时候就报这个问题了， 后来的解决办法： 就是把原来的进程删了， 重新启动， 莫名奇妙的好了

**Comment by mercuryqu** [comment]
我这边这个问题是因为部署在linux服务器上区分数据库大小写.导致这个报错

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
