### ISSUE TITLE
在部分macbook pro上，无论如何登录，总是提示验证码错误。

### ISSUE THREAD

**Issue by Zooc** [thx/rap2-delos#461]
**BUG描述**
在自己的macbook pro上，使用safari和chrome，账号和密码正确的情况下，我的账号点击登录都会提示验证码错误，但是当我把账号和密码在windows的chrome上面登录，就可以正常登录。
重新再注册一个账号，可以成功进入，但是退出登录后，就又提示验证码错误了。

奇怪的是，在其他人macbook（新款2018、旧款2015、还有air）上，在safari上登录会出现验证码错误，但是在chrome上就没问题。

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/6982204/54190020-f6333600-44ed-11e9-8a7b-7a6174fed189.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Zooc** [comment]
是因为通过Docker部署的原因，可能是里面的镜像有问题了。

**Comment by wyxy2005** [comment]
不是docker的原因，我是debian8.0 源码部署的，也遇到这个问题

**Comment by Stanny2017** [comment]
同遇

**Comment by txwsqk** [comment]
直接用ip地址访问
