### ISSUE TITLE
编辑接口中不能有null，否则报错

### ISSUE THREAD

**Issue by afresh** [thx/rap2-delos#462]
**BUG描述**
编辑接口中不能有null，否则报错"Unexpected token I in JSON at position 0"

**复现步骤**
编辑接口 -> 响应内容 -> 导入 -> 填写下面代码 -> 格式化 -> 提交 -> 保存
`{"code":0,"message":"成功","data":null}`
这里由于导入后data被识别成string类型，json中为null，产生错误。

**期望结果**
保存成功，解除编辑锁定。

**实际结果**
编辑锁定，保存报错。

**截图**
![TIM截图20190312174132](https://user-images.githubusercontent.com/5461256/54191679-6099a580-44f1-11e9-9bdf-725472ea1602.png)
![TIM截图20190312174209](https://user-images.githubusercontent.com/5461256/54191681-6099a580-44f1-11e9-8a4b-1803bbe07be2.png)
![TIM截图20190312174234](https://user-images.githubusercontent.com/5461256/54191683-6099a580-44f1-11e9-87aa-e60f845bc32f.png)

**环境**
* 自建服务器，Windows Server 2008 R2 Standard 64bit。
* 浏览器版本 Chrome 43.0.2357.81
* 前台是IIS搭载的web服务

**附加信息**

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
