### ISSUE TITLE
head必选之后   postman请求返回必选参数未传值

### ISSUE THREAD

**Issue by deyi2019** [thx/rap2-delos#465]
**BUG描述**
head必选之后   postman请求返回必选参数未传值，
wire Shark 查看数据 header中有sn 但是报错sn未传值
head设置未非必选 postman请求正常返回

**环境**
http://rap2.taobao.org/

**Comment by deyi2019** [comment]
![image](https://user-images.githubusercontent.com/48235534/54655345-9562b980-4afc-11e9-9a29-6dea801740de.png)

**Comment by Ankerxiao** [comment]
@deyi2019 我也遇到这个问题了，请问你是怎么解决的

**Comment by deyi2019** [comment]
有问题我就没用这个了，用了简单一点的moco
  然后这个问题，6月3管理员Bosn 发邮件给我说已Merged #457 into master.





------------------ 原始邮件 ------------------
发件人: "Hero"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午10:28
收件人: "thx/rap2-delos"<rap2-delos@noreply.github.com>;
抄送: "小子"<1466298100@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [thx/rap2-delos] head必选之后   postman请求返回必选参数未传值 (#465)




@deyi2019 我也遇到这个问题了，请问你是怎么解决的

**Comment by Ankerxiao** [comment]
@deyi2019 那我升级下后端，是不是就行了？

**Comment by deyi2019** [comment]
不确定，我后面没用这个了   你升级试试呗




------------------ 原始邮件 ------------------
发件人: "Hero"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午10:49
收件人: "thx/rap2-delos"<rap2-delos@noreply.github.com>;
抄送: "小子"<1466298100@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [thx/rap2-delos] head必选之后   postman请求返回必选参数未传值 (#465)




@deyi2019 那我升级下后端，是不是就行了？

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
