### ISSUE TITLE
rap2-dolores添加接口后 不能自动刷新

### ISSUE THREAD

**Issue by clkevin** [thx/rap2-delos#466]
**BUG描述**
1. 新增接口后，页面不自动刷新，手动刷新后，接口才在模块下展示
2. 编辑接口，保存后提示 “发生错误：undefined”
![image](https://user-images.githubusercontent.com/28770196/54683587-f619e280-4b4c-11e9-96ef-f77e777407c7.png)

**期望结果**
1. 新增接口后，自动刷新展示新增的接口
2. 编辑接口时，点击保存后，保存成功

**Comment by alonesword** [comment]
> @clkevin 是采用 docker 部署吗？官方的 Dockerfile 文件部署时，我也遇到同样问题，同时还有 接口的test 链接 ，postman 链接都显示 404 错误。
需要修改 Dockfile 文件，将 public 、test 目录打包到 docker 容器中方能正常。
参见： 
https://github.com/thx/rap2-delos/issues/468
https://github.com/alonesword/rap2-delos/blob/master/Dockerfile

**Comment by clkevin** [comment]
是通过docker部署的
出现问题的是在dockerhub上找的镜像，问题原因是前后端 docker image 版本不一致导致 
自己重新通过github打镜像  解决上述问题
