### ISSUE TITLE
采用docker部署的服务，无法使用 test 、postman 相关功能

### ISSUE THREAD

**Issue by alonesword** [thx/rap2-delos#468]
**BUG描述**
采用 docker-compose up -d 部署容器后，点击接口的 test链接 或 postman 链接，页面显示404错误

**复现步骤**
1、采用 docker 部署 rap2-delos 容器
2、前端正常部署（本机部署 或 docker 容器部署均可）

**期望结果**
和 rap2.taobao.org 一样，点击接口 test、postman 链接，能出现正常的接口原信息内容

**实际结果**
点击 test 、postman 链接均出现404 错误

**截图**

**环境**
* OS： Centos 7.4
* 后端部署脚本问题

** 解决办法 **
Dockerfile 中缺少 mv ./public /app && mv ./test /app 命令导致少部署了内容

**附加信息**
![Image 011](https://user-images.githubusercontent.com/4519530/54968932-5da1b900-4fb7-11e9-8577-8a9a5292ffb3.png)

**Comment by alonesword** [comment]
已经在 fork 版本中修复了此问题
[https://github.com/alonesword/rap2-delos/blob/master/Dockerfile](url)

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
