### ISSUE TITLE
Attempted import error: 'applyMiddleware' is not exported from 'react-redux'

### ISSUE THREAD

**Issue by candy123360** [thx/rap2-delos#469]
**BUG描述**
rap2-dolores执行npm run build报错
Wrote 38 CSS files to /usr/local/rap2/rap2-dolores/src/
Creating an optimized production build...
Failed to compile.

./src/family/index.js
Attempted import error: 'applyMiddleware' is not exported from 'react-redux'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-26T12_49_35_999Z-debug.log

日志文件内容如下：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.7.0
3 info using node@v11.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rap2-dolores@1.0.0~prebuild: rap2-dolores@1.0.0
6 info lifecycle rap2-dolores@1.0.0~build: rap2-dolores@1.0.0
7 verbose lifecycle rap2-dolores@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle rap2-dolores@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/rap2/rap2-dolores/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/apache-maven-3.5.4/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/git/bin:/root/bin
9 verbose lifecycle rap2-dolores@1.0.0~build: CWD: /usr/local/rap2/rap2-dolores
10 silly lifecycle rap2-dolores@1.0.0~build: Args: [ '-c', 'npm run build-css && react-scripts build' ]
11 silly lifecycle rap2-dolores@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle rap2-dolores@1.0.0~build: Failed to exec build script
13 verbose stack Error: rap2-dolores@1.0.0 build: `npm run build-css && react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:988:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid rap2-dolores@1.0.0
15 verbose cwd /usr/local/rap2/rap2-dolores
16 verbose Linux 2.6.32-431.el6.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v11.12.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error rap2-dolores@1.0.0 build: `npm run build-css && react-scripts build`
22 error Exit status 1
**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/1002951/54998704-c3b72c00-5009-11e9-8c09-9cb0d640fbb8.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
是否按照readme步骤执行了npm install

**Comment by candy123360** [comment]
> 是否按照readme步骤执行了npm install

23天了，终于有人回复了，我都快要放弃了，我已经忘记我的步骤了，对于node，我是个小白，只会按照文档操作，难道就没有别人遇到过这个问题吗？

**Comment by wirelesscongnitive** [comment]
我也遇到这个问题了貌似现在这个接口文档不维护了！还是不开源了哈，感觉开源出来的代码是有问题的

**Comment by zhang-jh** [comment]
Attempted import error: 'applyMiddleware' is not exported from 'react-redux'.
