### ISSUE TITLE
密码找回

### ISSUE THREAD

**Issue by jimkuo** [thx/rap2-delos#473]
忘记密码一直收不到验证码，。。。。。。。。。。。。。。。

**Comment by wanguzhang** [comment]
同问，邮箱收不到验证码

**Comment by pawoma** [comment]
写了两天的接口文档，现在官网登录不了，一直提示密码错误，但我确定密码肯定正确， 密码找回也是收不到邮件，文档要发给产品看了，非常着急 ，能麻烦团队看下吗

**Comment by Bosn** [comment]
官网主要是demo站点，邮箱找回，是自行配置邮箱STMP服务器对应账号密码的。在config.*.ts中配置。
