### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by MaGaoFeng** [thx/rap2-delos#474]
**BUG描述**
![image](https://user-images.githubusercontent.com/22322269/55469431-19a65800-5638-11e9-9b6a-b20362fadb1b.png)

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by rockskyawp** [comment]
解决了没有？同样的问题。

**Comment by Bosn** [comment]
pkg版本问题，已修复。请更新代码库重新npm i && tsc
