### ISSUE TITLE
自建服务报错：Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by anazh** [thx/rap2-delos#475]
**BUG描述**
注册，登录，都会出现这个报错
服务器返回：500 Internal Server Error

页面提示：Unexpected token I in JSON at position 0

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
自建服务器
centos7 CentOS Linux 7.5.1804 
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
后端挂了，看下后端日志。是不是数据库配错了，或者其他rap2-delos的原因。

**Comment by aqaun** [comment]
我也遇到同样的问题，检查并无数据库连接问题，楼上有解决吗？

**Comment by anazh** [comment]
> 我也遇到同样的问题，检查并无数据库连接问题，楼上有解决吗？

没有，放弃了

**Comment by aqaun** [comment]
安装1.0版本，可以正常使用

**Comment by aieyes** [comment]
我这边是build有问题，dev没问题，看一下日志发现数据库名称错了，修改config.prod.js的数据库对应上创建那个就可以了, rap改为了RAP2_DELOS_APP

**Comment by mercuryqu** [comment]
我这边是数据库表名的问题 linux区分大小写
