### ISSUE TITLE
如何修改dolores的默认启动端口3000

### ISSUE THREAD

**Issue by BurningCloud** [thx/rap2-delos#476]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
dolores生产环境就是react app，具体参考其他react应用的部署方法。不在本repo讨论范围哦亲
