### ISSUE TITLE
新建团队，修改仓库信息后 页面不会及时刷新

### ISSUE THREAD

**Issue by roy500** [thx/rap2-delos#479]
**BUG描述**
我是用doker安装的 2.6.aa3be03最新版本，新建团队，修改仓库信息后，还有就是在仓库里面修改仓库名称时   页面不会及时刷新，手动刷新后才会出现

**复现步骤**

**期望结果**
新建团队，修改仓库信息后，还有就是在仓库里面修改仓库名称时自动刷新

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by vae520283995** [comment]
I have a same problem

**Comment by Bosn** [comment]
Docker并不是官方提供的版本，而是开源爱好者自己做的。版本不太新。在最新的release里已经修复。
