### ISSUE TITLE
我今天登陆自己的账号显示的却是别人的名称和信息

### ISSUE THREAD

**Issue by BQSQ** [thx/rap2-delos#48]
今天下午由于长时间没有操作，操作的时候跳转到登陆页面，登陆成功后显示的却是chenchuanwen的账号信息，看到的也是他的厂库和内容，本人在他的厂库里面新建了一条消息做为提醒，没有删除任何内容，但是这样的情况出现时非常危险的，为什么我登陆自己的账号却跳转到别人的里面？

**Comment by Bosn** [comment]
是否还有复现？目前并没有其它同学反馈过问题，并且无法复现该问题。暂时close
