### ISSUE TITLE
前端项目build编译后生产环境404问题

### ISSUE THREAD

**Issue by KingSirs** [thx/rap2-delos#480]
**BUG描述**
前端项目build编译后生产环境404问题，点击退出404，域名后有地址的例如http://localhost/api，刷新网页404

**复现步骤**
1.打开浏览器，输入项目地址例http://localhost
2.输入用户名、密码、验证码，点击登录
3.点击退出或者点击除首页外的模块后刷新网页

**期望结果**
正常退出登录到登录页面或者刷新网页成功

**实际结果**
无法路由，404错误

**截图**
![image](https://user-images.githubusercontent.com/18433201/56020739-6a096e00-5d3a-11e9-81f0-29e978cb08c9.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
系统环境：阿里云CentOS7镜像服务器
浏览器：QQ浏览器10.4，谷歌浏览器69.0.3497.100
访问逛网的rap2.taobao.org没有这种问题，npm run dev 没有这种问题

**附加信息**

**Comment by KingSirs** [comment]
解决了
  location / {
      root '/home/rap2-view/build/';
      try_files $uri /index.html;#主要配置，这样/后面的path由index.html负责处理，就可以走路由了
      index index.html index.htm index.php;
    }

**Comment by xiexifeng** [comment]
Caddy还不支持

**Comment by long1012** [comment]
http://119.45.15.20/  访问首页也是404呢，这是什么原因呢
![image](https://user-images.githubusercontent.com/26102173/127127171-5d6e12cc-f153-4375-80f1-79c48855b6cd.png)
