### ISSUE TITLE
请问此项目是否经过性能测试，可否用于性能测试的mock

### ISSUE THREAD

**Issue by zengxiaoliang** [thx/rap2-delos#481]
在8C16G 环境中部署项目，并发１００个用户请求一个Ｇｅｔ接口，处理耗时５０ms．　对性能结果存在较大影响，希望优化。

**Comment by Bosn** [comment]
亲，该项目会尽可能的优化。但是服务器本身不是用来做压测的，建议使用压测工具，或者导出Postman Collection后，通过Postman来针对真实服务器做批量请求及校验。
