### ISSUE TITLE
json数组格式[]的导入

### ISSUE THREAD

**Issue by kangjianqq809295733** [thx/rap2-delos#482]
响应模板
{
  "_root_": [
    1,
    2
  ]
}
响应数据
[
  1,
  2
]
为什么会自动添加root，如果不需要添加root怎么操作

**Comment by Bosn** [comment]
因为rap本身文档是JSON形式的，root表示的是根节点，当我们需要最外层是数组形式时，用root（为root设置规则）表示最根部（或者最外层结构）的规则。
