### ISSUE TITLE
PUT/POST API预览不区分Header参数和Body参数

### ISSUE THREAD

**Issue by shengang1978** [thx/rap2-delos#483]
**BUG描述**
创建一个 PUT 的接口，录入 http head的参数， 录入 body参数（json格式），再录入response（json格式）。保存后点击“预览”，请求模板和请求数据 里的json内容把http head参数和http body参数放在一起了。

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/5358448/56350811-3462fa00-61fe-11e9-81a3-d732bca024c5.png)

**环境**
* 是否是自建服务器？官网 rap2.taobao.org

**附加信息**

**Comment by shengang1978** [comment]
按我的理解，一个完整的http请求， 有URL， head， body，response。 是我使用的有问题吗？

**Comment by shengang1978** [comment]
我没有看错的话， rap2 把http head参数和body里的参数混在一起了？为啥这样设计？是bug， 还是就这样设计的？

**Comment by shengang1978** [comment]
:( 我晕啊，看到是阿里的东西， 才使用的。 这个项目已经没有人维护了吗？？？？？最近一次提交只是改了配置。 已经半年没有提交代码了啊啊啊啊啊啊啊。。。。。

**Comment by Bosn** [comment]
近期会增加人力支持哦，这个项目是非盈利的内部创新项目，分享出来了。内部的业务压力，并不保证持续有人维护哦。该项目本身也是开源的，欢迎提交MR

**Comment by shengang1978** [comment]
可惜了, nodejs 偶不懂啊
