### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by liqihua** [thx/rap2-delos#486]
**BUG描述**
我rap2-dolores跑起来后首页一直空白，F12提示错误信息如下：
uncaught at n at n
TypeError: Failed to fetch

**Comment by 1156721874** [comment]
> **BUG描述**
> 我rap2-dolores跑起来后首页一直空白，F12提示错误信息如下：
> uncaught at n at n
> TypeError: Failed to fetch

你的问题砸解决的，我也遇到了

**Comment by 1156721874** [comment]
解决方式：客户端的配置的服务端的ip要使用局域网的ip，不要使用127.0.0.1或者localhost。

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
