### ISSUE TITLE
慢SQL查询性能太差

### ISSUE THREAD

**Issue by nisiyong** [thx/rap2-delos#487]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
目前部署了rap2在内部使用，发现每次进入仓库是加载整个仓库的所有接口，当接口越来越多，这时候查询性能非常慢。原因是SQL一次查处所有数据，连表太多了。

**您是否有建议的实现方案**
建议分步加载，不要一次加载整个仓库接口数据。慢SQL连了12次表真的不能忍！

**其它帮助我们理解您需求的描述、截图**
由于公司内部做了MySQL的慢SQL告警，经常收到rap2的慢SQL，慢的有20多秒。
下面贴下rap2的SQL，有点吓到。
![image](https://user-images.githubusercontent.com/8198862/56596300-e6e1f500-6622-11e9-9053-810008233a23.png)

**Comment by bigfengyu** [comment]
感谢反馈，这个问题在新版中进行了优化，麻烦更新再试一下哈。
