### ISSUE TITLE
接口版本管理功能是否有计划or排期

### ISSUE THREAD

**Issue by asynclog** [thx/rap2-delos#488]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
rap1 中版本管理功能是否有新的计划

**您是否有建议的实现方案**
https://github.com/thx/rap2-delos/issues/269#issue-345652870

**Comment by Bosn** [comment]
接口版本的管理暂时不在RAP2提供了，近期会增加changelog的记录和查询。

该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
