### ISSUE TITLE
Attempted import error: 'applyMiddleware' is not exported from 'react-redux'.

### ISSUE THREAD

**Issue by bpzhang** [thx/rap2-delos#489]
**BUG描述**

Attempted import error: 'applyMiddleware' is not exported from 'react-redux'.
**复现步骤**
npm run build

**期望结果**

**实际结果**
Attempted import error: 'applyMiddleware' is not exported from 'react-redux'.

**截图**

![image](https://user-images.githubusercontent.com/1734396/56874183-dab6c700-6a6a-11e9-82c0-c88ee89bf9dc.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by shekobe** [comment]
同上啊，还有人维护不

**Comment by bpzhang** [comment]
> 同上啊，还有人维护不

我的应该是按照这个文章解决了https://incoder.org/2018/03/27/rap2/
最后是可以运行了。
官方提供的部署方案应该是有问题

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
