### ISSUE TITLE
RAP2点击地址无法模拟接口

### ISSUE THREAD

**Issue by caoqiwen2001** [thx/rap2-delos#490]
测试接口没有问题，新建接口模拟访问报如下错误：

{"isOk":false,"errMsg":"未匹配到任何接口 No matched interface"}

**Comment by LiuSWHL** [comment]
你这个可能不是 GET 接口，只有 GET 接口才能直接点击访问，其它类型的你可以试试  postman

**Comment by Bosn** [comment]
看一下协议，如果你接口写的是POST，但是你用了GET请求去访问（比如浏览器直接点连接），就会出现该问题。

**Comment by caoqiwen2001** [comment]
感谢，解决了
