### ISSUE TITLE
通过Dockerfile 无法运行rap

### ISSUE THREAD

**Issue by 619851705** [thx/rap2-delos#491]
**BUG描述**

**复现步骤**
 1. 安装docker
2. 修改docker-compose.xml中的配置。默认使用mysql和redis的镜像。可修改为自己的配置
 3. 通过源码运行。
        docker-compose up -d
 4. 第一次运行需要手动初始化mysql数据库。分别执行以下命令：
        docker exec -it rap2-delos sh
    // 登录成功以后执行：
        node scripts/init
    // 执行完毕后退出
        exit
    // 如果仍然有问题，重新启动
        docker-compose down
    // 重新运行
        docker-compose up -d

**期望结果**
    出现 RAP登录界面

**实际结果**
   运行完后：访问http://127.0.0.1:38080
   出现：Hello RAP!
**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
dockerfile非官方提供，本repo不提供docker相关技术支持哦~~~
