### ISSUE TITLE
优化线上属性值为函数时的编辑体验

### ISSUE THREAD

**Issue by tjx666** [thx/rap2-delos#495]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
编辑体验太差。
![Snipaste_2019-05-15_22-45-38](https://user-images.githubusercontent.com/41773861/57784849-34094080-7763-11e9-9305-6e4d12acfc0c.png)

**您是否有建议的实现方案**
比如当用户选择属性值为 Function  类型时，输入值那里显示一个按钮，点击可以点击弹出一个 Modal 编辑窗口，最好还加上代码高亮。

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
我们会考虑的谢谢，同时，代码编辑，建议用VSCode等成熟的代码编辑器，我们精力有限没办法重复去做IDE
