### ISSUE TITLE
初始值改为属性值

### ISSUE THREAD

**Issue by tjx666** [thx/rap2-delos#496]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
建议和 mockjs 文档同步。很多情况下使用初始值描述不直观，反直觉，比如要输入正则类型的属性值的时候，明显属性值比初始值描述更恰当。
![Snipaste_2019-05-15_22-45-38](https://user-images.githubusercontent.com/41773861/57785409-4afc6280-7764-11e9-8d84-64a0b1123de8.png)

![Snipaste_2019-05-15_22-45-38](https://user-images.githubusercontent.com/41773861/57785103-a417c680-7763-11e9-9862-2a8621ed1851.png)

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
我们已经在开发mockjs2 来实现RAP2的扩展需求了，原来的mockjs很早已经不再维护。
