### ISSUE TITLE
CPU占用异常

### ISSUE THREAD

**Issue by liguifa** [thx/rap2-delos#497]
**BUG描述**
CPU占用异常

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/8682840/58156577-006d6f80-7ca9-11e9-9b59-d2f4681e49c7.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
嗨，亲，请补全信息reopen哦，您的截图无法复现该问题
