### ISSUE TITLE
Rap2不支持根据请求参数来动态生成MockJS模板

### ISSUE THREAD

**Issue by zzyugl** [thx/rap2-delos#498]
**Rap2不支持根据请求参数来动态生成MockJS模板**

**rap1文档中提到可以通过占位符${}方式实现**
`参考说明：`
[https://github.com/thx/RAP/wiki/user_manual_cn#%E6%A0%B9%E6%8D%AE%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0%E6%9D%A5%E5%8A%A8%E6%80%81%E7%94%9F%E6%88%90mockjs%E6%A8%A1%E6%9D%BF](https://github.com/thx/RAP/wiki/user_manual_cn#%E6%A0%B9%E6%8D%AE%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0%E6%9D%A5%E5%8A%A8%E6%80%81%E7%94%9F%E6%88%90mockjs%E6%A8%A1%E6%9D%BF)
```
通过${page}这样的语法，RAP会根据请求参数的值替换掉${page}对应的位置，page是参数名。例如：

@mock=${page}
表示根据请求参数page来决定mockjs模板，若请求参数page传入的是123，则这里会等价于:@mock=123

如果该模板放置在变量名中，注意变量名是不需要写@mock=的，例如：

{"arr|10" : []}
这里表示数组arr的长度是10，如果这里的10需要参数化，则可以这样写：

"arr|${total}"
则当参数传入total=100时，这里等价于"arr|100"，即生成100个元素。

@mock=${page=10}
表示在请求参数没有page时，默认等价于@mock=10
```

**Rap2是否支持获取请求参数呢？**
目前通过rap1中的说明手册操作并不可行，通过如下方式在rap2中可以勉强实现，但是参数名称不可控。
比如
+ 请求参数：
  - app_name=RapDemo
+ 模板设置：
  - 参数名=app_name
  - 生成规则=非Rule规则语法的其他任何值，比如空格、$、字母等
  - 初始值=@app_name
+ 响应结果：
  - 参数名=app_name[生成规则设置的字符]，比如app_name$
  - 参数值=RapDemo

![示例](https://raw.githubusercontent.com/zzyugl/issuedata/master/B7607ABB-F46E-491D-9BB4-1448906B15A9.png)

**Comment by akkuman** [comment]
https://github.com/thx/rap2-delos/wiki/user_manual#%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0

**Comment by Bosn** [comment]
支持，见楼上链接，定义好参数，用$paramName$来引用

**Comment by geeklyc** [comment]
配置的是
$pageIndex$
请求的是
http://rap2api.taobao.org/app/mock/275364/dakaliebiao?pageIndex=1&pageOffset=10
结果返回
"num": "$pageIndex$"
