### ISSUE TITLE
请求参数添加按类型排序功能

### ISSUE THREAD

**Issue by LiuSWHL** [thx/rap2-delos#502]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
添加不同类型（head, query, body）的请求参数时，请求参数是按添加顺序排序的

**您是否有建议的实现方案**
建议按固定顺序排序，比如 head, query, body 这样的顺序

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/50821204/58680871-583c6280-839c-11e9-9f70-ad7a61986c0c.png)

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
