### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kaihuaxie** [thx/rap2-delos#504]
**BUG描述**
 使用成员检索的时候报后台异常

**复现步骤**
   成员检索

**期望结果**
  正常返回
 
**实际结果**
  后台异常

**截图**
   
![image](https://user-images.githubusercontent.com/6407687/58952339-fe85cf00-87c5-11e9-92fa-cf194d08dbbf.png)
.
![image](https://user-images.githubusercontent.com/6407687/58952362-0a719100-87c6-11e9-9a1f-0e0adb433966.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本  centos 7
* 如果是前端错误，请提供浏览器版本  chrome  71.0.3578.98
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by kaihuaxie** [comment]
哎呀，，用dev版本是正常，，master不行

**Comment by JunzhiCHEN** [comment]
@kaihuaxie  我在dev 版本也不正常，而且网上搜不到解决办法， 我最后采用的直接去操作数据库

**Comment by mogudada** [comment]
怎么操作才能解决

**Comment by shzhouchen** [comment]
表示不会react nodejs 这些，想了个笨办法，/account/list 这个地址正常，直接把找到报错的那块修改rap2-dolores-master\src\relatives\services\Account.js  95行的fetchUserList 地址去掉url后面的参数就行。人数少，一次拿到全部成员姓名无所谓了

**Comment by Bosn** [comment]
已经修复啦，更新master代码即可。这个是sequelize升级的时候导致的bug
