### ISSUE TITLE
无法搜索成员 

### ISSUE THREAD

**Issue by mogudada** [thx/rap2-delos#506]
**BUG描述**

http://116.62.139.242:8086/account/list?name=te&cursor=1&limit=100
500 Internal Server Error

**复现步骤**
一搜索就报500

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/34201576/59190590-ada01d00-8baf-11e9-99fc-fdd367da380f.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
是 centos7
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-delos/commit/2502acbf4551be9e7f1aa716a43ffaa38369697f
