### ISSUE TITLE
MAC safari登录页面输入正确的验证码显示错误

### ISSUE THREAD

**Issue by bryanYao** [thx/rap2-delos#509]
**BUG描述**
同样的笔记本safari浏览器输入验证码显示错误, 无法登录, chrome则可以登录

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
测试了下没问题，请检查Safari浏览器输入法？或者提供完整复现case

**Comment by bryanYao** [comment]
Safari 版本 12.1.1 (14607.2.6.1.1)
使用的nginx搭建的前端,
![09_29_00__07_19_2019](https://user-images.githubusercontent.com/7325404/61502854-1e84f100-aa08-11e9-8e73-ff098b63e957.jpg)

**Comment by ilaotan** [comment]
看来是老毛病了，升级2.9.0之前，我们也偶尔有这毛病，但不是必然的，很是神奇
