### ISSUE TITLE
新建团队时必填项校验失败

### ISSUE THREAD

**Issue by qq192052888** [thx/rap2-delos#510]
**BUG描述**

新建团队时必填项校验失败，提示不能为空 但是可以提交
**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/30657112/59586475-9e702080-9115-11e9-9117-681a9daf875c.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
