### ISSUE TITLE
请求rap2-delos的接口文档

### ISSUE THREAD

**Issue by PengShangwen** [thx/rap2-delos#511]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我在做一个自动生成restful web项目的工具，需要在生成代码的同时在rap2上创建库及添加接口。

**您是否有建议的实现方案**
我希望获得rap2-delos的接口文档，以进行开发。

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
官方暂时没有提供RAP2系统接口文档的计划，该项目为开源项目，可以自行从源代码routers中了解。（BTW，RAP2后台是TypeScript的哦）
