### ISSUE TITLE
基于Windows版本的环境搭建

### ISSUE THREAD

**Issue by gogoing1** [thx/rap2-delos#515]
############################################################  基于Windows版本的环境搭建 
# 一，基本工具安装
  # git（通用版本即可）
    下载后端与前端的代码
     https://github.com/thx/rap2-delos
     https://github.com/thx/rap2-dolores

  # mysql 5.7+ （搭建好本地数据库，使用navicate可以连接即可）

  # node  8.9.4+ （注意下载里面的msi版 https://nodejs.org/download/release/v8.9.4/）
    windows环境搭建（https://www.cnblogs.com/zhouyu2017/p/6485265.html）
 
  # redis 4.0+  (注意下载里面的msi版 https://github.com/tporadowski/redis/releases/tag/v4.0.2.3-alpha)

  # vscode（推荐编译器）

----------------------------------------------------------- 第一部分，后端环境搭建

# 二，修改src/config 下的3个环境的ts文件（config.dev.ts,config.local.ts,config.prod.ts）
  全部替换掉里面的mysql与redis配置如下：
  db: {
    dialect: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    username: 'root',
    password: 'root',
    database: 'RAP2_DELOS_APP',
    pool: {
      max: 5,
      min: 0,
      idle: 10000,
    },
    logging: false,
  },
  redis: {
    host: '127.0.0.1',
    port: 6379,
  },

# 创建数据库
进入mysql终端，执行 CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
通过 show databases; 命令查看是否创建成功

# 安装项目所需依赖
npm install

# 全局安装PM2
npm install -g pm2

# 安装TypeScript编译包
npm install typescript -g

# 修改了项目的代码（上面的config配置）之后一定重新编译，不然修改不起作用
npm run build

# 创建数据库表（过程较慢，耐心等待完成）
npm run create-db

# 编译启动项目（执行mocha测试用例和js代码规范检查，可以检查项目的配置，代码的正确性）
npm run check

# 运行开发模式（注意8080端口不要被占用，有的话需要关闭占用的程序）
npm run dev
正常运行的情况下后台环境已经搭好了，打开 localhost:8080 即可

----------------------------------------------------------- 第二部分，前端环境搭建
npm install
npm run dev

遇到的问题：
1，提示mysql数据库连接失败
解决：一定要将3个配置文件全部修改

2，提示dist目录不存在
解决: 修改完config后先 npm run build 在npm run create-db

3，Error: listen EADDRINUSE :::8080
解决：错误类型表示8080端口被占用，cmd打开终端 输入netstat -ano 查看列表左侧本地地址尾部被占用的8080端口，最后面找到它进程号

**Comment by bigfengyu** [comment]
谢谢你！
