### ISSUE TITLE
前端项目执行npm run build报错

### ISSUE THREAD

**Issue by jhulk** [thx/rap2-delos#517]
由于内网服务器无法访问外网，所以就从一台可以连外网的虚拟机上把环境搭建好了，然后把rap2-dolose拷过来，然后编译就会报错，系统版本centos7

![image](https://user-images.githubusercontent.com/22445203/60513877-d75de700-9d0a-11e9-801b-409e3c7fdec8.png)

**Comment by jhulk** [comment]
emmmm，我执行npm run build -f 编译通过了。。。。很神奇

**Comment by Bosn** [comment]
node版本更新下呢，另外npm install有没有执行。。。。按照Readme做一般不会出问题哦
