### ISSUE TITLE
能否增加swagger转rap2的功能

### ISSUE THREAD

**Issue by catpeter** [thx/rap2-delos#519]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by catpeter** [comment]
老项目想用rap2没法从swagger迁移

**Comment by nestingLee** [comment]
有没有办法 吧swagger2做的接口，集成到rap2中？

**Comment by catpeter** [comment]
我写了一套代码直接去修改的自己服务器rap2数据库，在我的github里，可以给你参考

**Comment by MRchao90s** [comment]
是的，我觉得rap2 要是能兼容open-api的格式，会走的很远

**Comment by Bosn** [comment]
已经在开发了，谢谢亲的反馈
