### ISSUE TITLE
仓库点击“插件” ，出现乱码

### ISSUE THREAD

**Issue by gitors** [thx/rap2-delos#52]
在仓库 上方点击“插件” 按钮，跳转到新页面会出现乱码。 当前系统版本```macOS 10.13.2 (17C88)```
浏览器：Safari, 版本 11.0.2 (13604.4.7.1.3)、chrome ,版本 63.0.3239.84（正式版本） （64 位）
均出现上述问题。

![image](https://user-images.githubusercontent.com/31715318/34346149-c239a81c-ea2f-11e7-8224-e2e85345b8d6.png)

![image](https://user-images.githubusercontent.com/31715318/34346155-ce4bc554-ea2f-11e7-873a-f9149148c08a.png)

**Comment by BQSQ** [comment]
我也遇到了这样的情况




丁永标


E_mail：dingyongbiao123@163.com


在2017年12月26日 11:31，LiuWenlong<notifications@github.com> 写道：

在仓库 上方点击“插件” 按钮，跳转到新页面会出现乱码。 当前系统版本macOS 10.13.2 (17C88)
浏览器：Safari, 版本 11.0.2 (13604.4.7.1.3)、chrome ,版本 63.0.3239.84（正式版本） （64 位）
均出现上述问题。

**Comment by gitors** [comment]
@BQSQ 这个不是一个网页，本地去请求这个地址，自己解码是可以的
