### ISSUE TITLE
编辑接口时，通过导入数据生成响应内容的话，后台会报错

### ISSUE THREAD

**Issue by IceOfCat** [thx/rap2-delos#521]
**BUG描述**
编辑接口时，通过导入数据生成响应内容的话，后台会报错

**复现步骤**
![image](https://user-images.githubusercontent.com/51316307/61192123-9e4b4c80-a6e4-11e9-8ac2-ff3948bd3791.png)
![image](https://user-images.githubusercontent.com/51316307/61192133-ac00d200-a6e4-11e9-88b6-71ccaf8a3fd3.png)
点击保存就会出现如下的错误

**期望结果**
通过导入数据生成响应内容

**实际结果**
后台报错

**截图**
![image](https://user-images.githubusercontent.com/51316307/61192102-70fe9e80-a6e4-11e9-899c-e07847580d15.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by hldh214** [comment]
+1

**Comment by hldh214** [comment]
https://github.com/thx/rap2-delos/pull/383

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
