### ISSUE TITLE
删除某个字段无效

### ISSUE THREAD

**Issue by ZLJASON** [thx/rap2-delos#523]
**BUG描述**
编辑接口-删除某个字段无效
Uncaught TypeError: (0 , a.context.handleDeleteMemoryProperty) is not a function
 at a.handleDeleteMemoryProperty (PropertyList.tsx:298)
at Object.onClick (PropertyList.tsx:89)
 at t.n.handleClick (react-router-dom.js:125)
**复现步骤**
1.编辑
2.删除某个字段

**期望结果**
字段删除

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
fixed https://github.com/thx/rap2-dolores/commit/19ed4040fff4f1f35d4fdea2a5e9e9c839abf9fa
