### ISSUE TITLE
添加的参数不能删除，js报错了

### ISSUE THREAD

**Issue by nerverforget** [thx/rap2-delos#524]
**BUG描述**

删除参数没反应，js报错了
react-dom.production.min.js:232 Uncaught TypeError: (0 , a.context.handleDeleteMemoryProperty) is not a function

**复现步骤**
接口删除字段即可

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/11918849/61436975-90a8f780-a96e-11e9-873e-7370c926be4e.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by nerverforget** [comment]
使用的是谷歌浏览器

**Comment by Bosn** [comment]
fixed
https://github.com/thx/rap2-dolores/commit/19ed4040fff4f1f35d4fdea2a5e9e9c839abf9fa
