### ISSUE TITLE
rap2-dolores npm run build报错

### ISSUE THREAD

**Issue by jimpier** [thx/rap2-delos#526]
**BUG描述**
前端代码拉下来，npm run build报错

**复现步骤**
git clone https://github.com/thx/rap2-dolores.git
npm install
npm run build

**截图**
![image](https://user-images.githubusercontent.com/23303312/61522934-f6b47e00-aa45-11e9-9813-8265c662fd75.png)

**Comment by llitfkitfk** [comment]
node 8 和10 都没有问题

**Comment by wakaryry** [comment]
我的也报错。我是node 10. 不过我的是直接语法检测不合格。
