### ISSUE TITLE
无法登录问题【点击登录不可以，回车登录可以】

### ISSUE THREAD

**Issue by zhangyuhan2016** [thx/rap2-delos#528]
**BUG描述**

账号密码验证码正确胡情况下，点击登录无法登录，但回车即可成功登录。

**复现步骤**
退出登录，即可复现

**期望结果**
点击登录成功登录

**实际结果**

**截图**

**环境**

http://rap2.taobao.org

**附加信息**

**Comment by FineJadeXavier** [comment]
我一直登录不上去，原来回车登录可以啊，谢谢大佬

**Comment by Taoxixxi** [comment]
哈哈哈哈，终于登进去了。感谢大佬

**Comment by bigfengyu** [comment]
已经修复，抱歉
