### ISSUE TITLE
做的啥玩意  一推bug

### ISSUE THREAD

**Issue by qingwuyijiu** [thx/rap2-delos#530]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
登陆只能回车才能进去，啥玩意

**您是否有建议的实现方案**
 接口页面左侧边栏太小了，查看接口真特么麻烦

**其它帮助我们理解您需求的描述、截图**
接口数据导入，存在bug，导入二维json后，生成的实例如果是二维数组的数据全跑同一个数组里面了

**Comment by Bosn** [comment]
文化素质课幼儿园就有吧？
楼主年纪轻轻就会上Git令人佩服
