### ISSUE TITLE
请求参数和响应内容使用导入方式添加字段时,字段值为null时无法保存

### ISSUE THREAD

**Issue by ihuning** [thx/rap2-delos#532]
**BUG描述**

请求参数和响应内容使用导入方式添加字段时,字段值为null时无法保存

**复现步骤**

1. 打开任意模块并新建接口；
2. 点击编辑按钮；
3. 点击请求参数或者相应内容的导入按钮;
4. 在弹出的输入框中输入如下内容:

{
   'id':null
}

5. 点击提交按钮；
6. 点击保存按钮；

**期望结果**

点击保存按钮，保存成功

**实际结果**

点击保存按钮未响应

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by hldh214** [comment]
https://github.com/thx/rap2-delos/pull/383
