### ISSUE TITLE
mock数据不支持https

### ISSUE THREAD

**Issue by ningboo** [thx/rap2-delos#533]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
小团队开发，没有做私有部署，使用的是官方仓库。
现在mock接口不支持https。

**您是否有建议的实现方案**
请支持https协议。

**其它帮助我们理解您需求的描述、截图**
![TIM截图20190723103518](https://user-images.githubusercontent.com/17962744/61678529-a8e59180-ad35-11e9-91d1-7d3cf85e84e0.png)

**Comment by Bosn** [comment]
重复问题，搜HTTPS
