### ISSUE TITLE
团队成员被移除后，接口还是被其锁定

### ISSUE THREAD

**Issue by MapleLove2014** [thx/rap2-delos#534]
**BUG描述**
团队成员被移除后，接口还是被其锁定

**截图**
![image](https://user-images.githubusercontent.com/34023519/61694429-00025b00-ad64-11e9-9d3f-75570337bb8b.png)

**环境**
非自建服务器

**附加信息**

**Comment by bigfengyu** [comment]
目前的全新版本会解锁锁定超过一天的接口，这个问题也就没啥关系了吧
