### ISSUE TITLE
java 自动生成 接口文档

### ISSUE THREAD

**Issue by mlyz-wdy** [thx/rap2-delos#540]
手写文档毕竟慢，跟不上内容，是否可以按规则java后台生成一份文档，这样及时更新，避免手动更新

**Comment by zhaoenweiex** [comment]
> 手写文档毕竟慢，跟不上内容，是否可以按规则java后台生成一份文档，这样及时更新，避免手动更新

这种模式使用swagger即可，但这样的话，接口就会变成后台主导，前台有接口需求就需要跑去求后台改接口，项目复杂一点的话，后台初期压力会比较大。
两种模式各有利弊

**Comment by kings1990** [comment]
> 手写文档毕竟慢，跟不上内容，是否可以按规则java后台生成一份文档，这样及时更新，避免手动更新

https://github.com/kings1990/kings-rap2generator

**Comment by Bosn** [comment]
感谢楼上同学提供的工具，同时近期我们也在开发导入导出API，可以自行进行开发和使用。
