### ISSUE TITLE
修改密码功能

### ISSUE THREAD

**Issue by robertfun** [thx/rap2-delos#543]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

前端界面用ts重构后，就没有修改密码功能了，因为我们有使用者需要运维重置密码，但是重置后，想要改掉密码，保证账号安全，这个功能还是比较重要的，希望可以添加回来

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/18359409/62922711-a62f0700-bdde-11e9-9d44-c4578de48555.png)

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen

**Comment by Javison666** [comment]
你好，我在最新版还是没有看到修改密码功能，请fix一下

**Comment by ilaotan** [comment]
还是没看到修改密码功能啊，哪个分支？
