### ISSUE TITLE
无法选取团队成员

### ISSUE THREAD

**Issue by DanielGitHub123** [thx/rap2-delos#547]
**BUG描述**
在创建仓库或编辑仓库时，无法下拉选取成员

**复现步骤**
注册完完毕进行系统，创建一个仓库或者修改一个自己创建的仓库，在成员那里输入后内容后，观察到接口返回{"isOk":false,"errMsg":"need login"}

**期望结果**
成员字段能展示下拉列表

**实际结果**
后台返回{"isOk":false,"errMsg":"need login"}

**截图**
![image](https://user-images.githubusercontent.com/21676818/63564598-497adb80-c598-11e9-85d1-c9395160641b.png)

**环境**
* 自建服务器,centos7.5
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by ftzzh004** [comment]
遇到同样问题了

**Comment by ililing** [comment]
嗯嗯，同样的问题

**Comment by ChanSrowen** [comment]
同问题 +1

**Comment by zerooverture** [comment]
看了下 是在调用 account/list接口时 未传入 cookie 导致无法获取用户登录信息 

rap2-dolores/src/relatives/services/Account.ts
93行改为
`    return fetch(`${serve}/account/list?name=${name}&cursor=${cursor}&limit=${limit}`, {
      ...CREDENTIALS,
    })
`

**Comment by ChanSrowen** [comment]
> 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> 
> rap2-dolores / src / relatives / services / Account.ts 
> 93行改为
> 
> ```ts
>    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
>        ... CREDENTIALS，
>     }）
> ```

改完之后出现了新的问题
我自己创建的团队 编辑团队成员的时候提示 “您没有访问权限”

**Comment by zerooverture** [comment]
> > 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> > rap2-dolores / src / relatives / services / Account.ts
> > 93行改为
> > ```ts
> >    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
> >        ... CREDENTIALS，
> >     }）
> > ```
> 
> 改完之后还是有问题
> 新建/编辑团队 选择项目成员的时候提示 “您没有访问权限”

哦 忘了告诉你了= = 后端接口有个检查 检查操作人员是否是 isAdmin 实现形式是  判断用户的id是否是`1`.因此你有3种方式，

-  是修改后端的验证id 把1改成你要设置成管理员的ID。
-  是去数据库把你要设置成管理员的ID改为1。 
-  就是你自己去把isAdmin的方式重写，这样你就能多设置一些管理员

本身搭建这个项目就是为了内部使用 那么基本设置一个管理员即可

**Comment by ChanSrowen** [comment]
> > > 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> > > rap2-dolores / src / relatives / services / Account.ts
> > > 93行改为
> > > ```ts
> > >    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
> > >        ... CREDENTIALS，
> > >     }）
> > > ```
> > 
> > 
> > 改完之后还是有问题
> > 新建/编辑团队 选择项目成员的时候提示 “您没有访问权限”
> 
> 哦 忘了告诉你了= = 后端接口有个检查 检查操作人员是否是 isAdmin 实现形式是 判断用户的id是否是`1`.因此你有3种方式，
> 
> * 是修改后端的验证id 把1改成你要设置成管理员的ID。
> * 是去数据库把你要设置成管理员的ID改为1。
> * 就是你自己去把isAdmin的方式重写，这样你就能多设置一些管理员
> 
> 本身搭建这个项目就是为了内部使用 那么基本设置一个管理员即可

可以了，谢谢 我看目前的搜索搜的是 fullname 字段 能否增加搜索账号 也就是email 字段

**Comment by zerooverture** [comment]
> > > > 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> > > > rap2-dolores / src / relatives / services / Account.ts
> > > > 93行改为
> > > > ```ts
> > > >    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
> > > >        ... CREDENTIALS，
> > > >     }）
> > > > ```
> > > 
> > > 
> > > 改完之后还是有问题
> > > 新建/编辑团队 选择项目成员的时候提示 “您没有访问权限”
> > 
> > 
> > 哦 忘了告诉你了= = 后端接口有个检查 检查操作人员是否是 isAdmin 实现形式是 判断用户的id是否是`1`.因此你有3种方式，
> > 
> > * 是修改后端的验证id 把1改成你要设置成管理员的ID。
> > * 是去数据库把你要设置成管理员的ID改为1。
> > * 就是你自己去把isAdmin的方式重写，这样你就能多设置一些管理员
> > 
> > 本身搭建这个项目就是为了内部使用 那么基本设置一个管理员即可
> 
> 可以了，谢谢 我看目前的搜索搜的是 fullname 字段 能否增加搜索账号 也就是email 字段

。。。。这个是开源的，基本你想怎么改就可以怎么改的，不过本身没提供这功能，你需要先去修改前端界面，然后在后端接口修改查询语句

**Comment by farawei** [comment]
1，我找到了rap2-dolores/src/relatives/services/ Account.ts地方，却不会修改；
2，我看到后台代码已经注释了判断是否为isAdmin
<img width="563" alt="4C11228F-DD95-40B1-988C-D989DA95591B" src="https://user-images.githubusercontent.com/5398348/65028334-7db2a380-d96e-11e9-98c2-e5f0d0810904.png">
能贴一些代码出来看看吗？

**Comment by farawei** [comment]
> > > > > 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> > > > > rap2-dolores / src / relatives / services / Account.ts
> > > > > 93行改为
> > > > > ```ts
> > > > >    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
> > > > >        ... CREDENTIALS，
> > > > >     }）
> > > > > ```
> > > > 
> > > > 
> > > > 改完之后还是有问题
> > > > 新建/编辑团队 选择项目成员的时候提示 “您没有访问权限”
> > > 
> > > 
> > > 哦 忘了告诉你了= = 后端接口有个检查 检查操作人员是否是 isAdmin 实现形式是 判断用户的id是否是`1`.因此你有3种方式，
> > > 
> > > * 是修改后端的验证id 把1改成你要设置成管理员的ID。
> > > * 是去数据库把你要设置成管理员的ID改为1。
> > > * 就是你自己去把isAdmin的方式重写，这样你就能多设置一些管理员
> > > 
> > > 本身搭建这个项目就是为了内部使用 那么基本设置一个管理员即可
> > 
> > 
> > 可以了，谢谢 我看目前的搜索搜的是 fullname 字段 能否增加搜索账号 也就是email 字段
> 
> 。。。。这个是开源的，基本你想怎么改就可以怎么改的，不过本身没提供这功能，你需要先去修改前端界面，然后在后端接口修改查询语句



> > > > > 看了下是在调用account / list接口时未传入cookie导致无法获取用户登录信息
> > > > > rap2-dolores / src / relatives / services / Account.ts
> > > > > 93行改为
> > > > > ```ts
> > > > >    return  fetch（` $ { serve } / account / list？name = $ { name }＆cursor = $ { cursor }＆limit = $ { limit } `，{
> > > > >        ... CREDENTIALS，
> > > > >     }）
> > > > > ```
> > > > 
> > > > 
> > > > 改完之后还是有问题
> > > > 新建/编辑团队 选择项目成员的时候提示 “您没有访问权限”
> > > 
> > > 
> > > 哦 忘了告诉你了= = 后端接口有个检查 检查操作人员是否是 isAdmin 实现形式是 判断用户的id是否是`1`.因此你有3种方式，
> > > 
> > > * 是修改后端的验证id 把1改成你要设置成管理员的ID。
> > > * 是去数据库把你要设置成管理员的ID改为1。
> > > * 就是你自己去把isAdmin的方式重写，这样你就能多设置一些管理员
> > > 
> > > 本身搭建这个项目就是为了内部使用 那么基本设置一个管理员即可
> > 
> > 
> > 可以了，谢谢 我看目前的搜索搜的是 fullname 字段 能否增加搜索账号 也就是email 字段
> 
> 。。。。这个是开源的，基本你想怎么改就可以怎么改的，不过本身没提供这功能，你需要先去修改前端界面，然后在后端接口修改查询语句

我把  ***/rap2-delos/src/routes路径下的base.ts文件修改了一下，直接不做判断
<img width="732" alt="0884F63A-C088-4FC7-A7E1-CB2B993CF8DD" src="https://user-images.githubusercontent.com/5398348/65029867-0d595180-d971-11e9-9689-6105474cedf8.png">

然后再在build一下，启动，也可以

**Comment by bigfengyu** [comment]
问题已修复，感谢各位回复！
