### ISSUE TITLE
新建团队后删除无效

### ISSUE THREAD

**Issue by Yingzheng918** [thx/rap2-delos#548]
**BUG描述**
新建团队后删除无效

**复现步骤**

**期望结果**
希望可以正常删除个人创建的团队

**实际结果**
点击删除后确认，然后没有然后了

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by bigfengyu** [comment]
fixed
