### ISSUE TITLE
点击团队的编辑，弹出的是新建团队模态框

### ISSUE THREAD

**Issue by Yingzheng918** [thx/rap2-delos#549]
**BUG描述**
点击团队的编辑，弹出的是新建团队模态框

**复现步骤**

**期望结果**
可以正常编辑团队名称，及成员

**实际结果**
点击团队的编辑，弹出的是新建团队模态框

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
