### ISSUE TITLE
json对象不好移动

### ISSUE THREAD

**Issue by dongm2ez** [thx/rap2-delos#55]
文档中一个对象很大的话，没有收起展开功能，这个很难移动位置，因为对象占了屏幕很大的位置，基本拖放不了，尤其是向下拖动

**Comment by Bosn** [comment]
看到标题我想错了...

**Comment by alvarto** [comment]
1. 收起展开功能
2. 树拖动功能

**Comment by Bosn** [comment]
请通过JSON导出导入解决
