### ISSUE TITLE
注册成功后，登录失败

### ISSUE THREAD

**Issue by acid122** [thx/rap2-delos#550]
**BUG描述**
点击注册后，成功注册自动跳转至登录页面，但是登录报账号或密码错误

**复现步骤**
先注册，然后系统自动跳到登录界面，这一步应该是已经注册成功吧，然后使用新注册的邮箱和密码登录；

**期望结果**
登录成功并进入首页。

**实际结果**
报账号或密码错误

**截图**
![image](https://user-images.githubusercontent.com/20023593/63660428-006d9600-c7e9-11e9-933b-a8e9b946f28d.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
Google Chrome 版本 76.0.3809.100（正式版本） （64 位）
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by zpzxgcr** [comment]
+1 啊

**Comment by Bosn** [comment]
最新版已fixed，若扔有问题欢迎reopen
