### ISSUE TITLE
Function类型的响应内容，函数里面不能取参数做逻辑判断

### ISSUE THREAD

**Issue by hejiv5** [thx/rap2-delos#551]
**BUG描述**
我在响应内容的函数里面通过$参数名$获取的请求参数不能做逻辑判断

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
可以的，确认下对应参数是否在请求参数里定义了，如果定义了，例如响应参数选择Function，规则填写：() => "haha" + "$foo$"

这样参数$foo$就会被正确填充，如实际请求xx?foo=123，则返回结果haha123

**Comment by yi-ge** [comment]
@Bosn
在函数内部写判断条件似乎不生效。

**Comment by liangfeng093** [comment]
Function类型的规则里面可以写if吗？

**Comment by Bosn** [comment]
@yi-ge @liangfeng093 

字段名 `testFoo`
初始值 `() => { return "$companyId$ haha"}`

请求链接：
http://rap2api.taobao.org/app/mock/287086/api/getEmployees.json?companyId=10086

生成的Mock数据（注意不要看预览，预览不支持请求参数）
```json
// 20210817165037
// http://rap2api.taobao.org/app/mock/287086/api/getEmployees.json?companyId=10086

{
  "data": {
    "employees": [
      {
        "id": 2324,
        "name": "邓芳",
        "test": ""
      },
      {
        "id": 3836,
        "name": "吕芳",
        "test": ""
      },
      {
        "id": 3987,
        "name": "武磊",
        "test": ""
      },
      {
        "id": 4369,
        "name": "傅娟",
        "test": ""
      },
      {
        "id": 3980,
        "name": "黎艳",
        "test": ""
      }
    ]
  },
  "errCode": "",
  "isOk": true,
  "testFunc": "() => { return \"10086 haha\"}"
}
```

**Comment by cuiguojie** [comment]
@Bosn 直接调用没问题，但是没办法当做条件执行判断

```
testFunc: () => {
    if ($companyId$ === '10086') {
        return 1;
    } 
    
    return 2;
}

```

请问这种场景有写法可以支持么？
