### ISSUE TITLE
最新版本生产环境启动失败，报错：Cannot find module '../constants.js'

### ISSUE THREAD

**Issue by ftzzh004** [thx/rap2-delos#552]
**BUG描述**
执行命令： npm start
后报如下错误
![image](https://user-images.githubusercontent.com/10509143/63833162-f55f6500-c9a4-11e9-9a82-48a8f703f068.png)

**复现步骤**
重新从git下载，执行命令 npm run dev 没问题，最后执行 npm start 还是报同样的错误

**环境**
* 自建服务器  linux  CentOS release 6.8 (Final)

**Comment by Bosn** [comment]
该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
