### ISSUE TITLE
期待导出功能完善，支持word文档、html或者pdf导出

### ISSUE THREAD

**Issue by JonSnow592622272** [thx/rap2-delos#554]
期待导出功能完善，支持word文档、html或者pdf导出

**Comment by ChangRC** [comment]
我也有word文档导出的需求，还有人管这个项目吗？不然转用老版本？

**Comment by bigfengyu** [comment]
> 我也有word文档导出的需求，还有人管这个项目吗？不然转用老版本？

这个功能正在施工中，近期将上线！
更快的更新信息在钉钉群：11789704
