### ISSUE TITLE
部署rap2-dolores前端访问任何页面都404

### ISSUE THREAD

**Issue by duantianliao** [thx/rap2-delos#555]
**BUG描述**
部署rap2-dolores前端访问任何页面都404，采用dev模式启动可以正常访问，用npm run build出来访问所有页面都返回404，如果带了登陆信息就可以正常操作

**复现步骤**
git clone https://github.com/thx/rap2-dolores.git
修改src/config/config.prod.ts配置后端接口
npm install
npm run build
serve -s ./build -p 80

**期望结果**
访问首页可以正常使用

**实际结果**
404

**截图**
![image](https://user-images.githubusercontent.com/18131602/64515373-1027c700-d31f-11e9-9a9a-e6ff9f581cc4.png)

**Comment by SamZSL** [comment]
可参考：https://github.com/thx/rap2-delos/issues/480
