### ISSUE TITLE
http://127.0.0.1:38080/ 显示Hello RAP!

### ISSUE THREAD

**Issue by huatangzhi** [thx/rap2-delos#559]
**BUG描述**
http://127.0.0.1:38080/ 显示Hello RAP！没有显示其他页面

**复现步骤**
docker-compose up -d

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/4861883/64689159-63854b00-d4c0-11e9-8e15-cf0dad545630.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本 windows 10
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
docker之前是开源网友提供的，近期我们已在README提供了官方的docker，并在后续会持续进行维护，可以尝试一下，如果仍有问题可以新开issue，感谢您的反馈。

该issue已过期，若最新部署版本问题依旧，请重新reopen，谢谢。
