### ISSUE TITLE
Linux系统本地部署成功，创建团队，不能搜索到其他的成员

### ISSUE THREAD

**Issue by farawei** [thx/rap2-delos#561]
**BUG描述**
在编辑修改团队页面，搜索成员，发现请求链接account/list?name=c&cursor=1&limit=100响应为
{"isOk":false,"errMsg":"need login"}

**复现步骤**
登录自己的账号---点击团队---创建团队---项目成员搜索

**期望结果**
期望可以搜索到成员

**实际结果**
响应为：{"isOk":false,"errMsg":"need login"}

**截图**

<img width="1357" alt="屏幕快照 2019-09-17 下午4 04 06" src="https://user-images.githubusercontent.com/5398348/65023178-e39a2d80-d964-11e9-9abf-9368d8664645.png">

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
在Linux下自建的服务器
Linux whatytest0002 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

* 如果是前端错误，请提供浏览器版本
无

* 其它可能帮助我们排查问题的环境信息
我使用http://rap2.taobao.org/
你们线上的服务器，却没有这个问题

**附加信息**

**Comment by bigfengyu** [comment]
这个问题解决了哈
