### ISSUE TITLE
在团队下创建仓库，无法显示在团队下面

### ISSUE THREAD

**Issue by lyt8384** [thx/rap2-delos#564]
**BUG描述**
在团队下创建仓库，无法显示在团队下面

**复现步骤**
1. 拉取前后端的最新版本
2. 按照说明部署
3. 清空初始化的数据
4. 创建新用户
5. 创建团队，不设置Owner和项目成员
6. 在团队下新建仓库，不选择成员
7. 提交后，仓库不在团队下，提交数据中organizationid=0

**期望结果**
在团队下创建的仓库可以归属于团队

**实际结果**
在团队下创建的仓库归属于个人了，并非团队

**截图**

**环境**
用官方的在线版本可以复现问题

**附加信息**

**Comment by yeluobaicaoku** [comment]
同样遇到的此问题

**Comment by a044161** [comment]
同样遇到该问题

**Comment by lyt8384** [comment]
看了下在 `RepositoryListParts.tsx` 下面的第[62](https://github.com/thx/rap2-dolores/blob/b72834064df9a6b0d710d8115fac27fcb3f9f06b/src/components/repository/RepositoryListParts.tsx#L62)行新建仓库的按钮并没有根据条件把`organization.id`传递给`repository`的`organizationid`，可能因为这个导致的吧，猜测。
可惜我不是前端不会Typescript

**Comment by bigfengyu** [comment]
> 看了下在 `RepositoryListParts.tsx` 下面的第[62](https://github.com/thx/rap2-dolores/blob/b72834064df9a6b0d710d8115fac27fcb3f9f06b/src/components/repository/RepositoryListParts.tsx#L62)行新建仓库的按钮并没有根据条件把`organization.id`传递给`repository`的`organizationid`，可能因为这个导致的吧，猜测。
> 可惜我不是前端不会Typescript

感谢，解决了这个问题哈！
