### ISSUE TITLE
注销后重新登陆，数据不会刷新

### ISSUE THREAD

**Issue by SamZSL** [thx/rap2-delos#565]
**BUG描述**
账号注销后，重新登陆，数据不会刷新

**复现步骤**
条件：两个账号以上，
操作：账号A新建了模块或者接口，账号B进行注销后，重新登陆，或菜单切换都获取不到A新建的模块或接口

**期望结果**
重新登陆、菜单切换都可以获取到当前模块下最新内容。这样对于团队协作更友好。

**实际结果**
获取不到最新数据，必须手动刷新整个页面才可以获取到

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
在编辑时，会重新拉取。极端的同步情况，暂不处理。自己刷新下吧
