### ISSUE TITLE
[TIP]Just for people who start other services by Docker

### ISSUE THREAD

**Issue by taoism-o** [thx/rap2-delos#567]
What I met is the problem as I started MySQL by using Docker container not on my domain,
Which means if I need to connect to my MySQL service, I also need to configure my port and my protocol, if I’m using bridged network, should be specified as like ‘tcp’. 

So that, if those parameters could also be in the config.file will be great, or if there are other better ways.

I’m trying to give a answer, but not sure that certain.
That’s why writing down here is for someone who could have one that we could talk.

**Comment by Bosn** [comment]
快来和楼主talk talk 你的docker config是否能满足楼主的desire
if 不能，那就check check

**Comment by chengqigang** [comment]
docker一键部署后，前端登录注册的时候500
![image](https://user-images.githubusercontent.com/29392211/70764848-c45c4200-1d93-11ea-87a3-17964078258b.png)
后端访问也是500
![image](https://user-images.githubusercontent.com/29392211/70764787-9a0a8480-1d93-11ea-8863-30abfcfc7c3e.png)
这是啥情况，求助
