### ISSUE TITLE
找不到之前建的仓库了

### ISSUE THREAD

**Issue by meathross** [thx/rap2-delos#568]
**BUG描述**
之前建的仓库找不到了。在http://rap2.taobao.org/

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/14865604/65668369-2bf7d080-e074-11e9-9433-1305540414e1.png)

**环境**
* 不是自建服务器

**附加信息**

**Comment by liuzwei** [comment]
很早之前建的项目还有，最近建的没有了，不知道怎么个情况

**Comment by zhangdaren** [comment]
我也是。、

**Comment by meathross** [comment]
正常了
