### ISSUE TITLE
采用导入方式编辑接口时，当字段值为null时，无法正常保存。

### ISSUE THREAD

**Issue by sivannnn** [thx/rap2-delos#569]
**BUG描述**
采用导入方式编辑接口时，当字段值为null时，无法正常保存。

**复现步骤**
1、点击"编辑"按钮。
2、点击"导入"按钮。
3、粘贴字段值存在null的json字符串至弹出层文本域。
4、点击弹出层的"提交"按钮。
5、点击"保存"。
6、字段值为null之后的所有内容均无法识别。
**期望结果**
字段值为null的字段，默认识别为string类型。能够正常保存结果。

**Comment by Bosn** [comment]
测试了下，导入null值，类型默认选择也会null

至于null是string还是number或者是 boolean，编辑器在不知道的情况下确实不应该随意去修改的。
