### ISSUE TITLE
拉的git的master分支 部署好之后创建仓库api报错500？

### ISSUE THREAD

**Issue by doufeng007** [thx/rap2-delos#571]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by bigfengyu** [comment]
感谢反馈，已经修正了，重新拉去 rap2-dolores 皆可
