### ISSUE TITLE
创建仓库报500错误

### ISSUE THREAD

**Issue by SummerWindL** [thx/rap2-delos#572]
**BUG描述**
创建仓库报500错误

**复现步骤**
执行完npm run create-db 从前端访问创建仓库报错

**期望结果**

**实际结果**
SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`RAP2_DELOS_APP`.`Repositories`, CONSTRAINT `Repositories_ibfk_2` FOREIGN KEY (`organizationId`) REFERENCES `Organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

**截图**
![image](https://user-images.githubusercontent.com/24834548/66468232-6754bf00-eab8-11e9-89fb-0726734cd4f5.png)
![image](https://user-images.githubusercontent.com/24834548/66468446-bd296700-eab8-11e9-8c10-a14d74b2f69f.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
Linux version 3.13.0-116-generic (buildd@lcy01-03) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
目前我使用的mysql版本是5.6的，不知道是否是mysql版本的问题，执行npm run create-db过程未出现任何错误。

**Comment by bigfengyu** [comment]
请更新 rap2-dolores 仓库到最新再试一下~

**Comment by SummerWindL** [comment]
> 请更新 rap2-dolores 仓库到最新再试一下~

谢谢大佬，问题解决了
