### ISSUE TITLE
接口404

### ISSUE THREAD

**Issue by jin82** [thx/rap2-delos#574]
**BUG描述**

/test/test.plugin.jquery.html?id=17
/export/postman?id=17
访问都是404
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
测试都正常，应该是部署问题。提供信息过于简略没办法排查。
