### ISSUE TITLE
本地环境接口500

### ISSUE THREAD

**Issue by zhaokgithub** [thx/rap2-delos#575]
**BUG描述**
Cannot set property name of  which has only a getter

**复现步骤**
按照官方提供的文档安装完后启动没问题，访问任何接口都500错误信息如下
  TypeError: Cannot set property name of  which has only a getter
      at defaultErrorHanlder (/Users/zhaokai/work/rap2-delos/node_modules/koa-generic-session/lib/session.js:523:12)
      at /Users/zhaokai/work/rap2-delos/node_modules/koa-generic-session/lib/session.js:193:9
      at Generator.throw (<anonymous>)
      at step (/Users/zhaokai/work/rap2-delos/node_modules/koa-generic-session/lib/session.js:3:191)
      at /Users/zhaokai/work/rap2-delos/node_modules/koa-generic-session/lib/session.js:3:402
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
    操作系统是macos
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by smz8023** [comment]
哥们~解决了么？我也遇到该问题

**Comment by zhaokgithub** [comment]
解决了------------------ 原始邮件 ------------------
发件人: "smz8023"<notifications@github.com>
发送时间: 2019年11月22日(星期五) 下午3:40
收件人: "thx/rap2-delos"<rap2-delos@noreply.github.com>;
抄送: "疯狂的snail"<820641374@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [thx/rap2-delos] 本地环境接口500 (#575)



哥们~解决了么？我也遇到该问题
 
&mdash;

**Comment by zoggee** [comment]
> 解决了------------------ 原始邮件 ------------------ 发件人: "smz8023"<notifications@github.com> 发送时间: 2019年11月22日(星期五) 下午3:40 收件人: "thx/rap2-delos"<rap2-delos@noreply.github.com>; 抄送: "疯狂的snail"<820641374@qq.com>;"State change"<state_change@noreply.github.com>; 主题: Re: [thx/rap2-delos] 本地环境接口500 (#575) 哥们~解决了么？我也遇到该问题 &mdash; You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

能问一下是怎么解决的吗,我也遇到这个问题了

**Comment by studycwq** [comment]
> > 解决了------------------ 原始邮件 ------------------ 发件人: "smz8023"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2019年11月22日(星期五) 下午3:40 收件人: "thx/rap2-delos"[rap2-delos@noreply.github.com](mailto:rap2-delos@noreply.github.com); 抄送: "疯狂的snail"[820641374@qq.com](mailto:820641374@qq.com);"State change"[state_chqinqinggllange@noreply.github.com](mailto:state_change@noreply.github.com); 主题: Re: [thx/rap2-delos] 本地环境接口500 (#575) 哥们~解决了么？我也遇到该问题 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 能问一下是怎么解决的吗,我也遇到这个问题了

我也遇到了，把redis数据库清空就可以了
