### ISSUE TITLE
生产环境使用nginx代理编译之后的文件，地址配置成 "域名/xxx" ，跳转登录时会404

### ISSUE THREAD

**Issue by changyinliangbaikai** [thx/rap2-delos#576]
**BUG描述**
生产环境使用nginx代理编译之后的文件，地址配置成 "域名/xxx" ，跳转登录时会404
nginx配置为
location /rap/ {
            root /mnt/rap2/rap2-dolores;
            try_files $uri /index.html;
            index index.html;
        }

**复现步骤**
不加try_files 跳登录时直接404
加了之后跳登录是白屏 静态文件加载错误

**环境**
阿里云  centos7
nginx代理
使用master版本的代码编译

**附加信息**
怀疑是下面写的问题
src/index.tsx  49行
window.location.href = `/account/login${hasOriginal ? `?original=${encodeURIComponent(pathname + search + hash)}` : ''}`

**Comment by Bosn** [comment]
关键字搜索：
linux nginx try_files

这是运维问题，和开源项目无关。建议自行学习下React的部署方式。
