### ISSUE TITLE
"新建仓库"这四个字，颜色太浅了吧！

### ISSUE THREAD

**Issue by TheLittleBoy** [thx/rap2-delos#577]
**BUG描述**
字体颜色非常浅，以至于都看不清了。

**复现步骤**

1、Safari浏览器
2、新用户登录http://rap2.taobao.org 网址

**期望结果**

字体颜色应该正常一些。

**实际结果**

看不清。

**截图**

![QQ20191014-142646](https://user-images.githubusercontent.com/3365421/66732584-1b769100-ee8f-11e9-9120-2e8046b28b46.png)

**Comment by Bosn** [comment]
最新版已FIXED，请关注最近更新。
