### ISSUE TITLE
Cannot find module: '@material-ui/core/styles/MuiThemeProvider'. Make sure this package is installed

### ISSUE THREAD

**Issue by foodjth** [thx/rap2-delos#578]
**BUG描述**
在npm run build 的时候一直报：Cannot find module: '@material-ui/core/styles/MuiThemeProvider'. Make sure this package is installed

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by jisiallen** [comment]
同样遇到了这个问题，该怎么解决呢

**Comment by LX111** [comment]
一样遇到了 尝试重新拉取 唯独MuiThemeProvider文件无法获取成功 求解答

**Comment by pomele** [comment]
把material-ui/core的版本改成4.3.3就可以了

**Comment by pomele** [comment]
> **BUG描述**
> 在npm run build 的时候一直报：Cannot find module: '@material-ui/core/styles/MuiThemeProvider'. Make sure this package is installed
> 
> **复现步骤**
> 
> **期望结果**
> 
> **实际结果**
> 
> **截图**
> 
> **环境**
> 
> * 是否是自建服务器？如果为自建，请提供操作系统版本
> * 如果是前端错误，请提供浏览器版本
> * 其它可能帮助我们排查问题的环境信息
> 
> **附加信息**

把material-ui/core的版本改成4.3.3就可以了

**Comment by LX111** [comment]
> > **BUG描述**
> > 在npm run build 的时候一直报：Cannot find module: '@material-ui/core/styles/MuiThemeProvider'. Make sure this package is installed
> > **复现步骤**
> > **期望结果**
> > **实际结果**
> > **截图**
> > **环境**
> > 
> > * 是否是自建服务器？如果为自建，请提供操作系统版本
> > * 如果是前端错误，请提供浏览器版本
> > * 其它可能帮助我们排查问题的环境信息
> > 
> > **附加信息**
> 
> 把material-ui/core的版本改成4.3.3就可以了

把package.json里面的material-ui/core版本更换成4.3.3也不行呀

**Comment by Bosn** [comment]
更新到最新版即可解决，若还有问题可以群中提问，具体见README
