### ISSUE TITLE
postman导入失败

### ISSUE THREAD

**Issue by yinxin-will** [thx/rap2-delos#580]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by bigfengyu** [comment]
已解决

**Comment by bigfengyu** [comment]
这个问题其实是我们最近加强了仓库权限校验导致的，由于导出 postman 的接口也加了权限校验，要看当前用户是否有查看仓库的权限，所以直接从链接导出这种无状态的形式就不行了，把这个功能改成了点击下载 json 文件，通过文件导出即可。
