### ISSUE TITLE
rap2-dolores 运行后提示 Module not found

### ISSUE THREAD

**Issue by hejiyong** [thx/rap2-delos#582]
**BUG描述**
Failed to compile
./src/family/start.tsx
Module not found: Can't resolve '@material-ui/core/styles/MuiThemeProvider' in 'E:\GitHub\docs\rap2-dolores\src\family'

**复现步骤**
根据rap2-dolores部署步骤执行，再最新运行npm run dev 成功后自动打开的页面中提示了这个错误

**截图**
![image](https://user-images.githubusercontent.com/54531955/66909124-ce392180-f03e-11e9-9034-d5f6faa3f32b.png)

![image](https://user-images.githubusercontent.com/54531955/66909072-b8c3f780-f03e-11e9-89fb-33087221241d.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
window 10 
* 如果是前端错误，请提供浏览器版本
chrome 
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by bigfengyu** [comment]
已解决，请更新仓库
