### ISSUE TITLE
团队添加组员搜索不到对应账号

### ISSUE THREAD

**Issue by superdemon520** [thx/rap2-delos#583]
**BUG描述**
新建团队中选择添加成员，搜索公司同事注册的账号（邮箱地址）或用户名，搜索不到，提示搜不到数据

**复现步骤**
新建团队（修改团队）成员框中输入邮箱，提示搜不到数据

**期望结果**
成功搜索到成员加入团队

**实际结果**
搜索不到数据

**截图**
<img width="553" alt="image" src="https://user-images.githubusercontent.com/12293314/67059315-16655a80-f18b-11e9-9cb5-07cd0c4f0343.png">

**环境**
rap2.taobao.org网上平台

**附加信息**

**Comment by superdemon520** [comment]
仓库添加成员存在同样问题

**Comment by bigfengyu** [comment]
请搜索账户名，http://rap2api.taobao.org/account/info 在这里可以获取自己的账户名

**Comment by LX111** [comment]
这个问题 在自己搭建的服务器上面也存在 麻烦关注一波
