### ISSUE TITLE
后台不响应

### ISSUE THREAD

**Issue by simplesheep** [thx/rap2-delos#584]
**BUG描述**
您好，我在后台使用pm2 以守护进程方式启动了delos后，下午的时候后台突然不响应了，通过pm2 -list查看，服务是正常的，但是我用curl的方式查看也得不到响应结果，之后重启一下就好了；请问这可能是哪方面原因呢？
<img width="991" alt="图片" src="https://user-images.githubusercontent.com/24515241/67382384-f6d19600-f5bf-11e9-9353-89dee25e0f91.png">

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by simplesheep** [comment]
是自建服务，操作系统是阿里云ECS服务器，镜像版本centos7.4
非前端错误，/account/info 接口一直不响应
![image](https://user-images.githubusercontent.com/24515241/67915775-be891380-fbce-11e9-9ded-feae99606c7f.png)

**Comment by Bosn** [comment]
运维问题不在本开源项目技术支持范围，建议在群里和其它网友交流。
