### ISSUE TITLE
建议修改字段时支持拖拽到某个字段内部

### ISSUE THREAD

**Issue by xinconan** [thx/rap2-delos#585]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
建议修改字段时支持拖拽到某个字段内部，现在修改数据结构时发现，需要在原来的字段a上包装一层b，在a同级建了b字段后，想将a直接挪到b的内部，现在拖动只能改变a和b同级的位置，需要手动在b里新建一遍和a一模一样的数据

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
拖拽问题麻烦大佬处理下吧 @bigfengyu 之前你有改过

**Comment by Bosn** [comment]
暂不支持跨层级拖拽
