### ISSUE TITLE
已经实现自动化将实体类导入到rap2

### ISSUE THREAD

**Issue by kings1990** [thx/rap2-delos#587]
每次拷贝简介烦死了,而且字段层级搞错所有的简介得全部重新copy过,写了个工具:
https://github.com/kings1990/rap2-generator

测试代码如下
https://github.com/kings1990/rap2-generator-demo

**Comment by Bosn** [comment]
棒棒哒

**Comment by Bosn** [comment]
@bigfengyu RAP2官网需要有个插件列表，来访类似的开源周边

**Comment by kings1990** [comment]
> 棒棒哒

@Bosn 
网页版: [https://github.com/kings1990/rap2-generator-web](https://github.com/kings1990/rap2-generator-web)

在线 : [http://rap.sheng90.wang](http://rap.sheng90.wang)
