### ISSUE TITLE
关于项目接口一键导入，避免项目初期巨大工作量的copy操作

### ISSUE THREAD

**Issue by shijinting0321** [thx/rap2-delos#588]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
在往rap上写接口时，对后端人员来说极其痛苦，每个字段含义及说明都需要copy。费时费力！
小型项目都需要2天以上的工作量来做这些操作太浪费人力
**您是否有建议的实现方案**
建议增加通过项目配置的方式自动导入，可部分借鉴Swagger。经量减少后端机械式工作量
获取可以，先初始化一次全项目接口，后记接口变更，则对接口以版本递增的形式进行管理，
**其它帮助我们理解您需求的描述、截图**

**Comment by kings1990** [comment]
https://github.com/kings1990/kings-rap2-generator

**Comment by shijinting0321** [comment]
> https://github.com/kings1990/rap2-generator
感觉这个还是太复杂。。。没有特别的精简。最优方案还是少量配置加注解方式。

**Comment by Bosn** [comment]
先搞清楚导入源头是啥啊

目前提供的是比较通用的JSON导入，我们在开发OpenAPI，提供接口，可以自行开发导入工具。
