### ISSUE TITLE
类型为Number时生成规则 输入 “.0” 会导致浏览器内存溢出

### ISSUE THREAD

**Issue by SIR1016** [thx/rap2-delos#590]
**BUG描述**
类型为Number时生成规则 输入 “.0” 会导致浏览器内存溢出。

**复现步骤**
选择类型    Number  →  生成规则 “23.0”  【此时页面无响应，Chrome内存飙升】

**期望结果**
规则不生效

**实际结果**
页面崩溃

**截图**
![image](https://user-images.githubusercontent.com/44308645/68266696-cd6a3d00-008a-11ea-87c5-f49daec03aa6.png)

![image](https://user-images.githubusercontent.com/44308645/68266626-98f68100-008a-11ea-82ea-ffcaa737eccd.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
Google Chrome 78.0.3904.87（正式版本） （64 位）
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
fixed
