### ISSUE TITLE
BUG：因前端问题导致后端注册模块报错行为异常

### ISSUE THREAD

**Issue by MeteorOC** [thx/rap2-delos#591]
**BUG描述**
在使用过程中，我发现后端注册的报错：“该邮件已被注册，请更换再试”无效。

**复现步骤**
若出现邮件被注册的情况，前端将直接返回login页面不报任何错误。可以尝试注册一个新号，然后再重复注册一样信息的新号，即可复现。

**期望结果**
报错正常展示

**实际结果**
无报错，直接跳回login页。（先跳回info，info再跳到login）

**截图**
Bug位于前端的rap2-dolores库 /src/relatives/AccountRelative.ts  [AccountAction.addUser]中
修复前后对比：
![image](https://user-images.githubusercontent.com/38990160/68300683-41333680-00d9-11ea-90b8-c78dee4008fb.png)
**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息
**附加信息**
已在截图中给出，很小的一个bug，自建服务器接LDAP登录时发现。
图片无法看到请直接看修复后的代码~
```
*[AccountAction.addUser(null, null).type](action: any) {
      try {
        const user = yield call(AccountService.addUser, action.user)
        if (user.errMsg) {
          throw new Error(user.errMsg)
        }
        if (user && user.id) {
          yield put(AccountAction.addUserSucceeded(user))
          try {
            const user = yield call(AccountService.fetchLoginInfo)
            if (user.id) {
              yield put(AccountAction.fetchLoginInfoSucceeded(user))
            }
          } catch (e) {
            yield put(AccountAction.fetchLoginInfoFailed(e.message))
          }
          yield put(push('/'))
        } else {
          yield put(AccountAction.addUserFailed('注册失败'))
        }
        if (action.onResolved) {
          action.onResolved()
        }
      } catch (e) {
        yield put(showMessage(e.message, MSG_TYPE.WARNING))
        yield put(AccountAction.addUserFailed(e.message))
      }
    }
```

**Comment by Bosn** [comment]
已在内部版本：commit 51d3fd92e316f8deaa544d4894fbbd79edd10025
修复，待提交。
