### ISSUE TITLE
接口参数、响应 导入json 报错

### ISSUE THREAD

**Issue by zhoumingyu** [thx/rap2-delos#592]
**BUG描述**

接口参数、响应 导入json 报错
**复现步骤**
编辑 导入接口参数json格式 保存报错
经确认 属性值有 =null 会报错
**期望结果**

**实际结果**

**截图**
![QQ图片20191111144819](https://user-images.githubusercontent.com/11784638/68566809-5f5eb500-0492-11ea-9aaf-cbe5aff95cd2.png)
**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
docker 部署
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
********************************************原始数据***************************************
{
    "success": true,
    "code": "201",
    "msg": "订单支付中",
    "exceptionString": null,
    "data": {
        "order_no": "3D1911080000065",
        "member_id": "101000040466",
        "terminal_type": "mobile",
        "terminal_info": "FB342408-F76A-462B-B8E7-88EF8D26770A",
        "merchant_id": "100000001304881",
        "title": "商品",
        "body": "191108547964338",
        "member_ip": "10.217.242.100",
        "notify_url": "https://mobilemall-test.maya1618.com/payment/reapalPayCallBack",
        "token": "f982ce6df79148d472dc4a8adafc61705090648adfe542f3267c5ef474d828ea",
        "result_msg": "token获取成功",
        "transtime": "2019-11-08 11:02:05",
        "token_id": "6113bce50ca240979053b505dd714c8c",
        "service": "SDK",
        "total_fee": "1",
        "business_type": "5",
        "ledger_info": "1,100000001304881,2,1",
        "result_code": "0000",
        "sign_type": "RSA"
    }
}
********************************************原始数据***************************************

**Comment by Bosn** [comment]
没复现。。。@bigfengyu 帮忙看看

**Comment by zhoumingyu** [comment]
http://rap2.taobao.org/ 我在这个网站上边提交 {"exceptionString": null} 这个数据格式 是可以提交的
但是在我自己部署的docker里边 
![1](https://user-images.githubusercontent.com/11784638/69233651-4196fb80-0bc8-11ea-90de-f5002d71298e.png)
![2](https://user-images.githubusercontent.com/11784638/69233652-422f9200-0bc8-11ea-910b-114e95b3e43c.png)
![3](https://user-images.githubusercontent.com/11784638/69233654-422f9200-0bc8-11ea-890b-4d158012b749.png)
![4](https://user-images.githubusercontent.com/11784638/69233657-42c82880-0bc8-11ea-8eff-e4237d6f8611.png)

**Comment by Weirdo-Z** [comment]
同出现了这个问题,linux部署 2.7.0版本
如果导入的json里value值为null可以提交,但保存接口信息的时候会报错

**Comment by Bosn** [comment]
最新版可以再试一下如果扔有问题欢迎reopen排查。

请使用最新版的源代码进行部署
