### ISSUE TITLE
接口简介描述无法换行

### ISSUE THREAD

**Issue by taopigu** [thx/rap2-delos#593]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
接口编辑种简介能换行输入，保存以后自动变成了一行。

**您是否有建议的实现方案**
期望在编辑简介保存后也能换行

**其它帮助我们理解您需求的描述、截图**

**Comment by boxsnake** [comment]
Issue: https://github.com/thx/rap2-delos/issues/595
PR: https://github.com/thx/rap2-dolores/pull/99

**Comment by Bosn** [comment]
已经支持markdown了亲
