### ISSUE TITLE
直接返回数组数据问题，改为__root__也没有用。

### ISSUE THREAD

**Issue by xilovesyu** [thx/rap2-delos#594]
**BUG描述**
在官方的网站 http://rap2.taobao.org/， 想直接返回数组但是不成功，搜索发现需要将name改成__root__， 修改完成后仍然不行。

**复现步骤**
定义返回格式：

![image](https://user-images.githubusercontent.com/14347674/68648721-1410d900-055c-11ea-88df-b9757f208f07.png)

返回结果
![image](https://user-images.githubusercontent.com/14347674/68648764-27bc3f80-055c-11ea-8dbc-ef5c4d17aeee.png)

**期望结果**
 应该能够返回正确的数组。

**实际结果**
返回的是对象

**附加信息**
查了代码发现 src/routes/utils/tree.ts 132行，     if (keys.length === 1 && keys[0] === '__root__') data = data.__root__ 这里的keys的length不为1， 同时发现src/routes/mock.ts 375行中也有相关的代码，不过这里判断的是_root_。 

我的解决方案是把 src/routes/utils/tree.ts 中的去掉，然后改src/routes/mock.ts 中改_root_为__root__

**Comment by Bosn** [comment]
已在内网commit b2a3558ba4cff62f9f2f1198882f2385eba866aa 修复，请关注下一个版本。
