### ISSUE TITLE
建议添加Markdown或多行支持

### ISSUE THREAD

**Issue by boxsnake** [thx/rap2-delos#595]
建议对以下内容添加Markdown或者多行文本支持：
- 项目、模块和接口的描述部分
- 字段的简介部分

**Comment by Bosn** [comment]
类似问题提过了，我们是接口格式管理的工具，markdown文档，有专门的文档工具。例如语雀，请用专业的文档工具去管理文本文档会更适合。

**Comment by boxsnake** [comment]
@Bosn 
那么，可以加入文本换行吗？现在要写多行的说明，结果一保存全部堆在一起了，对于看文档的人来说就是噩梦……

**Comment by Bosn** [comment]
可以的

**Comment by Bosn** [comment]
@bigfengyu 麻烦加一下换行功能，对于\n做下识别，生成br

**Comment by boxsnake** [comment]
@bigfengyu @Bosn 我自己修改了，提交了PR: https://github.com/thx/rap2-dolores/pull/99
