### ISSUE TITLE
接口地址命名的问题

### ISSUE THREAD

**Issue by baiej214** [thx/rap2-delos#599]
**BUG描述**

POST请求路径中带有get就一直报请求类型的错误，比如 /getxxx，但是只要把 /getxxx改成 /xxx，去掉get，竟然就好了！！？

**复现步骤**

某个POST路径
![image](https://user-images.githubusercontent.com/683351/68750316-a38cb980-063a-11ea-8f69-8a8a6618a966.png)

Content-Type = application/json; charset=utf-8

不要求传任何参数

用Postman请求，一直报
`{
    "isOk": false,
    "errMsg": "未匹配到任何接口，请检查请求类型是否一致。"
}`

但是如果把请求路径最后面的getPointList改成PointList，就！好！了！

**注意，是在Postman里改，而rap2上面，实际配置的接口还是 /getPointList**

**期望结果**

```
{
   key:value
}

```
**实际结果**

```
{
    "isOk": false,
    "errMsg": "未匹配到任何接口，请检查请求类型是否一致。"
}
```

**截图**

> 异常：

![image](https://user-images.githubusercontent.com/683351/68751691-fa938e00-063c-11ea-8278-14dd57912855.png)

> 正常：

![image](https://user-images.githubusercontent.com/683351/68752370-2a8f6100-063e-11ea-831d-bd5296f53d43.png)

**环境**
非自建，直接请求的 

> http://rap2api.taobao.org/

**附加信息**

**Comment by baiej214** [comment]
后来试了试，delete 也有同样的问题。其他我就没再试，你们自己试试吧

**Comment by Bosn** [comment]
应该是保留字匹配上的BUG
