### ISSUE TITLE
【关于用户列表】是否BUG？

### ISSUE THREAD

**Issue by Paleozoic** [thx/rap2-delos#6]
通过访问http://rap2.taobao.org/account，看到了所有的用户列表，包含的信息是用户名和邮箱。
= =|| 爬虫会不会爬取一波，然后发广告？
然后删除是disabled的，html修改一下后，试了试删除自己，然后真删除了。（有可能删除别人也可以）
重新登录一下，结果……登陆不上了。。。
是否缺少对用户数据权限的处理？

**Comment by Bosn** [comment]
我排查下，之前一直内部用，刚刚放出来。建议自己先内部部署。官网仍然主要用于DEMO

**Comment by webkong** [comment]
刚在本地部署并且正确运行了， 感觉缺少权限用户的权限控制， admin不能删除用户。 去掉了源码中的disabled就能删除了。

admin 用户在某个仓库中可以删除自己，自己看不到删除自己之后的仓库。admin不是管理员吗？应该可以看到所有仓库？还是说admin只是一个普通的账户。

**Comment by Bosn** [comment]
已在 commit b4a8373 中修复

**Comment by wangyunshuai** [comment]
admin 账号为什么不能删除其他账号，和非 admin 账号创建的仓库呢？
