### ISSUE TITLE
一个接口多个状态码

### ISSUE THREAD

**Issue by Caeson** [thx/rap2-delos#603]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
请问一个接口有多个状态码，每个状态码返回的response body具有不同结构。这个该如何表示？谢谢！

**您是否有建议的实现方案**
无

**其它帮助我们理解您需求的描述、截图**
无

**Comment by Bosn** [comment]
那就需要创建多个接口了哦，可以通过参数化来在mock服务中区分，例如url中填写
url?method=post
url?method=get

则mock服务会根据method的传参来适配正确的接口，并返回对应的正确状态码

**Comment by Caeson** [comment]
明白了。

如果不通过参数化呢？比如一个接口是 GET /content，可能返回200 + response body，也可能返回404(content not found之类)。这个就没办法在一个接口里表现了吧？

**Comment by Bosn** [comment]
同样路径，同样参数，返回不一样格式？

这个自己创建多接口，想测哪个，就用哪个。接口文档要保证参数 + 路径 => 确定返回 的一致性。

**Comment by Caeson** [comment]
明白了，理解了项目的设计思路了。谢谢！
