### ISSUE TITLE
接口设置Header请求参数无效，报错

### ISSUE THREAD

**Issue by superdemon520** [thx/rap2-delos#607]
**BUG描述**
设置Header参数，使用postman按照协议发送请求，报错提示错误

**复现步骤**

**期望结果**

**实际结果**

**截图**
rap2接口设置截图
<img width="1199" alt="WX20191119-092318@2x" src="https://user-images.githubusercontent.com/12293314/69108212-f9d08100-0aae-11ea-86a1-1848623c6b6d.png">

postman截图
<img width="966" alt="WX20191119-092421@2x" src="https://user-images.githubusercontent.com/12293314/69108228-01902580-0aaf-11ea-9551-36ccd9f4368f.png">

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by superdemon520** [comment]
body也存在这个问题

**Comment by Bosn** [comment]
测试了没问题啊，你啥版本

**Comment by superdemon520** [comment]
<img width="284" alt="WX20191120-125703@2x" src="https://user-images.githubusercontent.com/12293314/69210307-4abaa500-0b95-11ea-92ca-48960b34860d.png">

我同事试了也不行

**Comment by ycyy** [comment]
使用http://rap2.taobao.org/ 服务也复现该问题

**Comment by w316149998** [comment]
我的临时解决方案  https://github.com/thx/rap2-delos/issues/630#issuecomment-617497161

**Comment by Bosn** [comment]
已经修复了
