### ISSUE TITLE
我有几个仓库，其中一个仓库打不开。【在点击之后一直 loading 】

### ISSUE THREAD

**Issue by lixingyangok** [thx/rap2-delos#608]
**BUG描述**
我有几个仓库， 其中一个仓库在点击之后报错，无法进入。

**复现步骤**
点击上方导航【仓库】- 在仓库列表中点击错误的仓库即可，然后就是无限的 laoding。其它仓库如常没错误。

**期望结果**
期望看到仓库内容，即正常显示

**实际结果**
实际一直在loading

**截图**
![TIM截图20191119140416](https://user-images.githubusercontent.com/19503772/69121434-56479680-0ad7-11ea-9222-ec684c1c7970.png)

**环境**
● bug发生在 rap2.taobao.org， 非自建服务器
● chrome 版本 78.0.3904.97, 搜狗10.0，等几个同事的几个浏览器都不能访问

**附加信息**
★ 提交这条 issure 时截图怎么发也发不上来，后来翻个墙才把图传上来。
★ 刚刚把 issure 写好，同事说【突然好了，可以打开了】。OMG！历时今天一上午的bug，自愈了。
★ 还是顺手把这提交上来吧，或许有些价值呢。
-
-
感谢开发人员，感谢阿里人
-
-

**Comment by Bosn** [comment]
麻烦把 /repository/get?id=xxxx 这个接口返回的项目数据，发到我的邮箱，排查一下，谢谢。

bosn@outlook.com

**Comment by bigfengyu** [comment]
是服务器磁盘满了，已经解决了哈~

**Comment by lixingyangok** [comment]
感谢相关人员的回复，已解决了那太好了，谢谢你们
