### ISSUE TITLE
未匹配到任何接口

### ISSUE THREAD

**Issue by johnlee17** [thx/rap2-delos#61]
示例接口的地址都拿不到数据

**Comment by ranhan** [comment]
me too..

**Comment by SuperAL** [comment]
我也遇到过，我的原因是我前后端使用的代码不太匹配，后端代码使用了某tree分支的代码（为了执行 create-db 脚本才切换过去的）。
后来我后端代码切换为作者用ts重构前的代码，接口就可以正常显示了。

**Comment by Bosn** [comment]
no demo, no solve.
