### ISSUE TITLE
建议docker镜像打上版本号

### ISSUE THREAD

**Issue by yanunon** [thx/rap2-delos#610]
前段时间以docker形式部署了一套rap，镜像指向的是latest，今天重启了服务发现一些异常，排查后发现原因是远端镜像已经更新了，并且对数据库表的新增了字段，然而我们的db还未同步更新表结构。

希望每次发布版本，都打一个版本号tag，同时docker镜像也同步该tag生成一个镜像。这样使用者部署时，可以锁定到某个稳定版本。

**Comment by Bosn** [comment]
谢谢您的反馈
