### ISSUE TITLE
全局错误码

### ISSUE THREAD

**Issue by xiaolannuoyi** [thx/rap2-delos#613]
请问,全局的错误码 在哪设置,类似这种
<img width="751" alt="截屏2019-11-3015 46 35" src="https://user-images.githubusercontent.com/21079721/69897565-b288a100-1388-11ea-889b-38e3006457d9.png">
谢谢

**Comment by Bosn** [comment]
放在仓库描述里。现已支持Markdown（内测中，近期版本放出）
