### ISSUE TITLE
导出到Postman的URL无法访问

### ISSUE THREAD

**Issue by atorzhang** [thx/rap2-delos#616]
**BUG描述**
导出到Postman的URL粘贴在postman中无法访问到，后来发现只有登陆状态访问该地址可以访问，希望导出到postman的url可以去除登陆状态验证。

**复现步骤**
复制导出到postman的地址粘贴到postman中

**期望结果**
复制导出到postman的地址粘贴到postman中，postman可以获取到数据

**实际结果**
复制导出到postman的地址粘贴到postman中，postman无法获取到数据

**截图**
![image](https://user-images.githubusercontent.com/33924707/70026042-a6dfe900-15d9-11ea-8aac-6c8195d1697d.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by liujiabaoaa** [comment]
这个url地址好像是写到浏览器地址栏中的，保持jason文件，再把jason文件导入到postman

**Comment by w316149998** [comment]
老版本的可以通过url可以，更新到新版以后，貌似只能用postman的导入文件方式了

**Comment by Bosn** [comment]
测试了下，权限正常。请更新到最新版本，如果仍然有问题再reopen
