### ISSUE TITLE
rap2-dolores：Uncaught TypeError: Cannot read property 'itf' of undefined

### ISSUE THREAD

**Issue by nekoimi** [thx/rap2-delos#617]
**BUG描述**
TypeError: Cannot read property 'itf' of undefined

**复现步骤**

新建仓库 进入编辑页面：
http://192.168.0.100:3000/organization/repository/editor?id=3
刷新页面

**期望结果**
初次进入没有问题
刷新页面之后不显示东西

**实际结果**
页面空白  浏览器Console报错

**截图**
![20191208225307.png](https://i.loli.net/2019/12/08/Ol2iuoaTK1fRPUw.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
内网自建：CentOS 7
浏览器：Chrome （版本 78.0.3904.108（正式版本） （64 位））

**Comment by nekoimi** [comment]
代码： src/selectors/interface.ts:11

```javascript
   8 | 
   9 | const interfaceSelector = (state: RootState) => {
  10 |   const router = getRouter(state)
> 11 |   const itfId = +(router.location as any).params.itf
  12 |   if (itfId > 0) {
  13 |     for (const mod of state.repository.data.modules) {
  14 |       for (const itf of mod.interfaces) {
```

应该是空对象,,,, 不是很会写前端
目前临时处理了下
```javascript
  const params = (router.location as any).params
  if (params == null || !params.hasOwnProperty('itf')) {
    return null
  }
```

**Comment by eyis** [comment]
已定位问题，等待测试完成后上线

**Comment by wheelo** [comment]
同问这个问题

**Comment by dawsonyan186** [comment]
同问这个问题

**Comment by wereind** [comment]
同问这个问题，dock部署的，也是同样的问题

**Comment by lizehui995** [comment]
一样，dock部署的，有解决办法吗

**Comment by dawsonyan186** [comment]
参考上面改好代码，重新打包个私有镜像就可以了 @lizehui995

**Comment by dawsonyan186** [comment]
我参考上面改好代码，重新打包了个镜像
docker pull registry.cn-hangzhou.aliyuncs.com/kmteam/rap2-dolores:latest

**Comment by bigfengyu** [comment]
已经修复
