### ISSUE TITLE
默认值：第二次保存默认值会将所有默认清空

### ISSUE THREAD

**Issue by gitlwz** [thx/rap2-delos#618]
**BUG描述**
第二保存默认值会将所有默认清空

**复现步骤**
添加一个默认值->保存成功->刷新页面->再添加一个默认值,保存成功->再刷新页面->默认值全部被清空了

**期望结果**
希望默认值添加成功，并且全部存在

**实际结果**
全部被清空了

**截图**

**环境**
Google Chrome版本 78.0.3904.108（正式版本） （64 位）

**附加信息**

**Comment by gitlwz** [comment]
我发现是在刷新之后调用 http://rap2api.taobao.org/repository/defaultVal/update 这个接口报了 500 的错误，不刷新的话可以一直添加，只要一刷新 ，再添加的话就会报500

**Comment by Bosn** [comment]
已修复，今天晚些时间merged到主仓库。

是编辑时，id未排除导致唯一校验失败。删除成功，新增失败，导致该问题。
