### ISSUE TITLE
进行团队项目搜索时，报出如图异常

### ISSUE THREAD

**Issue by spencer-live** [thx/rap2-delos#62]
刚在本地搭起来的应用，未改过代码~
浏览器：Chorme 62.0.3202.89（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/15086629/34553527-ed00241a-f162-11e7-87d8-babeec4a4d5f.png)

**Comment by Bosn** [comment]
sorry，图片无法加载，请重新贴图。
