### ISSUE TITLE
请问忘记密码怎么处理？

### ISSUE THREAD

**Issue by javase** [thx/rap2-delos#620]
经常碰到忘记密码的同事，但是找不到重置密码的地方。

建议添加重置密码的功能。

**Comment by eyis** [comment]
相关功能正在测试，近期会上线，麻烦等待一下

**Comment by ilaotan** [comment]
啥时候上线啊，不想要kpi了吗？2020年了，在 #543 里已经说fixd， 我们还是看不到

**Comment by Bosn** [comment]
已经有了哈，最新版本，登录页右下角
