### ISSUE TITLE
浏览器刷新问题

### ISSUE THREAD

**Issue by theYllwRvrNo98** [thx/rap2-delos#624]
私有部署前端
http://xx.xx.xx/repository/editor?id=9&mod=110&itf=960
点击浏览器的刷新按钮，直接出现空白页

报错信息：

TypeError: undefined is not an object (evaluating 'Object(re.a)(e).location.params.itf')
（匿名函数） — RepositoryEditor.9a034b98.chunk.js:159:165
（匿名函数） — index.js:80
（匿名函数） — index.js:30
le — RepositoryEditor.9a034b98.chunk.js:164:2679
（匿名函数） — wrapMapToProps.js:50
（匿名函数） — selectorFactory.js:20
useMemo — react-dom.production.min.js:164:495
p — connectAdvanced.js:193
ha — react-dom.production.min.js:154:100
Qa — react-dom.production.min.js:174:276
Au — react-dom.production.min.js:230
Tu — react-dom.production.min.js:229:365
wu — react-dom.production.min.js:223:216
wu
（匿名函数） — react-dom.production.min.js:121:115
（匿名函数） — scheduler.production.min.js:18:437
Zi — react-dom.production.min.js:121
Qi — react-dom.production.min.js:120:496
Ou — react-dom.production.min.js:224:156
notify — Subscription.js:23
（匿名函数） — Subscription.js:65
（匿名函数） — Subscription.js:70
[native code]
m — redux.js:220
（匿名函数） — redux-saga-core.esm.js:1410
（匿名函数） — redux-saga-core.esm.js:472
p — redux-saga-core.esm.js:31
y — redux-saga-core.esm.js:87

**Comment by Eyeefly** [comment]
我这边也是出现同样的问题，浏览器刷新会出现空白。

**Comment by lizehui995** [comment]
我也是这个问题

**Comment by blackysy** [comment]
我也有这个问题，刷新浏览器当前页面就变成空白了！

**Comment by Bosn** [comment]
React配置的问题。。。
关键字：tryfiles

所有React App都有类似的“问题”，可以自行搜索研究下哦
