### ISSUE TITLE
Docker部署，初始化的user表密码是明文

### ISSUE THREAD

**Issue by ourforPP** [thx/rap2-delos#626]
**BUG描述**
Docker部署，初始化的user表密码是明文

**复现步骤**
使用docker-compose部署，生成的user表里password字段是明文

**期望结果**
password字段应该是双md5值

**实际结果**
password字段明文

**截图**
![image](https://user-images.githubusercontent.com/45449335/71514224-9ff67e80-28d8-11ea-8403-e12ff3262ddc.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
无影响，密码登陆会做两次MD5校验，这里所看到的明文，实际上永远无法通过界面登陆。也因此确保了安全性。
