### ISSUE TITLE
导入数组格式response时，mock服务返回会从json结构根部增加一个_root_，建议去掉

### ISSUE THREAD

**Issue by magohome** [thx/rap2-delos#627]
**BUG描述**
导入数组格式response时，mock服务返回会从json结构根部增加一个_root_，建议去掉

**复现步骤**
1.新建一个接口的mock，
2.导入 response返回的json结构 如
[{},{}]
3.保存 查看mock返回数据
**期望结果**
返回[{},{}]

**实际结果**
返回
{_root_:[{},{}]}

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by crystalztl** [comment]
有同样问题，希望解决

**Comment by Bosn** [comment]
这里要区分模板和数据。

模板：__root__ 用来表示虚拟根部（解决最外层结构的问题）
数据：会自动将__root__这一层拿掉


所以返回模板的接口，返回__root__是正常的。
返回数据的接口，或者通过浏览器端的插件去通过 Mock.mock将规则转换为数据时，会在这一层拿掉root

**Comment by crystalztl** [comment]
这里主要指的是数据层，由于没有使用Mock.mock，而是在移动端直接使用Mock API 进行JSON反序列化，在对于top-level array json的时候会有这个问题。

**Comment by Bosn** [comment]
规则层没办法去掉，原生Mock.mock不支持最外层为数组

**Comment by Bosn** [comment]
特殊情况需要自行处理，其实也很简单，可以源代码搜索__root__

**Comment by crystalztl** [comment]
> 特殊情况需要自行处理，其实也很简单，可以源代码搜索__root__

好的，谢谢回复
