### ISSUE TITLE
mock数据设置Array长度为1时返回的是不是array

### ISSUE THREAD

**Issue by wakaryry** [thx/rap2-delos#629]
![image](https://user-images.githubusercontent.com/7576559/72120876-5310ae80-3394-11ea-9c85-a539862a7d4b.png)

**Comment by Bosn** [comment]
截图不完整

**Comment by Bosn** [comment]
复现了，谢谢，修复中

**Comment by Bosn** [comment]
```javascript
Mock.mock({"arr|1": [{"test": 1}]})
```

经排查为Mock.js工具的BUG，已转交。

**Comment by Bosn** [comment]
转移至：https://github.com/thx/Mock/issues/1

**Comment by wakaryry** [comment]
好的
