### ISSUE TITLE
修改请求时选 Body Params ->raw 类型无效,post请求的内容不支持 json 格式

### ISSUE THREAD

**Issue by gggfreak** [thx/rap2-delos#630]
**BUG描述**
post类型的接口，修改请求时 Body Params ->raw 类型无效

post请求的内容不支持 json 格式。

**复现步骤**
编辑指定接口，在请求参数这边选 Body Params ->raw
然后填入请求参数属性内容如下：
{
  "username": "",
  "password": ""
}
其中username 必选 
保存后再重新编辑，Body Params 原来选了 raw 选项的消失了。
通过curl 请求
curl  "http://rap2api.taobao.org/app/mock/242129/user/login" -d '{"username": "aaa", "password": "bbb"}'
返回如下错误 ：
{"isOk":false,"errMsg":"必选参数username未传值。 Required parameter username has no value."}

但换成 form-data的方式请求返回正常
curl  "http://rap2api.taobao.org/app/mock/242129/user/login" -d 'username=aaa&password=bbb"'
{
  "code": 0,
  "msg": "ok",
  "data": {}
}

**期望结果**
通过curl 请求
curl  "http://rap2api.taobao.org/app/mock/242129/user/login" -d '{"username": "aaa", "password": "bbb"}'
返回正常

**实际结果**
{"isOk":false,"errMsg":"必选参数username未传值。 Required parameter username has no value."}

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by w316149998** [comment]
昨天遇到这个问题跟我们前端开发研究了下（Body Params的类型都没存数据库，当然无效啦），简易的修改方案如下：

1 修改数据表interfaces，新增varchar类型的字段bodyOption，用于存储request的参数类型

2 修改delos\src\routes\repository.ts 954 行，新增如下代码

  if (summary.bodyOption) {
    if(summary.bodyOption === 'FORM_URLENCODED'){
      itf.bodyOption = 'urlencoded'
    }else if(summary.bodyOption === 'FORM_DATA'){
      itf.bodyOption = 'formdata'
    }else if(summary.bodyOption === 'RAW'){
      itf.bodyOption = 'raw'
    }else if(summary.bodyOption === 'BINARY'){
      itf.bodyOption = 'binary'
    }
  }

3 修改delos\src\models\bo\interface.ts 74行，新增如下代码

  @Column(DataType.STRING(256))
  bodyOption: string

4 修改delos\src\service\export\postman.ts 55行，修改代码

  body: getBody(requestParams),
  body: getBody(requestParams,itf.bodyOption),

  第76行，修改代码

  function getBody(pList: Property[]) {
    return {
      "mode": "formdata" as "formdata",
      "formdata": pList.filter(x => x.pos === REQUEST_PARAMS_TYPE.BODY_PARAMS)
        .map(x => ({ key: x.name, value: x.value, description: x.description, type: "text" as "text"})),
    }
  }

function getBody(pList: Property[], dataParam) {
  if(!dataParam){
	dataParam = "formdata"	
  }
  var returnData = {}
  returnData['mode'] = dataParam
  returnData[dataParam] = pList.filter(x => x.pos === REQUEST_PARAMS_TYPE.BODY_PARAMS)
    .map(x => ({ key: x.name, value: x.value, description: x.description, type: "text" as "text"}))
  return returnData
}

**Comment by Bosn** [comment]
暂时不支持header设置为强制校验
