### ISSUE TITLE
响应内容 初始值 设置前缀 0x开头，保存的时候，页面会卡，甚至奔溃

### ISSUE THREAD

**Issue by 346359827** [thx/rap2-delos#631]
**BUG描述**

rap2-dolores：响应内容 初始值 设置前缀 0x开头，保存的时候，前端会卡，甚至奔溃
**复现步骤**
响应体里 字段设置初始值 0x开头，保存奔溃

**期望结果**
正常保存

**实际结果**
页面卡死

**截图**
<img width="1110" alt="1111" src="https://user-images.githubusercontent.com/8197906/72136767-7d7a6000-33c4-11ea-9cca-d476a4ddd397.png">
<img width="343" alt="2222" src="https://user-images.githubusercontent.com/8197906/72136771-7f442380-33c4-11ea-98ba-c66551d6bfad.png">

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by 346359827** [comment]
问题存在挺久了。

**Comment by zomaco** [comment]
遇到同样BUG

**BUG描述**
当某个接口的请求参数/响应内容中，有某个参数的“初始值”填写“0x00”时，点击保存，页面会卡住很长时间，失去响应。

**复现步骤**
1. 选择任意接口，新增一个请求参数或响应内容，名称任意填写，类型选String，初始值填写0x00；
2. 点击保存。BUG现象出现：页面失去响应，卡住很长时间（几十秒）后成功保存；
3. 选择切换到其他接口，再重新选择刚刚编辑的接口，BUG现象也可以出现：页面失去响应，卡住很长时间（几十秒）后恢复。

**环境**
* 自建服务器，系统版本 4.17.1-1.el7.elrepo.x86_64
* 供浏览器版本Firefox 73.0.1
* rap-server-delos 2.8.0

**Comment by Bosn** [comment]
最新版应该已经修复，请用最新版尝试，如有问题再reopen
