### ISSUE TITLE
docker构建，查看测试数据delos缺失test目录及libs目录

### ISSUE THREAD

**Issue by ccmiaomiao** [thx/rap2-delos#634]
**BUG描述**
可以正确读取接口及操作，点击测试，弹出新界面，路径错误404

**复现步骤**
如题

**期望结果**
正确加载mock测试数据

**实际结果**
未找到test及libs下相关静态资源

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by 1036956372** [comment]
同问

**Comment by llf-970310** [comment]
一样的问题，也是docker构建，centos 7.5

**Comment by twodogegg** [comment]
同问。
