### ISSUE TITLE
rap2对于接口分类模块的设计震撼到我了

### ISSUE THREAD

**Issue by ludingding228** [thx/rap2-delos#639]
听说rap2比rap在性能上提升了很多，所以我兴冲冲的费了九牛二虎之力，将接口文档从rap迁移至rap2。由于rap2没有page层级了，所以我将之前的page转换成了module，然后就成了这个样子。。
![image](https://user-images.githubusercontent.com/16095656/75412543-bfa03680-595d-11ea-8ffb-65201dbb0c61.png)

但是如果我不把原page转换成module，左侧接口列表就会极其长，不方便一目了然的看到接口分类。
所以是不是可以考虑在左侧接口列表增加类似原rap中可折叠的page层级？

**Comment by ludingding228** [comment]
在新老数据迁移的过程中发现数据库表是这样的。。小小的db有如此多的冗余字段，不知其中是否有啥玄妙：
表properties：外键有1. interfaceId，2. moduleId，3. repositoryId
表interfaces：外键有1. moduleId，2. repositoryId
表modules：外键有1. repositoryId

**Comment by Bosn** [comment]
RAP1基本是我一个人写的，当时还在上学。。。考虑的不周全。整个项目一个大JSON，每次小修改都会把整个项目做一次JSON序列化、反序列化。后续出现了大量的性能问题和优化瓶颈，所以才重做了RAP2。

对于接口特别多的情况可以考虑用协同仓库。

比如项目B，是在A的基础上进行，在A到 协同仓库增加B，就可以以原型链的方式管理接口，同时也不用把所有项目混在一起。

同时现在也已经支持模块和接口的移动功能。
