### ISSUE TITLE
导出docx时报错，cannot read property 'data' of null at app.use(/home/rap2/rap2-delos-master/dist/scripts/app.js:38:50)

### ISSUE THREAD

**Issue by quguozhe** [thx/rap2-delos#641]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
复现步骤不明确
