### ISSUE TITLE
刷新接口文档无法显示

### ISSUE THREAD

**Issue by lackoxygen** [thx/rap2-delos#642]
**BUG描述**
浏览器刷新接口文档无法显示

**复现步骤**
去到接口详情页面刷新尝试，

**期望结果**
正常渲染

**实际结果**

白屏
**截图**
![image](https://user-images.githubusercontent.com/44201583/75967264-88ee9100-5f06-11ea-9541-d8093a380de7.png)
![image](https://user-images.githubusercontent.com/44201583/75967290-90ae3580-5f06-11ea-8d39-eafcabf90128.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
版本 80.0.3987.122（正式版本） （64 位）

**Comment by git-cleverly** [comment]
你好，请问你这个问题解决了吗？
我用的是docker一键部署，接口刷新也出现这个问题。

**Comment by lackoxygen** [comment]
没有，因为不影响使用，所以没有去修改报错源

**Comment by bigfengyu** [comment]
已经解决，请更新~

**Comment by amirfish** [comment]
已升级到当前最新版，问题依旧。
