### ISSUE TITLE
mac打开报500

### ISSUE THREAD

**Issue by tonyjt** [thx/rap2-delos#645]
**BUG描述**
接口报500错误

**复现步骤**
用mac的safari/chrome打开，登录后报500错误

**期望结果**
正常打开

**实际结果**
server error 500

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by theo1201** [comment]
问题如上

**Comment by LYlanfeng** [comment]
同样，今天刚部署，用的docker方式部署的，出了/account/info没问题。其他500，注册，登录不了

**Comment by wsz7777** [comment]
docker部署的，/account/info 500 其他不知道。。。

**Comment by yuyeqing** [comment]
> 同样，今天刚部署，用的docker方式部署的，除了/account/info没问题。其他500，注册，登录不了

请问最后怎么解决，也出现同样的问题？
