### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by LYlanfeng** [thx/rap2-delos#646]
**BUG描述**
1. 配置body Params raw选项，参数丢失，配置无效
2. 仓库配置团队，参数丢失，配置无效

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
类似问题已提交处理中
