### ISSUE TITLE
swagger导入时递归处理有问题

### ISSUE THREAD

**Issue by zhoffice** [thx/rap2-delos#648]
**BUG描述**
如果有一个类的成员变量类型是它自己，导入swagger的时候就出现了无限递归的情况

**复现步骤**
定义一个带有自身类型成员变量的类，如
class A{
 A a;
}
生成swagger.json，导入
**期望结果**
能够正确识别递归

**实际结果**
卡死

**Comment by wenlincheng** [comment]
遇到同样的问题，swagger.json无法导入

**Comment by Bosn** [comment]
麻烦提供一下可以复现Bug的JSON后再reopen，感谢亲~~~
