### ISSUE TITLE
官方Docker镜像能否加上对应的版本tag，而不只是latest

### ISSUE THREAD

**Issue by nisiyong** [thx/rap2-delos#649]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

之前已经在虚拟机部署过rap2，现在准备直接用Docker镜像部署，但是在DockerHub上发现镜像没有对应版本的tag。

**您是否有建议的实现方案**

请问后续官方镜像能否按固定的版本发布，有专门的镜像标签。以及每个版本升级rap2要变更的哪些步骤，不然旧版升级实在有点难度

**其它帮助我们理解您需求的描述、截图**

![image](https://user-images.githubusercontent.com/8198862/77659249-c8af1280-6fb2-11ea-940f-996928c9b131.png)

**Comment by Bosn** [comment]
有类似问题反馈，正在解决

**Comment by nisiyong** [comment]
怎么还没解决就close issue了？😳

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/issues/610
你可以follow这个issue，重复了

**Comment by nisiyong** [comment]
嗯，说明下关联上就行
