### ISSUE TITLE
请问把接口类型放到url里面是出于什么考虑？

### ISSUE THREAD

**Issue by chj-damon** [thx/rap2-delos#65]
现在的rap2在实际使用时发现，最后生成的访问链接里面带上了接口的类型，如GET/POST/DELETE等。
比如我的接口地址为test/add，接口类型为GET，那么最后得到的访问地址为：http://ip:port/app/mock/33/GET/test/add。
请问是出于什么考虑把接口类型放到接口地址里面呢？
如果我想去掉这个类型，有什么办法吗？

**Comment by occultskyrong** [comment]
web端使用的时候（模拟接口访问），你所有的请求都是GET的。。。
因为都是点击链接进行的跳转。。所以没法模拟POST。。
只能将请求方式放到url。

### 个人理解。。

**Comment by Bosn** [comment]
我非常不赞同。。原来我做RAP1的时候，其实只要该根路径就可以实现无缝的mock / prod / dev环境的切换。这个问题我会在最近的版本中修复。

**Comment by alvarto** [comment]
之前是为了支持 Restful 才这样做的。后续可能会考虑将这个功能置入项目配置中。

**Comment by alvarto** [comment]
Ref: https://github.com/thx/rap2-dolores/issues/15

**Comment by alvarto** [comment]
改动方式：

短期：

同时支持`http://ip:port/app/mock/33/GET/test/add`和`http://ip:port/app/mock/33/test/add`。

注意：

会导致corner case，比如一个接口有POST`/api/apple`和 GET`/api/apple`，如果两种匹配模式都支持，在非Restful 项目里可能导致返回用户不期望的值。

***

长期：

增加一个是否为 Restful 的配置，项目级别，默认为非 Restful。

Restful 的表现：

- Mock 匹配规则加入不可忽略的 method
- 接口重复判定基于 path + method

非 Restful 的表现：

- Mock 匹配规则加入可忽略的 method
- 接口重复判定基于 path

**Comment by chj-damon** [comment]
@alvarto 谢谢您的回复！

**Comment by Bosn** [comment]
该问题 @alvarto 已修复，请参考上面的 commit 3746970
