### ISSUE TITLE
关于“检测到重复接口”的问题

### ISSUE THREAD

**Issue by zhangzhiming3767** [thx/rap2-delos#650]
因为某些原因，项目里写了大量重复接口，然后rap2页面提示检测到重复接口并展示出来了，足足展示了好几页，还没办法关闭或隐藏或收起提醒，导致每次编辑接口都需要鼠标滑动好久，体验很差，建议出一个关闭或隐藏或收起提醒的功能

![image](https://user-images.githubusercontent.com/47933470/77870937-528e0280-7275-11ea-851c-e7a69833f78c.png)

**Comment by bigfengyu** [comment]
感谢建议，已经改成可以折叠了~
