### ISSUE TITLE
ERROR: Cannot copy to clipboard: write EPIPE

### ISSUE THREAD

**Issue by Randy-xuefm** [thx/rap2-delos#651]
输入命令:[rap2-dolores-master]$ serve -s ./build -p 8090
报错信息:ERROR: Cannot copy to clipboard: write EPIPE
如何解决?
[wasadmin@E193051 rap2-dolores-master]$ serve -s ./build -p 8090
ERROR: Cannot copy to clipboard: write EPIPE

   ┌─────────────────────────────────────────────────────┐
   │                                                     │
   │   Serving!                                          │
   │                                                     │
   │   - Local:            http://localhost:46014        │
   │   - On Your Network:  http://192.168.193.51:46014   │
   │                                                     │
   │   This port was picked because 8090 is in use.      │
   │                                                     │

**Comment by Bosn** [comment]
环境配置问题请咨询对应工具的社区哦，部署问题也可以加群和部署成功的朋友互相交流。

**Comment by chase-si** [comment]
try `serve -s ./build -p 8090 -n`
