### ISSUE TITLE
能不能支持自定义类型

### ISSUE THREAD

**Issue by narci2010** [thx/rap2-delos#652]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
这个issue看到被close掉了，但随着软件工程化发展，这个需求越来越重要，js都要被ts取代了
建议rap2团队支持下这个功能。
参数除了系统内的string,object...比如能否自己定义一个User、Teacher之类的作为参数类型。
这对代码自动生成等非常重要。
现在开发团队，CRUD的工作本该由系统自动生成。
工程师的时间应该在业务逻辑的解决上。

**您是否有建议的实现方案**
无

**其它帮助我们理解您需求的描述、截图**
无

**Comment by narci2010** [comment]
http://editor.swagger.io/
swaggereditor是支持自定义的，但是增加api不是可视化的，这提高了编写api的门口
rap2的优势是可视化编辑api，但不支持自定义类型

**Comment by narci2010** [comment]
而且从配套来看，目前rap2支持导入swagger格式，但不支持导出swagger格式api或openapi格式文件，可惜。这个可以参考下大搜车的easy-mock项目。可惜他们实力不够，现在更新很慢。

**Comment by narci2010** [comment]
https://github.com/easy-mock/easy-mock

**Comment by Bosn** [comment]
谢谢亲的反馈，其实增加自定义类型是简单的，但是配套的所有mock、校验、case工具是比较复杂的，这块儿我们在未来版本迭代里会去考虑，同时也请给一些实际场景。目前我们暂时还没有遇到。
