### ISSUE TITLE
自定义 Redis auth 无效

### ISSUE THREAD

**Issue by gzymomo** [thx/rap2-delos#653]
**redis 配置已修改为如下**：

 redis: {
    host: process.env.REDIS_URL || 'localhost',
    port: (process.env.REDIS_PORT && parseInt(process.env.REDIS_PORT)) || 6379,
    password: process.env.REDIS_PWD,
  },

**重新 run build， 环境变量已配置，无法正常启动，错误如下**：
ReplyError: Ready check failed: NOAUTH Authentication required. (uncaughtException throw 1 times on pid:2146)
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'INFO',
  code: 'NOAUTH'
}
**官方有个配置说明** 
f set, client will run Redis auth command on connect. Alias auth_pass Note Node Redis < 2.5 must use auth_pass

是配置auth_pass 还是 password

**Comment by gzymomo** [comment]
配置 password 已成功

**Comment by kpeng2016** [comment]
请问

> 配置 password 已成功

请问你是怎么配置的，我这里也没成功呢？谢谢！

**Comment by gzymomo** [comment]
redis: {
    host: process.env.REDIS_URL || 'localhost',
    port: (process.env.REDIS_PORT && parseInt(process.env.REDIS_PORT)) || 6379,
    password: process.env.REDIS_PWD || ''
  },

**Comment by gzymomo** [comment]
> 请问
> 
> > 配置 password 已成功
> 
> 请问你是怎么配置的，我这里也没成功呢？谢谢！

redis: {
host: process.env.REDIS_URL || 'localhost',
port: (process.env.REDIS_PORT && parseInt(process.env.REDIS_PORT)) || 6379,
password: process.env.REDIS_PWD || ''
},
