### ISSUE TITLE
新建接口后，左边的列表不会自动选中刚创建的接口

### ISSUE THREAD

**Issue by showmethecode9527** [thx/rap2-delos#655]
**BUG描述**
新建接口成功后，不能自动选中新建的接口，容易导致误操作。

**复现步骤**
点击新建接口，出现新建接口弹窗，先写接口信息，提交，新建接口成功，此时新创建的接口出现在左边接口列表的下方，此时选中的接口不会自动切换到刚刚创建的接口。

**期望结果**
新接口创建成功后，自动选中刚刚创建的接口。

**实际结果**
任然是之前选中的接口。如果是刚刚切换的模块，则选中的是接口列表的第一个接口。

**截图**
无

**环境**
使用的是线上版本[http://rap2.taobao.org/](http://rap2.taobao.org/)

**附加信息**
无

**Comment by Bosn** [comment]
fixed, code will be commited later today.
