### ISSUE TITLE
mysql 5.1,delos查出来中文乱码

### ISSUE THREAD

**Issue by InnovationTeamWiki** [thx/rap2-delos#656]
**BUG描述**
其实是咨询，mysql 5.1版本预置了一些接口，然后delos为比较新的版本，但接口查出来都是中文乱码

**复现步骤**
db预置一些接口properties。然后启动最近的release delos生产包。
![image](https://user-images.githubusercontent.com/45226860/79184431-af2d1800-7e46-11ea-9980-1965b18425ae.png)

**环境**
* 自建服务器，delos为最近拉的代码，然后手动部署
RedHat4.4.7
mysql 5.1.73比较老。

**Comment by Bosn** [comment]
MySQL字符集是不是UTF8呢？
字符集属于环境配置问题，建议加群里和其他配置成功的开源网友一起讨论哦
