### ISSUE TITLE
rap2没有rap好用

### ISSUE THREAD

**Issue by yankeys** [thx/rap2-delos#658]
题目包含了我想说的内容

主要槽点有以下两个：
1、团队成员编辑查看权限似乎是没有？
2、界面内容太多且单一色调，没有rap简洁醒目和一目了然

**Comment by Bosn** [comment]
1、目前有简单的权限分配的。分私有仓库、公开仓库。私有团队，公开图案丢。
2、新版本已经有自定义皮肤了，样式也做了整体的优化。我们会在近期放出敬请期待。

**Comment by Bosn** [comment]
RAP1是我最早写的版本，过了太久了，J2ee那套工具不太适合前端同学维护，所以我们团队重写了RAP2。
也欢迎大家多多提PR共同完善开源工具哦

**Comment by robertzhangwenjie** [comment]
目前的权限问题很大，只要你能够看到仓库就可以编辑仓库中的信息。团队成员可以管理所有团队内的仓库。基本只能在小团队使用，无法用到企业基本。还是需要把权限系统做完善
