### ISSUE TITLE
访问38080端口问题

### ISSUE THREAD

**Issue by liup1211** [thx/rap2-delos#664]
**BUG描述**
使用docker，按git步骤部署在一台ip为200的PC上，访问前端是正常的，访问38080的后端，效果看最后一张图

**复现步骤**

**期望结果**

**实际结果**

**截图**
![图片](https://user-images.githubusercontent.com/13359281/81244882-2751bc80-9046-11ea-8eb0-6452131dd571.png)
![图片](https://user-images.githubusercontent.com/13359281/81245066-ac3cd600-9046-11ea-8749-82ef8d1664c4.png)
![图片](https://user-images.githubusercontent.com/13359281/81245122-caa2d180-9046-11ea-8c56-2aa219bd4844.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
docker配置及使用问题。。。不在本社区讨论范围内哈。建议咨询docker服务相关的社区。

**Comment by Bosn** [comment]
或者加钉钉群和群友共同交流哦~~~
