### ISSUE TITLE
contentype设置form-data ，raw保存后效果一样

### ISSUE THREAD

**Issue by mailzf** [thx/rap2-delos#665]
**BUG描述**
请求body参数，设置form-data ，raw保存后效果一样，看不出来区别，
再次编辑还是未选中状态。
请求参数类型也不能选择文件类型
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by treadpit** [comment]
这个是因为 `rap2-dolores` 前台系统在编辑时没有使用接口返回的类型。如果是自建部署，可暂时使用 [这个仓库](https://github.com/treadpit/rap2-dolores)

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/issues/668

合并问题并处理中，请follow 668
