### ISSUE TITLE
默认的管理员帐号密码是多少？

### ISSUE THREAD

**Issue by Lysuwel** [thx/rap2-delos#666]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by CatSirSir** [comment]
自己注册一个就可以了

**Comment by Bosn** [comment]
目前并没有管理员后台功能哈，sorry~~~
RAP1我也没做。。。⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
