### ISSUE TITLE
docker部署 能否修改前端访问后端的端口号，能否讲38080改成80

### ISSUE THREAD

**Issue by zmmDinAc** [thx/rap2-delos#667]
docker部署 能否像手动部署那样修改前端访问后端的端口号，能否讲38080改成80，然后url支持可以扩展增加

**Comment by ganl** [comment]
虽然docker-compose.yml留了配置项：
https://github.com/ganl/rap2-delos/blob/b761f9e4681a75e2c60df5d21b2f7e0fd58778c1/docker-compose.yml#L20

      - 38080:38080

https://github.com/ganl/rap2-delos/blob/b761f9e4681a75e2c60df5d21b2f7e0fd58778c1/docker-compose.yml#L22

      - SERVE_PORT=38080

但官方镜像`config.prod.ts`写死了端口，https://github.com/thx/rap2-dolores/blob/master/docker/config.prod.ts：
```
const config: IConfig = {
  serve: `http://${window.location.hostname}:38080`,
  keys: ['some secret hurr'],
  session: {
    key: 'koa:sess',
  },
}

export default config
```
可以基于官方[dockerfile](https://hub.docker.com/r/rapteam/rap2-dolores/dockerfile)生成自己的镜像，修改示例：
https://github.com/ganl/rap2-docker/blob/d33cb69c987166b7a342c7269ecfd0ea199ed693/dolores/Dockerfile#L25

修改可参考：https://github.com/ganl/rap2-docker

**Comment by Bosn** [comment]
感谢楼上同学的回复
