### ISSUE TITLE
【Bug】保存的请求参数类型失效，刷新后被重置

### ISSUE THREAD

**Issue by TommyLemon** [thx/rap2-delos#668]
**BUG描述**
如图，原因是接口没有返回请求参数类型相关字段 
![image](https://user-images.githubusercontent.com/5738175/83333290-60422180-a2d2-11ea-8561-24f5c881d523.png)

![image](https://user-images.githubusercontent.com/5738175/83333160-d5612700-a2d1-11ea-886e-940bef3cfeea.png)

**复现步骤**
选择类型为 Body Params/form-data (其它的类型都试过了，也是保存失效)

**期望结果**
下次刷新后能恢复上次保存的请求参数类型

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/5738175/83333290-60422180-a2d2-11ea-8561-24f5c881d523.png)
![image](https://user-images.githubusercontent.com/5738175/83333160-d5612700-a2d1-11ea-886e-940bef3cfeea.png)

**环境**
官网
http://rap2.taobao.org/repository/editor?id=1243&itf=1596193
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
这块儿。。。没开发完。今天补上。sorry😂😂😂

**Comment by Bosn** [comment]
已修复，稍后更新代码到仓库。
