### ISSUE TITLE
sso接口

### ISSUE THREAD

**Issue by xiangjian** [thx/rap2-delos#669]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
能否提供sso接口，团队内部可以对接已有的账户环境

**您是否有建议的实现方案**
提供单点登录的接口

**其它帮助我们理解您需求的描述、截图**
对接团队已有的账号系统

**Comment by Bosn** [comment]
SSO需要自行开发，亲。我们公司内网也有SSO的RAP版本。
