### ISSUE TITLE
新版本build之后，运行报错

### ISSUE THREAD

**Issue by webkong** [thx/rap2-delos#67]
<img width="738" alt="wx20180110-185018 2x" src="https://user-images.githubusercontent.com/10398591/34769512-f8594e88-f638-11e7-9da5-df3bdb065108.png">

**Comment by WeekiXu** [comment]
我也是。 npm run dev 没问题，但是不能 nohup 运行

**Comment by webkong** [comment]
我的run dev 都不好使，我只能回滚到了之前 17年11月7号的提交。

**Comment by ranhan** [comment]
me too ...

**Comment by Bosn** [comment]
```bash
nohup npm run dev &
```

这样就可以nohup了啊，你npm run dev都可以，nohup当然也可以，除非你写错了。
另外推荐使用pm2来管理
```bash
pm2 start [command]
```

后续我会考虑把pm2加入到scripts中作为默认的配置方式。
