### ISSUE TITLE
接口中定义headers结果为参数

### ISSUE THREAD

**Issue by huangyingjun1989** [thx/rap2-delos#672]
**BUG描述**
在接口中定义headers后，结果显示是参数而不是header。
例如：我在/api/v1/usrs这个接口中定义了header X-Auth-Token并设置该项为选。用CURL测试
curl   -H 'X-Auth-Token: 3e4f0531baad4b80a26b74cf5576c839' http://172.16.68.75:38080/app/mock/16/api/v1/users

结果返回：
{"isOk":false,"errMsg":"必选参数X-Auth-Token未传值。 Required parameter X-Auth-Token has no value."}

**复现步骤**
编辑某个接口-->选择headers-->添加一个header并设为必选

**期望结果**
请求时应该是对headers做检查.而不是参数

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/25094006/84113333-f60d4780-aa5c-11ea-8e3a-16a11a94d5d3.png)
![image](https://user-images.githubusercontent.com/25094006/84113365-07eeea80-aa5d-11ea-9786-eb689fcb1873.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
目前最新版，必选header参数若没有传，将会提供一个错误header
考虑到我们内网的实际使用，我们没有把header做成强校验，如果需要强校验，可以考虑监听RAP warning的方式实现。


![image](https://user-images.githubusercontent.com/1892986/88021955-fa02ae00-cb60-11ea-82c6-66fc402c8e1c.png)
