### ISSUE TITLE
rap2接口文档导入到postman，url path前面多出一个冒号

### ISSUE THREAD

**Issue by Gorginee** [thx/rap2-delos#673]
![image](https://user-images.githubusercontent.com/43122596/84975330-ad8a1400-b157-11ea-91c3-984f2b320999.png)

**Comment by Bosn** [comment]
fixed, 代码今日晚些时间提交

**Comment by Gorginee** [comment]
更新了没 大佬 我到官网导出示例接口试了下 还是会存在这个现象
