### ISSUE TITLE
希望支持postman导入

### ISSUE THREAD

**Issue by ghostsf** [thx/rap2-delos#674]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
postman导入到RAP吗？目前我们暂时没有这个计划，欢迎亲提PR。

同时，建议可以使用Postman => JSON => RAP2来导入结构部分。
