### ISSUE TITLE
请求响应体可以支持设置模板吗？

### ISSUE THREAD

**Issue by linxiaowu66** [thx/rap2-delos#676]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
比如我的项目的所有请求返回的数据结构是这样的：
```
{
  data： xxx,
 status: true,
message: xxx,
errorCode: xxx
}
```

然后可以在哪里设置这么一个模板，然后我编辑响应体的时候只需要编辑data字段就行了

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
非常感谢亲的反馈，我们有这种功能了，目前还在内网测试阶段。会在后续版本迭代中放出
![image](https://user-images.githubusercontent.com/1892986/87902435-28628980-ca8c-11ea-86ea-c96baee89769.png)

**Comment by xmsz** [comment]
> 非常感谢亲的反馈，我们有这种功能了，目前还在内网测试阶段。会在后续版本迭代中放出
> ![image](https://user-images.githubusercontent.com/1892986/87902435-28628980-ca8c-11ea-86ea-c96baee89769.png)

还没发布吗
