### ISSUE TITLE
接口地址问题

### ISSUE THREAD

**Issue by wdevid** [thx/rap2-delos#677]
**BUG描述**
新建两个接口，地址分别为test/qwe和test/asd
访问这两个接口时候会出现 {isok  false ,errmsg 未匹配到任何接口}提示

**环境**
* 自建，操作系统版本Red Hat 4.85－11

**Comment by wdevid** [comment]
类型都为post 状态码200

**Comment by Bosn** [comment]
亲用POST去请求试试

新建的POST如果用GET去请求可能会发生这个问题
