### ISSUE TITLE
使用npm run build报错

### ISSUE THREAD

**Issue by 244180** [thx/rap2-delos#678]
./src/components/editor/MoveModuleForm.tsx
  Line 81:6:  React Hook useEffect has missing dependencies: 'dispatch' and 'repositories.length'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/editor/MoveInterfaceForm.tsx
  Line 83:6:  React Hook useEffect has missing dependencies: 'dispatch' and 'repositories.length'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

./src/components/repository/RepositoryForm.tsx
  Line 91:6:  React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by Bosn** [comment]
这是warning不是错误哈，目前在预发检查上，可能存在一些警告，这个我们会关注会在新的版本中尽快修复，但是不影响系统的使用。感谢您的反馈
