### ISSUE TITLE
编辑接口信息，配置新字段类型为正则后，填写特定正则，引发页面白屏问题

### ISSUE THREAD

**Issue by Arayui** [thx/rap2-delos#681]
**BUG描述**
如题，在编辑接口请求信息的时候，新建字段并标注生成规则为正则，而后填写特定正则值会引发屏幕白屏。

**复现步骤**
1、打开任意接口进行编辑
2、新增一条请求参数信息，名称随意，选择类型为正则
3、在该条的预设值中输入//
4、将光标移至//中间并输入[]，形成/[]/
5、键入]瞬间页面白屏，所有内容无显示

**期望结果**
1、页面显示正确
2、添加功能正常
3、可以正常编辑

**实际结果**
1、界面全白，所有模块组件不可见，内容丢失

**截图**

**环境**
QQ浏览器（Chromium极速）环境

**附加信息**
建议当焦点从输入框移除后再触发生成预览数据。

**Comment by Arayui** [comment]
附控制台错误信息：
TypeError: Cannot set property 'response' of undefined
Uncaught TypeError: Cannot set property 'response' of undefined

查看源码发现#root下无任何子元素，为空div。

**Comment by Bosn** [comment]
fixed, code will commit today later.
