### ISSUE TITLE
英文版

### ISSUE THREAD

**Issue by crystalztl** [thx/rap2-delos#682]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
国际化团队试图推广该工具，需要英文版

**Comment by Bosn** [comment]
亲，人力原因，暂时没有支持国际化的打算哈，不过RAP是开源的，您可以考虑自行实现相关功能嗷~~~

**Comment by crystalztl** [comment]
> 亲，人力原因，暂时没有支持国际化的打算哈，不过RAP是开源的，您可以考虑自行实现相关功能嗷~~~

谢谢回复，我们有计划针对这个问题提个PR
