### ISSUE TITLE
从swagger json导入数据，导入失败，无法解析json

### ISSUE THREAD

**Issue by 66xc1** [thx/rap2-delos#684]
**BUG描述**
从swagger json导入数据，导入失败，无法解析json

**复现步骤**
下面是json内容
{"swagger":"2.0","info":{"description":"API文档","version":"1.0","title":"健康管理平台API","contact":{"name":"solo","email":"776735626@qq.com"}},"host":"192.168.201.100:8080","basePath":"/","tags":[{"name":"登录","description":"Auth Controller"}],"paths":{"/auth/getCaptcha/{randomId}":{"get":{"tags":["登录"],"summary":"获取验证码","operationId":"captchaUsingGET","produces":["image/jpeg"],"parameters":[{"name":"randomId","in":"path","description":"随机Id","required":true,"type":"string"}],"responses":{"200":{"description":"OK"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false,"x-order":"1"}},"/auth/getPublicKey":{"post":{"tags":["登录"],"summary":"获取公钥","operationId":"getPublicKsyUsingPOST","consumes":["application/json"],"produces":["*/*"],"parameters":[{"in":"body","name":"getPublicKsyDto","required":true,"schema":{"$ref":"#/definitions/GetPublicKsyDto","originalRef":"GetPublicKsyDto"}}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Result«PublicKsyVo»","originalRef":"Result«PublicKsyVo»"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false,"x-order":"2"}},"/auth/logout":{"post":{"tags":["登录"],"summary":"用户退出登录","operationId":"logoutUsingPOST","consumes":["application/json"],"produces":["*/*"],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/Result«string»","originalRef":"Result«string»"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}},"deprecated":false,"x-order":"2147483647"}}},"definitions":{"GetPublicKsyDto":{"type":"object","required":["userName"],"properties":{"userName":{"type":"string","description":"用户名"}},"title":"GetPublicKsyDto"},"PublicKsyVo":{"type":"object","properties":{"exponent":{"type":"string"},"module":{"type":"string"}},"title":"PublicKsyVo"},"Result«PublicKsyVo»":{"type":"object","properties":{"code":{"type":"string"},"data":{"$ref":"#/definitions/PublicKsyVo","originalRef":"PublicKsyVo"},"msg":{"type":"string"},"state":{"type":"boolean"}},"title":"Result«PublicKsyVo»"},"Result«string»":{"type":"object","properties":{"code":{"type":"string"},"data":{"type":"string"},"msg":{"type":"string"},"state":{"type":"boolean"}},"title":"Result«string»"}}}

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
自建服务器 cnetos 7
* 如果是前端错误，请提供浏览器版本

* 其它可能帮助我们排查问题的环境信息

**附加信息**

日志报错如下：
TypeError: Cannot read property '$ref' of undefined
    at Function.swaggerToModelRespnse (/app/service/migrate.js:481:21)
    at Function.importRepoFromSwaggerProjectData (/app/service/migrate.js:626:49)
    at async Function.importRepoFromSwaggerDocUrl (/app/service/migrate.js:878:33)
    at async /app/routes/repository.js:967:20
    at async isLoggedIn (/app/routes/base.js:12:9)
    at async serve (/app/node_modules/koa-static/index.js:53:9)
    at async serve (/app/node_modules/koa-static/index.js:53:9)
    at async /app/scripts/app.js:44:5
    at async /app/scripts/app.js:37:5
    at async /app/scripts/app.js:25:5

**Comment by qhme** [comment]
我也碰到同样的问题，请问解决了吗？

**Comment by ZanyRain** [comment]
同样问题，有点坑啊

**Comment by Bosn** [comment]
经测试最新源代码已修复，有问题再reopen谢谢
