### ISSUE TITLE
你好这边支持配置前缀吗？ 比将服务配置在某个path下面

### ISSUE THREAD

**Issue by bobiscool** [thx/rap2-delos#686]
如题，

我的域名 只有 www.abc.com/

想配置  www.abc.com/mock为 这个平台  需要怎么做呢，是否支持配置，docker yml里面可以配置吗

**Comment by Bosn** [comment]
相对路径貌似不支持哦...

虽然可以用nginx做一些代理，但是前端的一些链接木有考虑到context不为/的情况哦
