### ISSUE TITLE
导出docx 报错 TypeError: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by zktz** [thx/rap2-delos#689]
**BUG描述**

导出docx 报错，500错误
node日志：
1|rap-server-delos  |   TypeError: Cannot read property 'data' of null
1|rap-server-delos  |       at app.use (/docker_data/rap2-delos-2.2.2/dist/scripts/app.js:38:50)

**复现步骤**
点击【导出】，点击 docx的导出链接

**期望结果**
下载docx文件

**实际结果**
显示Internal Server Error

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
_**是自建。服务器CentOS 7.5**_
* 如果是前端错误，请提供浏览器版本
_**不是前端错误，是服务器端错误**_
* 其它可能帮助我们排查问题的环境信息

**附加信息**
node日志
1|rap-server-delos  |   TypeError: Cannot read property 'data' of null
1|rap-server-delos  |       at app.use (/docker_data/rap2-delos-2.2.2/dist/scripts/app.js:38:50)

**Comment by zktz** [comment]
是否是自建服务器？如果为自建，请提供操作系统版本
是自建。服务器CentOS 7.5
如果是前端错误，请提供浏览器版本
不是前端错误，是服务器端错误

**Comment by leijee** [comment]
自建服务器，也遇到同样的问题，一样的报错，无法导出docx 
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

**Comment by Bosn** [comment]
已修复，如有问题再reopen谢谢
