### ISSUE TITLE
是否考虑支持二三级菜单

### ISSUE THREAD

**Issue by zhuangjiaju** [thx/rap2-delos#690]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
这个功能真的很重要，建了一个模块后，里面一堆接口，比如我的模块是人员管理，里面几百个接口真的很难管理。建议支持，二级或则多级模块。类似于我们平时最常用的后台管理系统这种菜单来做。

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
之前分三级的时候大家觉得太麻烦了改成了2级。你可以了解下协同仓库，我们一般不会把几百个接口放在一个项目。而是随着项目迭代，新建项目，同时通过协作仓库来共享Mock接口。
