### ISSUE TITLE
Body Params 导入数据后显示到 Query Params 

### ISSUE THREAD

**Issue by LouisKai** [thx/rap2-delos#691]
**BUG描述**
Body Params 导入数据后显示到 Query Params 

**复现步骤**
1. 选择 POST 或者 PUT 请求方式
2. 点击 Body Params
3. 点击导入
4. 输入 json 数据点击保存

**期望结果**
导入的数据应该属于 Body Params 下方

**实际结果**
导入的数据放到了 Query Params 下方

**截图**
<img width="1136" alt="屏幕快照 2020-07-29 17 42 38" src="https://user-images.githubusercontent.com/10755388/88785446-c8728e00-d1c3-11ea-9f4b-c73e6f08c096.png">
<img width="635" alt="屏幕快照 2020-07-29 17 43 46" src="https://user-images.githubusercontent.com/10755388/88785460-cdcfd880-d1c3-11ea-8a38-7500c16264b0.png">

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
内网版已fixed，晚些时间merged到github

**Comment by Bosn** [comment]
https://github.com/thx/rap2-dolores/commit/8ebcb42158170e31d3355a43fd32feca60b01746

**Comment by LouisKai** [comment]
内网试了还是无效 :(

**Comment by Bosn** [comment]
只是代码fix，内网外网的上线发布会按照计划经营
