### ISSUE TITLE
接口信息从RAP2平台导入至另一个RAP2平台

### ISSUE THREAD

**Issue by lialun** [thx/rap2-delos#692]
我在http://rap2.taobao.org/ 创建了多个项目、多个接口，现在想将接口导入至自己搭建的RAP2平台，请问应该如何操作？平台没有提供对称的的导入、导出操作吗？

**Comment by Bosn** [comment]
平台为了RAP1迁移，做了RAP1 => RAP2的导入，RAP2的数据导出导入有没有得确认下。@bigfengyu 看下，如果没有的话，是要加一下。一些数据备份还原场景也会用到。

**Comment by Bosn** [comment]
源代码已更新，增加了导入导出功能。官网近期也会按计划迭代更新。
