### ISSUE TITLE
导入请求数据解析格式出错

### ISSUE THREAD

**Issue by lanfeng6** [thx/rap2-delos#694]
**BUG描述**
导入json请求体，明明选择的市formdata或者raw，解析出来却成了query

**复现步骤**
直接导入一个json就是

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
bug代码已经修复，线上服务不定期更新中。
