### ISSUE TITLE
可否添加接口修改，邮件提醒功能（可选）

### ISSUE THREAD

**Issue by okamiv** [thx/rap2-delos#696]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
可否添加接口修改，邮件提醒功能（可选）
  

**您是否有建议的实现方案**
  添加接口或者仓库关注功能
  如果关注接口或者仓库的话，接口发生修改，邮件即时提示

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
感谢您的意见反馈，会在未来的规划中考虑。谢谢
