### ISSUE TITLE
希望响应部分支持多种ContentType.比如text/plain

### ISSUE THREAD

**Issue by okamiv** [thx/rap2-delos#698]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
前端已增加参数类型的选择显示

ContentType有特殊要求，可以直接在接口描述里写（支持Markdown）目前功能上没特殊处理，所以不用单独设置类型。
