### ISSUE TITLE
导入数据有误

### ISSUE THREAD

**Issue by HiCarryWe** [thx/rap2-delos#699]
**BUG描述**
导入请求参数，无论选择什么格式进行导入，保存后都为QueryParams

**复现步骤**

**期望结果**
选择BodyParams进行导入保存后，应该参数显示为Body参数

**实际结果**
选择BodyParams进行导入保存后，参数显示为Query参数

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
最新代码已修复该BUG，若为rap2.taobao.org，下一版上线即可恢复。
