### ISSUE TITLE
下载完按README都安装好了，怎么访问呀

### ISSUE THREAD

**Issue by fzhwww** [thx/rap2-delos#7]
都安装好了，没有报错，但访问时首页，只显示一个超链接：https://rap2.alibaba-inc.com啊；
怎么访问，不会nodejs，只想搭建做接口管理系统。

**Comment by Bosn** [comment]
你访问的是后端服务器的主页。前端的主页在rap2-dolores中。开发模式默认是3000端口。后端的服务器默认是6001

**Comment by Bosn** [comment]
rap2-delos和rap2-dolores两个包的README中，我增加了配置文件的说明，具体可以看一下，其实都对应config.prod.js  (部署时的配置）

开发时默认都是本机，也可以在config.dev.js中调整。

个人部署node server，需要对node运维有一定知识掌握。
