### ISSUE TITLE
新版接口编辑-描述中内容，会丢失下划线

### ISSUE THREAD

**Issue by Wang-Yang** [thx/rap2-delos#700]
**BUG描述**
新版接口编辑-描述中内容，会丢失下划线，比如：1_1， 保存之后展示为11

**复现步骤**
![image](https://user-images.githubusercontent.com/25840593/89605642-a2727b00-d8a0-11ea-9d76-c7f32f5863d2.png)

**期望结果**
还原输入的11_11

**实际结果**
  11_11  保存之后  就变成  1111 了

**截图**
![image](https://user-images.githubusercontent.com/25840593/89605743-dbaaeb00-d8a0-11ea-92b1-e0871df94d71.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
  是自建服务器，win10操作系统，谷歌浏览器
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
您好，这是因为这里被解释为markdown，如果需要下划线，请参加markdown的语法即可。

例如使用`__1__2__`

**Comment by Bosn** [comment]
也就是用两个 ` 符号来包起来
