### ISSUE TITLE
谷歌浏览器打开无法登录

### ISSUE THREAD

**Issue by zeemood** [thx/rap2-delos#701]
**BUG描述**
登录一直提示验证码失败

**复现步骤**
打开页面，点击刷新验证码，登录，验证码失败，点击刷新验证码，验证码失败

**期望结果**
能登录

**实际结果**
登录不上

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
谷歌新版浏览器阻止了cookies的写入

**Comment by Bosn** [comment]
您说的是本机自建还是使用rap2.taobao.org呢

**Comment by martianlm** [comment]
谷歌浏览器打开chrome://flags/页面，把SameSite by default cookies、Cookies without SameSite must be secure
、Cookie deprecation messages这三项改成disabled，然后重启浏览器就可以了

**Comment by zeemood** [comment]
> 您说的是本机自建还是使用rap2.taobao.org呢

自建的，是容器化之前最近的一个版本。

**Comment by zeemood** [comment]
> 谷歌浏览器打开chrome://flags/页面，把SameSite by default cookies、Cookies without SameSite must be secure
> 、Cookie deprecation messages这三项改成disabled，然后重启浏览器就可以了

这个我知道，主要是leader说没人愿意自己设置，让我搞一个不用设置那两个东西的容器化rap2

**Comment by martianlm** [comment]
其他方法我也没找到，如果你有好的解决方案希望共享一下

**Comment by zeemood** [comment]
> 您说的是本机自建还是使用rap2.taobao.org呢

我有空尝试下用容器化后的版本试一下。貌似一键docker部署出来的已经不会了。谷歌浏览器版本是_版本 84.0.4147.125（正式版本） （64 位）_

**Comment by zeemood** [comment]
> 其他方法我也没找到，如果你有好的解决方案希望共享一下

新版的容器化，我用docker一键部署好像是没有这个问题的，但是也只是我本地试了一下，没有上测试环境和灰度

**Comment by Cyberhan123** [comment]
在用tke搭建的时候我也遇到了这个问题，如果是直接用ip的话就有这个问题，所以需要自己构建前后端镜像设置对的请求路径，将后台服务和前端服务放在一个ingress下，通过路由区分即可。

**Comment by zeemood** [comment]
目前猜测可能跟挂了LVS有关

**Comment by ilaotan** [comment]
最新版chrome已经没法设置上面那几个参数了. 测试了一下, 都用ip是没问题的. 现在有问题的情况是前端用域名,后端是用的ip. 现在将api也做成域名,经测试没问题了.
如果你也搜到这个问题了,可以试一试.
