### ISSUE TITLE
按照文档使用docker部署时mysql启动不了并报错

### ISSUE THREAD

**Issue by resjscn** [thx/rap2-delos#702]
**BUG描述**
环境：linux centos7，虚拟机环境

**复现步骤**
按照文档正常部署，mysql报错容器无法启动或退出

**期望结果**
mysql正常运行，数据库可以正常链接

**实际结果**
mysql报错，前端可正常运行

**截图**
![image](https://user-images.githubusercontent.com/51428217/90084055-db01d100-dd46-11ea-8033-4632767c2326.png)

**环境**
虚拟机，前端无报错正常运行，数据库报错未正常启动，本地无安装过mysql任何版本3306端口正常未被占用

**附加信息**
因为对docker不是很熟，未修改docker-compose.yml文件，不知道是否需要修改配置项

**Comment by Bosn** [comment]
docker配置及使用不在本仓库的讨论范围，建议加钉钉群和其他配置成功的群友共同交流哦~~~感谢亲的反馈。

**Comment by resjscn** [comment]
谢谢，换了个ubuntu的虚拟机部署正常了
