### ISSUE TITLE
Redis环境变量无法配置密码的问题

### ISSUE THREAD

**Issue by sxrstrive** [thx/rap2-delos#703]
**BUG描述**
按照文档进行配置Redis，配置了REDIS_URL，REDIS_PORT，但因为生产环境的Redis存在密码，导致启动鉴权报错。

**复现步骤**
Redis鉴权报错

**期望结果**
正常

**实际结果**
鉴权报错

**Comment by Bosn** [comment]
是配置了密码不生效吗？还是啥情况？

密码的配置在config文件里，具体有TypeScript类型定义参考下，实际启动也只是传参。具体密码是否正确，hosts是否正确请本机用redis-server进行连接测试。更多网络配置相关超出本项目范围。
