### ISSUE TITLE
swagger导入时，如果接口是无参或者无返回值是会报导入失败错误

### ISSUE THREAD

**Issue by DreamingLight** [thx/rap2-delos#705]
**BUG描述**
1.当导入的swagger接口是无参时，接口json串中缺少parameters属性，会导致错误，添加"parameters":[]之后会导入成功。但是手动添加太麻烦了。
2.当导入的swagger接口是void的无返回值接口时，接口json串中responses的200属性中缺少schema属性，会出现导入不成功。

**复现步骤**
创建一个无参数和无返回值的接口即可重新bug.

**期望结果**
1.希望在导入时，可以判断是否缺少参数，进行自动添加处理，如果处理不了，请给出具体导入错误的接口信息。
2.希望在导出接口时，如果部分接口出现错误，可以不影响后面接口的导入，自动跳过错误的接口，记录错误接口信息。

**实际结果**
swagger导入时，会提示导入失败，且从导入错误的接口开始，其它后面所有接口全部导入失败。

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
parameters的bug已修复，谢谢。

该功能第三方同学贡献开发的😂修复起来慢了点，sorry。
