### ISSUE TITLE
rap2-dolores 按照你们的部署来的，但是出现了这个问题，不知道是什么问题

### ISSUE THREAD

**Issue by yadongwang110** [thx/rap2-delos#706]
[root@ecs-15a5 rap2-dolores]# npm run build

> rap2-dolores@1.0.0 build /root/rap2/rap2-dolores
> npm run lint && npm run build-css && react-scripts build

> rap2-dolores@1.0.0 lint /root/rap2/rap2-dolores
> tslint --project ./ -c tslint.json --fix

> rap2-dolores@1.0.0 build-css /root/rap2/rap2-dolores
> node ./node_modules/sass/sass src/:src/ --quiet

Creating an optimized production build...
Failed to compile.

/root/rap2/rap2-dolores/src/components/account/LoginForm.tsx
TypeScript error in /root/rap2/rap2-dolores/src/components/account/LoginForm.tsx(85,46):
Argument of type 'string | string[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.  TS2345

    83 |           const original = uri.search(true).original
    84 |           if (original) {
  > 85 |             dispatch(push(decodeURIComponent(original)))
       |                                              ^
    86 |           } else {
    87 |             dispatch(push('/'))
    88 |           }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build: `npm run lint && npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-16T09_58_13_576Z-debug.log

**Comment by Bosn** [comment]
typescript更新到最新的正式版

然后npm install


再tsc一下看看是否还有错误。看起来像是版本问题

**Comment by Bosn** [comment]
稍等，用最新的pkg确实复现了问题，我们正在修复。稍后放出来。

**Comment by Bosn** [comment]
fixed in https://github.com/thx/rap2-dolores/commit/83b96a7a4b546aa6e7520b45c6ebf66749c30d9a
