### ISSUE TITLE
编辑接口 请求参数导入json格式文本后没反应，响应参数导入正常

### ISSUE THREAD

**Issue by mailzf** [thx/rap2-delos#707]
**BUG描述**

编辑接口 请求参数导入后没反应，参数没变
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by mailzf** [comment]
编辑接口 请求参数导入后没反应，参数没变,   导入的是Body Params 但是保存后刷新变成了Query Params!

**Comment by JetLu** [comment]
导入Body Params这边bug影响使用

**Comment by Bosn** [comment]
应该很早已经修复了，可以回归下有问题再reopen谢谢
