### ISSUE TITLE
是否能增加 REST 接口的支持

### ISSUE THREAD

**Issue by DvShu** [thx/rap2-delos#709]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
能否添加对于 REST 接口的支持，比如 URL Params 以及更多的状态码比如：201，204 等

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
感谢您的建议，我们会在未来产品规划中考虑。
