### ISSUE TITLE
项目简介和接口简介不能保存格式

### ISSUE THREAD

**Issue by dongm2ez** [thx/rap2-delos#71]
希望能够保留格式，一些简单描述文档无格式较难阅读，最好是能够切换无格式和有格式的，比如支持makedown方式书写简介

**Comment by Bosn** [comment]
Markdown有Markdown专门的工具。RAP2虽然是文档，但是精力有限，它更关注接口的结构，而不是Markdown书面的简介，这些文本类介绍请放在更适合的文档管理工具（如Wiki）中。
