### ISSUE TITLE
真没第一代好用，手残数据都冲了

### ISSUE THREAD

**Issue by bobiscool** [thx/rap2-delos#710]
真没第一代好用，手残数据都冲掉了
版本管理一直都没

**Comment by Bosn** [comment]
版本管理已经有了哦，最新版。了解一下。

**Comment by Bosn** [comment]
历史记录功能可以看到所有改动，改动较大或删除接口的时候，会生成可以重新导入的接口级的备份。

前者已经上线了，后者近期会发布到社区版。
