### ISSUE TITLE
导入 YApi 生成的 SwaggerJson 数据失败

### ISSUE THREAD

**Issue by Mitscherlich** [thx/rap2-delos#711]
**BUG描述**
使用 rap2 导入 yapi 生成的 swagger v2 json 数据时，提示「导入失败」。

**复现步骤**
1. 在 yapi 平台的「数据管理」中，选择「数据导出」，并使用「swaggerjson」格式；
2. 在 rap2 中新建仓库，选择「导入」，将生成的 swagger json 数据粘贴到输入框中，点击导入；

**期望结果**
正常导入

**实际结果**
导入失败

**截图**
![image](https://user-images.githubusercontent.com/19310241/91137405-2d48d780-e6e1-11ea-8bc2-28b88e9dc5e6.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
是，操作系统为 CentOS 7

```sh
$ cat /etc/redhat-release
# CentOS Linux release 7.6.1810 (Core)
$ cat /proc/version
# Linux version 3.10.0-957.el7.x86_64
```

* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
[migrate.ts#L511-L513](https://github.com/thx/rap2-delos/blob/0c0be4ad930b92d6e069eb4d8dead0e7143b2c76/src/service/migrate.ts#L511-L513) 尝试解析上传的 swagger json 中的 `definitions` 字段，但该字段在 yapi 导出的数据中不存在，故导致该异；该字段并不总是存在，应在 `JSON.parse` 时考虑该字段为空的情况。

https://github.com/thx/rap2-delos/blob/0c0be4ad930b92d6e069eb4d8dead0e7143b2c76/src/service/migrate.ts#L511-L513

![image](https://user-images.githubusercontent.com/19310241/91137689-418cd480-e6e1-11ea-8976-9a9c90758452.png)
![image](https://user-images.githubusercontent.com/19310241/91142095-ce845d80-e6e2-11ea-9e3f-adb518a19862.png)

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/pull/712

已修复
