### ISSUE TITLE
首页顶部菜单栏问题

### ISSUE THREAD

**Issue by PhageT2** [thx/rap2-delos#713]
- [ ] **BUG描述**

首页顶部菜单栏，点击之后文字就看不到了，需要鼠标放到文字上才显示
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
自建服务器和公网服务器都有这个问题

**附加信息**

**Comment by Bosn** [comment]
没办法复现。。。请截图并提供浏览器版本信息等
