### ISSUE TITLE
关于rap2建议

### ISSUE THREAD

**Issue by god8816** [thx/rap2-delos#714]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
   问题： rap2文档编写占用大量的开发时间，让编写rap2的人员疲于编写文档。

**您是否有建议的实现方案**
   解决方案：
       思想：代码即是文档
 解决办法：rap2团队定义好rap2文档推送接口，有需求方编写程序接口后自动生成rap2文档，然后调用接口自动推送到rap2中。
       好处：及时性、方便性、准确性

**其它帮助我们理解您需求的描述、截图**

**Comment by god8816** [comment]
联系微信：ppgou88

**Comment by Bosn** [comment]
这个主要看应用场景，如果已经有成熟的线上API，我们团队内部也会有一些同步工具，把已有API自动同步到RAP2，RAP2也提供了导入导出的API。

而更多的时候，RAP2用于项目初期，还没有代码时的早期设计，前后端人员制定接口，然后各自开发互不影响。RAP2在这个场景下，更具实际意义。至于其他场景，我们将通过开放数据接口的方式去和其它不同目的的平台对接。
