### ISSUE TITLE
导入json格式的body请求体参数，结果出现在查询参数栏

### ISSUE THREAD

**Issue by dengdengkai** [thx/rap2-delos#715]
**BUG描述**
点击新建接口->点击右侧编辑->选中参数类型(body params)->选择导入->粘贴json字符串，点击保存->点解该接口的body paramas 无刚才的导入信息，点击 query params出现了刚才的导入信息
**复现步骤**

**期望结果**
body paramas类型的参数 出现在该栏 而不是出现在query params栏； 这个bug出现在增加皮肤功能之后，皮肤功能未上线之前一切正常

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

否
**附加信息**

**Comment by dengdengkai** [comment]
皮肤功能上线后出现的新bug

**Comment by Bosn** [comment]
问题应该已经修复了，可以回归下，有问题再reopen谢谢。
另外最好附上截图😂
