### ISSUE TITLE
求出个在k8s部署的指南

### ISSUE THREAD

**Issue by Cyberhan123** [thx/rap2-delos#717]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我想要在腾讯云的k8s集群上部署，但是遇到很多问题，能不能出个新手指南呀，感激不尽。

遇到的问题

1    因为现在的镜像制作的基础镜像问题不支持远程登录镜像
2    k8s如何初始化数据库

**Comment by Cyberhan123** [comment]
docker compose我通过kompose 转换成功了，但是服务起来了配置了ingress在外网也访问不到

**Comment by Cyberhan123** [comment]
总算解决了，这个部署还是建议大家看看源码，来根据自己需求部署

**Comment by Cyberhan123** [comment]
已经上岸感谢妈妈

**Comment by sivanXu001** [comment]
@Cyberhan123 ingress怎么转发的能知道一下吗？非常感谢！

**Comment by Cyberhan123** [comment]
> @Cyberhan123 ingress怎么转发的能知道一下吗？非常感谢！

https://github.com/thx/rap2-delos/wiki/docker
