### ISSUE TITLE
http://rap2.taobao.org/repository/joined 线上环境创建仓库500

### ISSUE THREAD

**Issue by doubunv** [thx/rap2-delos#719]
**BUG描述**

http://rap2.taobao.org/repository/joined 线上环境创建仓库500

Request URL: http://rap2.taobao.org:38080/repository/create
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 47.105.94.66:38080
Referrer Policy: no-referrer-when-downgrade
**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
问题无法复现，如果问题依旧，请携带网络面板请求信息，看看是否创建仓库时有什么特殊的选项导致的创建失败。
