### ISSUE TITLE
采用docker安装的，由于redis有密码，怎么在docker-compose.yml文件中配置密码，密码的key值命名的是什么

### ISSUE THREAD

**Issue by TinyMeng** [thx/rap2-delos#720]
**BUG描述**
不知道docker安装的docker-compose.yml的redis config中怎么配置密码

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Cyberhan123** [comment]
带密码的话需要你自己构建镜像，并在配置文件上加入password

**Comment by Bosn** [comment]
如上，参考配置文件中的变量带入即可。
