### ISSUE TITLE
2.9.0版本权限BUG，团队成员可以删除成员，可以管理非成员仓库，仓库成员可以删除其他成员

### ISSUE THREAD

**Issue by robertzhangwenjie** [thx/rap2-delos#722]
**BUG描述**
团队成员可以删除其他团队成员，可以对非成员仓库进行管理。仓库成员可以删除其他成员。

**复现步骤**
1. 使用docker-compose部署的最新版本
2. 创建测试人员、开发人员、项目经理3个角色，使用项目经理创建团队，然后开发创建仓库
3. 测试人员登陆后可以管理团队和仓库

**期望结果**
与user manual 的描述一致
![image](https://user-images.githubusercontent.com/35749198/92324963-4bb3b900-f079-11ea-9b43-210321e68b7e.png)

**实际结果**
非仓库成员可以维护团队和仓库

**截图**
![image](https://user-images.githubusercontent.com/35749198/92322910-ff5f7d80-f066-11ea-8255-fc7132baeb8e.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
ubuntu20.4 LTS
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by robertzhangwenjie** [comment]
@Bosn  这个问题大概什么时候会修复？

**Comment by Bosn** [comment]
”BUG描述
团队成员可以删除其他团队成员，可以对非成员仓库进行管理。仓库成员可以删除其他成员。“

团队成员目前没有区分管理员 or 成员。大家都是统一的权限，可以互相删除或添加。
对于我们那里内部，因为RAP2目前都是公司内部部署，都是内网员工使用，也不存在敏感信息，所以没有做特别的权限配置。


如果在权限上，有特殊需要可以自行编写。
