### ISSUE TITLE
docker部署方式能否补充一下docker、docker compose等版本

### ISSUE THREAD

**Issue by SNGxx** [thx/rap2-delos#723]
docker小白，在ubuntu 16.04上安装了docker 19.03和docker compose 1.8.0。
执行`docker-compose up -d`时报错
![image](https://user-images.githubusercontent.com/11484496/92349432-a34d3580-f108-11ea-8980-18794eedbb07.png)

看起来是版本问题

**Comment by Bosn** [comment]
docker镜像非官方维护哦，建议升级到最新再尝试，有问题再reopen谢谢
