### ISSUE TITLE
从swagger导入的时候提示跨域

### ISSUE THREAD

**Issue by jeremy7xu** [thx/rap2-delos#727]
**BUG描述**
从swagger导入的时候提示跨域

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by wanghengGit** [comment]
![image](https://user-images.githubusercontent.com/13342563/95549822-87f08580-0a3a-11eb-8649-da195667d319.png)

**Comment by Bosn** [comment]
跨域可以使用直接粘贴的形式进行导入
