### ISSUE TITLE
最近老是访问不了rap2的页面 什么情况~

### ISSUE THREAD

**Issue by faithcoco** [thx/rap2-delos#728]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/45283661/93842846-b2b4ad00-fcca-11ea-8fd2-2e9a73cffc45.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Wzb3422** [comment]
同样的问题

**Comment by hailingfeng** [comment]
+1

**Comment by maris205** [comment]
好卡啊，登不上去，难道非要自己搭建啊

**Comment by maris205** [comment]
http://rap2.taobao.org
用的官方版的

**Comment by mj520** [comment]
昨天是慢 早上还能访问 现在是失联中 http://rap2.taobao.org

**Comment by dearlin** [comment]
http://rap2.taobao.org 官方不能访问了，应该是服务器挂了吧？

**Comment by yihuowandou** [comment]
http://rap2.taobao.org 挂了，访问不了了，都一天了，响应太慢了吧。我还有数据在上边了。

**Comment by cirry** [comment]
感谢rap2，让我放假大半天

**Comment by LiJohnson** [comment]
+1

**Comment by linzaixian888** [comment]
只能说对这官方的http://rap2.taobao.org 太无语了

**Comment by wangliyang206** [comment]
打不开，一直加载中

**Comment by wakaryry** [comment]
打不开。昨天开始打不开。今天还是打不开

**Comment by zwb8926** [comment]
+1

**Comment by 1157009511** [comment]
一天过去了

**Comment by cirry** [comment]
终于好了

**Comment by bigfengyu** [comment]
抱歉各位，昨天遭遇了云服务的故障，今天新部署了实例，服务 rap2.taobao.org 已经得以恢复。

**Comment by chenweiyj** [comment]
> 抱歉各位，昨天遭遇了云服务的故障，今天新部署了实例，服务 rap2.taobao.org 已经得以恢复。

国庆期间又挂了，现在还挂着 @bigfengyu
