### ISSUE TITLE
团队成员可以编辑接口文档，如何设置使团队成员只能读文档不可编辑

### ISSUE THREAD

**Issue by arvinyu** [thx/rap2-delos#729]
**BUG描述**
用户并非仓库拥有者，也不是仓库成员，只属于仓库的团队成员，但是却能编辑接口文档

**复现步骤**
创建仓库A，拥有者aa
创建团队B，加入团队成员 bb@bb.com
将B设置为A的团队
bb@bb.com却能编辑A下的接口文档（bb@bb.com此时并非A的仓库成员）

**期望结果**
用户并非仓库拥有者，也不是仓库成员，只属于仓库的团队成员，应该只能读不能编辑接口文档

**实际结果**
用户并非仓库拥有者，也不是仓库成员，只属于仓库的团队成员，即能读又能编辑接口文档

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by cattles** [comment]
权限隔离，呼声很高啊

**Comment by robertzhangwenjie** [comment]
权限问题 确实是公司里推行的一大阻碍

**Comment by Bosn** [comment]
只读不可编辑的话，只要满足：

1. 在团队
2. 项目为私有

就可以了
