### ISSUE TITLE
可否全站支持https?

### ISSUE THREAD

**Issue by thinkerchan** [thx/rap2-delos#731]
![image](https://user-images.githubusercontent.com/4480412/94128715-0ff85c00-fe8d-11ea-8566-0beddf715ab1.png)

**Comment by afeiluo** [comment]
同样的问题， 自己部署的时候也用不了https, 提示错误 “ Account.ts:6 Mixed Content: The page at 'xxx' was loaded over HTTPS, but requested an insecure resource 'xxxx'. This request has been blocked; the content must be served over HTTPS.”

**Comment by callmesoul** [comment]
小程序需要https啊，有https就更好了

**Comment by Bosn** [comment]
RAP2是mock服务哈，小程序的话不要访问mock服务了。

目前官网暂时无考虑上HTTPS哈。有需求的可以自行搭建私密的服务器，更适合一些哦。
