### ISSUE TITLE
导出到 postman有问题

### ISSUE THREAD

**Issue by leiming8801** [thx/rap2-delos#732]
**BUG描述**
在 rap2导出 postman把导出的文件导入到 postman里在URL中多了一个":"号

**复现步骤**
![image](https://user-images.githubusercontent.com/4609129/94536172-0861fa00-0275-11eb-8e0e-9a6b70897d44.png)
![image](https://user-images.githubusercontent.com/4609129/94536201-10ba3500-0275-11eb-9c06-b12ac586acb7.png)

**期望结果**
postman url 中无：号

**实际结果**
有

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by jiachunzhen** [comment]
导出文件中 "port":"",  这个些字符去掉。

**Comment by Bosn** [comment]
fixed, 稍后push

导出的port设置为null即可

官方文档说：string类型，为空即可，但是它指的空，不是""而是null....
