### ISSUE TITLE
模块接口分目录

### ISSUE THREAD

**Issue by qq87804245** [thx/rap2-delos#733]
每个模块下的接口文档 都是在同一级，这样全部放在一起，不好做区分，这样要是分很多模块也不是很方便，如果能在模块下的接口加个类似文件夹一样的目录就更好了，希望采纳！

**Comment by qq87804245** [comment]
1

**Comment by Bosn** [comment]
项目，模块，接口目前三个层级。因为项目（仓库）之间可以通过协作ID串联，我们不建议一个仓库存放过多的接口。

暂时不考虑多一个层级。有需要可以自行改动。
