### ISSUE TITLE
请求参数Body Params raw格式，导出时为form-data格式。

### ISSUE THREAD

**Issue by jiachunzhen** [thx/rap2-delos#737]
**BUG描述**
请求参数Body Params raw格式，导出时为form-data格式。

**复现步骤**
新增接口，请求参数格式设置为Body Params，选择raw，填写任意数据，保存。
点击导出，导出文件中请求参数格式为Body Params form-data，应为raw

**期望结果**
请求参数Body Params raw格式，导出时为raw格式。

**实际结果**
请求参数Body Params raw格式，导出时为form-data格式。

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by ilaotan** [comment]
3个月了，这bug还没解决。。。。。 阿里妈妈不需要kpi啦？

**Comment by Bosn** [comment]
已修复

**Comment by Bosn** [comment]
@ilaotan RAP2是团队内的技术创新开源工具，并没有专人专项人力支持。精力有限我们只会不定期维护更新。

如果对于产品稳定性有特别要求，可以自行修复也可以选择其它产品，谢谢。

**Comment by jiachunzhen** [comment]
怎么删除这个issues ...

**Comment by jiachunzhen** [comment]
请删除这条issue
