### ISSUE TITLE
类型不符

### ISSUE THREAD

**Issue by yujia0501** [thx/rap2-delos#738]
**BUG描述**
我选择类型是string，但是输入的初始值是[{a:1}]这种格式的时候，返回的就是数组

**复现步骤**
选择类型是string，输入的初始值是[{a:1}]

**期望结果**
期望返回值的类型相符

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
建议带上截图和详细的案例，目前的描述对于问题不清晰
