### ISSUE TITLE
左侧接口列表加上请求类型的展示，界面上增加请求类型的筛选框

### ISSUE THREAD

**Issue by LouisKai** [thx/rap2-delos#739]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
接口数量太多，希望能加上“请求类型”的筛选项，另外在左侧列表展示的时候能否把请求类型（如 GET、POST）也展示出来，否则得点到指定接口才能看到

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
![20201022152300](https://user-images.githubusercontent.com/10755388/96838464-7f587000-147a-11eb-90b2-9a211a7d56d4.jpg)

**Comment by Bosn** [comment]
谢谢您的反馈，该功能暂不支持。我们会在未来产品规划中去考虑。。。
