### ISSUE TITLE
请问数据库初始化时指定远程数据库在什么地方修改

### ISSUE THREAD

**Issue by keven0706** [thx/rap2-delos#74]
修改了config.dev里的数据库链接不起作用还是连接本地的。谢谢

**Comment by developerFer** [comment]
@keven0706 我也遇到相同的问题，配置好后重新初始化解决了该问题

**Comment by Bosn** [comment]
npm run dev 是启动开发环境，所以配置在config.dev.ts中
npm start 是启动生产环境，配置在config.prod.ts中

详情参考README.md
