### ISSUE TITLE
官网打不卡了，麻烦看下，谢谢

### ISSUE THREAD

**Issue by zhangtaodeveloper** [thx/rap2-delos#741]
**BUG描述**
官网打不卡了，麻烦看下，谢谢

**复现步骤**
访问：http://rap2.taobao.org 提示一直拼命加载

**期望结果**
正常访问

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/8908528/97545203-9b718980-1a05-11eb-9cc7-daf8a30e6b3d.png)

**环境**
* 是否是自建服务器？
不是自建
* 如果是前端错误，请提供浏览器版本
刚才还可以访问，现在不可以了

* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by ht159357** [comment]
官网一样打不开，mock服务器也一样挂了

**Comment by binperson** [comment]
一样一样的

**Comment by wangnanxu** [comment]
一样一样的
