### ISSUE TITLE
需要单接口强制备份及拖拽数据到对应的key功能

### ISSUE THREAD

**Issue by colincatsu** [thx/rap2-delos#742]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
    需要单接口强制备份及拖拽数据到对应的key功能
    现在只能自动备份，这个颗粒度太大，无法手动控制，希望强制备份功能
    拖拽数据进入对应的子KEY，现在无法拖拽，重新导入无备注，很难受
来自DLNU的建议，望采纳~~~bson ma~~~

**Comment by Bosn** [comment]
感谢您的建议

导出功能已在规划（目前确实需要手动改动至少5个字段才能触发）

拖拽到不同key太麻烦了没时间做T  。T
