### ISSUE TITLE
标题栏文字不显示

### ISSUE THREAD

**Issue by qdxkrs** [thx/rap2-delos#743]
**BUG描述**
火狐浏览器、chrome浏览器标题文字不显示，鼠标放上才显示

**期望结果**
正常显示标题栏

**实际结果**
标题栏文字不显示

**截图**
![123](https://user-images.githubusercontent.com/39894542/97822499-23e77700-1cf1-11eb-87ac-1f754c6cb02d.png)

**环境**
docker compose 构建

**附加信息**

**Comment by Bosn** [comment]
暂不支持火狐
