### ISSUE TITLE
centos环境下docker部署mysql异常

### ISSUE THREAD

**Issue by resjscn** [thx/rap2-delos#744]
**BUG描述**
使用docker按步骤部署，启动发现mysql的容器挂了，查看log提示/var/lib/mysql Permission denied。
注释掉volumes部分重新启动发现启动正常但是后端服务、初始化库的时候报错连不上库，于是查看mysql状态，使用sqlyong可以正常链接。

**期望结果**
mysql在centos中部署总是出现各种奇怪的问题，期望给予正确的解决方法
![1](https://user-images.githubusercontent.com/51428217/97961276-f16f7400-1ded-11eb-8c10-e578c779ab61.jpg)
![image](https://user-images.githubusercontent.com/51428217/97961298-fd5b3600-1ded-11eb-86c7-518e338d2f1c.png)

**环境**
centos7

**附加信息**

**Comment by Bosn** [comment]
部署技术支持，建议加群交流。。。运维技术相关问题不在本区讨论范围。
