### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by SuperJINcn** [thx/rap2-delos#747]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
![接口文档保存报错](https://user-images.githubusercontent.com/44902011/98636204-5a606a00-2361-11eb-80da-29053ef0a755.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
上面已经写了啊
