### ISSUE TITLE
官网打不开，报 cors

### ISSUE THREAD

**Issue by Go-loneliness-of-man** [thx/rap2-delos#748]
**BUG描述**
下午还好好的，刚刚突然就打不开了，用手机也打不开，朋友也打不开

**复现步骤**
直接访问 http://rap2.taobao.org 就好

**期望结果**
正常打开操作

**实际结果**
控制台报 cors

**截图**
![$C%GWXVJO @B2DSC3JDHTR9](https://user-images.githubusercontent.com/35656445/99077428-b47a5d00-25f7-11eb-8ea7-1b7b1aba36c8.png)

**环境**
* 不是自建，官方示例 http://rap2.taobao.org
* chrome 86
* 其它可能帮助我们排查问题的环境信息
这是控制台报错：
joined:1 Access to fetch at 'http://rap2api.taobao.org/account/info' from origin 'http://rap2.taobao.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**附加信息**
时间是 2020-11-13 21:00 左右

**Comment by MnameHZJ** [comment]
坐等官方人员回应

**Comment by Go-loneliness-of-man** [comment]
> 坐等官方人员回应

你也打不开是吗？

**Comment by MnameHZJ** [comment]
> > 坐等官方人员回应
> 
> 你也打不开是吗？

是呀。应该是网站服务器出问题了吧

**Comment by Go-loneliness-of-man** [comment]
> > > 坐等官方人员回应
> > 
> > 
> > 你也打不开是吗？
> 
> 是呀。应该是网站服务器出问题了吧

哈哈那我就放心了，不是我一个就好，耐心等待官方解决吧

**Comment by januwA** [comment]
以前也出现过，什么时候能好啊

**Comment by muyu-LG** [comment]
什么时候能恢复

**Comment by Bosn** [comment]
实时问题麻烦在客服群里问哈，这样响应会快一点哦~
