### ISSUE TITLE
我想根据不同的参数生成不同数据，请问下如何实现，post 请求

### ISSUE THREAD

**Issue by didiaohu** [thx/rap2-delos#750]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
https://github.com/thx/rap2-delos/wiki/faq#%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87%E4%B8%8D%E5%90%8C%E7%9A%84%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0%E5%80%BC%E8%BF%94%E5%9B%9E%E4%B8%8D%E5%90%8C%E7%BB%93%E6%9E%9C%E4%BE%8B%E5%A6%82%E9%80%9A%E8%BF%87%E8%AF%B7%E6%B1%82query-id%E7%9A%84%E8%BE%93%E5%85%A5%E6%9D%A5%E8%BE%93%E5%87%BA

**Comment by Bosn** [comment]
Mock规则相关
如何通过不同的请求参数值，返回不同结果？例如通过请求query id的输入，来输出？
可以的，通过语法：$identifier$ 即可，例如请求参数id，响应体重，将初始值设置为：result is $id$，如果实际请求输入的值为id=39，则该字段返回：result is 39
