### ISSUE TITLE
能否提供从swagger那边同步接口过来

### ISSUE THREAD

**Issue by fangwei1688** [thx/rap2-delos#753]
我们是Java语言写的服务端,一直用swagger或别的api生成工具.从来不想手写接口文档.
公司现在前端开发受阿里影响,强推了rap2

你们能否提供接口(包含安全鉴权机制),每次swagger生成文档后同步到rap2

**Comment by Bosn** [comment]
亲，RAP2是开源的。。。有定制功能需求自己实现。。。有问题也欢迎随时在群里和我们交流哦。

RAP2目前没有专人专项，都是我们在业务相对不忙的时候出来做维护哈。
