### ISSUE TITLE
平台API接口访问（如：rap2.xxxx.com/repository/get?id=@id，）需要登录态？

### ISSUE THREAD

**Issue by changzhiwin** [thx/rap2-delos#754]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
开放的api，没有说明文档说怎么鉴权吗？只有登录态才可以访问？

**您是否有建议的实现方案**
更新api访问文档

**其它帮助我们理解您需求的描述、截图**
无登录态访问直接500

**Comment by Bosn** [comment]
可以看一下RAP2的说明书，有鉴权方面的说明，时间过的比较久有问题再reopen也欢迎群里随时交流。
