### ISSUE TITLE
编译dolores-2.2.3报错：Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

### ISSUE THREAD

**Issue by madguy520** [thx/rap2-delos#756]
**BUG描述**
编译dolores-2.2.3报错。

**复现步骤**

**期望结果**

**实际结果**

**截图**
Creating an optimized production build...
Failed to compile.

/usr/local/software/rap2.2.3/rap2-dolores-2.2.3/src/components/common/Select.tsx
TypeScript error in /usr/local/software/rap2.2.3/rap2-dolores-2.2.3/src/components/common/Select.tsx(78,34):
Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

    76 | )
    77 | 
  > 78 | function NoOptionsMessage(props: NoticeProps<OptionType>) {
       |                                  ^
    79 |   return (
    80 |     <Typography
    81 |       color="textSecondary"

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rap2-dolores@1.0.0 build: `npm run lint && npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rap2-dolores@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T01_46_36_514Z-debug.log

**环境**
CentOS7.9

**附加信息**

**Comment by sevenmark** [comment]
遇到相同问题，请问已经解决了嘛？

**Comment by yutou1064** [comment]
相同问题+1

**Comment by Bosn** [comment]
类似问题提过了哈，最新版本已修复，马上提代码，稍等。

**Comment by limng06** [comment]
有直接放 build 包的吗 ？ 同样的问题  好难哦

**Comment by Bosn** [comment]
拉最新代码就好了，npm run build一下重新build @limng06 
这个是新的依赖的package定义变了导致的
