### ISSUE TITLE
支持配置多个响应，备注支持富文本

### ISSUE THREAD

**Issue by 928234269** [thx/rap2-delos#757]
### 您提出的功能是否和您遇到的问题有关，请描述该问题
1.使用rap记录errMsg不方便,errMsg通常有多种状态码.
2. rap不支持多个response

### 您是否有建议的实现方案
1.需要多个response比如200,403同时配置.
我期望的响应如下图可以填多种
![image](https://user-images.githubusercontent.com/40171666/101449238-5ecd7200-3963-11eb-954a-2f951433152e.png)

2.接口的描述支持富文本
![image](https://user-images.githubusercontent.com/40171666/101448999-f2527300-3962-11eb-9140-ea5045740776.png)
这样我就可以在描述里填写errMsg
![image](https://user-images.githubusercontent.com/40171666/101449166-42c9d080-3963-11eb-8fdf-9aa99fae2560.png)
yapi已经支持 https://hellosean1025.github.io/yapi/
![image](https://user-images.githubusercontent.com/40171666/101449776-5c1f4c80-3964-11eb-84a3-e6621a9d52fd.png)

**Comment by Bosn** [comment]
场景功能可以满足，不过场景功能我们还在内部测试，待完善后会放出。敬请期待。
