### ISSUE TITLE
编译dolores-master报错 TypeScript error in /home/rap2-dolores-master/src/components/common/Select.tsx(78,34)

### ISSUE THREAD

**Issue by gbf311** [thx/rap2-delos#758]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**
Failed to compile.

/home/rap2-dolores-master/src/components/common/Select.tsx
TypeScript error in /home/rap2-dolores-master/src/components/common/Select.tsx(78,34):
Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

    76 | )
    77 | 
  > 78 | function NoOptionsMessage(props: NoticeProps<OptionType>) {
       |                                  ^
    79 |   return (
    80 |     <Typography
    81 |       color="textSecondary"

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
系统版本为：centos-release-7-8.2003.0.el7.centos.x86_64
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by yutou1064** [comment]
同样的bug+1，版本centos6.8，centos7.4都试过，一样的bug

**Comment by Bosn** [comment]
类似问题有了哈，最新代码已修复，新版本兼容问题
