### ISSUE TITLE
编译rap2-dolores报错Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

### ISSUE THREAD

**Issue by yutou1064** [thx/rap2-delos#759]
**BUG描述**
编译rap2-dolores2.2.3报错：

/home/rap2-dolores/src/components/common/Select.tsx
TypeScript error in /home/rap2-dolores/src/components/common/Select.tsx(78,34):
Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

    76 | )
    77 | 
  > 78 | function NoOptionsMessage(props: NoticeProps<OptionType>) {
       |                                  ^
    79 |   return (
    80 |     <Typography
    81 |       color="textSecondary"

**复现步骤**
rap2-dolores根目录npm run dev

**期望结果**
run success

**实际结果**
编译错误

**截图**
![image](https://user-images.githubusercontent.com/52066984/101714619-de2e8300-3ad4-11eb-9963-7c7e730d3dd2.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
centos6.8，centos7.4
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**
使用rap2-dolores2.2.1时，依旧报错，但错误提示不同：

TypeScript error in /home/rap2-dolores-2.2.1/src/components/account/LoginForm.tsx(85,46):
Argument of type 'string | string[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.  TS2345

    83 |           const original = uri.search(true).original
    84 |           if (original) {
  > 85 |             dispatch(push(decodeURIComponent(original)))
       |                                              ^
    86 |           } else {
    87 |             dispatch(push('/'))
    88 |           }

**Comment by yutou1064** [comment]
暂时使用rap2-dolores0.0.1版本   未发现此问题，其余版本依旧有此问题

**Comment by 630354780** [comment]
Starting the development server...
Files successfully emitted, waiting for typecheck results...
Failed to compile.

F:/rap2-dolores/src/components/common/Select.tsx
TypeScript error in F:/rap2-dolores/src/components/common/Select.tsx(78,34):
Generic type 'NoticeProps' requires 2 type argument(s).  TS2314

    76 | )
    77 |
  > 78 | function NoOptionsMessage(props: NoticeProps<OptionType>) {
       |                                  ^
    79 |   return (
    80 |     <Typography
    81 |       color="textSecondary"


我的操作系统是Windows10

**Comment by yutou1064** [comment]
> Starting the development server...
> Files successfully emitted, waiting for typecheck results...
> Failed to compile.
> 
> F:/rap2-dolores/src/components/common/Select.tsx
> TypeScript error in F:/rap2-dolores/src/components/common/Select.tsx(78,34):
> Generic type 'NoticeProps' requires 2 type argument(s). TS2314
> 
> ```
> 76 | )
> 77 |
> ```
> 
> > 78 | function NoOptionsMessage(props: NoticeProps) {
> > |                                  ^
> > 79 |   return (
> > 80 |     <Typography
> > 81 |       color="textSecondary"
> 
> 我的操作系统是Windows10

我直接换了最旧的版本（rap2-dolores-0.0.1），没出现这个问题了，但是bug貌似不少......

**Comment by Bosn** [comment]
最新代码已修复，请关注今天稍后更新的提交，第二参加any就好了，最新版本的定义变了导致的。
