### ISSUE TITLE
rapper运行报错看不懂

### ISSUE THREAD

**Issue by milobluebell** [thx/rap2-delos#760]
**BUG描述**
按照rap2上 `</>rapper2`按钮的抽屉弹窗指引，并且生成script命令后，执行该命令报错看不懂

**复现步骤**

 如上

**期望结果**

正确运行

**实际结果**

`rapper: 失败！undefined` 看不懂的报错

**截图**
![image](https://user-images.githubusercontent.com/11535146/101726737-1098aa00-3aee-11eb-85c9-e87c89ed8a65.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
nope

* 如果是前端错误，请提供浏览器版本
命令执行出错，而不是浏览器

* 其它可能帮助我们排查问题的环境信息

**附加信息**

null

**Comment by milobluebell** [comment]
另外你rapper是不是很久没维护了，现在是什么情况？ 如果使用的话，能否保证维护速度跟上呢？ ty

**Comment by Bosn** [comment]
@mochen666 麻烦看一下哈

**Comment by mochen666** [comment]
> 另外你rapper是不是很久没维护了，现在是什么情况？ 如果使用的话，能否保证维护速度跟上呢？ ty

![image](https://user-images.githubusercontent.com/13551778/107135025-49100500-6932-11eb-89ec-2ed235c25e70.png)

我们一直在更新维护哦
