### ISSUE TITLE
支持复杂类型以及枚举值

### ISSUE THREAD

**Issue by lou1swu** [thx/rap2-delos#762]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
我们是通过rapper来生成service层代码的，生成代码的过程中发现一些不太方便的地方，希望可以支持or共建
1. 很多接口的入参及出参所用的模型是一致的，且有具体的含义，比如购买接口的入参模型叫IPurchaseModel，目前只能是类似['/purchase']['Req']这种形式来获取入参模型

2. 希望支持枚举值的设置，这样生成的类型就可以是enum 

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
枚举类型的mock办法，举个栗子：

变量名：`status`
类型：`number`
生成规则：`1`
初始值：`[10, 50, 90]`

则根据Mock规则，返回的值，即为10， 50， 90中选取的枚举值。

**Comment by Bosn** [comment]
目前RAP2暂时还没向service层延伸，但是通过这个方法，我们经常用于前端Mock枚举类型，也可以用作Service层枚举的约定。

我建议可以先通过这个约定，来实现枚举类型的编写，同时你们如果做了Rapper的扩展，也可以通过这个方式去识别。
