### ISSUE TITLE
火狐浏览器兼容问题

### ISSUE THREAD

**Issue by Fichel-wangshaofei** [thx/rap2-delos#763]
**BUG描述**
头部点击过的菜单，鼠标移开会和背景一个颜色，导致看不清字。

**复现步骤**
点击头部菜单，然后切换到其他菜单

**期望结果**
正常显示

**截图**
![图片](https://user-images.githubusercontent.com/33342609/102593441-dcf1fb80-414f-11eb-989a-5211e4752a73.png)

**环境**
火狐84.0

**附加信息**

**Comment by Bosn** [comment]
暂时不支持火狐浏览器😂sorry
