### ISSUE TITLE
建议增加各种枚举值的展示位置，比如返回码等

### ISSUE THREAD

**Issue by slt12157905** [thx/rap2-delos#764]
我们现在会将返回码、一些枚举的数据，写在本地文档里供开发用，如果可以在rap上一起编辑查看。最好是可以进行相关关联，一点击就可以跳转过去看就更完美了！！！

**Comment by Bosn** [comment]
枚举是比较常见的情况

描述层面：在备注里写可选值及中文释义
Mock数据层面：模拟规则写 `1` ，值用数组，例如 `[1, 10, 20]` 即可实现枚举值随机其中一个

从字段本身，因为我们面向的是接口，HTTP接口里没有枚举类型这种东西。所以根据自己需要string、number就行，具体枚举范围可用上述方法区分和实现。
