### ISSUE TITLE
swagger2 导入的bug

### ISSUE THREAD

**Issue by JarynXu** [thx/rap2-delos#765]
**BUG描述**
导入 swagger2 时，如果使用restful的方式会导致同一个url的不同method接口被最后一个同url的接口覆盖

**复现步骤**
如: 有两个接口, GET 用于根据ID获取user, DELETE 用于根据ID删除
GET /api/v1/user
DELETE /api/v1/user

**期望结果**
导入后获得两个接口: GET 和 DELETE

**实际结果**
只获得最后一个接口: DELETE

**截图**

**环境**
使用的是docker自建的，rap2的版本是2.2.3, 操作系统是windows10

**附加信息**

**Comment by kexiai** [comment]
我的swagger 直接导入不进去，请问你是通过什么方式导入的？URL跟JSON都不行。

**Comment by JarynXu** [comment]
URL 和 JSON 都可以导入

**Comment by kexiai** [comment]
我的直接报导入失败啊。。你用的是网页版的吗？我把JSON拷进去，然后我看他调了一个请求，response 返回导入失败。。

**Comment by kexiai** [comment]
方便加个wx吗？请教一下，我的是zxl774631431

**Comment by feizhaojun** [comment]
> 我的直接报导入失败啊。。你用的是网页版的吗？我把JSON拷进去，然后我看他调了一个请求，response 返回导入失败。。

导入swagger时，如果导入的接口没有参数，会导入失败。

**Comment by Bosn** [comment]
@feizhaojun 今天上午推的代码已经修复了这个问题

**Comment by Bosn** [comment]
@JarynXu 麻烦给个导入的JSON再reopen吧，能复现问题的。谢谢
