### ISSUE TITLE
为什么抒写完毕的接口，content-type类型没有显示，导致applicaiton/json 和 x-www-form-urlencoded 无法区分.

### ISSUE THREAD

**Issue by jingjian-1420** [thx/rap2-delos#766]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
为什么抒写完毕的接口，content-type类型没有显示，导致applicaiton/json 和 x-www-form-urlencoded 无法区分.

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
是否可以在地址、类型、状态码下 显示一下content-type?

**Comment by ilaotan** [comment]
遇到类似问题了，设置完content-type后，只有本地显示正常，别人那压根显示不正确。 查了下数据库，保存的是正常，就前端展示问题。

**Comment by Bosn** [comment]
增加了红色参数区分，来显示是raw或者url-encoded-form。
但是具体的content-type设置暂时没计划加，看参数就知道了，content-type如果真的需要指定，可在接口描述中自行书写。

该修改将在稍后的code commits里可见。
