### ISSUE TITLE
导入rap2 json失败

### ISSUE THREAD

**Issue by 0127abcd** [thx/rap2-delos#768]
**BUG描述**
导出为rap2格式的json后再进行导入报错

**复现步骤**
导出为rap2格式的json后再进行导入报错

**期望结果**
导入成功

**实际结果**
导入失败，请检查文件格式，详细错误：导入失败: Cannot read property 'name' of undefined.

**截图**
![image](https://user-images.githubusercontent.com/12032178/103628402-ea91e880-4f79-11eb-8717-ecf7490b8ea6.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by 0127abcd** [comment]
![image](https://user-images.githubusercontent.com/12032178/103629041-c682d700-4f7a-11eb-9641-fdfdd9fefd29.png)

**Comment by Bosn** [comment]
格式支持两种：
1. RAP2备份（当改动较大，删除接口时，在历史记录里的备份）
2.RAP2接口导出（功能还没开发，但是导出整个项目的时候，接口级JSON可以copy paste）

其它类型的接口。。。暂时不支持。
