### ISSUE TITLE
关于Rap2导出Postman-Json后body下mode的值固定为formdata

### ISSUE THREAD

**Issue by 771523908** [thx/rap2-delos#770]
**BUG描述**
使用rap2的Postman导出功能，导出Json后body下mode的值固定为formdata

**复现步骤**
1.新建接口，选择类型POST,新增Body Params参数，选择raw 模式，保存。
2.使用Rap导出功能，选择Postman，成功导出json
3.打开Postman，导入步骤2的json文件。
4.查看postman显示body，模式为form-data

**期望结果**
步骤4，查看postman，body模式为raw，类型为json

**实际结果**
postman显示body，模式为form-data

**截图**

![image](https://user-images.githubusercontent.com/24774391/103747399-8df80180-503d-11eb-84ab-94cc07b8a8c8.png)
![image](https://user-images.githubusercontent.com/24774391/103747422-99e3c380-503d-11eb-9f67-54623ce54a7e.png)

**环境**
自建服务器

**附加信息**

**Comment by Bosn** [comment]
raw类型实际上不需要参数，而是纯文本。该种类型RAP2暂时不支持，可以自行粘贴处理即可。可以考虑放在接口定义了。（支持Markdown）
