### ISSUE TITLE
TS语法错误，泛型需要2个类型参数

### ISSUE THREAD

**Issue by LookFor1231** [thx/rap2-delos#771]
**BUG描述**
src/components/common/Select.tsx
line:78
泛型类型“NoticeProps”需要 2 个类型参数。
master节点。最后拉取时间：2021-01-08

**复现步骤**
bulid 的时候提示错误，查看源码时，提示上诉错误

**期望结果**

**实际结果**
此类型错误，在当前文件下，有6-7处是相同问题，在参数后面加个bool值，false即可

**截图**
![image](https://user-images.githubusercontent.com/13689840/103970419-2fe52e80-51a3-11eb-8130-ad3cc0327a2d.png)

**环境**

**附加信息**

**Comment by Bosn** [comment]
新版本已修复。请关注今日commit的代码
