### ISSUE TITLE
swagger导入的loading

### ISSUE THREAD

**Issue by cnmxiaobudian** [thx/rap2-delos#773]
**BUG描述**
swagger导入时，页面交互无提示

**复现步骤**

**期望结果**
期望加上loading，避免重复导入

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
已添加，稍后更新代码仓库
