### ISSUE TITLE
swagger重复导入的策略问题

### ISSUE THREAD

**Issue by cnmxiaobudian** [thx/rap2-delos#774]
**BUG描述**
由于项目中存在swagger重复导入，而每次重复导入都是直接新增，带来大量重复操作

**复现步骤**

**期望结果**
导入的策略从add调整为merge

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by DavidRen** [comment]
的确在最新版本中有这样的问题，官方能否尽快回复

**Comment by Bosn** [comment]
merge涉及到merge策略的问题，我们暂时不提供merge功能，但是我们有好的建议可以解决这个问题。

1. 设置入口仓库（仓库Entry），为空即可。然后协作仓库ID，设置为第二部创建的仓库的ID
2. 将需要同步的内容，新建一个仓库A，然后在入口仓库的协作仓库ID设置为A的ID

这样，把不需要后续导入的内容放在仓库Entry，而需要经常根据swagger更新的仓库，每次新建，修改一次Entry仓库的协作ID即可。这样就可以不需要修改项目代码中的ID，同时每次导入时都可以更新。
