### ISSUE TITLE
1、用户管理和注册放开与否配置

### ISSUE THREAD

**Issue by verseboys** [thx/rap2-delos#775]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by verseboys** [comment]
团队内使用时，管理员可以配置在登陆端是否放开注册账户的模块，以达到团队工具安全已经不会被外部人员注册

**Comment by Bosn** [comment]
暂时没有开发管理端的计划哦~~· 我们管理员都是手动SQL。

因为本来就是组内开发工具，暂时没人力去开发管理功能。
