### ISSUE TITLE
Docker 部署需要 REDIS_PASSWD 变量以支持带密码的Redis

### ISSUE THREAD

**Issue by Ricky-Hao** [thx/rap2-delos#776]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**
https://github.com/thx/rap2-delos/blob/bf296f8d1b279240966bbc98c045f09e09c9a88f/src/config/config.prod.ts#L29-L32
增加password字段
**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
亲，根据自己需要直接加就可以了呀，还有更多的配置，我们没办法一个一个列出来哦

**Comment by Ricky-Hao** [comment]
那容器化部署怎么办？总不能每次更新版本，我们自己打包镜像吧…
我认为这些较为常用的参数还是需要列一下的

**Comment by Bosn** [comment]
好的，容器部署以前是第三方，刚才问了下同事我们自己也在弄了，那这个我们再改一下好了。

**Comment by Bosn** [comment]
已经改了代码，docker打包要看打包计划。代码修改可以关注今天稍晚些的push，我都处理完一批issues一起push
