### ISSUE TITLE
希望可以加上字段自由拖动的功能，现在文档要是有问题，字段多的话改起来基本跟重写差不多

### ISSUE THREAD

**Issue by xDaWenXi** [thx/rap2-delos#777]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
支持同层级的拖动，不同层级的拖动，太麻烦了不想写。。。。（我很诚实）

**Comment by Bosn** [comment]
有问题再reopen，欢迎MR。。。

**Comment by xDaWenXi** [comment]
好的，感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Bosn<mailto:notifications@github.com>
发送时间: 2021年2月7日 10:02
收件人: thx/rap2-delos<mailto:rap2-delos@noreply.github.com>
抄送: xDaWenXi<mailto:fengkun6@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [thx/rap2-delos] 希望可以加上字段自由拖动的功能，现在文档要是有问题，字段多的话改起来基本跟重写差不多 (#777)


支持同层级的拖动，不同层级的拖动，太麻烦了不想写。。。。（我很诚实）

―
