### ISSUE TITLE
选择Body Params形式传参，raw选择后保存再查看 变成form-data

### ISSUE THREAD

**Issue by caojiele** [thx/rap2-delos#778]
**BUG描述**
选择Body Params形式传参，raw选择后保存再查看 变成form-data

**复现步骤**
选择Body Params形式传参，raw选择后保存再查看

**期望结果**
选择Body Params形式传参，raw选择后保存再查看 还是raw格式

**实际结果**
选择Body Params形式传参，raw选择后保存再查看

**截图**
![image](https://user-images.githubusercontent.com/29936718/106557805-8e60bb00-655d-11eb-9811-354a2be9b040.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
最新版代码已经修复了，线上还未更新。

**Comment by Bosn** [comment]
现在代码仓库的应该就是ok的，你可以试一下。线上系统的更新，在节后。

**Comment by caojiele** [comment]
> 现在代码仓库的应该就是ok的，你可以试一下。线上系统的更新，在节后。

Thx.
