### ISSUE TITLE
[功能需求]接口模板

### ISSUE THREAD

**Issue by xmsz** [thx/rap2-delos#779]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
很多项目了的接口结构都是相同的，每次都创建都要手动输入一次太麻烦了

**您是否有建议的实现方案**
支持接口模板功能
新建接口的时候可以选择模板创建

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/5879146/106695312-47ce9780-6615-11eb-949b-a73ad4c5f4e7.png)
![image](https://user-images.githubusercontent.com/5879146/106695328-50bf6900-6615-11eb-8e39-17c5f650ebef.png)

**Comment by Bosn** [comment]
这块儿我打算用导入导出来实现。

导入功能其实已经做好了，导入，RAP2接口备份，在做大的修改时（比如删除接口，或者字段修改超过5个）就会触发自动的接口备份。

所以所谓模板，其实到家导出后再导入，再进行修改就好了。


手动导出这个近期就会发布到代码仓库，官网上线要等等。快过年了，稳定压倒一切。

**Comment by Bosn** [comment]
有问题再reopen哦
