### ISSUE TITLE
这个产品具体情况怎么样

### ISSUE THREAD

**Issue by xmsz** [thx/rap2-delos#780]
最近再找替换现有请求文档工具的产品，市面上的产品或多或少不是都满足所有需求

rap2这个产品会优先考虑，毕竟大厂的产品死亡概率更低一些

所以有几个问题

1. 这个项目维护者有多少，负责什么角色
2. 有多少内部项目在使用 
3. 未来公共版会继续迭代吗
4. 公共版和内部使用版差多少
5. 能否使用内部版

上面想知道的产品的稳定性

然后
1. 产品规划是怎么样
我看https://github.com/thx/rap2-delos/blob/master/docs/Schedule.md 2017年就停止了

现在只实现了文档写的环节，和基础看的部分，其他很多东西都缺失
例如调试、测试用例等，都是很必须的基础功能

2. 界面实在丑的惨不忍睹
虽然是给开发者用的，但实在丑得看不下去。能否有请设计师同学帮忙一下

**Comment by Bosn** [comment]
这个项目维护者有多少，负责什么角色
1个人在维护，就是最原始的作者我本人

有多少内部项目在使用
用的人非常多，具体保密

未来公共版会继续迭代吗
一直在迭代，但是也看业务项目繁忙程度。RAP2是我们内部小二自己开发的技术工具，没有专人专项人力。以满足我们自己需求为主，社区的不定期也会更新。同时RAP2也是开源的，有很多小伙伴根据自己需要也可以进行扩展。

公共版和内部使用版差多少
内部多一些域账号登陆、和其它内部平台的对接，主要功能都一样

能否使用内部版
这个问题很有趣



RAP2没设计师，设计原则和UI使用的是Google旗下的Material Design，组件库是Material UI。目前人力确实cover不住大的外观重构，RAP2是开源的，对界面有意见也可以自己去改，然后自己内部用即可。

**Comment by Bosn** [comment]
已回复暂关，有问题再reopen
