### ISSUE TITLE
是否支持接口批量导入?

### ISSUE THREAD

**Issue by XxXindyz** [thx/rap2-delos#782]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
目前好像仅支持单个接口的导入,能否支持接口批量导入?

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by jiachunzhen** [comment]
> **您提出的功能是否和您遇到的问题有关，请描述该问题**
> 目前好像仅支持单个接口的导入,能否支持接口批量导入?
> 
> **您是否有建议的实现方案**
> 
> **其它帮助我们理解您需求的描述、截图**

aaa

**Comment by Bosn** [comment]
暂时没有计划支持，但是我们支持整个仓库的导出和导入。
