### ISSUE TITLE
导入swagger API信息报错，提示导入失败

### ISSUE THREAD

**Issue by yerz** [thx/rap2-delos#783]
**BUG描述**
导入swagger API信息报错，提示导入失败
同时试过JSON/URL

**复现步骤**
部署站点使用的是http，我们的swagger地址是公网https这样会导致跨域失败

JSON：
直接复制/swagger/v1/swagger.json地址下的JSON进行导入，也会提示失败

**期望结果**
希望正常能够正常导入；

**实际结果**
URL模式：
_无法获取 Swagger 数据,请检查您的 Swagger 服务是否允许 CORS，或者使用直接粘贴 JSON 导入_

JSON模式：
_导入失败，请检查文件格式，详细错误：导入失败._

**截图**
URL导入
![image](https://user-images.githubusercontent.com/30039842/108816334-fa7c8f00-75f0-11eb-8d01-c1c20348f3da.png)

JSON导入
![image](https://user-images.githubusercontent.com/30039842/108816436-24ce4c80-75f1-11eb-95ea-f1980be06d25.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by jiachunzhen** [comment]
asdf

**Comment by Bosn** [comment]
请提供JSON文件后再Reopen，无法复现的case无法排查，谢谢。若涉及隐私，可脱敏后发送邮件至 bosn@outlook.com

**Comment by wjzero** [comment]
我也遇到了，请问后来怎么解决的？
