### ISSUE TITLE
Docker安装后，无法打开应用，一直显示“拼命加载中...(*╹▽╹*)”

### ISSUE THREAD

**Issue by YanxiFeng** [thx/rap2-delos#785]
**BUG描述**
Docker安装后，无法打开前端应用，一直显示“拼命加载中...(*╹▽╹*)”

**复现步骤**
Docker安装后，无法打开前端应用，一直显示“拼命加载中...(*╹▽╹*)”

**期望结果**
前端能正常打开

**实际结果**
前端不能正常打开

**截图**
![image](https://user-images.githubusercontent.com/8113409/109390043-4fe6d200-794a-11eb-94ef-f78cdd02d624.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本 CenterOS 7
* 如果是前端错误，请提供浏览器版本 Firefox 78.7
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by DukeWF** [comment]
我也发现了类似的问题，后来排查后发现是后端服务在38080端口，需要放开。
建议F12排查下是否是名为info的后端服务无法访问。

另：我个人用到了API网关，目前在考虑如何修改下前端配置，使得接入API网关，不必放开38080端口的外部权限。

**Comment by Bosn** [comment]
感谢楼上的答复，Docker配置运维相关问题，建议在RAP群里和群友沟通。
GitHub上针对软件Bug，不交流运维问题，谢谢

**Comment by Bosn** [comment]
可以看一下网络面板，XHR可以查到服务接口的状态，也需要验证下服务接口rap2-delos是否已正常启动
