### ISSUE TITLE
导航栏怎么不显示？要鼠标移过去才显示

### ISSUE THREAD

**Issue by lidechang123** [thx/rap2-delos#786]
**BUG描述**
鼠标未移过去：
![图片](https://user-images.githubusercontent.com/39289750/109931121-6488e880-7d03-11eb-86c9-efa426f8778a.png)

鼠标移动过去：
![图片](https://user-images.githubusercontent.com/39289750/109931206-84b8a780-7d03-11eb-8cd1-129473354c24.png)

**复现步骤**

**期望结果**
可以正常显示导航栏

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 
![图片](https://user-images.githubusercontent.com/39289750/109931616-06a8d080-7d04-11eb-9b01-4ce4ad23d12d.png)

* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by vibeme** [comment]
同，一样的问题
