### ISSUE TITLE
树形结构的模块

### ISSUE THREAD

**Issue by yhydev** [thx/rap2-delos#787]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
想拥有如下的API结构：
module1
- module1-1
- module1-2
   - module1-2-1
   - api1-2-1-1 
- api1

module2
- module2-1
- module2-2

**您是否有建议的实现方案**
一个比较笨的方案，可以通过Chrome 插件，通过一个特定的名称规则实现树形结构。但是目前的模块名称有限制。

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
老RAP1是三层，RAP2改成两层了。第一版RAP2不是我设计的，但是个人觉得2层是够用的，通过搜索可以很快的定位，没必要分太多的层级。

同时，多个项目（或者模块）可以通过协作仓库 来串联，来避免同一个文档内容量过大。

**Comment by yhydev** [comment]
好的，谢谢回复！
________________________________
发件人: Bosn ***@***.***>
发送时间: 2021年3月25日 20:23
收件人: thx/rap2-delos ***@***.***>
抄送: yhydev ***@***.***>; Author ***@***.***>
主题: Re: [thx/rap2-delos] 树形结构的模块 (#787)


老RAP1是三层，RAP2改成两层了。第一版RAP2不是我设计的，但是个人觉得2层是够用的，通过搜索可以很快的定位，没必要分太多的层级。

同时，多个项目（或者模块）可以通过协作仓库 来串联，来避免同一个文档内容量过大。

―
