### ISSUE TITLE
严重！！严重！！严重！！不要使用自己搭建，甚至不要再用

### ISSUE THREAD

**Issue by zwb8926** [thx/rap2-delos#788]
redis不支持密码，就是故意的
我前些日子使用后就被种上病毒了
中了挖矿病毒！！！
中了挖矿病毒！！！
中了挖矿病毒！！！

我就不信，redis支持密码那么难

**Comment by mjj-Martin** [comment]
> redis不支持密码，就是故意的
> 我前些日子使用后就被种上病毒了
> 中了挖矿病毒！！！
> 中了挖矿病毒！！！
> 中了挖矿病毒！！！
> 
> 我就不信，redis支持密码那么难

支持redis密码的。。。设置一下就好

**Comment by Bosn** [comment]
...........

**Comment by Bosn** [comment]
自己数据库、redis、web服务怎么配置需要自己去做管理

这是个开源软件，没义务教你如果做好基本的安全运维。

**Comment by zwb8926** [comment]
![image](https://user-images.githubusercontent.com/10557179/114506088-e1dd3c80-9c63-11eb-8f35-79b6713f534f.png)

你看看，哪里有reids密码了

有密码配置故意不写出来？

就因为没密码，被人利用redis种下病毒了
