### ISSUE TITLE
本地部署的项目点击接口地址提示“未匹配到任何接口 No matched interface”

### ISSUE THREAD

**Issue by zhangcq** [thx/rap2-delos#79]

**Comment by ghzofhit** [comment]
把url中的get或者post方法字段去掉。  例如http://127.0.0.1:8080/app/mock/16/GET/example/1516963455034  去掉get
http://127.0.0.1:8080/app/mock/16/example/1516963455034。如果是post的方法，那么需要用post的方法，发送请求。
