### ISSUE TITLE
npm build failed

### ISSUE THREAD

**Issue by maxianwei** [thx/rap2-delos#790]
**BUG描述**
npm buid的时候报错如下：
9 verbose lifecycle rap2-delos@2.9.0~build: CWD: /data/.jenkins/workspace/sls-developer-platform-service-test
10 silly lifecycle rap2-delos@2.9.0~build: Args: [ '-c', 'rimraf -rf dist/ && tsc' ]
11 silly lifecycle rap2-delos@2.9.0~build: Returned: code: 2  signal: null
12 info lifecycle rap2-delos@2.9.0~build: Failed to exec build script
13 verbose stack Error: rap2-delos@2.9.0 build: `rimraf -rf dist/ && tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid rap2-delos@2.9.0
15 verbose cwd /data/.jenkins/workspace/sls-developer-platform-service-test
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/root/.nvm/v10.16.0/bin/node" "/root/.nvm/v10.16.0/bin/npm" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error rap2-delos@2.9.0 build: `rimraf -rf dist/ && tsc`
22 error Exit status 2
23 error Failed at the rap2-delos@2.9.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

** jenkins  步骤
 sh 'cd /data/.jenkins/workspace/sls-developer-platform-service-test && npm install --unsafe-perm --registry=https://registry.npm.taobao.org'
       sh 'cd /data/.jenkins/workspace/sls-developer-platform-service-test && npm run build'

**期望结果**
![image](https://user-images.githubusercontent.com/34542869/113106547-7774d700-9235-11eb-9bd6-a978b5e93abd.png)

**实际结果**
![image](https://user-images.githubusercontent.com/34542869/113106851-d1759c80-9235-11eb-9ba0-ba131644f669.png)

**环境**
* 自建服务器 centos7.6

**Comment by maxianwei** [comment]
我看到https://github.com/thx/rap2-delos/issues/439  这个issue里面提到打开 tsconfig.json 文件，找到 noImplicitAny，改为 false，但是我的此项配置就是false
![image](https://user-images.githubusercontent.com/34542869/113107078-0e419380-9236-11eb-834e-66dceafbaa85.png)

**Comment by Bosn** [comment]
应该是TypeScript版本的问题，用最新版master再试一下
