### ISSUE TITLE
https部署工程不能访问

### ISSUE THREAD

**Issue by YanxiFeng** [thx/rap2-delos#791]
**BUG描述**
使用https部署工程，页面无法加载，报错如下：
Account.ts:6 Mixed Content: The page at 'https://rap2.xxx.com/' was loaded over HTTPS, but requested an insecure resource 'http://rap2.xxx.com:38080/account/info'. This request has been blocked; the content must be served over HTTPS.

**Comment by Bosn** [comment]
前端用了https，后端服务也必须用才行

**Comment by YanxiFeng** [comment]
解决了，谢谢！
