### ISSUE TITLE
导出doc文档出现错误

### ISSUE THREAD

**Issue by mhyadmin** [thx/rap2-delos#792]
**BUG描述**
导出doc文档出现错误

**复现步骤**
![image](https://user-images.githubusercontent.com/37857548/115007314-6e922f80-9edc-11eb-884c-e77f62821226.png)

**期望结果**
导出文档

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/37857548/115007358-781b9780-9edc-11eb-9940-fceb0b5a6ab1.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本   是 win10
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
出现错误。。。具体是什么错误？请补全问题再open哦
