### ISSUE TITLE
导出doc文档失败

### ISSUE THREAD

**Issue by mhyadmin** [thx/rap2-delos#793]
**BUG描述**

导出doc文档失败
**复现步骤**

**期望结果**

成功导出
**实际结果**
导出失败

**截图**
![image](https://user-images.githubusercontent.com/37857548/115008031-38a17b00-9edd-11eb-8350-543f99899050.png)

![image](https://user-images.githubusercontent.com/37857548/115007955-258eab00-9edd-11eb-8342-1427ee425a09.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本  是 ，win10
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
GitHub rap2-delos 的README.md

搜索：pandoc 2.73 (供文档生成使用)

你得装这个，才能生成文档。

**Comment by mhyadmin** [comment]
不好意思，现在才看到邮箱，有段时间没有用，现在登录不了是什么原因呢，提示验证码错误，之前也有这个情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thx/rap2-delos] 导出doc文档失败 (#793)





 
GitHub rap2-delos 的README.md
 
搜索：pandoc 2.73 (供文档生成使用)
 
你得装这个，才能生成文档。
