### ISSUE TITLE
用户注册这里能不能做成单点登录？

### ISSUE THREAD

**Issue by cabbage89** [thx/rap2-delos#8]
比如支持LDAP ，CAS， http 头代理认证， oauth   这样可以方便企业集成用户

**Comment by cabbage89** [comment]
最简单最容易实用的是  反向代理 认证
https://github.com/gogits/gogs/blob/master/conf/app.ini#L189
gogs就用了这种方式，还有 日志服务 graylog也支持，文档管理alfresco也支持。

原理就是app不直接被浏览器访问，而是通过一个认证代理服务器，比如cas apache网关，在认证通过后，代理到后端系统之前，加上用户的信息到请求头里面，如用户名，显示名等

**Comment by cabbage89** [comment]
具体可以参考gogs实现反向代理认证的讨论
https://github.com/gogits/gogs/issues/165

**Comment by Bosn** [comment]
已经开源了，有需要可以自己实现下...
我这边重点会放在和Postman/Swagger继承、自动化测试方向，暂时没这个计划哦

**Comment by cabbage89** [comment]
好吧 ，谢谢，我们研究下
