### ISSUE TITLE
rap2.taobao.org 无法访问，是服务出问题了么？？？

### ISSUE THREAD

**Issue by NorthLine** [thx/rap2-delos#803]
**BUG描述**
rap2.taobao.org 无法访问

**复现步骤**
rap2.taobao.org 无法访问

**期望结果**
rap2.taobao.org 正常访问

**Comment by Bosn** [comment]
是的亲，我们遭受的DDOS攻击，从中午11点30开始的，触发了阿里云的黑洞报警，目前VIP已经下线了，恢复时间要根据目前受攻击的情况来看。已经在处理了。

**Comment by NorthLine** [comment]
> 是的亲，我们遭受的DDOS攻击，从中午11点30开始的，触发了阿里云的黑洞报警，目前VIP已经下线了，恢复时间要根据目前受攻击的情况来看。已经在处理了。

可以

**Comment by NorthLine** [comment]
> 是的亲，我们遭受的DDOS攻击，从中午11点30开始的，触发了阿里云的黑洞报警，目前VIP已经下线了，恢复时间要根据目前受攻击的情况来看。已经在处理了。

有备用服务可以访问么?

**Comment by Bosn** [comment]
没有
________________________________
