### ISSUE TITLE
http://rap2.taobao.org/ 网站打不开了

### ISSUE THREAD

**Issue by tu6ge** [thx/rap2-delos#804]
**BUG描述**
http://rap2.taobao.org/ 网站打不开了
页面显示
**拼命加载中...(*╹▽╹*)**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by LeToNode** [comment]
同样问题

**Comment by Bosn** [comment]
服务器被30G DDOS恶意攻击，攻击结束后会自动恢复负载蛤

**Comment by lidailin** [comment]
等待...

**Comment by firelk** [comment]
deng deng deng

**Comment by cham-space** [comment]
一天了...还是打不开

**Comment by xyhui83** [comment]
还没有恢复，急急急！！！

**Comment by firelk** [comment]
好了一上午，又又，打不开了

**Comment by Bosn** [comment]
是因为DDOS攻击，当前时间已恢复，后面可能还会因为DDOS攻击而终止服务，建议尽快完成备份，并导入自建服务器。
