### ISSUE TITLE
最近一直显示 正在加载中 就是打不开

### ISSUE THREAD

**Issue by 469081725** [thx/rap2-delos#806]
**BUG描述**

**复现步骤**

**期望结果**

**实际结果**

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by xyhui83** [comment]
早上上班能打开，现在又挂了

**Comment by 469081725** [comment]
是的，&nbsp;我刚还在用，&nbsp;刷新了一下就挂了 - -




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 上午10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thx/rap2-delos] 最近一直显示 正在加载中 就是打不开 (#806)






早上上班能打开,现在又挂了

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Bosn** [comment]
是因为DDOS攻击，当前时间已恢复，后面可能还会因为DDOS攻击而终止服务，建议尽快完成备份，并导入自建服务器。

**Comment by 469081725** [comment]
怎么自建服务器阿&nbsp;大佬，有教程吗。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thx/rap2-delos] 最近一直显示 正在加载中 就是打不开 (#806)






关闭#806.

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
