### ISSUE TITLE
有个问题，就是自有服务器，部署完之后，后台那部分，过一段时间就访问不了了，然后pm2 list找到PID，kill掉就立马好使了，咋回事呢

### ISSUE THREAD

**Issue by WH13869634534** [thx/rap2-delos#809]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
是

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
昨天在http://rap2.taobao.org/  这里面也遇到过那个场景，一会就进不去了，请问怎么处理下呢

**Comment by WH13869634534** [comment]
请问为什么后台一段时间后就进不去了呢，怎么处理下，一直显示  拼命加载中...(*╹▽╹*)

**Comment by Bosn** [comment]
这要看具体的错误日志了。。。这个和RAP2无关了，而是具体的运维问题。

显示拼命加载说明rap2-dolores正常rap2-delos挂了。
