### ISSUE TITLE
请问这种数据怎么填写mock生成规则

### ISSUE THREAD

**Issue by jackma11** [thx/rap2-delos#810]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
数组里的对象,数组长度固定,元素为对象,对象内某个字段的值是不同且需固定

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**
![image](https://user-images.githubusercontent.com/51396482/118363530-dd2edf80-b5a5-11eb-8c93-139e11396125.png)

**Comment by Bosn** [comment]
外层（数组字段）的 `生成规则` 填写长度（比如10）
字段的 `生成规则` 填写 `+1` ，表示按顺序一次产生值。初始值填写`["Hello", "Mock.js" ]` 就可以了

例子：
<img width="590" alt="Screen Shot 2021-05-18 at 3 14 15 PM" src="https://user-images.githubusercontent.com/1892986/118607963-c4b00680-b7eb-11eb-89f3-70baf7a40ecd.png">

**Comment by jackma11** [comment]
非常感谢
