### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by Jerryye17** [thx/rap2-delos#815]
npm run build 报错

[root@iZuf62dkdgvkdmr0i6sfkeZ rap2-delos]# npm run build

> rap2-delos@2.9.0 build
> rimraf -rf dist/ && tsc

src/routes/repository.ts:618:9 - error TS2322: Type 'string' is not assignable to type 'number'.

618   const repositoryId: number = ctx.params.id
            ~~~~~~~~~~~~

src/routes/repository.ts:625:9 - error TS2322: Type 'string' is not assignable to type 'number'.

625   const repositoryId: number = ctx.params.id
            ~~~~~~~~~~~~

src/service/mail.ts:17:28 - error TS2339: Property 'response' does not exist on type 'SentMessageInfo'.

17               resolve(info.response)
                              ~~~~~~~~

src/service/mail.ts:44:28 - error TS2339: Property 'response' does not exist on type 'SentMessageInfo'.

44               resolve(info.response)
                              ~~~~~~~~

Found 4 errors.

[root@iZuf62dkdgvkdmr0i6sfkeZ rap2-delos]# 

**环境**
CentOS 7.9  MySQL 5.7  Nnodejs-15.14.0 Redis 5.09
git clone https://github.com/thx/rap2-delos.git 方式安装

**Comment by tangsiwen** [comment]
我也出现这个问题

**Comment by tangsiwen** [comment]
> npm run build 报错
> 
> [root@iZuf62dkdgvkdmr0i6sfkeZ rap2-delos]# npm run build
> 
> > rap2-delos@2.9.0 build
> > rimraf -rf dist/ && tsc
> 
> src/routes/repository.ts:618:9 - error TS2322: Type 'string' is not assignable to type 'number'.
> 
> 618 const repositoryId: number = ctx.params.id
> ~~~~~~~~~~~~
> 
> src/routes/repository.ts:625:9 - error TS2322: Type 'string' is not assignable to type 'number'.
> 
> 625 const repositoryId: number = ctx.params.id
> ~~~~~~~~~~~~
> 
> src/service/mail.ts:17:28 - error TS2339: Property 'response' does not exist on type 'SentMessageInfo'.
> 
> 17 resolve(info.response)
> ~~~~~~~~
> 
> src/service/mail.ts:44:28 - error TS2339: Property 'response' does not exist on type 'SentMessageInfo'.
> 
> 44 resolve(info.response)
> ~~~~~~~~
> 
> Found 4 errors.
> 
> [root@iZuf62dkdgvkdmr0i6sfkeZ rap2-delos]#
> 
> **环境**
> CentOS 7.9 MySQL 5.7 Nnodejs-15.14.0 Redis 5.09
> git clone https://github.com/thx/rap2-delos.git 方式安装

请问解决了吗？

**Comment by tangsiwen** [comment]
大佬，能解答一下不

**Comment by asawind** [comment]
ts强类型报错
src/routes/repository.ts  618 625 改为const repositoryId: number = parseInt(ctx.params.id)
src/service/mail.ts  17 44 我是将resolve(info.response)改为resolve(info)
