### ISSUE TITLE
安裝前段项目rap2-dolores build的时候报错，自己无力解决，请求大佬帮忙看看，焦急的等待着

### ISSUE THREAD

**Issue by huanhuboke** [thx/rap2-delos#826]
**BUG描述**
下载项目后，先 install了，然后就npm run build 结果报错，说是某个依赖缺失，多次install后都无果，结果去了material-ui的官方github后，发现这个依赖被改名字了，于是我自己尝试了一下，打开了那个引入这个依赖的文件，把依赖改成最新的名字，结果再build 又报代码错误，所以我就不敢再继续改了。只能等大佬解决

**复现步骤**

**期望结果**
build 成功

**实际结果**
build  失败

**截图**

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
重新拉取 master 代码即可，这是因为material-ui更新后，原来的包引入地址删除了。
