### ISSUE TITLE
Function类型的响应参数，规则中不支持if逻辑

### ISSUE THREAD

**Issue by liangfeng093** [thx/rap2-delos#837]
**BUG描述**
Function类型的响应参数不支持if逻辑，fastmock是支持的。

**复现步骤**

**期望结果**

**实际结果**

**截图**
![image](https://user-images.githubusercontent.com/25739714/128049538-674e309c-28bb-41cb-9316-6aaed38a53b7.png)
![image](https://user-images.githubusercontent.com/25739714/128049783-47818d31-a020-4c7a-98a0-7ea7254d66be.png)

**环境**
* 是否是自建服务器？如果为自建，请提供操作系统版本
* 如果是前端错误，请提供浏览器版本
* 其它可能帮助我们排查问题的环境信息

**附加信息**

**Comment by Bosn** [comment]
一个在key中，一个在value中，模板都不一样哦。。。

自定义函数要在 `初始值` 列中，写() => {if xxxxx...  }
