### ISSUE TITLE
mock接口不正常

### ISSUE THREAD

**Issue by wenlonghuo** [thx/rap2-delos#84]
当请求：
http://127.0.0.1:8080/app/mock/16/GET//example/1517487545096
时，返回“未匹配到任何接口 No matched interface”。经过查看，发现是
src/routes/mock.ts文件在从js迁移到ts时，改动接口/app/mock/:repository/:method/:url的逻辑，导致url参数不正确，请确认下修改是否正常？
谢谢

**Comment by qiuhaitao110** [comment]
http://172.20.90.48:8080/app/mock/16/:method/:url
http://172.20.90.48:8080/app/mock/16/GET//example/1518053935830
去掉路径参数GET后
http://172.20.90.48:8080/app/mock/16//example/1518053935830
可以得到正确数据

**Comment by wenlonghuo** [comment]
@qiuhaitao110 但前端页面测试接口写的还是带get的，我的意思是这个GET去掉是特意的，还是无意中去掉了。如果是特意去掉的话，前端管理页面那要更新一下了

**Comment by Bosn** [comment]
目前是要携带GET参数的，但是后续会做到自动适配。

**Comment by zhangdaren** [comment]
啥时候能直接把get和post干掉哇？现在需要把前面的公用部分做两份。

**Comment by wenit** [comment]
修改前端页面工程中的代码rap2-dolores/src/components/editor/InterfaceSummary.jsx

![p8rr_uryh z1da938iuo 98](https://user-images.githubusercontent.com/12817195/50400633-12fb7f80-07c3-11e9-9d88-e0cc23cfef8a.png)
