### ISSUE TITLE
是否支持将RAP1总的备份JSON导入到rap2？

### ISSUE THREAD

**Issue by Seins** [thx/rap2-delos#88]
以前一些项目在RAP1中，下午搭建了新的rap2但是没有找到导入的入口

**Comment by blackdog1987** [comment]
因为目前还没有迁移工具。。。

**Comment by illuSioN4ng** [comment]
同求，导入功能

**Comment by JesseZhao1990** [comment]
迁移工具还没出来，我们也在等待着迁移工具出来之后，升级一下。
https://github.com/thx/rap2-delos/issues/70

**Comment by Bosn** [comment]
最近业务项目繁忙，刚刚出来。我会加快进度。若排期完成请关注RAP2钉钉群。

**Comment by Seins** [comment]
有需要可以叫我们帮忙

2018年3月13日 17:27，"Bosn" <notifications@github.com>写道：
