### ISSUE TITLE
请问下文档导出word里面的参数显示都是树形结构的，是否可以修改为通用表格形势显示，可以怎么修改，望各位大佬告知下谢谢

### ISSUE THREAD

**Issue by weiyuanli** [thx/rap2-delos#916]
**您提出的功能是否和您遇到的问题有关，请描述该问题**

**您是否有建议的实现方案**

**其它帮助我们理解您需求的描述、截图**

**Comment by Bosn** [comment]
可以通过Open API自行做成想要的形式啦，Word导出只是为了方便。但是格式要求每个人都有自己想法，所以需要定制的话自己用Open API搞就行。

另一种方式就是RAP是有导出postman / swagger的，也可以用这些业界流行的符合自己习惯的生成文档库来生成。
