### ISSUE TITLE
请问有使用文档吗？

### ISSUE THREAD

**Issue by shenbinglife** [thx/rap2-delos#95]
我想看下有没有导入导出的功能，在官网上找不到这个。
希望能导出html或者markdown格式的文档

**Comment by Bosn** [comment]
RAP1有，RAP2暂时还没有。需求已记录。

功能需求比较大，但是人力😭....   啊啊啊啊啊最近我又被丢到一个大项目中了，0.8人力。剩下的0.2还要完成很多其它的工作。不过我会尽快搞定的。谢谢。
