### ISSUE TITLE
编辑仓库，填写协同仓库id后提交时报500

### ISSUE THREAD

**Issue by Juliazlj** [thx/rap2-delos#96]
![tim 20180227104210](https://user-images.githubusercontent.com/16634359/36707930-7b27a278-1bab-11e8-8fe6-5162f4fe9e0d.png)
貌似是collaboratorId没插入进去，repositoryId和collaboratorId也反了
另外“协同仓库”的概念没明确
-------------------------------------------分割线--------------------------------------------
后来发现是我填了一次id之后再次编辑时协同仓库id又为空了，再次填写协同仓库id提交才会出现这个问题，但是填了id也没发现有什么变化，协同仓库只是一个标记？？？

**Comment by Bosn** [comment]
该问题已经在最新版中修复，是TS重构后的BUG，请留意最新git。
如果是您自行部署的版本，请提供详细的错误日志再reopen，谢谢。
