### ISSUE TITLE
已编辑好的接口，如果后期修改时想调整字段的层级关系， 该如何操作？

### ISSUE THREAD

**Issue by jackgreentemp** [thx/rap2-delos#98]
比如之前的格式如下
```
{
  "statusCode": 200,
  "errMsg": "",
  "data": {
    "code": 0,
    "data": {
      
    }
  }
}
```

想调整为
```
{
  "code": 0,
  "data": {
      
  }
}
```

目前好像没法在rap2的接口编辑页面上调整，只能把模板copy出来，再“导入”进去，但是重新导入之后，之前写好的字段简介就没了，得重新写一遍

**Comment by Bosn** [comment]
暂时还不支持复杂的层级调整，不过确实这是一个问题。我觉得可以通过导出`元数据`来实现，例如导出时候携带 __comment__ 信息，用于导入时回填。该功能我会写在后续的计划里。
